import Nightstream.Implementation.Nebula.Production.FPrime.Recursive.RecursiveCoreGeometryFor

set_option autoImplicit false

namespace tests.NebulaProductionRecursiveCoreGeometryFor

open Nightstream.Implementation.Nebula.ProductionRecursiveCoreGeometryFor

#check productNifsRows_25
#check productNifsRows_26
#check knownCoreRows_25_table
#check knownCoreRows_26_table
#check knownCoreRows_26_exceed_25
#check knownCoreRows_26_fit_26
#check knownCoreRows_26_power_interval

end tests.NebulaProductionRecursiveCoreGeometryFor
