import DirectCcsFPrime.ProofSystem.PrivatePiDec.Impl.CanonicalPrivatePiDecVerifier

/-!
Typed interface for the canonical private `Pi_DEC` verifier relation.

Spec: `specs/ProofSystem/PrivatePiDec/Impl/CanonicalPrivatePiDecVerifier.spec.md`
-/

namespace DirectCcsFPrime

namespace CanonicalPrivatePiDecVerifierInterface

abbrev Verify :=
  @CanonicalPrivatePiDecVerifier.Verify

abbrev verify_sound :=
  @CanonicalPrivatePiDecVerifier.verify_sound

abbrev same_canonical_private_pidec_next_inputs :=
  @CanonicalPrivatePiDecVerifier.same_canonical_private_pidec_next_inputs

abbrev same_opened_parentCEB_digest_source_canonical_private_pidec_inputs_of_ajtaiCEOpening :=
  @CanonicalPrivatePiDecVerifier.same_opened_parentCEB_digest_source_canonical_private_pidec_inputs_of_ajtaiCEOpening

abbrev same_opened_parentCEB_digest_source_canonical_private_pidec_inputs_of_statementCommitment_and_ajtaiCEOpening :=
  @CanonicalPrivatePiDecVerifier.same_opened_parentCEB_digest_source_canonical_private_pidec_inputs_of_statementCommitment_and_ajtaiCEOpening

abbrev AuthorizedNextPiCCSInputs :=
  @CanonicalPrivatePiDecVerifier.AuthorizedNextPiCCSInputs

abbrev authorized_nextPiCCSInputs_functional_of_ajtaiCEOpening :=
  @CanonicalPrivatePiDecVerifier.authorized_nextPiCCSInputs_functional_of_ajtaiCEOpening

abbrev authorized_nextPiCCSInputs_functional_of_statementCommitment_and_ajtaiCEOpening :=
  @CanonicalPrivatePiDecVerifier.authorized_nextPiCCSInputs_functional_of_statementCommitment_and_ajtaiCEOpening

end CanonicalPrivatePiDecVerifierInterface

end DirectCcsFPrime
