//! Lean renderer for the linked one-slot canonical differential corpus.

use std::fmt::Write;

use super::{Case, Corpus, EncodeMap, FreshPublicMap, HashInputMap, HashReceiptMap, NifsMap, StepTraceMap};

pub(super) fn render(corpus: &Corpus) -> String {
    let mut out = String::new();
    writeln!(
        out,
        "import Nightstream.Implementation.Rust.CanonicalConformance.OneSlot\n"
    )
    .unwrap();
    writeln!(
        out,
        "/-!\nGenerated by the Rust linked canonical-step drift gate.\n\
         Exact public Rust values and mutation coordinates are retained in\n\
         `canonical_step_cases.json`.  This file is the equality quotient\n\
         consumed by the frozen one-slot checker.  Primitive outcomes remain\n\
         receipts and are not refinement theorems.  Do not edit by hand.\n-/\n"
    )
    .unwrap();
    writeln!(
        out,
        "namespace Nightstream.Implementation.Rust.CanonicalConformance.OneSlot.Generated\n\n\
         open Nightstream.Implementation.Rust.CanonicalConformance.OneSlot\n"
    )
    .unwrap();
    writeln!(out, "def corpusSchema : Nat := {}\n", corpus.schema).unwrap();
    let mut names = Vec::with_capacity(corpus.cases.len());
    for case in &corpus.cases {
        let name = lower_camel(&case.name);
        render_case(&mut out, &name, case);
        names.push(name);
    }
    writeln!(out, "def all : List StepCase := [{}]\n", names.join(", ")).unwrap();
    writeln!(out, "def honest : List StepCase := [honestBase, honestRecursive]\n").unwrap();
    writeln!(out, "def mutations : List StepCase := [{}]\n", names[2..].join(", ")).unwrap();
    writeln!(
        out,
        "end Nightstream.Implementation.Rust.CanonicalConformance.OneSlot.Generated"
    )
    .unwrap();
    out
}

fn render_case(out: &mut String, name: &str, case: &Case) {
    let mapped = &case.mapped;
    writeln!(
        out,
        "def {name} : StepCase where\n  verifierKey := {}\n  \
         defaultRunning := {}\n  iteration := {}\n  z0 := {}\n  zi := {}\n  \
         running := {}\n  fresh := {}\n  priorPc := {}\n  witness := {}\n  \
         nifsProof := {}\n  stepReceipt := {{ state := {}, witness := {}, output := {} }}\n  \
         trace := {}\n  claim := {{ zNext := {}, runningNext := {}, pcNext := {}, x := {} }}\n  \
         rustAccepted := {}\n",
        atom(mapped.verifier_key),
        atom(mapped.default_running),
        mapped.iteration,
        atom(mapped.z0),
        atom(mapped.zi),
        atom(mapped.running),
        atom(mapped.fresh),
        mapped.prior_pc,
        atom(mapped.witness),
        atom(mapped.nifs_proof),
        atom(mapped.step_receipt.state),
        atom(mapped.step_receipt.witness),
        atom(mapped.step_receipt.output),
        trace(&mapped.trace),
        atom(mapped.claim.z_next),
        atom(mapped.claim.running_next),
        mapped.claim.pc_next,
        atom(mapped.claim.x),
        bool_text(mapped.rust_accepted),
    )
    .unwrap();
}

fn trace(value: &StepTraceMap) -> String {
    match value {
        StepTraceMap::Base { next_hash } => {
            format!(".base {}", option(next_hash.as_ref().map(hash_receipt)))
        }
        StepTraceMap::Recursive {
            prior_hash,
            fresh_public,
            encode,
            nifs,
            next_hash,
        } => format!(
            ".recursive {} {} {} {} {}",
            option(prior_hash.as_ref().map(hash_receipt)),
            option(fresh_public.as_ref().map(fresh_public_receipt)),
            option(encode.as_ref().map(encode_receipt)),
            option(nifs.as_ref().map(nifs_receipt)),
            option(next_hash.as_ref().map(hash_receipt)),
        ),
    }
}

fn hash_input(value: &HashInputMap) -> String {
    format!(
        "{{ verifierKey := {}, iteration := {}, z0 := {}, current := {}, running := {}, pc := {} }}",
        atom(value.verifier_key),
        value.iteration,
        atom(value.z0),
        atom(value.current),
        atom(value.running),
        value.pc,
    )
}

fn hash_receipt(value: &HashReceiptMap) -> String {
    format!(
        "{{ input := {}, output := {} }}",
        hash_input(&value.input),
        atom(value.output),
    )
}

fn fresh_public_receipt(value: &FreshPublicMap) -> String {
    format!("{{ input := {}, output := {} }}", atom(value.input), atom(value.output),)
}

fn encode_receipt(value: &EncodeMap) -> String {
    format!("{{ input := {}, output := {} }}", atom(value.input), atom(value.output),)
}

fn nifs_receipt(value: &NifsMap) -> String {
    format!(
        "{{ key := {}, running := {}, fresh := {}, proof := {}, output := {} }}",
        atom(value.key),
        atom(value.running),
        atom(value.fresh),
        atom(value.proof),
        option(value.output.map(atom)),
    )
}

fn option(value: Option<String>) -> String {
    value.map_or_else(|| "none".to_owned(), |value| format!("(some {value})"))
}

fn atom(value: u32) -> String {
    format!("⟨{value}⟩")
}

fn bool_text(value: bool) -> &'static str {
    if value {
        "true"
    } else {
        "false"
    }
}

fn lower_camel(value: &str) -> String {
    let mut pieces = value.split('_');
    let mut output = pieces.next().unwrap_or_default().to_owned();
    for piece in pieces {
        let mut characters = piece.chars();
        if let Some(first) = characters.next() {
            output.extend(first.to_uppercase());
            output.extend(characters);
        }
    }
    output
}
