import Nightstream.Implementation.Nebula.Production.FPrime.Base.InvocationFor
import tests.Axioms.Support

set_option pp.universes true in
#audit_axioms Nightstream.Implementation.Nebula.ProductionPaperBaseInvocationFor.exact

#audit_axioms Nightstream.Implementation.Nebula.ProductionPaperBaseInvocationFor.initialState_canonical
#audit_axioms Nightstream.Implementation.Nebula.ProductionPaperBaseInvocationFor.state_preCarry_exact
