import Nightstream.Assurance.ConstraintMinimization
import tests.Axioms.Support

namespace tests.Axioms.ConstraintMinimization

open Nightstream.Assurance.ConstraintMinimization

#audit_axioms ScalarCertificate.candidate_holds_of_valid
#audit_axioms FamilyCertificate.redundant_of_valid
#audit_axioms FamilyCertificate.redundant_of_bound_valid
#audit_axioms FamilyCertificate.redundant_of_terminal_bound_valid
#audit_axioms FamilyCertificate.redundant_of_full_bound_valid
#audit_axioms FamilyCertificate.redundant_of_full_terminal_bound_valid
#audit_axioms normalizedRedundant_of_redundant
#audit_axioms Artifact.normalizedFullPlanSound
#audit_axioms Artifact.normalizedFullPlanComplete
#audit_axioms Artifact.normalizedFullPlanExact
#audit_axioms Artifact.normalizedFullPlanInclusionMinimalSound
#audit_axioms TerminalBoundArtifact.accepted_retains_native_guard
#audit_axioms TerminalBoundArtifact.accepted_native_guard_not_polynomial
#audit_axioms TerminalBoundArtifact.accepted_native_guard_ledger_exact
#audit_axioms TerminalBoundArtifact.accepted_retains_context_guards
#audit_axioms TerminalBoundArtifact.accepted_retains_statement_guards
#audit_axioms TerminalBoundArtifact.accepted_retains_proof_guards
#audit_axioms rust_terminal_native_guard_names_exact
#audit_axioms RemovalCounterexample.necessary_of_valid
#audit_axioms RemovalCounterexample.necessary_of_bound_valid
#audit_axioms RemovalCounterexample.necessary_of_terminal_bound_valid
#audit_axioms RemovalCounterexample.necessary_of_full_bound_valid
#audit_axioms RemovalCounterexample.necessary_of_full_terminal_bound_valid
#audit_axioms RemovalCounterexample.necessary_normalized_of_valid
#audit_axioms RemovalCounterexample.necessary_normalized_of_bound_valid
#audit_axioms RemovalCounterexample.necessary_normalized_of_terminal_bound_valid
#audit_axioms RemovalCounterexample.necessary_normalized_of_full_bound_valid
#audit_axioms RemovalCounterexample.necessary_normalized_of_full_terminal_bound_valid

end tests.Axioms.ConstraintMinimization
