import Nightstream.Implementation.NebulaV2.ProductionPaperStateContinuityFor
import tests.Axioms.Support

set_option pp.universes true in
#audit_axioms Nightstream.Implementation.NebulaV2.ProductionPaperStateContinuityFor.state_equal_or_collision
