import Nightstream.Assurance.TerminalStatementBoundary
import tests.Axioms.Support

namespace tests.Axioms.TerminalStatementBoundary

open Nightstream.Assurance.TerminalStatementBoundary

#audit_axioms guardNames_exact
#audit_axioms verify_eq_true_iff_target
#audit_axioms retained_necessary
#audit_axioms inclusionMinimalSound

end tests.Axioms.TerminalStatementBoundary
