use neo_fold_clean::frontends::r1cs_f_prime::R1csChainBuilder;
use neo_fold_clean::lifecycle::verify_uncompressed_audit;
use neo_wasm::{
    build_steps, opcode_code, preprocess_seeded_batched, semantic_state_digest, StackValueAccess, WasmOpcode,
    WasmOutputState, WasmParamInitState, WasmPcEdgeKind, WasmRowKind, WasmStepState, WasmStepTrace,
};

fn state(pc: u64, sp: u64, halted: bool) -> WasmStepState {
    WasmStepState {
        pc,
        sp,
        output: WasmOutputState::ZERO,
        call_stack_depth: 0,
        memory_pages: None,
        max_memory_pages: None,
        locals_fbp: 0,
        halted,
        trapped: false,
        param_init: WasmParamInitState::ZERO,
    }
}

#[test]
fn wasm_frontend_scaffold_runs_through_clean_lifecycle() {
    let initial_state = state(0, 0, false);
    let digest = semantic_state_digest(initial_state);
    let prep = preprocess_seeded_batched(1, digest).expect("prep");

    let steps = vec![
        WasmStepTrace {
            cycle: 0,
            row_kind: WasmRowKind::Program,
            state_before: state(0, 0, false),
            state_after: state(1, 1, false),
            control_choice: 0,
            pc_edge_kind: WasmPcEdgeKind::Static,
            wide_values_enabled: false,
            opcode: WasmOpcode::I32Const,
            info: neo_wasm::opcode_info_from_code(opcode_code(WasmOpcode::I32Const)),
            stack_reads_override: None,
            stack_writes_override: None,
            output_captured: false,
            current_function_ref: 0,
            current_function_num_locals: 0,
            stack_read0: None,
            stack_read1: None,
            stack_read2: None,
            stack_write0: Some(StackValueAccess::new(0, 7)),
            linear_memory: None,
            linear_memory_offset: 0,
            local_index: None,
            local_read_value: None,
            local_read_value_hi: None,
            local_write_value: None,
            local_write_value_hi: None,
            global_index: None,
            global_read_value: None,
            global_read_value_hi: None,
            global_write_value: None,
            global_write_value_hi: None,
            table_id: None,
            table_index: None,
            table_value: None,
            function_ref: None,
            target_function_is_guest: false,
            function_type_id: None,
            call_indirect_type_index: None,
            expected_type_id: None,
            table_size: None,
            call_param_count: None,
            call_result_count: None,
            call_stack_push: None,
            call_stack_pop: None,
        },
        WasmStepTrace {
            cycle: 1,
            row_kind: WasmRowKind::Program,
            state_before: state(1, 1, false),
            state_after: state(2, 2, false),
            control_choice: 0,
            pc_edge_kind: WasmPcEdgeKind::Static,
            wide_values_enabled: false,
            opcode: WasmOpcode::I32Const,
            info: neo_wasm::opcode_info_from_code(opcode_code(WasmOpcode::I32Const)),
            stack_reads_override: None,
            stack_writes_override: None,
            output_captured: false,
            current_function_ref: 0,
            current_function_num_locals: 0,
            stack_read0: None,
            stack_read1: None,
            stack_read2: None,
            stack_write0: Some(StackValueAccess::new(2, 9)),
            linear_memory: None,
            linear_memory_offset: 0,
            local_index: None,
            local_read_value: None,
            local_read_value_hi: None,
            local_write_value: None,
            local_write_value_hi: None,
            global_index: None,
            global_read_value: None,
            global_read_value_hi: None,
            global_write_value: None,
            global_write_value_hi: None,
            table_id: None,
            table_index: None,
            table_value: None,
            function_ref: None,
            target_function_is_guest: false,
            function_type_id: None,
            call_indirect_type_index: None,
            expected_type_id: None,
            table_size: None,
            call_param_count: None,
            call_result_count: None,
            call_stack_push: None,
            call_stack_pop: None,
        },
        WasmStepTrace {
            cycle: 2,
            row_kind: WasmRowKind::Program,
            state_before: state(2, 2, false),
            state_after: state(3, 1, false),
            control_choice: 0,
            pc_edge_kind: WasmPcEdgeKind::Static,
            wide_values_enabled: false,
            opcode: WasmOpcode::I32Add,
            info: neo_wasm::opcode_info_from_code(opcode_code(WasmOpcode::I32Add)),
            stack_reads_override: None,
            stack_writes_override: None,
            output_captured: false,
            current_function_ref: 0,
            current_function_num_locals: 0,
            stack_read0: Some(StackValueAccess::new(0, 7)),
            stack_read1: Some(StackValueAccess::new(2, 9)),
            stack_read2: None,
            stack_write0: Some(StackValueAccess::new(0, 16)),
            linear_memory: None,
            linear_memory_offset: 0,
            local_index: None,
            local_read_value: None,
            local_read_value_hi: None,
            local_write_value: None,
            local_write_value_hi: None,
            global_index: None,
            global_read_value: None,
            global_read_value_hi: None,
            global_write_value: None,
            global_write_value_hi: None,
            table_id: None,
            table_index: None,
            table_value: None,
            function_ref: None,
            target_function_is_guest: false,
            function_type_id: None,
            call_indirect_type_index: None,
            expected_type_id: None,
            table_size: None,
            call_param_count: None,
            call_result_count: None,
            call_stack_push: None,
            call_stack_pop: None,
        },
        WasmStepTrace {
            cycle: 3,
            row_kind: WasmRowKind::Program,
            state_before: state(3, 1, false),
            state_after: state(4, 1, true),
            control_choice: 0,
            pc_edge_kind: WasmPcEdgeKind::ReturnLike,
            wide_values_enabled: false,
            opcode: WasmOpcode::Return,
            info: neo_wasm::opcode_info_from_code(opcode_code(WasmOpcode::Return)),
            stack_reads_override: None,
            stack_writes_override: None,
            output_captured: false,
            current_function_ref: 0,
            current_function_num_locals: 0,
            stack_read0: None,
            stack_read1: None,
            stack_read2: None,
            stack_write0: None,
            linear_memory: None,
            linear_memory_offset: 0,
            local_index: None,
            local_read_value: None,
            local_read_value_hi: None,
            local_write_value: None,
            local_write_value_hi: None,
            global_index: None,
            global_read_value: None,
            global_read_value_hi: None,
            global_write_value: None,
            global_write_value_hi: None,
            table_id: None,
            table_index: None,
            table_value: None,
            function_ref: None,
            target_function_is_guest: false,
            function_type_id: None,
            call_indirect_type_index: None,
            expected_type_id: None,
            table_size: None,
            call_param_count: None,
            call_result_count: None,
            call_stack_push: None,
            call_stack_pop: None,
        },
    ];

    let prepared = build_steps(&steps);

    let mut chain = R1csChainBuilder::new(&prep).expect("chain");
    for step in &prepared {
        chain
            .append_assignment(step.assignment.clone())
            .expect("append assignment");
    }
    let proof = chain.finish_with_audit().expect("finish");
    verify_uncompressed_audit(&prep.prep, &proof).expect("verify");
}
