use neo_fold_clean::frontends::r1cs_f_prime::R1csChainBuilder;
use neo_fold_clean::lifecycle::verify_uncompressed;
use neo_wasm::preprocess::preprocess_seeded;
use neo_wasm::{
    build_steps, opcode_code, StackValueAccess, WasmOpcode, WasmParamInitState, WasmPcEdgeKind, WasmRowKind,
    WasmStepTrace, WasmVmSpec,
};

#[test]
fn wasm_frontend_scaffold_runs_through_clean_lifecycle() {
    let vm = WasmVmSpec::new().expect("vm");
    let prep = preprocess_seeded(&vm).expect("prep");

    let steps = vec![
        WasmStepTrace {
            cycle: 0,
            row_kind: WasmRowKind::Program,
            pc_before: 0,
            pc_after: 1,
            control_choice: 0,
            pc_edge_kind: WasmPcEdgeKind::Static,
            param_init_before: WasmParamInitState::ZERO,
            param_init_after: WasmParamInitState::ZERO,
            wide_values_enabled: false,
            opcode_code: opcode_code(WasmOpcode::I32Const),
            opcode: WasmOpcode::I32Const,
            info: neo_wasm::opcode_info_from_code(opcode_code(WasmOpcode::I32Const)),
            stack_reads_override: None,
            stack_writes_override: None,
            sp_before: 0,
            sp_after: 1,
            output_enabled_before: false,
            output_enabled_after: false,
            output_value_lo_before: 0,
            output_value_lo_after: 0,
            output_value_hi_before: 0,
            output_value_hi_after: 0,
            output_captured: false,
            call_stack_depth_before: 0,
            call_stack_depth_after: 0,
            current_function_ref: 0,
            current_function_num_locals: 0,
            stack_read0: None,
            stack_read1: None,
            stack_read2: None,
            stack_write0: Some(StackValueAccess::new(0, 7)),
            linear_memory: None,
            linear_memory_offset: 0,
            memory_pages_before: None,
            memory_pages_after: None,
            halted: false,
            locals_fbp: 0,
            locals_fbp_after: 0,
            local_index: None,
            local_read_value: None,
            local_read_value_hi: None,
            local_write_value: None,
            local_write_value_hi: None,
            global_index: None,
            global_read_value: None,
            global_read_value_hi: None,
            global_write_value: None,
            global_write_value_hi: None,
            table_id: None,
            table_index: None,
            table_value: None,
            function_ref: None,
            target_function_is_guest: false,
            function_type_id: None,
            call_indirect_type_index: None,
            expected_type_id: None,
            table_size: None,
            call_param_count: None,
            call_result_count: None,
            call_stack_push: None,
            call_stack_pop: None,
        },
        WasmStepTrace {
            cycle: 1,
            row_kind: WasmRowKind::Program,
            pc_before: 1,
            pc_after: 2,
            control_choice: 0,
            pc_edge_kind: WasmPcEdgeKind::Static,
            param_init_before: WasmParamInitState::ZERO,
            param_init_after: WasmParamInitState::ZERO,
            wide_values_enabled: false,
            opcode_code: opcode_code(WasmOpcode::I32Const),
            opcode: WasmOpcode::I32Const,
            info: neo_wasm::opcode_info_from_code(opcode_code(WasmOpcode::I32Const)),
            stack_reads_override: None,
            stack_writes_override: None,
            sp_before: 1,
            sp_after: 2,
            output_enabled_before: false,
            output_enabled_after: false,
            output_value_lo_before: 0,
            output_value_lo_after: 0,
            output_value_hi_before: 0,
            output_value_hi_after: 0,
            output_captured: false,
            call_stack_depth_before: 0,
            call_stack_depth_after: 0,
            current_function_ref: 0,
            current_function_num_locals: 0,
            stack_read0: None,
            stack_read1: None,
            stack_read2: None,
            stack_write0: Some(StackValueAccess::new(2, 9)),
            linear_memory: None,
            linear_memory_offset: 0,
            memory_pages_before: None,
            memory_pages_after: None,
            halted: false,
            locals_fbp: 0,
            locals_fbp_after: 0,
            local_index: None,
            local_read_value: None,
            local_read_value_hi: None,
            local_write_value: None,
            local_write_value_hi: None,
            global_index: None,
            global_read_value: None,
            global_read_value_hi: None,
            global_write_value: None,
            global_write_value_hi: None,
            table_id: None,
            table_index: None,
            table_value: None,
            function_ref: None,
            target_function_is_guest: false,
            function_type_id: None,
            call_indirect_type_index: None,
            expected_type_id: None,
            table_size: None,
            call_param_count: None,
            call_result_count: None,
            call_stack_push: None,
            call_stack_pop: None,
        },
        WasmStepTrace {
            cycle: 2,
            row_kind: WasmRowKind::Program,
            pc_before: 2,
            pc_after: 3,
            control_choice: 0,
            pc_edge_kind: WasmPcEdgeKind::Static,
            param_init_before: WasmParamInitState::ZERO,
            param_init_after: WasmParamInitState::ZERO,
            wide_values_enabled: false,
            opcode_code: opcode_code(WasmOpcode::I32Add),
            opcode: WasmOpcode::I32Add,
            info: neo_wasm::opcode_info_from_code(opcode_code(WasmOpcode::I32Add)),
            stack_reads_override: None,
            stack_writes_override: None,
            sp_before: 2,
            sp_after: 1,
            output_enabled_before: false,
            output_enabled_after: false,
            output_value_lo_before: 0,
            output_value_lo_after: 0,
            output_value_hi_before: 0,
            output_value_hi_after: 0,
            output_captured: false,
            call_stack_depth_before: 0,
            call_stack_depth_after: 0,
            current_function_ref: 0,
            current_function_num_locals: 0,
            stack_read0: Some(StackValueAccess::new(0, 7)),
            stack_read1: Some(StackValueAccess::new(2, 9)),
            stack_read2: None,
            stack_write0: Some(StackValueAccess::new(0, 16)),
            linear_memory: None,
            linear_memory_offset: 0,
            memory_pages_before: None,
            memory_pages_after: None,
            halted: false,
            locals_fbp: 0,
            locals_fbp_after: 0,
            local_index: None,
            local_read_value: None,
            local_read_value_hi: None,
            local_write_value: None,
            local_write_value_hi: None,
            global_index: None,
            global_read_value: None,
            global_read_value_hi: None,
            global_write_value: None,
            global_write_value_hi: None,
            table_id: None,
            table_index: None,
            table_value: None,
            function_ref: None,
            target_function_is_guest: false,
            function_type_id: None,
            call_indirect_type_index: None,
            expected_type_id: None,
            table_size: None,
            call_param_count: None,
            call_result_count: None,
            call_stack_push: None,
            call_stack_pop: None,
        },
        WasmStepTrace {
            cycle: 3,
            row_kind: WasmRowKind::Program,
            pc_before: 3,
            pc_after: 4,
            control_choice: 0,
            pc_edge_kind: WasmPcEdgeKind::ReturnLike,
            param_init_before: WasmParamInitState::ZERO,
            param_init_after: WasmParamInitState::ZERO,
            wide_values_enabled: false,
            opcode_code: opcode_code(WasmOpcode::Return),
            opcode: WasmOpcode::Return,
            info: neo_wasm::opcode_info_from_code(opcode_code(WasmOpcode::Return)),
            stack_reads_override: None,
            stack_writes_override: None,
            sp_before: 1,
            sp_after: 1,
            output_enabled_before: false,
            output_enabled_after: false,
            output_value_lo_before: 0,
            output_value_lo_after: 0,
            output_value_hi_before: 0,
            output_value_hi_after: 0,
            output_captured: false,
            call_stack_depth_before: 0,
            call_stack_depth_after: 0,
            current_function_ref: 0,
            current_function_num_locals: 0,
            stack_read0: None,
            stack_read1: None,
            stack_read2: None,
            stack_write0: None,
            linear_memory: None,
            linear_memory_offset: 0,
            memory_pages_before: None,
            memory_pages_after: None,
            halted: true,
            locals_fbp: 0,
            locals_fbp_after: 0,
            local_index: None,
            local_read_value: None,
            local_read_value_hi: None,
            local_write_value: None,
            local_write_value_hi: None,
            global_index: None,
            global_read_value: None,
            global_read_value_hi: None,
            global_write_value: None,
            global_write_value_hi: None,
            table_id: None,
            table_index: None,
            table_value: None,
            function_ref: None,
            target_function_is_guest: false,
            function_type_id: None,
            call_indirect_type_index: None,
            expected_type_id: None,
            table_size: None,
            call_param_count: None,
            call_result_count: None,
            call_stack_push: None,
            call_stack_pop: None,
        },
    ];

    let prepared = build_steps(&steps);

    let mut chain = R1csChainBuilder::new(&prep).expect("chain");
    for step in &prepared {
        chain
            .append_assignment(step.assignment.clone())
            .expect("append assignment");
    }
    let proof = chain.finish().expect("finish");
    verify_uncompressed(&prep.prep, &proof).expect("verify");
}
