//! Compact Lean rendering for the native-step differential corpus.
//!
//! The adjacent JSON keeps the exact public Rust payload.  This renderer
//! deliberately emits only equality-normalized, nonzero atoms and the calls
//! needed by the independent Lean native-step checker.

use std::fmt::Write;

use neo_fold_clean::paper::digest;
use neo_math::F;
use p3_field::{PrimeCharacteristicRing, PrimeField64};

use super::{
    Dispatch, ExecutionEventKind, ExecutionStage, Felt, FoldAtom, Mode, NativeStepCorpus, NifsOutcome, Outcome,
    StableError, StateAtom, StateBranch,
};

pub(super) fn render(corpus: &NativeStepCorpus) -> String {
    let mut renderer = Renderer::new(corpus);
    renderer.render()
}

#[derive(Default)]
struct DigestIds {
    values: Vec<[u8; 32]>,
    raw_fields: Vec<[Felt; 4]>,
}

impl DigestIds {
    fn id(&mut self, value: [u8; 32]) -> u32 {
        let raw_fields = digest::digest32_as_fields(value).map(|field| Felt(field.as_canonical_u64()));
        if let Some(index) = self.values.iter().position(|found| *found == value) {
            assert_eq!(self.raw_fields[index], raw_fields);
            return u32::try_from(index + 1).expect("Lean digest atom fits u32");
        }
        self.values.push(value);
        self.raw_fields.push(raw_fields);
        u32::try_from(self.values.len()).expect("Lean digest atom fits u32")
    }

    fn field_digest(&mut self, value: [Felt; 4]) -> u32 {
        let fields = value.map(|limb| F::from_u64(limb.0));
        let id = self.id(digest::digest_fields_as_digest32(fields));
        assert_eq!(self.raw_fields[id as usize - 1], value);
        id
    }
}

struct Renderer<'a> {
    corpus: &'a NativeStepCorpus,
    digests: DigestIds,
    inputs: Vec<Vec<u32>>,
    case_inputs: Vec<u32>,
    default_running: u32,
}

impl<'a> Renderer<'a> {
    fn new(corpus: &'a NativeStepCorpus) -> Self {
        let mut inputs = Vec::<Vec<u32>>::new();
        let case_inputs = corpus
            .cases
            .iter()
            .map(|case| {
                if let Some(index) = inputs.iter().position(|found| found == &case.next_latest) {
                    u32::try_from(index + 1).expect("Lean input id fits u32")
                } else {
                    inputs.push(case.next_latest.clone());
                    u32::try_from(inputs.len()).expect("Lean input id fits u32")
                }
            })
            .collect();
        let honest_base = corpus
            .cases
            .iter()
            .find(|case| case.name == "honest_base")
            .expect("native-step corpus contains the honest base receipt");
        let next = honest_base
            .recorded_next
            .expect("the honest base receipt has a next state");
        let StateBranch::Active { running, .. } = corpus.atoms.states[next as usize].branch else {
            panic!("the honest base receipt produces an active state")
        };
        let default_running = running + 1;
        let initial = &corpus.atoms.states[honest_base.input_state as usize];
        assert!(matches!(initial.branch, StateBranch::Initial));
        Self {
            corpus,
            digests: DigestIds::default(),
            inputs,
            case_inputs,
            default_running,
        }
    }

    fn render(&mut self) -> String {
        let mut out = String::new();
        writeln!(
            out,
            "import Nightstream.Implementation.Rust.CanonicalConformance.NativeStep\n"
        )
        .unwrap();
        writeln!(
            out,
            "/-!\nGenerated by the Rust native-step conformance drift gate.\n\
             This file contains compact equality atoms only.  Exact public Rust\n\
             payloads remain in `native_step_receipts.json` as audit data and\n\
             are not semantic authority.  Do not edit this file by hand.\n-/\n"
        )
        .unwrap();
        writeln!(
            out,
            "namespace Nightstream.Implementation.Rust.CanonicalConformance.NativeStep.Generated\n"
        )
        .unwrap();

        self.render_context(&mut out);
        writeln!(out, "def emptyRunning : Running := {}\n", atom(self.default_running)).unwrap();
        self.render_states(&mut out);
        self.render_inputs(&mut out);
        self.render_proofs(&mut out);
        self.render_receipts(&mut out);
        writeln!(
            out,
            "end Nightstream.Implementation.Rust.CanonicalConformance.NativeStep.Generated"
        )
        .unwrap();
        out
    }

    fn render_context(&mut self, out: &mut String) {
        let initial = self
            .corpus
            .atoms
            .states
            .first()
            .expect("native-step corpus has a base state")
            .initial_semantic_state_digest;
        let initial = atom(self.digests.id(initial));
        let public_input = match self.corpus.profile.relation.public_input_len {
            Some(value) => format!("some {value}"),
            None => "none".to_owned(),
        };
        writeln!(
            out,
            "def context : NativeContext where\n  params := ⟨1⟩\n  \
             structureDigest := ⟨1⟩\n  piCcsHeader := ⟨1⟩\n  \
             publicInputLength := {public_input}\n  initialSemanticState := {initial}\n"
        )
        .unwrap();
    }

    fn render_states(&mut self, out: &mut String) {
        for (index, state) in self.corpus.atoms.states.iter().enumerate() {
            assert_eq!(state.nebula, "absent");
            let proof = match &state.branch {
                StateBranch::Initial => ".initial".to_owned(),
                StateBranch::Active { running, latest } => {
                    let latest = &self.corpus.atoms.latest[*latest as usize];
                    format!(
                        ".active {} {}",
                        atom(*running + 1),
                        atom_list(&latest.ordered_claims, 1)
                    )
                }
            };
            writeln!(
                out,
                "def state{} : NativeState where\n  chunkCount := {}\n  \
                 stepCount := {}\n  z0 := {}\n  zi := {}\n  \
                 initialSemanticState := {}\n  semanticState := {}\n  pc := {}\n  \
                 accumulatorDigest := {}\n  publicTrace := {}\n  proof := {proof}\n  \
                 nebula := none\n",
                index + 1,
                state.chunk_count,
                state.step_count,
                atom(self.digests.id(state.z_0)),
                atom(self.digests.id(state.z_i)),
                atom(self.digests.id(state.initial_semantic_state_digest)),
                atom(self.digests.id(state.semantic_state_digest)),
                state.pc,
                atom(self.digests.id(state.acc_digest)),
                atom(self.digests.id(state.public_trace)),
            )
            .unwrap();
        }
    }

    fn render_inputs(&self, out: &mut String) {
        for (index, next_latest) in self.inputs.iter().enumerate() {
            writeln!(
                out,
                "def input{} : NativeInput where\n  nextLatest := {}\n  \
                 nebulaOpen := none\n  nebulaNext := none\n",
                index + 1,
                atom_list(next_latest, 1)
            )
            .unwrap();
        }
    }

    fn render_proofs(&mut self, out: &mut String) {
        for (index, proof) in self.corpus.atoms.step_proofs.iter().enumerate() {
            assert!(proof.nebula_open.is_none());
            let fold = match proof.fold {
                FoldAtom::NoFold => ".noFold".to_owned(),
                FoldAtom::Recursive(nifs) => {
                    format!(".recursive {}", atom(nifs + 1))
                }
            };
            let x_out = digest_from_bits(&proof.x_out_bits_little_endian);
            writeln!(
                out,
                "def proof{} : NativeProof where\n  fold := {fold}\n  \
                 nebulaOpen := none\n  semanticStateDigest := {}\n  xOut := {}\n",
                index + 1,
                atom(self.digests.id(proof.semantic_state_digest)),
                atom(self.digests.id(x_out)),
            )
            .unwrap();
        }
    }

    fn render_receipts(&mut self, out: &mut String) {
        let mut names = Vec::with_capacity(self.corpus.cases.len());
        let mut definitions = Vec::with_capacity(self.corpus.cases.len());
        for index in 0..self.corpus.cases.len() {
            let name = lower_camel(&self.corpus.cases[index].name);
            let calls = self.render_calls(index);
            let observed = self.render_observed(index);
            let dispatch = self.render_dispatch(index);
            let outcome = self.render_outcome(index);
            let case = self.corpus.cases[index].clone();
            let vk_fs_digest = self.digests.id(self.corpus.profile.verifier_key_digest);
            let initial_boundary = self.digests.id(self.corpus.profile.initial_boundary_digest);
            let initial_accumulator = self
                .digests
                .id(self.corpus.profile.initial_accumulator_digest);
            let initial_public_trace = self.digests.id(self.corpus.profile.initial_public_trace);
            let authority_running_digest = match &case.authority_running_digest {
                Some(call) => format!(
                    "some ({}, {})",
                    atom(call.running + 1),
                    atom(self.digests.id(call.output))
                ),
                None => "none".to_owned(),
            };
            let mut definition = String::new();
            writeln!(
                definition,
                "def {name} : Receipt where\n  mode := {}\n  context := context\n  \
                 vkFsDigest := {}\n  relationColumns := {}\n  rawEncoding := rawEncoding\n  \
                 emptyRunning := emptyRunning\n  authority := {{ initialBoundary := {}, \
                 initialAccumulator := {}, initialPublicTrace := {}, \
                 priorRunningDigest := {authority_running_digest} }}\n  prior := state{}\n  input := input{}\n  \
                 proof := proof{}\n  dispatch := {dispatch}\n  calls := {calls}\n  \
                 observed := {observed}\n  outcome := {outcome}\n",
                mode(case.mode),
                atom(vk_fs_digest),
                self.corpus.profile.relation.columns,
                atom(initial_boundary),
                atom(initial_accumulator),
                atom(initial_public_trace),
                case.input_state + 1,
                self.case_inputs[index],
                case.step_proof + 1,
            )
            .unwrap();
            names.push(name);
            definitions.push(definition);
        }
        writeln!(
            out,
            "def rawEncoding : RawEncodingTable := {}\n",
            self.render_raw_encoding()
        )
        .unwrap();
        for definition in definitions {
            out.push_str(&definition);
        }
        writeln!(out, "def all : List Receipt := [{}]\n", names.join(", ")).unwrap();
    }

    fn render_raw_encoding(&self) -> String {
        let mut entries = self
            .digests
            .raw_fields
            .iter()
            .enumerate()
            .map(|(index, fields)| {
                format!(
                    "{{ key := .digest {}, fields := {} }}",
                    atom(u32::try_from(index + 1).expect("Lean digest encoding id")),
                    raw_fields(fields)
                )
            })
            .collect::<Vec<_>>();
        entries.push(format!(
            "{{ key := .header ⟨1⟩, fields := {} }}",
            raw_fields(&self.corpus.profile.pi_ccs_header_bundle)
        ));
        format!("[{}]", entries.join(", "))
    }

    fn render_observed(&mut self, case_index: usize) -> String {
        let case = self.corpus.cases[case_index].clone();
        let execution_order = case
            .calls
            .execution_order
            .iter()
            .copied()
            .map(event_kind)
            .collect::<Vec<_>>();
        let chunk_digest = match &case.calls.chunk_digest {
            None => "none".to_owned(),
            Some(call) => format!(
                "some {{ startIndex := {}, orderedClaims := {}, output := {} }}",
                call.start_index,
                atom_list(&call.ordered_claims, 1),
                atom(self.digests.field_digest(call.output)),
            ),
        };
        let transcript = match case.transcript {
            None => "none".to_owned(),
            Some(id) => {
                let receipt = self.corpus.atoms.transcripts[id as usize].clone();
                let appends = receipt
                    .ordered_absorbs
                    .iter()
                    .map(|append| {
                        format!(
                            "{{ label := {}, fields := {} }}",
                            transcript_label(&append.label),
                            raw_fields(&append.fields)
                        )
                    })
                    .collect::<Vec<_>>();
                format!(
                    "some {{ label := {}, orderedAppends := [{}], prefixSnapshot := \
                     {{ state := {}, absorbed := {} }} }}",
                    transcript_label(&receipt.label),
                    appends.join(", "),
                    raw_fields(&receipt.prefix_snapshot.state),
                    receipt.prefix_snapshot.absorbed,
                )
            }
        };
        let nifs_call = match case.calls.nifs_call {
            None => "none".to_owned(),
            Some(id) => {
                let call = self.corpus.atoms.nifs_calls[id as usize].clone();
                let outcome = match call.outcome {
                    NifsOutcome::Accepted(running) => {
                        format!("some {}", atom(running + 1))
                    }
                    NifsOutcome::Rejected(_) => "none".to_owned(),
                };
                format!(
                    "some {{ running := {}, fresh := {}, proof := {}, outcome := {outcome} }}",
                    atom(call.running + 1),
                    atom_list(&call.fresh, 1),
                    atom(call.proof + 1),
                )
            }
        };
        let running_digest = match &case.calls.running_digest {
            None => "none".to_owned(),
            Some(call) => format!(
                "some {{ running := {}, relationColumns := {}, output := {} }}",
                atom(call.running + 1),
                call.relation_columns,
                atom(self.digests.id(call.output)),
            ),
        };
        let advanced_state = case
            .calls
            .advanced_state
            .map_or_else(|| "none".to_owned(), |state| format!("some state{}", state + 1));
        let verifier_digest_read = case.calls.verifier_digest_read.map_or_else(
            || "none".to_owned(),
            |digest| format!("some {}", atom(self.digests.id(digest))),
        );
        let pi_ccs_header_read = match case.calls.pi_ccs_header_read {
            None => "none".to_owned(),
            Some(header) => {
                assert_eq!(header, self.corpus.profile.pi_ccs_header_bundle);
                "some ⟨1⟩".to_owned()
            }
        };
        assert!(
            case.calls.nebula_digest.is_none(),
            "fixed native-step Lean receipt profile excludes Nebula"
        );
        let state_x_out_hash = match &case.calls.computed_x_out {
            None => "none".to_owned(),
            Some(call) => {
                let output = digest_from_bits(&call.bits_little_endian);
                format!(
                    "some {{ rawPreimage := {}, outputDigest := {}, output := {} }}",
                    raw_fields(&call.preimage),
                    atom(self.digests.id(call.digest)),
                    atom(self.digests.id(output)),
                )
            }
        };
        format!(
            "{{ executionOrder := [{}], chunkDigest := {chunk_digest}, \
             transcript := {transcript}, nifsCall := {nifs_call}, \
             runningDigest := {running_digest}, advancedState := {advanced_state}, \
             verifierDigestRead := {verifier_digest_read}, \
             piCcsHeaderRead := {pi_ccs_header_read}, nebulaDigest := none, \
             stateXOutHash := {state_x_out_hash}, finalStage := {} }}",
            execution_order.join(", "),
            execution_stage(case.final_stage),
        )
    }

    fn render_dispatch(&self, case_index: usize) -> String {
        let case = &self.corpus.cases[case_index];
        let prior = &self.corpus.atoms.states[case.input_state as usize];
        let proof = &self.corpus.atoms.step_proofs[case.step_proof as usize];
        match case.dispatch {
            Dispatch::InitialNoFold => {
                assert!(matches!(prior.branch, StateBranch::Initial));
                assert!(matches!(proof.fold, FoldAtom::NoFold));
                ".initialNoFold".to_owned()
            }
            Dispatch::InitialRecursive => {
                assert!(matches!(prior.branch, StateBranch::Initial));
                let FoldAtom::Recursive(nifs) = proof.fold else {
                    panic!("initial-recursive dispatch has no NIFS proof")
                };
                format!(".initialRecursive {}", atom(nifs + 1))
            }
            Dispatch::ActiveNoFold => {
                assert!(matches!(proof.fold, FoldAtom::NoFold));
                let (running, latest) = self.active_parts(prior);
                format!(".activeNoFold {} {}", atom(running), latest)
            }
            Dispatch::ActiveRecursive => {
                let FoldAtom::Recursive(nifs) = proof.fold else {
                    panic!("active-recursive dispatch has no NIFS proof")
                };
                let (running, latest) = self.active_parts(prior);
                format!(".activeRecursive {} {} {}", atom(running), latest, atom(nifs + 1))
            }
        }
    }

    fn active_parts(&self, state: &StateAtom) -> (u32, String) {
        let StateBranch::Active { running, latest } = state.branch else {
            panic!("active dispatch has an initial prior")
        };
        let latest = &self.corpus.atoms.latest[latest as usize];
        (running + 1, atom_list(&latest.ordered_claims, 1))
    }

    fn render_calls(&mut self, case_index: usize) -> String {
        let case = self.corpus.cases[case_index].clone();
        let prior = self.corpus.atoms.states[case.input_state as usize].clone();
        let mut calls = Vec::new();

        if let Some(chunk) = &case.calls.chunk_digest {
            let output = self.digests.field_digest(chunk.output);
            calls.push(format!(
                ".chunkDigest {} {} {}",
                chunk.start_index,
                atom_list(&chunk.ordered_claims, 1),
                atom(output)
            ));
        }

        if let Some(call_id) = case.calls.nifs_call {
            let call = self.corpus.atoms.nifs_calls[call_id as usize].clone();
            let chunk = case
                .calls
                .chunk_digest
                .as_ref()
                .expect("NIFS call has a chunk digest");
            let context = self.render_nifs_context(&prior, chunk.output);
            let output = match call.outcome {
                NifsOutcome::Accepted(running) => {
                    format!("some {}", atom(running + 1))
                }
                NifsOutcome::Rejected(_) => "none".to_owned(),
            };
            calls.push(format!(
                ".nifs ({context} : NativeNifsContext) {} {} {} ({output})",
                atom(call.running + 1),
                atom_list(&call.fresh, 1),
                atom(call.proof + 1),
            ));
        }

        if let Some(running_digest) = &case.calls.running_digest {
            assert_eq!(
                running_digest.relation_columns, self.corpus.profile.relation.columns,
                "running-digest receipt must use the fixed relation profile"
            );
            calls.push(format!(
                ".runningDigest {} {}",
                atom(running_digest.running + 1),
                atom(self.digests.id(running_digest.output))
            ));
        }

        if let Some(state_id) = case.calls.advanced_state {
            let advanced = self.corpus.atoms.states[state_id as usize].clone();
            let running_digest = case
                .calls
                .running_digest
                .as_ref()
                .expect("observed state advance has an observed running digest");
            let StateBranch::Active {
                running: state_running,
                latest,
            } = advanced.branch
            else {
                panic!("advanced native state is not active")
            };
            assert_eq!(state_running, running_digest.running);
            assert_eq!(
                self.corpus.atoms.latest[latest as usize].ordered_claims,
                case.next_latest
            );
            assert_eq!(advanced.acc_digest, running_digest.output);
        }

        if let Some(computed) = &case.calls.computed_x_out {
            let state_id = case
                .calls
                .advanced_state
                .expect("computed xOut has an advanced state");
            let advanced = self.corpus.atoms.states[state_id as usize].clone();
            assert_eq!(computed.digest, digest_from_bits(&computed.bits_little_endian));
            assert!(
                !computed.preimage.is_empty(),
                "observed state hash has an empty preimage"
            );
            let verifier_digest = case
                .calls
                .verifier_digest_read
                .expect("observed state hash reads the verifier digest");
            assert_eq!(verifier_digest, self.corpus.profile.verifier_key_digest);
            let header = case
                .calls
                .pi_ccs_header_read
                .expect("observed state hash reads the Π_CCS header");
            assert_eq!(header, self.corpus.profile.pi_ccs_header_bundle);
            let verifier = self.digests.id(verifier_digest);
            calls.push(format!(".hash (.verifier context) {}", atom(verifier)));
            assert_eq!(advanced.nebula, "absent");
            assert!(case.calls.nebula_digest.is_none());
            let semantic = match case.mode {
                Mode::Stateless => "none".to_owned(),
                Mode::Stateful => {
                    format!("some {}", atom(self.digests.id(advanced.semantic_state_digest)))
                }
            };
            let preimage = format!(
                "{{ vkFsDigest := {}, piCcsHeader := ⟨1⟩, chunkCount := {}, \
                 stepCount := {}, pc := {}, currentBoundary := {}, \
                 semanticState := {semantic}, construction2Accumulator := {}, \
                 nebula := none }}",
                atom(verifier),
                advanced.chunk_count,
                advanced.step_count,
                advanced.pc,
                atom(self.digests.id(advanced.z_i)),
                atom(self.digests.id(advanced.acc_digest)),
            );
            calls.push(format!(
                ".hash (.stateOutput {preimage}) {}",
                atom(self.digests.id(computed.digest))
            ));
        }

        format!(
            "[{}]",
            if calls.is_empty() {
                String::new()
            } else {
                format!("\n    {}\n  ", calls.join(",\n    "))
            }
        )
    }

    fn render_nifs_context(&mut self, prior: &StateAtom, chunk: [Felt; 4]) -> String {
        format!(
            "{{ chunkCount := {}, stepCount := {}, z0 := {}, zi := {}, \
             initialSemanticState := {}, semanticState := {}, pc := {}, \
             accumulatorDigest := {}, publicTrace := {}, nebula := none, \
             nextChunkDigest := {} }}",
            prior.chunk_count,
            prior.step_count,
            atom(self.digests.id(prior.z_0)),
            atom(self.digests.id(prior.z_i)),
            atom(self.digests.id(prior.initial_semantic_state_digest)),
            atom(self.digests.id(prior.semantic_state_digest)),
            prior.pc,
            atom(self.digests.id(prior.acc_digest)),
            atom(self.digests.id(prior.public_trace)),
            atom(self.digests.field_digest(chunk)),
        )
    }

    fn render_outcome(&self, case_index: usize) -> String {
        let case = &self.corpus.cases[case_index];
        match case.outcome {
            Outcome::Accepted => {
                let next = case
                    .recorded_next
                    .expect("accepted Rust receipt has a next state");
                format!(".accepted state{}", next + 1)
            }
            Outcome::Rejected(error) => {
                assert!(case.recorded_next.is_none());
                format!(".rejected .{}", lean_error(error))
            }
        }
    }
}

fn lean_error(value: StableError) -> &'static str {
    match value {
        StableError::EmptyStep => "emptyStep",
        StableError::FoldProofVariantMismatch => "foldProofVariantMismatch",
        StableError::StateAuthorityMismatch => "stateAuthorityMismatch",
        StableError::StatelessSemanticInvariantViolated => "statelessSemanticInvariantViolated",
        StableError::XOutMismatch => "xOutMismatch",
        StableError::NifsPiDecVerifyRejected | StableError::NifsPiCcsOutputShapeMismatch => "nifsRejected",
    }
}

fn mode(value: Mode) -> &'static str {
    match value {
        Mode::Stateless => ".stateless",
        Mode::Stateful => ".stateful",
    }
}

fn event_kind(value: ExecutionEventKind) -> &'static str {
    match value {
        ExecutionEventKind::ChunkDigest => ".chunkDigest",
        ExecutionEventKind::Dispatch => ".dispatch",
        ExecutionEventKind::TranscriptStarted => ".transcriptStarted",
        ExecutionEventKind::TranscriptAppend => ".transcriptAppend",
        ExecutionEventKind::TranscriptPrefix => ".transcriptPrefix",
        ExecutionEventKind::NifsVerify => ".nifsVerify",
        ExecutionEventKind::RunningDigest => ".runningDigest",
        ExecutionEventKind::StateAdvanced => ".stateAdvanced",
        ExecutionEventKind::VerifierDigestRead => ".verifierDigestRead",
        ExecutionEventKind::PiCcsHeaderRead => ".piCcsHeaderRead",
        ExecutionEventKind::NebulaDigest => ".nebulaDigest",
        ExecutionEventKind::StateXOutHash => ".stateXOutHash",
    }
}

fn execution_stage(value: ExecutionStage) -> &'static str {
    match value {
        ExecutionStage::Entry => ".entry",
        ExecutionStage::ChunkDigest => ".chunkDigest",
        ExecutionStage::Dispatch => ".dispatch",
        ExecutionStage::Nifs => ".nifs",
        ExecutionStage::Nebula => ".nebula",
        ExecutionStage::Advance => ".advance",
        ExecutionStage::Semantic => ".semantic",
        ExecutionStage::XOut => ".xOut",
        ExecutionStage::Complete => ".complete",
    }
}

fn transcript_label(value: &str) -> &'static str {
    match value {
        "neo.fold.clean/f_prime/step/v1" => ".fPrimeStep",
        "f_prime/vk_fs" => ".vkFs",
        "f_prime/pi_ccs_header" => ".piCcsHeader",
        "f_prime/chunk_count_in" => ".chunkCountIn",
        "f_prime/step_count_in" => ".stepCountIn",
        "f_prime/z_0" => ".z0",
        "f_prime/z_i_in" => ".ziIn",
        "f_prime/pc" => ".pc",
        "f_prime/semantic_state_in" => ".semanticStateIn",
        "f_prime/acc_digest_in" => ".accDigestIn",
        "f_prime/public_trace_in" => ".publicTraceIn",
        "f_prime/nebula_lane_in" => ".nebulaLaneIn",
        "f_prime/chunk_digest" => ".chunkDigest",
        other => panic!("unexpected native transcript label {other:?}"),
    }
}

fn raw_fields(values: &[Felt]) -> String {
    let values = values
        .iter()
        .map(|value| value.0.to_string())
        .collect::<Vec<_>>();
    format!("[{}]", values.join(", "))
}

fn atom(value: u32) -> String {
    assert_ne!(value, 0, "zero is the Lean receipt poison atom");
    format!("⟨{value}⟩")
}

fn atom_list(values: &[u32], offset: u32) -> String {
    let values = values
        .iter()
        .map(|value| atom(*value + offset))
        .collect::<Vec<_>>();
    format!("[{}]", values.join(", "))
}

fn digest_from_bits(bits: &[u8]) -> [u8; 32] {
    assert_eq!(bits.len(), 256, "encoded digest must contain 256 bits");
    let mut digest = [0u8; 32];
    for (index, bit) in bits.iter().copied().enumerate() {
        assert!(bit <= 1, "encoded digest receipt is not binary");
        digest[index / 8] |= bit << (index % 8);
    }
    digest
}

fn lower_camel(value: &str) -> String {
    let mut words = value.split('_');
    let mut output = words.next().unwrap_or_default().to_owned();
    for word in words {
        let mut chars = word.chars();
        if let Some(first) = chars.next() {
            output.extend(first.to_uppercase());
            output.extend(chars);
        }
    }
    output
}
