import Nightstream.Implementation.Nebula.NIFS.PiCCS.TranscriptCursorFor

set_option autoImplicit false

namespace tests.NebulaProductPiCcsTranscriptCursorFor

open Nightstream.Implementation.Nebula.ProductPiCcsTranscriptCursorFor

#check fullOutputPayload_length
#check fullOutputFields_length
#check replayRounds_absorbed
#check afterFullOutput_absorbed

end tests.NebulaProductPiCcsTranscriptCursorFor
