import Nightstream.Implementation.Nebula.NIFS.PiCCS.TypedBridge

/-! Regression surface for the exact V2 product-PiCCS row bridge. -/

set_option autoImplicit false

namespace tests.NebulaProductPiCcsTypedBridge

#check Nightstream.Implementation.Nebula.ProductPiCcsTranscriptSemantics.rows_replay_semantics
#check Nightstream.Implementation.Nebula.ProductPiCcsTranscriptSemantics.absorbPublicInput_rows_semantics
#check Nightstream.Implementation.Nebula.ProductPiCcsTypedBridge.valuePreSumcheck_eq_paper
#check Nightstream.Implementation.Nebula.ProductPiCcsTypedBridge.valueRounds_eq_paper
#check Nightstream.Implementation.Nebula.ProductPiCcsTypedBridge.rows_imply_piCcsCheck_true
#check Nightstream.Implementation.Nebula.ProductPiCcsTypedBridge.rows_imply_outgoingState

end tests.NebulaProductPiCcsTypedBridge
