import DirectCcsFPrime.ProofSystem.Production.Impl.ConcretePrior.DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified

/-!
Typed interface for the certified concrete F' prior verifier.

Spec: `specs/ProofSystem/Production/Impl/ConcretePrior/DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.spec.md`
-/

namespace DirectCcsFPrime

namespace DirectParentOnlyProductionConcreteFPrimePriorVerifierCertifiedInterface

abbrev ProductionContext :=
  DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.ProductionContext

abbrev PublicImage :=
  DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.PublicImage

abbrev ProofCarryingPriorProof :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.ProofCarryingPriorProof

abbrev ConcretePriorVerifierSurface :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.ConcretePriorVerifierSurface

abbrev ConcreteVerifyPrior :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.ConcreteVerifyPrior

abbrev CertifiedPriorVerifier :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.CertifiedPriorVerifier

abbrev SoundPriorVerifier :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.SoundPriorVerifier

abbrev ConcreteRuntimeExactPublicIOSurface :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.ConcreteRuntimeExactPublicIOSurface

abbrev ExactPublicIOLayoutBinding :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.ExactPublicIOLayoutBinding

abbrev RuntimeVerifyPriorOfExactPublicIO :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.RuntimeVerifyPriorOfExactPublicIO

abbrev priorAuthorityOpenerOfConcretePriorVerifierSurface :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.priorAuthorityOpenerOfConcretePriorVerifierSurface

abbrev priorAuthorityOpenerOfConcretePriorVerifierSurface_openAuthority :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.priorAuthorityOpenerOfConcretePriorVerifierSurface_openAuthority

abbrev priorVerifierAuthorityOpeningOfConcretePriorVerifierSurface :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.priorVerifierAuthorityOpeningOfConcretePriorVerifierSurface

abbrev certifiedPriorVerifierOfConcretePriorVerifierSurface :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.certifiedPriorVerifierOfConcretePriorVerifierSurface

abbrev certifiedPriorVerifierOfConcretePriorVerifierSurface_verify :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.certifiedPriorVerifierOfConcretePriorVerifierSurface_verify

abbrev certifiedPriorVerifierOfConcretePriorVerifierSurface_opener :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.certifiedPriorVerifierOfConcretePriorVerifierSurface_opener

abbrev concreteVerifyPrior_certifiedAcceptedOpens :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.concreteVerifyPrior_certifiedAcceptedOpens

abbrev concretePriorVerifierSurfaceOfExactRuntimeSoundAndLayout :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.concretePriorVerifierSurfaceOfExactRuntimeSoundAndLayout

abbrev concretePriorVerifierSurfaceOfExactRuntimeSoundAndLayout_openAuthority :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.concretePriorVerifierSurfaceOfExactRuntimeSoundAndLayout_openAuthority

abbrev runtimeVerifyPriorOfExactRuntimeSoundAndLayout_toConcreteVerifyPrior :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.runtimeVerifyPriorOfExactRuntimeSoundAndLayout_toConcreteVerifyPrior

abbrev certifiedPriorVerifierOfExactRuntimeSoundAndLayout :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.certifiedPriorVerifierOfExactRuntimeSoundAndLayout

abbrev certifiedPriorVerifierOfExactRuntimeSoundAndLayout_verify :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.certifiedPriorVerifierOfExactRuntimeSoundAndLayout_verify

abbrev soundVerifierOfExactRuntimeSoundAndLayout :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.soundVerifierOfExactRuntimeSoundAndLayout

abbrev soundVerifierOfExactRuntimeSoundAndLayout_accepts_iff :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.soundVerifierOfExactRuntimeSoundAndLayout_accepts_iff

abbrev soundVerifierOfExactRuntimeSoundAndLayout_opensToFoldedAuthority :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.soundVerifierOfExactRuntimeSoundAndLayout_opensToFoldedAuthority

abbrev soundVerifierOfExactRuntimeSoundAndLayout_openedAuthority_accepts :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.soundVerifierOfExactRuntimeSoundAndLayout_openedAuthority_accepts

abbrev soundVerifierOfExactRuntimeSoundAndLayout_bindsOpenedAuthoritySteps :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.soundVerifierOfExactRuntimeSoundAndLayout_bindsOpenedAuthoritySteps

abbrev soundVerifierOfExactRuntimeSoundAndLayout_bindsOpenedAuthorityImage :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.soundVerifierOfExactRuntimeSoundAndLayout_bindsOpenedAuthorityImage

abbrev soundVerifierOfExactRuntimeSoundAndLayout_openAuthority_ne_none :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.soundVerifierOfExactRuntimeSoundAndLayout_openAuthority_ne_none

abbrev soundVerifierOfExactRuntimeSoundAndLayout_cannot_accept_without_opening :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.soundVerifierOfExactRuntimeSoundAndLayout_cannot_accept_without_opening

abbrev soundVerifierOfExactRuntimeSoundAndLayout_reaches_prior :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.soundVerifierOfExactRuntimeSoundAndLayout_reaches_prior

abbrev soundVerifierOfExactRuntimeSoundAndLayout_publicImageInvariants :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.soundVerifierOfExactRuntimeSoundAndLayout_publicImageInvariants

abbrev soundVerifierOfExactRuntimeSoundAndLayout_cannot_accept_unreachable_prior :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.soundVerifierOfExactRuntimeSoundAndLayout_cannot_accept_unreachable_prior

abbrev soundVerifierOfExactRuntimeSoundAndLayout_proofFunctional :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.soundVerifierOfExactRuntimeSoundAndLayout_proofFunctional

abbrev soundVerifierOfExactRuntimeSoundAndLayout_sameProof :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.soundVerifierOfExactRuntimeSoundAndLayout_sameProof

abbrev acceptedTerminalWithSoundVerifierOfExactRuntimeSoundAndLayoutLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.acceptedTerminalWithSoundVerifierOfExactRuntimeSoundAndLayoutLatestStep

abbrev runtimeVerifyPriorOfExactRuntimeSoundAndLayout_certifiedAcceptedOpens :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.runtimeVerifyPriorOfExactRuntimeSoundAndLayout_certifiedAcceptedOpens

abbrev runtimeVerifyPriorOfExactRuntimeSoundAndLayout_opensAuthority :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.runtimeVerifyPriorOfExactRuntimeSoundAndLayout_opensAuthority

abbrev runtimeVerifyPriorOfExactRuntimeSoundAndLayout_openedAuthority_accepts :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.runtimeVerifyPriorOfExactRuntimeSoundAndLayout_openedAuthority_accepts

abbrev runtimeVerifyPriorOfExactRuntimeSoundAndLayout_bindsOpenedAuthoritySteps :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.runtimeVerifyPriorOfExactRuntimeSoundAndLayout_bindsOpenedAuthoritySteps

abbrev runtimeVerifyPriorOfExactRuntimeSoundAndLayout_bindsOpenedAuthorityImage :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.runtimeVerifyPriorOfExactRuntimeSoundAndLayout_bindsOpenedAuthorityImage

abbrev runtimeVerifyPriorOfExactRuntimeSoundAndLayout_cannot_accept_without_opening :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.runtimeVerifyPriorOfExactRuntimeSoundAndLayout_cannot_accept_without_opening

abbrev runtimeVerifyPriorOfExactRuntimeSoundAndLayout_openAuthority_ne_none :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.runtimeVerifyPriorOfExactRuntimeSoundAndLayout_openAuthority_ne_none

abbrev runtimeVerifyPriorOfExactRuntimeSoundAndLayout_publicImageInvariants :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.runtimeVerifyPriorOfExactRuntimeSoundAndLayout_publicImageInvariants

abbrev proofFunctionalOfExactRuntimeSoundAndLayout :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.proofFunctionalOfExactRuntimeSoundAndLayout

abbrev concreteVerifyPrior_reaches_prior :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.concreteVerifyPrior_reaches_prior

abbrev concreteVerifyPrior_cannot_accept_unreachable_prior :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.concreteVerifyPrior_cannot_accept_unreachable_prior

abbrev runtimeVerifyPriorOfExactRuntimeSoundAndLayout_reaches_prior :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.runtimeVerifyPriorOfExactRuntimeSoundAndLayout_reaches_prior

abbrev runtimeVerifyPriorOfExactRuntimeSoundAndLayout_cannot_accept_unreachable_prior :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.runtimeVerifyPriorOfExactRuntimeSoundAndLayout_cannot_accept_unreachable_prior

abbrev certifiedSingleTerminalEndToEnd_ofConcretePriorVerifierLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.certifiedSingleTerminalEndToEnd_ofConcretePriorVerifierLatestStep

abbrev certifiedSingleTerminalEndToEnd_ofExactRuntimeSoundAndLayoutLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierCertified.certifiedSingleTerminalEndToEnd_ofExactRuntimeSoundAndLayoutLatestStep

end DirectParentOnlyProductionConcreteFPrimePriorVerifierCertifiedInterface

end DirectCcsFPrime
