import DirectCcsFPrime.ProofSystem.Production.Impl.ConcretePrior.DirectParentOnlyProductionConcreteFPrimePriorAuthority

/-!
Typed interface for the concrete prior F' verifier authority bridge.

Spec: `specs/ProofSystem/Production/Impl/ConcretePrior/DirectParentOnlyProductionConcreteFPrimePrior.spec.md`
-/

namespace DirectCcsFPrime

namespace DirectParentOnlyProductionConcreteFPrimePriorInterface

abbrev ProductionContext :=
  DirectParentOnlyProductionConcreteFPrimePrior.ProductionContext

abbrev PublicImage :=
  DirectParentOnlyProductionConcreteFPrimePrior.PublicImage

abbrev ProofCarryingPriorProof :=
  @DirectParentOnlyProductionConcreteFPrimePrior.ProofCarryingPriorProof

abbrev ConcreteVerifierBody :=
  @DirectParentOnlyProductionConcreteFPrimePrior.ConcreteVerifierBody

abbrev ConcreteVerifierBodyChecks :=
  @DirectParentOnlyProductionConcreteFPrimePrior.ConcreteVerifierBodyChecks

abbrev ConcreteVerifierStatementBinding :=
  @DirectParentOnlyProductionConcreteFPrimePrior.ConcreteVerifierStatementBinding

abbrev ConcreteVerifierStatementSurface :=
  @DirectParentOnlyProductionConcreteFPrimePrior.ConcreteVerifierStatementSurface

abbrev ConcretePriorVerifier :=
  @DirectParentOnlyProductionConcreteFPrimePrior.ConcretePriorVerifier

abbrev concreteVerifierBodyOfChecks :=
  @DirectParentOnlyProductionConcreteFPrimePrior.concreteVerifierBodyOfChecks

abbrev concreteVerifierBodyChecksOfStatementBinding :=
  @DirectParentOnlyProductionConcreteFPrimePrior.concreteVerifierBodyChecksOfStatementBinding

abbrev concreteVerifierBodyOfStatementBinding :=
  @DirectParentOnlyProductionConcreteFPrimePrior.concreteVerifierBodyOfStatementBinding

abbrev concreteVerifierStatementBindingOfSurface :=
  @DirectParentOnlyProductionConcreteFPrimePrior.concreteVerifierStatementBindingOfSurface

abbrev concreteVerifierBodyChecksOfStatementSurface :=
  @DirectParentOnlyProductionConcreteFPrimePrior.concreteVerifierBodyChecksOfStatementSurface

abbrev concreteVerifierBodyOfStatementSurface :=
  @DirectParentOnlyProductionConcreteFPrimePrior.concreteVerifierBodyOfStatementSurface

abbrev VerifyPrior :=
  @DirectParentOnlyProductionConcreteFPrimePrior.VerifyPrior

abbrev VerifyPriorOfChecks :=
  @DirectParentOnlyProductionConcreteFPrimePrior.VerifyPriorOfChecks

abbrev VerifyPriorOfStatementBinding :=
  @DirectParentOnlyProductionConcreteFPrimePrior.VerifyPriorOfStatementBinding

abbrev VerifyPriorOfStatementSurface :=
  @DirectParentOnlyProductionConcreteFPrimePrior.VerifyPriorOfStatementSurface

abbrev authorityOpener :=
  @DirectParentOnlyProductionConcreteFPrimePrior.authorityOpener

abbrev authorityOpenerOfChecks :=
  @DirectParentOnlyProductionConcreteFPrimePrior.authorityOpenerOfChecks

abbrev authorityOpenerOfStatementBinding :=
  @DirectParentOnlyProductionConcreteFPrimePrior.authorityOpenerOfStatementBinding

abbrev authorityOpenerOfStatementSurface :=
  @DirectParentOnlyProductionConcreteFPrimePrior.authorityOpenerOfStatementSurface

abbrev acceptedOpens :=
  @DirectParentOnlyProductionConcreteFPrimePrior.acceptedOpens

abbrev acceptedOpensOfChecks :=
  @DirectParentOnlyProductionConcreteFPrimePrior.acceptedOpensOfChecks

abbrev acceptedOpensOfStatementBinding :=
  @DirectParentOnlyProductionConcreteFPrimePrior.acceptedOpensOfStatementBinding

abbrev acceptedOpensOfStatementSurface :=
  @DirectParentOnlyProductionConcreteFPrimePrior.acceptedOpensOfStatementSurface

abbrev priorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionConcreteFPrimePrior.priorVerifierAuthorityOpening

abbrev priorVerifierAuthorityOpeningOfChecks :=
  @DirectParentOnlyProductionConcreteFPrimePrior.priorVerifierAuthorityOpeningOfChecks

abbrev priorVerifierAuthorityOpeningOfStatementBinding :=
  @DirectParentOnlyProductionConcreteFPrimePrior.priorVerifierAuthorityOpeningOfStatementBinding

abbrev priorVerifierAuthorityOpeningOfStatementSurface :=
  @DirectParentOnlyProductionConcreteFPrimePrior.priorVerifierAuthorityOpeningOfStatementSurface

abbrev certifiedPriorVerifier :=
  @DirectParentOnlyProductionConcreteFPrimePrior.certifiedPriorVerifier

abbrev certifiedPriorVerifierOfChecks :=
  @DirectParentOnlyProductionConcreteFPrimePrior.certifiedPriorVerifierOfChecks

abbrev certifiedPriorVerifierOfStatementBinding :=
  @DirectParentOnlyProductionConcreteFPrimePrior.certifiedPriorVerifierOfStatementBinding

abbrev certifiedPriorVerifierOfStatementSurface :=
  @DirectParentOnlyProductionConcreteFPrimePrior.certifiedPriorVerifierOfStatementSurface

abbrev certifiedPriorVerifier_verify :=
  @DirectParentOnlyProductionConcreteFPrimePrior.certifiedPriorVerifier_verify

abbrev certifiedPriorVerifierOfChecks_verify :=
  @DirectParentOnlyProductionConcreteFPrimePrior.certifiedPriorVerifierOfChecks_verify

abbrev certifiedPriorVerifierOfStatementBinding_verify :=
  @DirectParentOnlyProductionConcreteFPrimePrior.certifiedPriorVerifierOfStatementBinding_verify

abbrev certifiedPriorVerifierOfStatementSurface_verify :=
  @DirectParentOnlyProductionConcreteFPrimePrior.certifiedPriorVerifierOfStatementSurface_verify

abbrev verifyPrior_openAuthority_ne_none :=
  @DirectParentOnlyProductionConcreteFPrimePrior.verifyPrior_openAuthority_ne_none

abbrev verifyPriorOfChecks_openAuthority_ne_none :=
  @DirectParentOnlyProductionConcreteFPrimePrior.verifyPriorOfChecks_openAuthority_ne_none

abbrev verifyPriorOfStatementSurface_openAuthority_ne_none :=
  @DirectParentOnlyProductionConcreteFPrimePrior.verifyPriorOfStatementSurface_openAuthority_ne_none

abbrev verifyPrior_openedAuthority_accepts_of_open :=
  @DirectParentOnlyProductionConcreteFPrimePrior.verifyPrior_openedAuthority_accepts_of_open

abbrev verifyPriorOfChecks_openedAuthority_accepts_of_open :=
  @DirectParentOnlyProductionConcreteFPrimePrior.verifyPriorOfChecks_openedAuthority_accepts_of_open

abbrev verifyPriorOfStatementBinding_openedAuthority_accepts_of_open :=
  @DirectParentOnlyProductionConcreteFPrimePrior.verifyPriorOfStatementBinding_openedAuthority_accepts_of_open

abbrev verifyPriorOfStatementSurface_openedAuthority_accepts_of_open :=
  @DirectParentOnlyProductionConcreteFPrimePrior.verifyPriorOfStatementSurface_openedAuthority_accepts_of_open

abbrev verifyPrior_reaches_prior :=
  @DirectParentOnlyProductionConcreteFPrimePrior.verifyPrior_reaches_prior

abbrev verifyPriorOfChecks_reaches_prior :=
  @DirectParentOnlyProductionConcreteFPrimePrior.verifyPriorOfChecks_reaches_prior

abbrev verifyPriorOfStatementBinding_reaches_prior :=
  @DirectParentOnlyProductionConcreteFPrimePrior.verifyPriorOfStatementBinding_reaches_prior

abbrev verifyPriorOfStatementSurface_reaches_prior :=
  @DirectParentOnlyProductionConcreteFPrimePrior.verifyPriorOfStatementSurface_reaches_prior

abbrev verifyPrior_cannot_accept_unreachable_prior :=
  @DirectParentOnlyProductionConcreteFPrimePrior.verifyPrior_cannot_accept_unreachable_prior

abbrev verifyPriorOfChecks_cannot_accept_unreachable_prior :=
  @DirectParentOnlyProductionConcreteFPrimePrior.verifyPriorOfChecks_cannot_accept_unreachable_prior

abbrev verifyPriorOfStatementBinding_cannot_accept_unreachable_prior :=
  @DirectParentOnlyProductionConcreteFPrimePrior.verifyPriorOfStatementBinding_cannot_accept_unreachable_prior

abbrev verifyPriorOfStatementSurface_cannot_accept_unreachable_prior :=
  @DirectParentOnlyProductionConcreteFPrimePrior.verifyPriorOfStatementSurface_cannot_accept_unreachable_prior

abbrev AcceptedPriorPublicImageInvariants :=
  @DirectParentOnlyProductionConcreteFPrimePrior.AcceptedPriorPublicImageInvariants

abbrev verifyPrior_publicImageInvariants :=
  @DirectParentOnlyProductionConcreteFPrimePrior.verifyPrior_publicImageInvariants

abbrev verifyPriorOfChecks_publicImageInvariants :=
  @DirectParentOnlyProductionConcreteFPrimePrior.verifyPriorOfChecks_publicImageInvariants

abbrev verifyPriorOfStatementBinding_publicImageInvariants :=
  @DirectParentOnlyProductionConcreteFPrimePrior.verifyPriorOfStatementBinding_publicImageInvariants

abbrev verifyPriorOfStatementSurface_publicImageInvariants :=
  @DirectParentOnlyProductionConcreteFPrimePrior.verifyPriorOfStatementSurface_publicImageInvariants

abbrev proofFunctional :=
  @DirectParentOnlyProductionConcreteFPrimePrior.proofFunctional

abbrev proofFunctionalOfChecks :=
  @DirectParentOnlyProductionConcreteFPrimePrior.proofFunctionalOfChecks

abbrev proofFunctionalOfStatementSurface :=
  @DirectParentOnlyProductionConcreteFPrimePrior.proofFunctionalOfStatementSurface

abbrev certifiedSingleTerminalEndToEnd_ofConcretePriorVerifierLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePrior.certifiedSingleTerminalEndToEnd_ofConcretePriorVerifierLatestStep

abbrev certifiedSingleTerminalEndToEnd_ofConcreteVerifierChecksLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePrior.certifiedSingleTerminalEndToEnd_ofConcreteVerifierChecksLatestStep

abbrev certifiedSingleTerminalEndToEnd_ofConcreteVerifierStatementSurfaceLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePrior.certifiedSingleTerminalEndToEnd_ofConcreteVerifierStatementSurfaceLatestStep

abbrev nonAggregatePrivateDecStageFacts_ofConcretePriorVerifierLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePrior.nonAggregatePrivateDecStageFacts_ofConcretePriorVerifierLatestStep

abbrev nonAggregatePrivateDecStageFacts_ofConcreteVerifierChecksLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePrior.nonAggregatePrivateDecStageFacts_ofConcreteVerifierChecksLatestStep

abbrev section71StageTargetAuditTrail_ofConcretePriorVerifierLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePrior.section71StageTargetAuditTrail_ofConcretePriorVerifierLatestStep

abbrev section71StageTargetAuditTrail_ofConcreteVerifierChecksLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePrior.section71StageTargetAuditTrail_ofConcreteVerifierChecksLatestStep

end DirectParentOnlyProductionConcreteFPrimePriorInterface

end DirectCcsFPrime
