import DirectCcsFPrime.ProofSystem.Production.Impl.ConcretePrior.DirectParentOnlyProductionConcreteFPrimePriorVerifierTarget

/-!
Typed interface for the concrete F' prior verifier target.

Spec: `specs/ProofSystem/Production/Impl/ConcretePrior/DirectParentOnlyProductionConcreteFPrimePriorVerifierTarget.spec.md`
-/

namespace DirectCcsFPrime

namespace DirectParentOnlyProductionConcreteFPrimePriorVerifierTargetInterface

abbrev ProductionContext :=
  DirectParentOnlyProductionConcreteFPrimePriorVerifierTarget.ProductionContext

abbrev PublicImage :=
  DirectParentOnlyProductionConcreteFPrimePriorVerifierTarget.PublicImage

abbrev ProofCarryingPriorProof :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierTarget.ProofCarryingPriorProof

abbrev ExactTerminalBoundaryPublicIO :=
  DirectParentOnlyProductionConcreteFPrimePriorVerifierTarget.ExactTerminalBoundaryPublicIO

abbrev ConcretePriorVerifierSurface :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierTarget.ConcretePriorVerifierSurface

abbrev ConcreteVerifyPrior :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierTarget.ConcreteVerifyPrior

abbrev ConcreteFPrimeAuthorityTarget :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierTarget.ConcreteFPrimeAuthorityTarget

abbrev ConcreteVerifyPriorReplayEvidence :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierTarget.ConcreteVerifyPriorReplayEvidence

abbrev concreteVerifyPrior_replayEvidence :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierTarget.concreteVerifyPrior_replayEvidence

abbrev concreteVerifyPrior_bindsProofStatement :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierTarget.concreteVerifyPrior_bindsProofStatement

abbrev concreteVerifyPrior_opensAuthority :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierTarget.concreteVerifyPrior_opensAuthority

abbrev concreteVerifyPrior_openedAuthority_accepts :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierTarget.concreteVerifyPrior_openedAuthority_accepts

abbrev concreteVerifyPrior_bindsOpenedAuthoritySteps :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierTarget.concreteVerifyPrior_bindsOpenedAuthoritySteps

abbrev concreteVerifyPrior_bindsOpenedAuthorityImage :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierTarget.concreteVerifyPrior_bindsOpenedAuthorityImage

abbrev concreteFPrimeAuthorityTarget_holds :=
  @DirectParentOnlyProductionConcreteFPrimePriorVerifierTarget.concreteFPrimeAuthorityTarget_holds

end DirectParentOnlyProductionConcreteFPrimePriorVerifierTargetInterface

end DirectCcsFPrime
