import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.StreamingLifecycleRelation
import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.StreamingPreludeRelationArtifact
import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.StreamingPreludeXOutLifecycleBridge
import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.StreamingPaperNifsAuthority
import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.StreamingLifecycleRecursiveVerifierKeyBinding
import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.StreamingLifecycleSourceSemanticLinkArtifact
import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.StreamingPiRLCFamilyLifecycleBridge
import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.StreamingPhasedLifecycleRelation
import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.StreamingPriorStateReplayLifecycleBridge
import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.StreamingPiRLCFamilyPhasedLifecycle
import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.StreamingPiRLCFamilyTerminalLifecycle
import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.StreamingTerminalFullFinalizerTransitionRowSound
import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.StreamingTerminalFullFinalizerTransitionSound
import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.StreamingTerminalFullFinalizerLifecycleBridge
import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.StreamingTerminalXOutPoseidonOutputCopyBridge
import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.StreamingTerminalXOutPublicBinding
import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.StreamingTerminalXOutSourceFinalBridge
import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.StreamingTerminalFinalSelectiveLifecycleBridge
import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.StreamingTerminalLifecycleBridge

/-!
Owner facade for the streaming base, recursive, and terminal lifecycle
semantics and their current source-row refinement leaves.

This facade does not claim that the complete generated selective relation
implies the lifecycle relation. That composition theorem is still open.
-/
