import Nightstream.Implementation.Nebula.NIFS.PiDEC.TypedBridgeFor

set_option autoImplicit false

namespace tests.NebulaProductPiDecTypedBridgeFor

open Nightstream.Implementation.Nebula.ProductPiDecTypedBridgeFor

#check typedEquations_of_rows
#check paperAccepted_of_rows_for_attempt

end tests.NebulaProductPiDecTypedBridgeFor
