//! Exact Rust evidence for the SplitNc completed-carrier boundary.
//!
//! Owns: one deterministic `m = 257` witness pair evaluated by the production
//! packed-witness validation, logical/full decoding, and `y_zcol` helpers; and
//! a byte-for-byte drift gate for the generated Lean data module.
//!
//! Does not own: NIFS/F-prime acceptance, independent NC semantics, a general
//! verifier-refinement theorem, R1CS lowering, constraint removal, or counts.
//!
//! | Protocol | Phase | Family | Exported evidence |
//! |---|---|---|---|
//! | Pi_CCS SplitNc | packed witness | shape validation | both `54 x 5` matrices are shape-valid for `m = 257` |
//! | Pi_CCS SplitNc | source decoding | logical / full carrier | logical views agree while complete-carrier views differ at coordinate 257 |
//! | Pi_CCS SplitNc | public projection | `y_zcol` | the production logical-width projection agrees for the pair |
//! | Pi_CCS SplitNc | optimized protocol | prove / verify | complete public API accepts both exact witnesses |
//! | implementation refinement | Rust to Lean | artifact drift | exact generated bytes or a review-only `.expected` file |

use std::sync::Arc;

use neo_ajtai::{setup as ajtai_setup, AjtaiSModule};
use neo_ccs::traits::SModuleHomomorphism;
use neo_ccs::{CcsClaim, CcsStructure, CcsWitness, Mat, SparsePoly};
use neo_math::{KExtensions, D, F, K};
use neo_params::NeoParams;
use neo_reductions::api::{prove, verify, FoldingMode};
use neo_reductions::common::{
    compute_y_zcol_from_witness, decode_superneo_coeffs_from_witness_mat, decode_z_from_witness_mat,
    validate_superneo_witness_mat,
};
use neo_transcript::Transcript;
use p3_field::{PrimeCharacteristicRing, PrimeField64};
use rand_chacha::rand_core::SeedableRng;
use rand_chacha::ChaCha8Rng;

const LOGICAL_WIDTH: usize = 257;
const PACKED_COLUMN_COUNT: usize = LOGICAL_WIDTH.div_ceil(D);
const FIRST_COMPLETED_TAIL: usize = LOGICAL_WIDTH;
const FIRST_TAIL_BLOCK: usize = FIRST_COMPLETED_TAIL / D;
const FIRST_TAIL_LANE: usize = FIRST_COMPLETED_TAIL % D;
const ARTIFACT_REL_PATH: &str = "/../../formal/nightstream-lean/Nightstream/Implementation/R1CS/Artifacts/PiCcsNc/Generated/PiCcsNcCarrierArtifact.lean";

struct Snapshot {
    nc_bound: u32,
    zero_shape_accepted: bool,
    tail_shape_accepted: bool,
    zero_packed_storage: Vec<u64>,
    tail_packed_storage: Vec<u64>,
    zero_logical_decode: Vec<(u64, u64)>,
    tail_logical_decode: Vec<(u64, u64)>,
    zero_full_decode: Vec<(u64, u64)>,
    tail_full_decode: Vec<(u64, u64)>,
    zero_y_zcol: Vec<(u64, u64)>,
    tail_y_zcol: Vec<(u64, u64)>,
    zero_pi_ccs_accepted: bool,
    tail_pi_ccs_accepted: bool,
}

fn extension_pairs(values: &[K]) -> Vec<(u64, u64)> {
    values.iter().map(KExtensions::to_limbs_u64).collect()
}

fn pi_ccs_accepts(params: &NeoParams, witness_matrix: &Mat<F>) -> bool {
    let structure = CcsStructure::new(vec![Mat::identity(LOGICAL_WIDTH)], SparsePoly::new(1, Vec::new()))
        .expect("minimal zero-relation CCS structure");
    let mut rng = ChaCha8Rng::seed_from_u64(0x5049_4343_535f_4e43);
    let public_parameters =
        ajtai_setup(&mut rng, D, params.kappa as usize, LOGICAL_WIDTH.div_ceil(D)).expect("minimal Ajtai setup");
    let commitment_scheme = AjtaiSModule::new(Arc::new(public_parameters));
    let claim = CcsClaim {
        adv: None,
        c: commitment_scheme.commit(witness_matrix),
        x: Vec::new(),
        m_in: 0,
    };
    let witness = CcsWitness {
        w: vec![F::ZERO; LOGICAL_WIDTH],
        Z: witness_matrix.clone(),
    };

    const TRANSCRIPT_LABEL: &[u8] = b"nightstream/pi_ccs_nc_carrier_artifact/v1";
    let mut prover_transcript = neo_transcript::Poseidon2Transcript::new(TRANSCRIPT_LABEL);
    let (outputs, proof) = prove(
        FoldingMode::Optimized,
        &mut prover_transcript,
        params,
        &structure,
        core::slice::from_ref(&claim),
        core::slice::from_ref(&witness),
        &[],
        &[],
        &commitment_scheme,
    )
    .unwrap_or_else(|error| panic!("minimal Pi_CCS prover execution failed: {error}"));

    let mut verifier_transcript = neo_transcript::Poseidon2Transcript::new(TRANSCRIPT_LABEL);
    verify(
        FoldingMode::Optimized,
        &mut verifier_transcript,
        params,
        &structure,
        core::slice::from_ref(&claim),
        &[],
        &outputs,
        &proof,
    )
    .unwrap_or_else(|error| panic!("minimal Pi_CCS verifier execution failed: {error}"))
}

fn capture() -> Snapshot {
    let params = NeoParams::goldilocks_auto_r1cs_ccs(LOGICAL_WIDTH).expect("minimal SplitNc parameters");
    assert_eq!(params.b, 2, "the semantic counterexample uses the b = 2 NC alphabet");
    let zero = Mat::zero(D, PACKED_COLUMN_COUNT, F::ZERO);
    let mut tail = zero.clone();
    tail[(FIRST_TAIL_LANE, FIRST_TAIL_BLOCK)] = F::from_u64(2);

    let zero_shape_accepted = validate_superneo_witness_mat(&zero, LOGICAL_WIDTH).is_ok();
    let tail_shape_accepted = validate_superneo_witness_mat(&tail, LOGICAL_WIDTH).is_ok();
    let zero_logical_decode =
        decode_z_from_witness_mat(&params, &zero, LOGICAL_WIDTH).expect("zero witness has the production packed shape");
    let tail_logical_decode =
        decode_z_from_witness_mat(&params, &tail, LOGICAL_WIDTH).expect("tail witness has the production packed shape");
    let zero_full_decode = decode_superneo_coeffs_from_witness_mat(&zero, LOGICAL_WIDTH)
        .expect("zero witness has the production packed shape");
    let tail_full_decode = decode_superneo_coeffs_from_witness_mat(&tail, LOGICAL_WIDTH)
        .expect("tail witness has the production packed shape");
    let chi_s = vec![K::ONE; LOGICAL_WIDTH];
    let zero_y_zcol = compute_y_zcol_from_witness(&params, &zero, LOGICAL_WIDTH, &chi_s, D.next_power_of_two())
        .expect("zero witness has the production packed shape");
    let tail_y_zcol = compute_y_zcol_from_witness(&params, &tail, LOGICAL_WIDTH, &chi_s, D.next_power_of_two())
        .expect("tail witness has the production packed shape");

    Snapshot {
        nc_bound: params.b,
        zero_shape_accepted,
        tail_shape_accepted,
        zero_packed_storage: zero
            .as_slice()
            .iter()
            .map(PrimeField64::as_canonical_u64)
            .collect(),
        tail_packed_storage: tail
            .as_slice()
            .iter()
            .map(PrimeField64::as_canonical_u64)
            .collect(),
        zero_logical_decode: extension_pairs(&zero_logical_decode),
        tail_logical_decode: extension_pairs(&tail_logical_decode),
        zero_full_decode: extension_pairs(&zero_full_decode),
        tail_full_decode: extension_pairs(&tail_full_decode),
        zero_y_zcol: extension_pairs(&zero_y_zcol),
        tail_y_zcol: extension_pairs(&tail_y_zcol),
        zero_pi_ccs_accepted: pi_ccs_accepts(&params, &zero),
        tail_pi_ccs_accepted: pi_ccs_accepts(&params, &tail),
    }
}

fn render_nat_list(values: &[u64]) -> String {
    if values.iter().all(|value| *value == 0) {
        return format!("List.replicate {} 0", values.len());
    }
    let nonzero: Vec<(usize, u64)> = values
        .iter()
        .copied()
        .enumerate()
        .filter(|(_, value)| *value != 0)
        .collect();
    if let [(index, value)] = nonzero.as_slice() {
        return format!("(List.replicate {} 0).set {index} {value}", values.len());
    }
    let values: Vec<String> = values.iter().map(u64::to_string).collect();
    format!("[{}]", values.join(", "))
}

fn render_extension_list(values: &[(u64, u64)]) -> String {
    if values.iter().all(|value| *value == (0, 0)) {
        return format!("List.replicate {} (0, 0)", values.len());
    }
    let nonzero: Vec<(usize, (u64, u64))> = values
        .iter()
        .copied()
        .enumerate()
        .filter(|(_, value)| *value != (0, 0))
        .collect();
    if let [(index, (c0, c1))] = nonzero.as_slice() {
        return format!("(List.replicate {} (0, 0)).set {index} ({c0}, {c1})", values.len());
    }
    let values: Vec<String> = values
        .iter()
        .map(|(c0, c1)| format!("({c0}, {c1})"))
        .collect();
    format!("[{}]", values.join(", "))
}

fn emit_lean(snapshot: &Snapshot) -> String {
    let mut out = String::new();
    out.push_str("import Nightstream.SuperNeo.Concrete.Algebra\n\n");
    out.push_str("/-!\nGENERATED FILE - do not edit by hand.\n\n");
    out.push_str("Exact outputs of the optimized production Pi_CCS path for one `m = 257`,\n");
    out.push_str("`b = 2` pair that differs only at completed carrier coordinate 257.\n");
    out.push_str("Regenerated and\n");
    out.push_str("drift-checked by\n");
    out.push_str("`cargo test -p neo-reductions --release --test pi_ccs_nc_carrier_lean_artifact`.\n\n");
    out.push_str("This is implementation evidence, not semantic authority. The booleans record\n");
    out.push_str("exact optimized Pi_CCS public-API executions; they do not establish a general\n");
    out.push_str("Rust refinement theorem or any NIFS/F-prime acceptance claim.\n-/\n\n");
    out.push_str("namespace Nightstream.Implementation.R1CS.PiCcsNcCarrierArtifact\n\n");
    out.push_str(&format!("def ringDegree : Nat := {D}\n"));
    out.push_str(&format!("def logicalWidth : Nat := {LOGICAL_WIDTH}\n"));
    out.push_str(&format!("def ncBound : Nat := {}\n", snapshot.nc_bound));
    out.push_str(&format!("def packedColumnCount : Nat := {PACKED_COLUMN_COUNT}\n"));
    out.push_str(&format!("def firstCompletedTail : Nat := {FIRST_COMPLETED_TAIL}\n"));
    out.push_str(&format!("def firstTailBlock : Nat := {FIRST_TAIL_BLOCK}\n"));
    out.push_str(&format!("def firstTailLane : Nat := {FIRST_TAIL_LANE}\n"));
    out.push_str(&format!(
        "def zeroShapeAccepted : Bool := {}\n",
        snapshot.zero_shape_accepted
    ));
    out.push_str(&format!(
        "def tailShapeAccepted : Bool := {}\n\n",
        snapshot.tail_shape_accepted
    ));
    out.push_str(&format!(
        "def zeroPiCcsAccepted : Bool := {}\n",
        snapshot.zero_pi_ccs_accepted
    ));
    out.push_str(&format!(
        "def tailPiCcsAccepted : Bool := {}\n\n",
        snapshot.tail_pi_ccs_accepted
    ));
    out.push_str(&format!(
        "def zeroPackedStorage : List Nat :=\n  {}\n\n",
        render_nat_list(&snapshot.zero_packed_storage)
    ));
    out.push_str(&format!(
        "def tailPackedStorage : List Nat :=\n  {}\n\n",
        render_nat_list(&snapshot.tail_packed_storage)
    ));
    out.push_str(&format!(
        "def zeroLogicalDecode : List (Nat × Nat) :=\n  {}\n\n",
        render_extension_list(&snapshot.zero_logical_decode)
    ));
    out.push_str(&format!(
        "def tailLogicalDecode : List (Nat × Nat) :=\n  {}\n\n",
        render_extension_list(&snapshot.tail_logical_decode)
    ));
    out.push_str(&format!(
        "def zeroFullDecode : List (Nat × Nat) :=\n  {}\n\n",
        render_extension_list(&snapshot.zero_full_decode)
    ));
    out.push_str(&format!(
        "def tailFullDecode : List (Nat × Nat) :=\n  {}\n\n",
        render_extension_list(&snapshot.tail_full_decode)
    ));
    out.push_str(&format!(
        "def zeroYZcol : List (Nat × Nat) :=\n  {}\n\n",
        render_extension_list(&snapshot.zero_y_zcol)
    ));
    out.push_str(&format!(
        "def tailYZcol : List (Nat × Nat) :=\n  {}\n\n",
        render_extension_list(&snapshot.tail_y_zcol)
    ));
    out.push_str("end Nightstream.Implementation.R1CS.PiCcsNcCarrierArtifact\n");
    out
}

#[test]
fn pi_ccs_nc_carrier_lean_artifact_matches_runtime() {
    assert_eq!(D, 54, "the carrier artifact is specialized to Phi81");
    let snapshot = capture();

    assert!(snapshot.zero_shape_accepted);
    assert!(snapshot.tail_shape_accepted);
    assert_eq!(snapshot.zero_logical_decode, snapshot.tail_logical_decode);
    assert_ne!(snapshot.zero_full_decode, snapshot.tail_full_decode);
    assert_eq!(snapshot.tail_full_decode[FIRST_COMPLETED_TAIL], (2, 0));
    assert_eq!(snapshot.zero_y_zcol, snapshot.tail_y_zcol);
    assert!(snapshot.zero_pi_ccs_accepted);
    assert!(snapshot.tail_pi_ccs_accepted);

    let emitted = emit_lean(&snapshot);
    let path = format!("{}{}", env!("CARGO_MANIFEST_DIR"), ARTIFACT_REL_PATH);
    let committed = std::fs::read_to_string(&path).unwrap_or_default();
    if committed != emitted {
        let expected_path = format!("{path}.expected");
        let parent = std::path::Path::new(&expected_path)
            .parent()
            .expect("artifact path has a parent");
        std::fs::create_dir_all(parent).expect("create generated artifact directory");
        std::fs::write(&expected_path, &emitted).expect("write .expected artifact");
        panic!(
            "Pi_CCS NC carrier Lean artifact drifted. Wrote {expected_path}; inspect it and promote it deliberately."
        );
    }
}
