import DirectCcsFPrime.ProofSystem.Production.Security.DirectParentOnlyProductionPriorOpeningFunctional

/-!
Typed interface for production prior-authority openings in the parent-only
direct CCS F' path.

Spec: `specs/ProofSystem/Production/Security/DirectParentOnlyProductionPriorOpening.spec.md`
-/

namespace DirectCcsFPrime

namespace DirectParentOnlyProductionPriorOpeningInterface

abbrev PriorAuthorityOpener :=
  @DirectParentOnlyProductionPriorOpening.PriorAuthorityOpener

abbrev VerifyWithAuthorityOpener :=
  @DirectParentOnlyProductionPriorOpening.VerifyWithAuthorityOpener

abbrev opensToProofCarryingPriorAuthority_of_verifyWithAuthorityOpener :=
  @DirectParentOnlyProductionPriorOpening.opensToProofCarryingPriorAuthority_of_verifyWithAuthorityOpener

abbrev soundPriorVerifier_of_authority_opener :=
  @DirectParentOnlyProductionPriorOpening.soundPriorVerifier_of_authority_opener

abbrev soundVerifier_of_authority_opener :=
  @DirectParentOnlyProductionPriorOpening.soundVerifier_of_authority_opener

abbrev soundVerifier_of_authority_opener_accepts_iff :=
  @DirectParentOnlyProductionPriorOpening.soundVerifier_of_authority_opener_accepts_iff

abbrev authority_opener_reaches_prior :=
  @DirectParentOnlyProductionPriorOpening.authority_opener_reaches_prior

abbrev authority_opener_cannot_accept_unreachable_prior :=
  @DirectParentOnlyProductionPriorOpening.authority_opener_cannot_accept_unreachable_prior

abbrev authority_opener_opened_authority_unique :=
  @DirectParentOnlyProductionPriorOpening.authority_opener_opened_authority_unique

abbrev verifyWithAuthorityOpener_openAuthority_ne_none :=
  @DirectParentOnlyProductionPriorOpening.verifyWithAuthorityOpener_openAuthority_ne_none

abbrev verifyWithAuthorityOpener_opened_authority_accepts_of_open :=
  @DirectParentOnlyProductionPriorOpening.verifyWithAuthorityOpener_opened_authority_accepts_of_open

abbrev verifyWithAuthorityOpener_functional_for_same_proof :=
  @DirectParentOnlyProductionPriorOpening.verifyWithAuthorityOpener_functional_for_same_proof

abbrev proofFunctional_of_authority_opener :=
  @DirectParentOnlyProductionPriorOpening.proofFunctional_of_authority_opener

abbrev soundVerifier_of_authority_opener_proofFunctional :=
  @DirectParentOnlyProductionPriorOpening.soundVerifier_of_authority_opener_proofFunctional

abbrev terminal_prior_pair_functional_for_same_proof_of_authority_opener :=
  @DirectParentOnlyProductionPriorOpening.terminal_prior_pair_functional_for_same_proof_of_authority_opener

abbrev PriorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionPriorOpening.PriorVerifierAuthorityOpening

abbrev opensToProofCarryingPriorAuthority_of_priorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionPriorOpening.opensToProofCarryingPriorAuthority_of_priorVerifierAuthorityOpening

abbrev priorVerifierAuthorityOpening_opened_authority :=
  @DirectParentOnlyProductionPriorOpening.priorVerifierAuthorityOpening_opened_authority

abbrev priorVerifierAuthorityOpening_openAuthority_ne_none :=
  @DirectParentOnlyProductionPriorOpening.priorVerifierAuthorityOpening_openAuthority_ne_none

abbrev priorVerifierAuthorityOpening_opened_authority_accepts_of_open :=
  @DirectParentOnlyProductionPriorOpening.priorVerifierAuthorityOpening_opened_authority_accepts_of_open

abbrev soundPriorVerifier_of_priorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionPriorOpening.soundPriorVerifier_of_priorVerifierAuthorityOpening

abbrev soundVerifier_of_priorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionPriorOpening.soundVerifier_of_priorVerifierAuthorityOpening

abbrev soundVerifier_of_priorVerifierAuthorityOpening_accepts_iff :=
  @DirectParentOnlyProductionPriorOpening.soundVerifier_of_priorVerifierAuthorityOpening_accepts_iff

abbrev priorVerifierAuthorityOpening_reaches_prior :=
  @DirectParentOnlyProductionPriorOpening.priorVerifierAuthorityOpening_reaches_prior

abbrev priorVerifierAuthorityOpening_cannot_accept_unreachable_prior :=
  @DirectParentOnlyProductionPriorOpening.priorVerifierAuthorityOpening_cannot_accept_unreachable_prior

abbrev priorVerifierAuthorityOpening_functional_for_same_proof :=
  @DirectParentOnlyProductionPriorOpening.priorVerifierAuthorityOpening_functional_for_same_proof

abbrev proofFunctional_of_priorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionPriorOpening.proofFunctional_of_priorVerifierAuthorityOpening

abbrev soundVerifier_of_priorVerifierAuthorityOpening_proofFunctional :=
  @DirectParentOnlyProductionPriorOpening.soundVerifier_of_priorVerifierAuthorityOpening_proofFunctional

abbrev terminal_prior_pair_functional_for_same_proof_of_priorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionPriorOpening.terminal_prior_pair_functional_for_same_proof_of_priorVerifierAuthorityOpening

abbrev terminal_soundness_with_fixed_ce_membership_of_authority_opener :=
  @DirectParentOnlyProductionPriorOpening.terminal_soundness_with_fixed_ce_membership_of_authority_opener

abbrev terminal_soundness_with_fixed_ce_membership_of_priorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionPriorOpening.terminal_soundness_with_fixed_ce_membership_of_priorVerifierAuthorityOpening

abbrev terminal_soundness_with_pointwise_child_audit_trail_of_authority_opener :=
  @DirectParentOnlyProductionPriorOpening.terminal_soundness_with_pointwise_child_audit_trail_of_authority_opener

abbrev terminal_soundness_with_pointwise_child_audit_trail_of_priorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionPriorOpening.terminal_soundness_with_pointwise_child_audit_trail_of_priorVerifierAuthorityOpening

abbrev terminal_soundness_with_prior_reachability_and_pointwise_child_audit_trail_of_authority_opener :=
  @DirectParentOnlyProductionPriorOpening.terminal_soundness_with_prior_reachability_and_pointwise_child_audit_trail_of_authority_opener

abbrev terminal_soundness_with_prior_reachability_and_pointwise_child_audit_trail_of_priorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionPriorOpening.terminal_soundness_with_prior_reachability_and_pointwise_child_audit_trail_of_priorVerifierAuthorityOpening

abbrev audited_public_endpoint_of_authority_opener :=
  @DirectParentOnlyProductionPriorOpening.audited_public_endpoint_of_authority_opener

abbrev audited_public_endpoint_of_priorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionPriorOpening.audited_public_endpoint_of_priorVerifierAuthorityOpening

abbrev audited_public_endpoint_with_stage_audit_of_authority_opener :=
  @DirectParentOnlyProductionPriorOpening.audited_public_endpoint_with_stage_audit_of_authority_opener

abbrev audited_public_endpoint_with_stage_audit_of_priorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionPriorOpening.audited_public_endpoint_with_stage_audit_of_priorVerifierAuthorityOpening

abbrev terminal_next_image_functional_for_same_proof_of_authority_opener :=
  @DirectParentOnlyProductionPriorOpening.terminal_next_image_functional_for_same_proof_of_authority_opener

abbrev terminal_next_image_functional_for_same_proof_of_priorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionPriorOpening.terminal_next_image_functional_for_same_proof_of_priorVerifierAuthorityOpening

end DirectParentOnlyProductionPriorOpeningInterface

end DirectCcsFPrime
