import DirectCcsFPrime.ProofSystem.Production.Security.DirectParentOnlyProductionEndpoint

/-!
Typed interface for the packaged production endpoint.

Spec: `specs/ProofSystem/Production/Security/DirectParentOnlyProductionEndpoint.spec.md`
-/

namespace DirectCcsFPrime

namespace DirectParentOnlyProductionEndpointInterface

abbrev PriorReachabilityAndUniquePointwiseChildren :=
  @DirectParentOnlyProductionEndpoint.PriorReachabilityAndUniquePointwiseChildren

abbrev PriorReachabilityAndPointwiseChildAuditTrail :=
  @DirectParentOnlyProductionEndpoint.PriorReachabilityAndPointwiseChildAuditTrail

abbrev AuditedPublicEndpoint :=
  @DirectParentOnlyProductionEndpoint.AuditedPublicEndpoint

abbrev audited_public_endpoint_of_prior_reachability_and_pointwise_child_audit_trail :=
  @DirectParentOnlyProductionEndpoint.audited_public_endpoint_of_prior_reachability_and_pointwise_child_audit_trail

abbrev terminal_soundness_with_prior_reachability_and_unique_pointwise_children :=
  @DirectParentOnlyProductionEndpoint.terminal_soundness_with_prior_reachability_and_unique_pointwise_children

abbrev terminal_soundness_with_prior_reachability_and_unique_pointwise_children_of_prior_verifier_opening :=
  @DirectParentOnlyProductionEndpoint.terminal_soundness_with_prior_reachability_and_unique_pointwise_children_of_prior_verifier_opening

abbrev terminal_soundness_with_prior_reachability_and_pointwise_child_audit_trail :=
  @DirectParentOnlyProductionEndpoint.terminal_soundness_with_prior_reachability_and_pointwise_child_audit_trail

abbrev audited_public_endpoint_of_sound_verifier :=
  @DirectParentOnlyProductionEndpoint.audited_public_endpoint_of_sound_verifier

abbrev terminal_soundness_with_prior_reachability_and_pointwise_child_audit_trail_of_prior_verifier_opening :=
  @DirectParentOnlyProductionEndpoint.terminal_soundness_with_prior_reachability_and_pointwise_child_audit_trail_of_prior_verifier_opening

abbrev audited_public_endpoint_of_prior_verifier_opening :=
  @DirectParentOnlyProductionEndpoint.audited_public_endpoint_of_prior_verifier_opening

end DirectParentOnlyProductionEndpointInterface

end DirectCcsFPrime
