import DirectCcsFPrime.ProofSystem.Production.Security.DirectParentOnlyProductionSoundness

/-!
Typed interface for the production-facing parent-only direct CCS F' soundness
surface.

Spec: `specs/ProofSystem/Production/Security/DirectParentOnlyProductionSoundness.spec.md`
-/

namespace DirectCcsFPrime

namespace DirectParentOnlyProductionSoundnessInterface

abbrev AccHandle :=
  @DirectParentOnlyProductionSoundness.AccHandle

abbrev PublicImage :=
  @DirectParentOnlyProductionSoundness.PublicImage

abbrev Context :=
  DirectParentOnlyProductionSoundness.Context

abbrev verifiedStage :=
  @DirectParentOnlyProductionSoundness.verifiedStage

abbrev AccumulatorStep :=
  @DirectParentOnlyProductionSoundness.AccumulatorStep

abbrev Transition :=
  @DirectParentOnlyProductionSoundness.Transition

abbrev VerifyLatestStep :=
  @DirectParentOnlyProductionSoundness.VerifyLatestStep

abbrev SoundPriorVerifier :=
  @DirectParentOnlyProductionSoundness.SoundPriorVerifier

abbrev ProofCarryingPriorProof :=
  @DirectParentOnlyProductionSoundness.ProofCarryingPriorProof

abbrev proofCarryingPriorVerifier :=
  @DirectParentOnlyProductionSoundness.proofCarryingPriorVerifier

abbrev proofCarryingPriorVerifier_accepts :=
  @DirectParentOnlyProductionSoundness.proofCarryingPriorVerifier_accepts

abbrev OpensToProofCarryingPriorAuthority :=
  @DirectParentOnlyProductionSoundness.OpensToProofCarryingPriorAuthority

abbrev soundPriorVerifier_of_opens_to_proof_carrying_prior_authority :=
  @DirectParentOnlyProductionSoundness.soundPriorVerifier_of_opens_to_proof_carrying_prior_authority

abbrev prior_verifier_reaches_prior_of_opening :=
  @DirectParentOnlyProductionSoundness.prior_verifier_reaches_prior_of_opening

abbrev prior_verifier_cannot_accept_unreachable_of_opening :=
  @DirectParentOnlyProductionSoundness.prior_verifier_cannot_accept_unreachable_of_opening

abbrev soundPriorVerifier_reaches_prior :=
  @DirectParentOnlyProductionSoundness.soundPriorVerifier_reaches_prior

abbrev soundPriorVerifier_cannot_accept_unreachable_prior :=
  @DirectParentOnlyProductionSoundness.soundPriorVerifier_cannot_accept_unreachable_prior

abbrev AcceptedTerminal :=
  @DirectParentOnlyProductionSoundness.AcceptedTerminal

abbrev AcceptedProofCarryingTerminal :=
  @DirectParentOnlyProductionSoundness.AcceptedProofCarryingTerminal

abbrev AlternateLatestStep :=
  @DirectParentOnlyProductionSoundness.AlternateLatestStep

abbrev TerminalSoundness :=
  @DirectParentOnlyProductionSoundness.TerminalSoundness

abbrev ComputedParentSource :=
  @DirectParentOnlyProductionSoundness.ComputedParentSource

abbrev ComputedNextImage :=
  @DirectParentOnlyProductionSoundness.ComputedNextImage

abbrev latest_eq_computed_next_image_of_parent_source :=
  @DirectParentOnlyProductionSoundness.latest_eq_computed_next_image_of_parent_source

abbrev terminal_soundness :=
  @DirectParentOnlyProductionSoundness.terminal_soundness

abbrev terminal_soundness_with_computed_parent_sources :=
  @DirectParentOnlyProductionSoundness.terminal_soundness_with_computed_parent_sources

abbrev terminal_soundness_with_computed_next_images :=
  @DirectParentOnlyProductionSoundness.terminal_soundness_with_computed_next_images

abbrev pointwise_private_dec_inputs_unique_of_context :=
  @DirectParentOnlyProductionSoundness.pointwise_private_dec_inputs_unique_of_context

abbrev terminal_soundness_with_unique_pointwise_children :=
  @DirectParentOnlyProductionSoundness.terminal_soundness_with_unique_pointwise_children

abbrev terminal_soundness_of_proof_carrying_prior_authority :=
  @DirectParentOnlyProductionSoundness.terminal_soundness_of_proof_carrying_prior_authority

abbrev terminal_soundness_with_computed_parent_sources_of_proof_carrying_prior_authority :=
  @DirectParentOnlyProductionSoundness.terminal_soundness_with_computed_parent_sources_of_proof_carrying_prior_authority

abbrev terminal_soundness_with_computed_next_images_of_proof_carrying_prior_authority :=
  @DirectParentOnlyProductionSoundness.terminal_soundness_with_computed_next_images_of_proof_carrying_prior_authority

abbrev terminal_soundness_with_computed_next_images_of_prior_verifier_opening :=
  @DirectParentOnlyProductionSoundness.terminal_soundness_with_computed_next_images_of_prior_verifier_opening

abbrev terminal_soundness_with_unique_pointwise_children_of_prior_verifier_opening :=
  @DirectParentOnlyProductionSoundness.terminal_soundness_with_unique_pointwise_children_of_prior_verifier_opening

end DirectParentOnlyProductionSoundnessInterface

end DirectCcsFPrime
