import DirectCcsFPrime.ProofSystem.Production.Security.DirectParentOnlyProductionChildMembership

/-!
Typed interface for production child membership in the parent-only direct CCS
F' path.

Spec: `specs/ProofSystem/Production/Security/DirectParentOnlyProductionChildMembership.spec.md`
-/

namespace DirectCcsFPrime

namespace DirectParentOnlyProductionChildMembershipInterface

abbrev PointwiseChildAuditCertificate :=
  @DirectParentOnlyProductionChildMembership.PointwiseChildAuditCertificate

abbrev PointwiseChildAuditTrail :=
  @DirectParentOnlyProductionChildMembership.PointwiseChildAuditTrail

abbrev TerminalChildAuditTrail :=
  @DirectParentOnlyProductionChildMembership.TerminalChildAuditTrail

abbrev pointwise_child_audit_trail_of_pointwise_private_dec_requirements :=
  @DirectParentOnlyProductionChildMembership.pointwise_child_audit_trail_of_pointwise_private_dec_requirements

abbrev privatePiDECAccepts_of_pointwise_child_audit_trail :=
  @DirectParentOnlyProductionChildMembership.privatePiDECAccepts_of_pointwise_child_audit_trail

abbrev fixedCEChildMembership_of_pointwise_child_audit_trail :=
  @DirectParentOnlyProductionChildMembership.fixedCEChildMembership_of_pointwise_child_audit_trail

abbrev nonaggregate_dec_facts_of_pointwise_child_audit_trail :=
  @DirectParentOnlyProductionChildMembership.nonaggregate_dec_facts_of_pointwise_child_audit_trail

abbrev nextPiCCSInputs_eq_childWitnessDigitTable_of_pointwise_child_audit_trail :=
  @DirectParentOnlyProductionChildMembership.nextPiCCSInputs_eq_childWitnessDigitTable_of_pointwise_child_audit_trail

abbrev pointwise_child_audit_trail_of_terminal_child_audit_trail :=
  @DirectParentOnlyProductionChildMembership.pointwise_child_audit_trail_of_terminal_child_audit_trail

abbrev terminal_soundness_with_unique_children_and_fixed_ce_membership :=
  @DirectParentOnlyProductionChildMembership.terminal_soundness_with_unique_children_and_fixed_ce_membership

abbrev terminal_soundness_with_pointwise_child_audit_trail :=
  @DirectParentOnlyProductionChildMembership.terminal_soundness_with_pointwise_child_audit_trail

abbrev terminal_soundness_with_unique_children_and_fixed_ce_membership_of_proof_carrying_prior_authority :=
  @DirectParentOnlyProductionChildMembership.terminal_soundness_with_unique_children_and_fixed_ce_membership_of_proof_carrying_prior_authority

abbrev terminal_soundness_with_pointwise_child_audit_trail_of_proof_carrying_prior_authority :=
  @DirectParentOnlyProductionChildMembership.terminal_soundness_with_pointwise_child_audit_trail_of_proof_carrying_prior_authority

abbrev terminal_soundness_with_unique_children_and_fixed_ce_membership_of_prior_verifier_opening :=
  @DirectParentOnlyProductionChildMembership.terminal_soundness_with_unique_children_and_fixed_ce_membership_of_prior_verifier_opening

abbrev terminal_soundness_with_pointwise_child_audit_trail_of_prior_verifier_opening :=
  @DirectParentOnlyProductionChildMembership.terminal_soundness_with_pointwise_child_audit_trail_of_prior_verifier_opening

end DirectParentOnlyProductionChildMembershipInterface

end DirectCcsFPrime
