import DirectCcsFPrime.ProofSystem.Production.Security.DirectParentOnlyProductionStageAudit

/-!
Typed interface for the production stage-audit endpoint.

Spec: `specs/ProofSystem/Production/Security/DirectParentOnlyProductionStageAudit.spec.md`
-/

namespace DirectCcsFPrime

namespace DirectParentOnlyProductionStageAuditInterface

abbrev childCarryingPrior :=
  @DirectParentOnlyProductionStageAudit.childCarryingPrior

abbrev ParentSourceStageAudit :=
  @DirectParentOnlyProductionStageAudit.ParentSourceStageAudit

abbrev parent_source_stage_audit_of_parentSourceFromPiStages :=
  @DirectParentOnlyProductionStageAudit.parent_source_stage_audit_of_parentSourceFromPiStages

abbrev piDEC_knowledge_of_parent_source_stage_audit :=
  @DirectParentOnlyProductionStageAudit.piDEC_knowledge_of_parent_source_stage_audit

abbrev piDEC_knowledge_of_piCCS_parent_source_stage_audit :=
  @DirectParentOnlyProductionStageAudit.piDEC_knowledge_of_piCCS_parent_source_stage_audit

abbrev source_eq_computePiRLC_of_parent_source_stage_audit :=
  @DirectParentOnlyProductionStageAudit.source_eq_computePiRLC_of_parent_source_stage_audit

abbrev piCCS_step_of_parent_source_stage_audit :=
  @DirectParentOnlyProductionStageAudit.piCCS_step_of_parent_source_stage_audit

abbrev piCCS_strong_of_parent_source_stage_audit :=
  @DirectParentOnlyProductionStageAudit.piCCS_strong_of_parent_source_stage_audit

abbrev piRLC_weak_of_parent_source_stage_audit :=
  @DirectParentOnlyProductionStageAudit.piRLC_weak_of_parent_source_stage_audit

abbrev TerminalStageAuditTrail :=
  @DirectParentOnlyProductionStageAudit.TerminalStageAuditTrail

abbrev computed_stage_evidence_of_terminal_stage_audit_trail :=
  @DirectParentOnlyProductionStageAudit.computed_stage_evidence_of_terminal_stage_audit_trail

abbrev terminal_stage_audit_trail_of_terminal_soundness_and_child_audit :=
  @DirectParentOnlyProductionStageAudit.terminal_stage_audit_trail_of_terminal_soundness_and_child_audit

abbrev AuditedPublicEndpointWithStageAudit :=
  @DirectParentOnlyProductionStageAudit.AuditedPublicEndpointWithStageAudit

abbrev audited_public_endpoint_with_stage_audit_of_sound_verifier :=
  @DirectParentOnlyProductionStageAudit.audited_public_endpoint_with_stage_audit_of_sound_verifier

abbrev audited_public_endpoint_with_stage_audit_of_prior_verifier_opening :=
  @DirectParentOnlyProductionStageAudit.audited_public_endpoint_with_stage_audit_of_prior_verifier_opening

end DirectParentOnlyProductionStageAuditInterface

end DirectCcsFPrime
