import DirectCcsFPrime.ProofSystem.Production.Security.DirectParentOnlyProductionSuperNeoReuseFinalEndpoint

/-!
Typed interface for the final Section 7.1-backed parent-only replay endpoint.

Spec: `specs/ProofSystem/Production/Security/DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.spec.md`
-/

namespace DirectCcsFPrime

namespace DirectParentOnlyProductionSuperNeoReuseFinalEndpointInterface

abbrev ProductionContext :=
  DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.ProductionContext

abbrev RawVerifierReplayTerminalEndpoint :=
  @DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.RawVerifierReplayTerminalEndpoint

abbrev ExplicitReplayNoSwapEvidence :=
  @DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.ExplicitReplayNoSwapEvidence

abbrev AuditedPublicEndpoint :=
  @DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.AuditedPublicEndpoint

abbrev TerminalStageAuditTrail :=
  @DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.TerminalStageAuditTrail

abbrev OpenedPriorAuthority :=
  @DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.OpenedPriorAuthority

abbrev PointwiseChildTableNoSwap :=
  @DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.PointwiseChildTableNoSwap

abbrev FinalPublicImageInvariants :=
  @DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.FinalPublicImageInvariants

abbrev rawVerifierReplayTerminalEndpoint_ofAcceptedOpens :=
  @DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.rawVerifierReplayTerminalEndpoint_ofAcceptedOpens

abbrev rawVerifierReplayTerminalEndpoint_ofPriorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.rawVerifierReplayTerminalEndpoint_ofPriorVerifierAuthorityOpening

abbrev openedPriorAuthority_of_rawVerifierReplayTerminalEndpoint :=
  @DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.openedPriorAuthority_of_rawVerifierReplayTerminalEndpoint

abbrev pointwiseChildTableNoSwap_of_rawVerifierReplayTerminalEndpoint :=
  @DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.pointwiseChildTableNoSwap_of_rawVerifierReplayTerminalEndpoint

abbrev pointwiseChildTableNoSwap_ofPriorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.pointwiseChildTableNoSwap_ofPriorVerifierAuthorityOpening

abbrev sameProofReplayEndpoint_of_rawVerifierReplayTerminalEndpoint :=
  @DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.sameProofReplayEndpoint_of_rawVerifierReplayTerminalEndpoint

abbrev computedStageReplayEvidence_of_rawVerifierReplayTerminalEndpoint :=
  @DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.computedStageReplayEvidence_of_rawVerifierReplayTerminalEndpoint

abbrev piCCSDecKnowledge_of_rawVerifierReplayTerminalEndpoint :=
  @DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.piCCSDecKnowledge_of_rawVerifierReplayTerminalEndpoint

abbrev piRLCDecKnowledge_of_rawVerifierReplayTerminalEndpoint :=
  @DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.piRLCDecKnowledge_of_rawVerifierReplayTerminalEndpoint

abbrev explicitReplayNoSwapEvidence_of_rawVerifierReplayTerminalEndpoint :=
  @DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.explicitReplayNoSwapEvidence_of_rawVerifierReplayTerminalEndpoint

abbrev auditedPublicEndpoint_of_rawVerifierReplayTerminalEndpoint :=
  @DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.auditedPublicEndpoint_of_rawVerifierReplayTerminalEndpoint

abbrev terminalStageAuditTrail_of_rawVerifierReplayTerminalEndpoint :=
  @DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.terminalStageAuditTrail_of_rawVerifierReplayTerminalEndpoint

abbrev finalPublicImageInvariants_of_rawVerifierReplayTerminalEndpoint :=
  @DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.finalPublicImageInvariants_of_rawVerifierReplayTerminalEndpoint

abbrev openedPriorAuthority_ofPriorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.openedPriorAuthority_ofPriorVerifierAuthorityOpening

abbrev sameProofReplayEndpoint_ofPriorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.sameProofReplayEndpoint_ofPriorVerifierAuthorityOpening

abbrev computedStageReplayEvidence_ofPriorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.computedStageReplayEvidence_ofPriorVerifierAuthorityOpening

abbrev piCCSDecKnowledge_ofPriorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.piCCSDecKnowledge_ofPriorVerifierAuthorityOpening

abbrev piRLCDecKnowledge_ofPriorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.piRLCDecKnowledge_ofPriorVerifierAuthorityOpening

abbrev explicitReplayNoSwapEvidence_ofPriorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.explicitReplayNoSwapEvidence_ofPriorVerifierAuthorityOpening

abbrev auditedPublicEndpoint_ofPriorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.auditedPublicEndpoint_ofPriorVerifierAuthorityOpening

abbrev terminalStageAuditTrail_ofPriorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.terminalStageAuditTrail_ofPriorVerifierAuthorityOpening

abbrev finalPublicImageInvariants_ofPriorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionSuperNeoReuseFinalEndpoint.finalPublicImageInvariants_ofPriorVerifierAuthorityOpening

end DirectParentOnlyProductionSuperNeoReuseFinalEndpointInterface

end DirectCcsFPrime
