import Nightstream.Rv64IM.ProofCompleteAudit

/-!
Interface for the executable RV64IM proof-completeness audit.
-/

namespace Nightstream.Rv64IM

namespace ProofCompleteAuditInterface

def implementationModule : String := "Nightstream.Rv64IM.ProofCompleteAudit"

def exportedModuleNames : List String :=
  [ "Nightstream.Rv64IM.Generated.AcceptedProofArtifactCorpus"
  , "Nightstream.Rv64IM.Kernel.RequiredBackendPayloadSurface"
  , "Nightstream.Rv64IM.Kernel.RequiredRootExecutionSemanticsSurface"
  , "Nightstream.Rv64IM.Kernel.RequiredKernelDesignBridgeSurface"
  , "Nightstream.Rv64IM.Kernel.RequiredProofCompleteRustExportSurface"
  , "Nightstream.Rv64IM.Generated.SideTerminalOpeningDigestBindingCorpus"
  , "Nightstream.Rv64IM.SideTerminalOpeningDigestBinding"
  , "Nightstream.Rv64IM.ProofCompleteAudit"
  ]

abbrev proofCompleteStaticChecks :=
  Nightstream.Rv64IM.proofCompleteStaticChecks
abbrev validRv64imProofCompleteStaticChecks :=
  Nightstream.Rv64IM.validRv64imProofCompleteStaticChecks
abbrev proofCompleteCaseAccepted :=
  Nightstream.Rv64IM.proofCompleteCaseAccepted
abbrev requiredProofCompleteRustExportBlockers :=
  Nightstream.Rv64IM.requiredProofCompleteRustExportBlockers
abbrev uniqueRequiredProofCompleteBackendRustExportBlockers :=
  Nightstream.Rv64IM.uniqueRequiredProofCompleteBackendRustExportBlockers
abbrev uniqueRequiredProofCompleteRootExecutionSemanticsRustExportBlockers :=
  Nightstream.Rv64IM.uniqueRequiredProofCompleteRootExecutionSemanticsRustExportBlockers
abbrev uniqueRequiredProofCompleteKernelDesignBridgeRustExportBlockers :=
  Nightstream.Rv64IM.uniqueRequiredProofCompleteKernelDesignBridgeRustExportBlockers
abbrev uniqueRequiredProofCompleteRustExportBlockers :=
  Nightstream.Rv64IM.uniqueRequiredProofCompleteRustExportBlockers
abbrev uniqueRequiredRootExecutionSemanticsRustExportBlockers :=
  Nightstream.Rv64IM.uniqueRequiredRootExecutionSemanticsRustExportBlockers
abbrev uniqueRequiredKernelDesignBridgeRustExportBlockers :=
  Nightstream.Rv64IM.uniqueRequiredKernelDesignBridgeRustExportBlockers
abbrev proofCompleteBackendRustExportBlockers :=
  Nightstream.Rv64IM.proofCompleteBackendRustExportBlockers
abbrev uniqueProofCompleteRequiredBackendPayloadFields :=
  Nightstream.Rv64IM.uniqueProofCompleteRequiredBackendPayloadFields
abbrev uniqueProofCompleteRequiredRootExecutionSemanticsFields :=
  Nightstream.Rv64IM.uniqueProofCompleteRequiredRootExecutionSemanticsFields
abbrev uniqueProofCompleteRequiredKernelDesignBridgeFields :=
  Nightstream.Rv64IM.uniqueProofCompleteRequiredKernelDesignBridgeFields
abbrev uniqueProofCompleteRequiredRustExportFields :=
  Nightstream.Rv64IM.uniqueProofCompleteRequiredRustExportFields
abbrev proofCompleteRootExecutionSemanticsRustExportBlockers :=
  Nightstream.Rv64IM.proofCompleteRootExecutionSemanticsRustExportBlockers
abbrev proofCompleteKernelDesignBridgeRustExportBlockers :=
  Nightstream.Rv64IM.proofCompleteKernelDesignBridgeRustExportBlockers
abbrev proofCompleteRustExportBlockers :=
  Nightstream.Rv64IM.proofCompleteRustExportBlockers
abbrev validProofCompleteRequiredBackendPayloadSurface :=
  Nightstream.Rv64IM.validProofCompleteRequiredBackendPayloadSurface
abbrev validProofCompleteRequiredRootExecutionSemanticsSurface :=
  Nightstream.Rv64IM.validProofCompleteRequiredRootExecutionSemanticsSurface
abbrev validProofCompleteRequiredKernelDesignBridgeSurface :=
  Nightstream.Rv64IM.validProofCompleteRequiredKernelDesignBridgeSurface
abbrev validProofCompleteRequiredRustExportSurface :=
  Nightstream.Rv64IM.validProofCompleteRequiredRustExportSurface
abbrev requiredBackendPayloadRustExportBlockers :=
  Nightstream.Rv64IM.requiredBackendPayloadRustExportBlockers
abbrev uniqueRequiredBackendPayloadRustExportBlockers :=
  Nightstream.Rv64IM.uniqueRequiredBackendPayloadRustExportBlockers
abbrev uniqueProofCompleteBackendRustExportBlockers :=
  Nightstream.Rv64IM.uniqueProofCompleteBackendRustExportBlockers
abbrev uniqueProofCompleteRootExecutionSemanticsRustExportBlockers :=
  Nightstream.Rv64IM.uniqueProofCompleteRootExecutionSemanticsRustExportBlockers
abbrev uniqueProofCompleteKernelDesignBridgeRustExportBlockers :=
  Nightstream.Rv64IM.uniqueProofCompleteKernelDesignBridgeRustExportBlockers
abbrev uniqueProofCompleteRustExportBlockers :=
  Nightstream.Rv64IM.uniqueProofCompleteRustExportBlockers
abbrev rv64imProofCompleteChecks :=
  Nightstream.Rv64IM.rv64imProofCompleteChecks
abbrev validGeneratedRv64imProofCompleteCases :=
  Nightstream.Rv64IM.validGeneratedRv64imProofCompleteCases
abbrev rv64imProofCompleteReports :=
  Nightstream.Rv64IM.rv64imProofCompleteReports
abbrev validRv64imProofCompleteClosure :=
  Nightstream.Rv64IM.validRv64imProofCompleteClosure
abbrev proofCompleteStaticFailures :=
  Nightstream.Rv64IM.proofCompleteStaticFailures
abbrev proofCompleteStaticFieldMissingRequiredFields :=
  Nightstream.Rv64IM.proofCompleteStaticFieldMissingRequiredFields
abbrev proofCompleteStaticFieldRustExportBlockers :=
  Nightstream.Rv64IM.proofCompleteStaticFieldRustExportBlockers
abbrev proofCompleteStaticFailureReports :=
  Nightstream.Rv64IM.proofCompleteStaticFailureReports
abbrev uniqueProofCompleteStaticFailureMissingRequiredFields :=
  Nightstream.Rv64IM.uniqueProofCompleteStaticFailureMissingRequiredFields
abbrev uniqueProofCompleteStaticFailureRustExportBlockers :=
  Nightstream.Rv64IM.uniqueProofCompleteStaticFailureRustExportBlockers
abbrev uniqueProofCompleteClosureBlockers :=
  Nightstream.Rv64IM.uniqueProofCompleteClosureBlockers

def entrypointContract : Prop := True

theorem entrypointContract_true : entrypointContract := by
  trivial

end ProofCompleteAuditInterface

end Nightstream.Rv64IM
