import DirectCcsFPrime.ProofSystem.Production.Security.Opening.DirectParentOnlyProductionConcreteFPrimePriorRawIOOpening

/-!
Typed interface for the raw public-IO opening-level prior F' verifier.

Spec: `specs/ProofSystem/Production/Security/Opening/DirectParentOnlyProductionConcreteFPrimePriorRawIOOpening.spec.md`
-/

namespace DirectCcsFPrime

namespace DirectParentOnlyProductionConcreteFPrimePriorRawIOOpeningInterface

abbrev ProductionContext :=
  DirectParentOnlyProductionConcreteFPrimePriorRawIOOpening.ProductionContext

abbrev PublicImage :=
  DirectParentOnlyProductionConcreteFPrimePriorRawIOOpening.PublicImage

abbrev ProofCarryingPriorProof :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOOpening.ProofCarryingPriorProof

abbrev ConcreteRawPublicIOVerifierChecks :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOOpening.ConcreteRawPublicIOVerifierChecks

abbrev RawPublicIOBoundStatementAccepted :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOOpening.RawPublicIOBoundStatementAccepted

abbrev ConcreteRawPublicIOSoundnessSurface :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOOpening.ConcreteRawPublicIOSoundnessSurface

abbrev ConcreteRawPublicIOOpeningSurface :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOOpening.ConcreteRawPublicIOOpeningSurface

abbrev rawBoundStatementAuthoritySound_ofOpeningSurface :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOOpening.rawBoundStatementAuthoritySound_ofOpeningSurface

abbrev rawPublicIOSoundnessSurfaceOfOpening :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOOpening.rawPublicIOSoundnessSurfaceOfOpening

abbrev RuntimeVerifyPriorOfRawPublicIOOpening :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOOpening.RuntimeVerifyPriorOfRawPublicIOOpening

abbrev certifiedPriorVerifierOfRawPublicIOOpening :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOOpening.certifiedPriorVerifierOfRawPublicIOOpening

abbrev certifiedPriorVerifierOfRawPublicIOOpening_verify :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOOpening.certifiedPriorVerifierOfRawPublicIOOpening_verify

abbrev runtimeVerifyPriorOfRawPublicIOOpening_acceptedOpens :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOOpening.runtimeVerifyPriorOfRawPublicIOOpening_acceptedOpens

abbrev runtimeVerifyPriorOfRawPublicIOOpening_openedAuthority_accepts_of_open :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOOpening.runtimeVerifyPriorOfRawPublicIOOpening_openedAuthority_accepts_of_open

abbrev runtimeVerifyPriorOfRawPublicIOOpening_reaches_prior :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOOpening.runtimeVerifyPriorOfRawPublicIOOpening_reaches_prior

abbrev proofFunctionalOfRawPublicIOOpening :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOOpening.proofFunctionalOfRawPublicIOOpening

abbrev runtimeVerifyPriorOfRawPublicIOOpening_publicImageInvariants :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOOpening.runtimeVerifyPriorOfRawPublicIOOpening_publicImageInvariants

abbrev runtimeVerifyPriorOfRawPublicIOOpening_cannot_accept_unreachable_prior :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOOpening.runtimeVerifyPriorOfRawPublicIOOpening_cannot_accept_unreachable_prior

end DirectParentOnlyProductionConcreteFPrimePriorRawIOOpeningInterface

end DirectCcsFPrime
