import DirectCcsFPrime.ProofSystem.Production.Security.Opening.DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening

/-!
Typed interface for the exact public-IO opening-level prior F' verifier.

Spec: `specs/ProofSystem/Production/Security/Opening/DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening.spec.md`
-/

namespace DirectCcsFPrime

namespace DirectParentOnlyProductionConcreteFPrimePriorExactIOOpeningInterface

abbrev ProductionContext :=
  DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening.ProductionContext

abbrev PublicImage :=
  DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening.PublicImage

abbrev ProofCarryingPriorProof :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening.ProofCarryingPriorProof

abbrev ExactTerminalBoundaryPublicIO :=
  DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening.ExactTerminalBoundaryPublicIO

abbrev ConcreteExactPublicIOVerifierChecks :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening.ConcreteExactPublicIOVerifierChecks

abbrev rawPublicIOVerifierChecksOfExactPublicIOOpening :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening.rawPublicIOVerifierChecksOfExactPublicIOOpening

abbrev ExactPublicIOVerifierAccepted :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening.ExactPublicIOVerifierAccepted

abbrev ExactPublicIOBoundStatementAccepted :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening.ExactPublicIOBoundStatementAccepted

abbrev ExactPublicIOTerminalLengthBinding :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening.ExactPublicIOTerminalLengthBinding

abbrev ExactPublicIOTerminalSliceBinding :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening.ExactPublicIOTerminalSliceBinding

abbrev exactPublicIOTerminalLengthBindingOfTerminalSlice :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening.exactPublicIOTerminalLengthBindingOfTerminalSlice

abbrev exactPublicIOBoundStatementAccepted_ofRawBoundStatement :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening.exactPublicIOBoundStatementAccepted_ofRawBoundStatement

abbrev ConcreteExactPublicIOOpeningSurface :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening.ConcreteExactPublicIOOpeningSurface

abbrev exactBoundStatementAuthoritySound_ofOpeningSurface :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening.exactBoundStatementAuthoritySound_ofOpeningSurface

abbrev rawPublicIOOpeningSurfaceOfExactPublicIOOpening :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening.rawPublicIOOpeningSurfaceOfExactPublicIOOpening

abbrev rawPublicIOSoundnessSurfaceOfExactPublicIOOpening :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening.rawPublicIOSoundnessSurfaceOfExactPublicIOOpening

abbrev RuntimeVerifyPriorOfExactPublicIOOpening :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening.RuntimeVerifyPriorOfExactPublicIOOpening

abbrev certifiedPriorVerifierOfExactPublicIOOpening :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening.certifiedPriorVerifierOfExactPublicIOOpening

abbrev certifiedPriorVerifierOfExactPublicIOOpening_verify :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening.certifiedPriorVerifierOfExactPublicIOOpening_verify

abbrev runtimeVerifyPriorOfExactPublicIOOpening_boundStatement :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening.runtimeVerifyPriorOfExactPublicIOOpening_boundStatement

abbrev runtimeVerifyPriorOfExactPublicIOOpening_acceptedOpens :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening.runtimeVerifyPriorOfExactPublicIOOpening_acceptedOpens

abbrev runtimeVerifyPriorOfExactPublicIOOpening_openedAuthority_accepts_of_open :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening.runtimeVerifyPriorOfExactPublicIOOpening_openedAuthority_accepts_of_open

abbrev runtimeVerifyPriorOfExactPublicIOOpening_reaches_prior :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening.runtimeVerifyPriorOfExactPublicIOOpening_reaches_prior

abbrev proofFunctionalOfExactPublicIOOpening :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening.proofFunctionalOfExactPublicIOOpening

abbrev runtimeVerifyPriorOfExactPublicIOOpening_publicImageInvariants :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening.runtimeVerifyPriorOfExactPublicIOOpening_publicImageInvariants

abbrev runtimeVerifyPriorOfExactPublicIOOpening_cannot_accept_unreachable_prior :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening.runtimeVerifyPriorOfExactPublicIOOpening_cannot_accept_unreachable_prior

abbrev certifiedSingleTerminalEndToEnd_ofExactPublicIOOpeningLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening.certifiedSingleTerminalEndToEnd_ofExactPublicIOOpeningLatestStep

abbrev nonAggregatePrivateDecStageFacts_ofExactPublicIOOpeningLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening.nonAggregatePrivateDecStageFacts_ofExactPublicIOOpeningLatestStep

abbrev section71StageTargetAuditTrail_ofExactPublicIOOpeningLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOOpening.section71StageTargetAuditTrail_ofExactPublicIOOpeningLatestStep

end DirectParentOnlyProductionConcreteFPrimePriorExactIOOpeningInterface

end DirectCcsFPrime
