import Nightstream.Implementation.NebulaV2.FPrime.Manifest.TerminalNifsCall

/-! Focused gate for the exact V2 terminal manifest and trailing call. -/

set_option autoImplicit false

namespace tests.NebulaV2TerminalManifest

open Nightstream.Implementation.NebulaV2

#check TerminalClosedCarryRows.parsed_phase_closed
#check TerminalManifestSchema.Artifact.terminalClosed_satisfied
#check TerminalManifestSchema.Artifact.foldedBundle_satisfied
#check TerminalManifestSchema.Artifact.foldedBundlesCommonOpenings
#check TerminalManifestSchema.Artifact.typedOpening_rows_length
#check TerminalManifestSchema.Artifact.knownNumericRows_lower_bound
#check TerminalManifestSchema.Artifact.combinedKnownRows_lower_bound
#check TerminalManifestSchema.Artifact.typedOpeningRows_exceed_25_variable_cube
#check TerminalManifestSchema.Artifact.cannot_fit_generated_domain_at_25
#check TerminalManifestSchema.Artifact.MatchesTerminalKey
#check TerminalManifestSchema.Artifact.opensSelectedRelationExponent
#check TerminalManifestNifsCall.Call.CarryBlocks.priorAccepted
#check TerminalManifestNifsCall.Call.CarryBlocks.intermediateAccepted
#check TerminalManifestNifsCall.Call.receiptOfRows
#check TerminalManifestNifsCall.Call.intermediatePhaseClosed
#check TerminalManifestNifsCall.Call.consumesExactAcceptedTrailingClaim
#check TerminalManifestNifsCall.Call.selectedTransitionToClosed
#check TerminalManifestNifsCall.Call.priorStateLinkedAndClosesExactAcceptedTrailingClaim
#check TerminalManifestNifsCall.Call.exactPaperInputMatchesRunningRows

end tests.NebulaV2TerminalManifest
