//! Three-matrix diagnostic wiring from PiRLC sampler outputs to rho consumers.
//!
//! Owns: the unique ordered 15 x 54 selection-trace window whose output
//! columns are consumed by both returned-parent `YZColLimb` identities, plus
//! its exact affine column formula.
//!
//! Does not own: satisfaction or semantics of the sampler rows, transcript
//! authority, rho evaluation rows, projection identities, encoded costs, or
//! row removal.
//!
//! Emits constraints: no.
//!
//! Authority boundary: this is artifact-checked physical aliasing only. A
//! later correspondence theorem must prove that the matched selection rows
//! implement the verifier-owned transcript sampler.
//!
//! | Producer -> consumer | Mathematical obligation | Multiplicity | Evidence |
//! |---|---|---:|---|
//! | `challenge.sampler.selection.bind.symbol -> projection_shared.rho_evaluations` | selected symbol wire is consumed as the matching rho coefficient | 15 x 54 | unique trace-column identity |

use std::fmt::Write as _;
use std::fs;
use std::ops::Range;

use neo_fold_clean::engine::r1cs_circuit::alphabet_sampling::pi_rlc_challenge_stage;
use neo_fold_clean::engine::r1cs_circuit::{ProjectionIdentityRole, R1csEncodingTrace};
use neo_fold_clean::paper::reductions::pi_rlc_circuit::stage as pi_rlc_stage;
use neo_math::ring::D;

use super::repo_root;

const LEAN_DATA_PATH: &str = "formal/nightstream-lean/Nightstream/Implementation/R1CS/Artifacts/FPrimeRecursive/PiRlcChallenge/Generated/ChallengeWiringData.lean";
const RHO_COUNT: usize = 15;

#[derive(Clone, Debug, PartialEq, Eq)]
struct ChallengeWiring {
    selection_trace: Range<usize>,
    output_base: usize,
    rho_stride: usize,
    coefficient_stride: usize,
}

pub(super) fn projection_rho_columns(trace: &R1csEncodingTrace) -> Vec<Vec<usize>> {
    let identities = trace
        .projection_identities()
        .iter()
        .filter_map(|identity| match identity.role {
            ProjectionIdentityRole::YZColLimb { limb } => Some((limb, identity)),
            _ => None,
        })
        .collect::<Vec<_>>();
    assert_eq!(
        identities.iter().map(|(limb, _)| *limb).collect::<Vec<_>>(),
        [0, 1],
        "diagnostic profile must contain exactly the ordered y_zcol identities"
    );
    assert_eq!(
        identities[0].1.rho_columns, identities[1].1.rho_columns,
        "both y_zcol limbs must consume the same rho coefficient wires"
    );
    assert_eq!(identities[0].1.rho_columns.len(), RHO_COUNT, "rho count");
    assert!(
        identities[0]
            .1
            .rho_columns
            .iter()
            .all(|columns| columns.len() == D),
        "rho coefficient width"
    );
    identities[0].1.rho_columns.clone()
}

fn extract_wiring(trace: &R1csEncodingTrace) -> ChallengeWiring {
    let rho_columns = projection_rho_columns(trace);
    let expected_outputs = rho_columns.iter().flatten().copied().collect::<Vec<_>>();
    let output_count = RHO_COUNT * D;
    assert_eq!(expected_outputs.len(), output_count, "rho consumer width");

    let selections = trace.first_accepted_selections();
    assert!(
        selections.len() >= output_count,
        "selection trace is shorter than the active 15 x 54 rho batch"
    );
    let matching_starts = (0..=selections.len() - output_count)
        .filter(|&start| {
            selections[start..start + output_count]
                .iter()
                .enumerate()
                .all(|(offset, selection)| {
                    selection.position == offset % D && selection.output.col() == expected_outputs[offset]
                })
        })
        .collect::<Vec<_>>();
    let &[start] = matching_starts.as_slice() else {
        panic!(
            "expected exactly one ordered 15 x 54 sampler-output window consumed by projection, found {}",
            matching_starts.len()
        );
    };
    let selection_trace = start..start + output_count;

    let output_base = expected_outputs[0];
    let coefficient_stride = expected_outputs[1]
        .checked_sub(output_base)
        .expect("sampler coefficient columns are increasing");
    let rho_stride = expected_outputs[D]
        .checked_sub(output_base)
        .expect("sampler rho columns are increasing");
    for rho in 0..RHO_COUNT {
        for coefficient in 0..D {
            assert_eq!(
                rho_columns[rho][coefficient],
                output_base + rho_stride * rho + coefficient_stride * coefficient,
                "active sampler output affine address"
            );
        }
    }

    ChallengeWiring {
        selection_trace,
        output_base,
        rho_stride,
        coefficient_stride,
    }
}

fn render(wiring: &ChallengeWiring) -> String {
    let mut rendered = String::new();
    rendered.push_str(
        "/-! Generated by `active_pi_rlc_projection_artifacts_match_production_trace`; do not hand-edit. -/\n\n",
    );
    rendered.push_str("namespace Nightstream.Implementation.R1CS.FPrimeRecursivePiRlcChallengeWiringData\n\n");
    writeln!(
        rendered,
        "def producerStagePath : String := \"{}\"",
        pi_rlc_challenge_stage::SELECT_BIND_SYMBOL
    )
    .expect("render producer stage");
    writeln!(
        rendered,
        "def consumerStagePath : String := \"{}\"",
        pi_rlc_stage::PROJECTION_SHARED_RHO_EVALUATIONS
    )
    .expect("render consumer stage");
    writeln!(
        rendered,
        "def selectionTraceStart : Nat := {}",
        wiring.selection_trace.start
    )
    .expect("render selection trace start");
    writeln!(
        rendered,
        "def selectionTraceEnd : Nat := {}",
        wiring.selection_trace.end
    )
    .expect("render selection trace end");
    writeln!(rendered, "def outputBase : Nat := {}", wiring.output_base).expect("render output base");
    writeln!(rendered, "def rhoStride : Nat := {}", wiring.rho_stride).expect("render rho stride");
    writeln!(
        rendered,
        "def coefficientStride : Nat := {}\n",
        wiring.coefficient_stride
    )
    .expect("render coefficient stride");
    rendered.push_str("end Nightstream.Implementation.R1CS.FPrimeRecursivePiRlcChallengeWiringData\n");
    rendered
}

pub(super) fn check_generated_artifact(trace: &R1csEncodingTrace) {
    let rendered = render(&extract_wiring(trace));
    let path = repo_root().join(LEAN_DATA_PATH);
    let committed = fs::read_to_string(&path).unwrap_or_default();
    if committed != rendered {
        let expected = path.with_extension("lean.expected");
        fs::create_dir_all(expected.parent().expect("generated artifact parent"))
            .expect("create generated artifact directory");
        fs::write(&expected, &rendered).expect("write expected active rho challenge wiring");
    }
    assert_eq!(committed, rendered, "active rho challenge wiring drifted");
}
