import Nightstream.Implementation.NebulaV2.NIFS.Running.ExactRows

set_option autoImplicit false

namespace tests.NebulaV2ExactNifsRunningRows

#check Nightstream.Implementation.NebulaV2.ExactNifsRunningRows.bitsPlaced_of_fullClaim
#check Nightstream.Implementation.NebulaV2.ExactNifsRunningRows.input_matches_rows
#check Nightstream.Implementation.NebulaV2.ExactNifsRunningRows.selected_input_matches_rows

end tests.NebulaV2ExactNifsRunningRows
