import Nightstream.Implementation.NebulaV2.NIFS.Running.RunningParserCorrect

set_option autoImplicit false

namespace tests.NebulaV2ProductNifsRunningParser

open Nightstream.Implementation.NebulaV2.ProductNifsRunningParser

#check exact_section_counts
#check point_coordinate_bound
#check bundle_coordinate_bound
#check public_input_coordinate_bound
#check evaluation_coordinate_bound
#check commitmentCodec_getD
#check bundleCodec_getD
#check evaluationCodec_getD
#check runningCodec_point_getD
#check runningCodec_bundle_getD
#check runningCodec_publicInput_getD
#check runningCodec_evaluation_getD
#check runningOfFields_fieldsOfRunning
#check fieldBlockOfRunning_eq
#check parse_blockOfRunning
#check parse_rejects_modulus_word

end tests.NebulaV2ProductNifsRunningParser
