name = "superneo_lean"
defaultTargets = ["SuperNeo"]

[[lean_lib]]
name = "SuperNeo"

[[lean_exe]]
name = "check"
root = "Main"

[[lean_exe]]
name = "goldilocks-golden"
root = "GoldilocksGolden"

[[lean_exe]]
name = "ring-golden"
root = "RingGolden"

[[lean_exe]]
name = "eq-mle-golden"
root = "EqMleGolden"

[[lean_exe]]
name = "p9-p11-p12-golden"
root = "P9P11P12Golden"

[[lean_exe]]
name = "p13-p14-golden"
root = "P13P14Golden"
