import SuperNeo.Decomp
#check Int.sub_eq
#check Int.sub_eq_add_neg
#check Int.add_assoc
#check Int.add_left_comm
#check Int.add_comm
#check add_assoc
#check sub_eq_add_neg
#check Int.add_sub_cancel
#check Int.add_sub_assoc
