import Nightstream.Implementation.Nebula.Production.Carrier.StreamingPiRLCAuthority

/-! Regression surface for authoritative production PiRLC replay. -/

set_option autoImplicit false

namespace tests.NebulaProductionStreamingPiRlcAuthority

open Nightstream.Implementation.Nebula.ProductionStreamingPiRlcAuthority

#check ringFields_length
#check ringFields_injective
#check sourceSchedule_length
#check sourceSchedule_values
#check sourceBlocks_lengths
#check phaseFields_length
#check phaseFields_injective
#check inputChunks_lengths
#check inputFrame_length
#check familySchedule_ordinals
#check authoritativeInputRings
#check piCcsOutputs_evaluations_eq_singleton
#check complete_family_run_eq_parent
#check phase_chunk_count_exact
#check fused_phase_recovers_inputs_or_collision
#check accepted_different_phase_implies_collision
#check FamilyState
#check initialFamilyState
#check FamilyStartTransition
#check FamilyStartRelation
#check familyStart_of_transition
#check inputResidualFields
#check inputResidualFields_length
#check familyStateFields
#check familyStateFields_length
#check FamilyTransition
#check FamilyPhaseRelation
#check familyPhase_uses_authoritative_challenges
#check familyPhase_recovers_authoritative_inputs_or_collision
#check local_rows_imply_concrete_phase
#check local_rows_imply_concrete_phase_from_input_rows
#check sampler_rows_imply_authoritative_start

end tests.NebulaProductionStreamingPiRlcAuthority
