import Nightstream.Implementation.Nebula.Production.Carrier.StreamingPiRLCInputBinding

/-! Regression surface for the complete production PiRLC input binding. -/

set_option autoImplicit false

namespace tests.NebulaProductionStreamingPiRlcInputBinding

open Nightstream.Implementation.Nebula.ProductionStreamingPiRlcInputBinding

#check exact_geometry
#check exact_shape
#check familyOrdinal_familyAtOrdinal
#check familyAtOrdinal_familyOrdinal
#check familyAtOrdinal_familyIndex
#check familyInputPosition
#check positionOrdinal_familyInputPosition
#check positionFamily_familyInputPosition
#check positionSource_familyInputPosition
#check positionLane_familyInputPosition
#check inputVector_familyInputPosition
#check inputVector_injective
#check flatIndex_messagePosition
#check flatIndex_lt
#check coordinateWitness_at
#check coordinateWitness_injective
#check coordinateWitness_unit_bound
#check equal_binding_recovers_fields_or_failure
#check equal_input_binding_recovers_inputs_or_failure
#check exact_source_geometry

end tests.NebulaProductionStreamingPiRlcInputBinding
