//! Exhaustive Rust-to-Lean artifact for the Phi81 bar matrix.
//!
//! Owns: row-major export of every entry returned by the production
//! `superneo_bar_matrix` cache and a byte-for-byte drift gate for the generated
//! Lean data module.
//!
//! Does not own: the mathematical Theorem-3 identity, matrix-cache consumers,
//! CCS row packing, R1CS lowering, or permission to remove constraints.
//!
//! | Protocol | Phase | Family | Exported evidence |
//! |---|---|---|---|
//! | coefficient embedding | runtime bar construction | 54 by 54 matrix | every canonical field entry in row-major order |
//! | implementation refinement | Rust to Lean | artifact drift | exact generated bytes or a review-only `.expected` file |

use neo_math::{superneo_bar_matrix, D};
use p3_field::PrimeField64;

const ARTIFACT_REL_PATH: &str = "/../../formal/nightstream-lean/Nightstream/Implementation/R1CS/Artifacts/Phi81/Generated/Phi81BarMatrixArtifact.lean";

fn emit_lean() -> String {
    let matrix = superneo_bar_matrix();
    let nonzero_count = matrix
        .iter()
        .flat_map(|row| row.iter())
        .filter(|entry| entry.as_canonical_u64() != 0)
        .count();

    let mut out = String::new();
    out.push_str("import Nightstream.SuperNeo.Concrete.Algebra\n\n");
    out.push_str("/-!\nGENERATED FILE - do not edit by hand.\n\n");
    out.push_str("Exhaustive row-major output of Rust `neo_math::superneo_bar_matrix`.\n");
    out.push_str("Regenerated and drift-checked by\n");
    out.push_str("`cargo test -p neo-math --release --test phi81_bar_lean_artifact`.\n\n");
    out.push_str("This is implementation evidence, not semantic authority. The handwritten\n");
    out.push_str("Lean consumer must prove equality with the independently defined Phi81 bar.\n-/\n\n");
    out.push_str("namespace Nightstream.Implementation.R1CS.Phi81BarMatrixArtifact\n\n");
    out.push_str(&format!("def rowCount : Nat := {D}\n"));
    out.push_str(&format!("def columnCount : Nat := {D}\n"));
    out.push_str(&format!("def nonzeroCount : Nat := {nonzero_count}\n\n"));
    out.push_str("def rows : List (List Nat) :=\n  [");

    let rendered_rows: Vec<String> = matrix
        .iter()
        .map(|row| {
            let entries: Vec<String> = row
                .iter()
                .map(|entry| entry.as_canonical_u64().to_string())
                .collect();
            format!("[{}]", entries.join(", "))
        })
        .collect();
    out.push_str(&rendered_rows.join(",\n   "));
    out.push_str("]\n\n");
    out.push_str("end Nightstream.Implementation.R1CS.Phi81BarMatrixArtifact\n");
    out
}

#[test]
fn phi81_bar_matrix_lean_artifact_matches_runtime() {
    assert_eq!(D, 54, "the Phi81 artifact is specialized to d = 54");

    let emitted = emit_lean();
    let path = format!("{}{}", env!("CARGO_MANIFEST_DIR"), ARTIFACT_REL_PATH);
    let committed = std::fs::read_to_string(&path).unwrap_or_default();
    if committed != emitted {
        let expected_path = format!("{path}.expected");
        let parent = std::path::Path::new(&expected_path)
            .parent()
            .expect("artifact path has a parent");
        std::fs::create_dir_all(parent).expect("create generated artifact directory");
        std::fs::write(&expected_path, &emitted).expect("write .expected artifact");
        panic!(
            "Phi81 bar-matrix Lean artifact drifted. Wrote {expected_path}; inspect it and promote it deliberately."
        );
    }
}
