import Nightstream.Implementation.NebulaV2.Production.FPrime.Recursive.RelationRowsSoundFor

open Nightstream.Implementation.NebulaV2.ProductionPaperRecursiveRelationRowsSoundFor

#check paperVerifier
#check rows_imply_verified_exact_claim_and_memory_transition
