import Nightstream.Implementation.Nebula.Production.Application.ApplicationBatchBridge

set_option autoImplicit false

namespace tests.NebulaProductionApplicationBatchBridge

open Nightstream.Implementation.Nebula.ProductionApplicationBatchBridge

#check memoryNormalizedRows_length
#check memoryNormalizedRows_accesses
#check stepAccesses_length
#check Matches.accesses_exact

end tests.NebulaProductionApplicationBatchBridge
