import Nightstream.Implementation.R1CS.Artifacts.FPrimeFullHistory.StreamingClaimReplayCanonicalCallCertificate
import Nightstream.Implementation.R1CS.Artifacts.FPrimeFullHistory.StreamingClaimReplayFinalGlueRowCertificate
import Nightstream.Implementation.R1CS.Artifacts.FPrimeFullHistory.StreamingClaimReplayFinalPoseidon2CallCertificate
import Nightstream.Implementation.R1CS.Artifacts.FPrimeFullHistory.StreamingClaimReplayFullGlueRowCertificate
import Nightstream.Implementation.R1CS.Artifacts.FPrimeFullHistory.StreamingClaimReplayFullPoseidon2CallCertificate

/-!
Contract: structural leaf-geometry certificates for both Rust-emitted streaming
claim-replay arms.

Assurance tier: Rust-to-Lean leaf-geometry certificate.

Owns the composition of canonical-u64, Poseidon2, and glue-row geometry facts.

Does not own leaf semantics, row ownership, or lifecycle integration.

Emits constraints: no.
-/

set_option autoImplicit false

namespace Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingClaimReplayLeafGeometryCertificate

open Nightstream.Implementation.R1CS.Artifacts.FPrimeFullHistory.Generated.FPrimeFullHistoryStreamingClaimReplay
open Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingClaimReplay.Artifact

theorem fullArm_leafGeometry_valid : fullArm.LeafGeometryValid :=
  ⟨Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingClaimReplayCanonicalCallCertificate.fullArm_canonicalCalls_valid,
    Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingClaimReplayFullPoseidon2CallCertificate.fullArm_poseidon2Calls_valid,
    Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingClaimReplayFullGlueRowCertificate.fullArm_glueRows_valid⟩

theorem finalArm_leafGeometry_valid : finalArm.LeafGeometryValid :=
  ⟨Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingClaimReplayCanonicalCallCertificate.finalArm_canonicalCalls_valid,
    Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingClaimReplayFinalPoseidon2CallCertificate.finalArm_poseidon2Calls_valid,
    Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingClaimReplayFinalGlueRowCertificate.finalArm_glueRows_valid⟩

end Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingClaimReplayLeafGeometryCertificate
