import Batteries.Data.Fin.Coding
import NightstreamFPrime.Export.Stage1.Invocations
import NightstreamFPrime.Layout.ProductionRelation.PoseidonSboxPlan

/-!
Owns a random-access selector for Poseidon2 invocations generated by a Duplex
action list. The selector walks the small action list and indexes absorb
chunks directly. It never indexes the fully expanded invocation list.

This module does not lower action expressions or select a concrete phase.
-/

namespace NightstreamFPrime.Export.Stage1.PoseidonActionSchedule

open NightstreamFPrime.Circuit
open NightstreamFPrime.Circuit.Quadratic
open NightstreamFPrime.Export.Stage1.Invocations
open NightstreamFPrime.Gadgets.Poseidon2
open NightstreamFPrime.Gadgets.Poseidon2.Duplex
open NightstreamFPrime.Layout.ProductionRelation

inductive Kind where
  | absorb (block : List Expr)
  | squeezeFirst (expected : KExpr)
  | squeezeSecond

def Kind.WellFormed : Kind → Prop
  | .absorb block => block.length ≤ Spec.Poseidon2.rate
  | .squeezeFirst _ | .squeezeSecond => True

def actionKinds : Formal.Action → List Kind
  | .absorb input => (Hash.inputChunks input).map Kind.absorb
  | .squeezeK expected => [.squeezeFirst expected, .squeezeSecond]

@[simp] theorem actionKinds_length (action : Formal.Action) :
    (actionKinds action).length =
      Invocations.Action.invocationCount action := by
  cases action <;>
    simp [actionKinds, Invocations.Action.invocationCount]

theorem actionKinds_wellFormed (action : Formal.Action) :
    ∀ kind ∈ actionKinds action, kind.WellFormed := by
  intro kind member
  cases action with
  | absorb input =>
      simp only [actionKinds, List.mem_map] at member
      rcases member with ⟨block, blockMember, rfl⟩
      change block.length ≤ Spec.Poseidon2.rate
      unfold Hash.inputChunks at blockMember
      simp only [List.mem_map] at blockMember
      rcases blockMember with ⟨index, _, rfl⟩
      exact List.length_take_le _ _
  | squeezeK expected =>
      simp [actionKinds] at member
      rcases member with rfl | rfl <;> trivial

def kinds (actions : List Formal.Action) : List Kind :=
  actions.flatMap actionKinds

@[simp] theorem kinds_length (actions : List Formal.Action) :
    (kinds actions).length = Invocations.invocationCount actions := by
  induction actions with
  | nil => rfl
  | cons action actions inductionHypothesis =>
      simp [kinds, Invocations.invocationCount, actionKinds_length]

theorem kinds_wellFormed (actions : List Formal.Action) :
    ∀ kind ∈ kinds actions, kind.WellFormed := by
  intro kind member
  unfold kinds at member
  rw [List.mem_flatMap] at member
  rcases member with ⟨action, actionMember, kindMember⟩
  exact actionKinds_wellFormed action kind kindMember

def actionKindAt (action : Formal.Action) :
    Fin (Invocations.Action.invocationCount action) → Kind :=
  match action with
  | .absorb input => fun index =>
      .absorb <| (Hash.inputChunks input).get index
  | .squeezeK expected => fun index =>
      Fin.cases (.squeezeFirst expected) (fun _ => .squeezeSecond) index

@[simp] theorem actionKindAt_materializes (action : Formal.Action) :
    List.ofFn (actionKindAt action) = actionKinds action := by
  cases action with
  | absorb input =>
      change List.ofFn (fun index =>
        Kind.absorb ((Hash.inputChunks input).get index)) =
          (Hash.inputChunks input).map Kind.absorb
      calc
        _ = (List.ofFn fun index : Fin (Hash.inputChunks input).length =>
              (Hash.inputChunks input).get index).map Kind.absorb := by
            rw [List.map_ofFn]
            apply congrArg List.ofFn
            funext index
            rfl
        _ = _ := congrArg (List.map Kind.absorb)
          (List.ofFn_get (Hash.inputChunks input))
  | squeezeK expected => rfl

/-- Random-access selector in exact action order. Its cost is proportional
to the small action list, not to the expanded invocation count. -/
def kindAt : (actions : List Formal.Action) →
    Fin (Invocations.invocationCount actions) → Kind
  | [], index => Fin.elim0 index
  | action :: actions, index =>
      Fin.append (actionKindAt action) (kindAt actions) index

/-- Materializing the fast selector gives the canonical expanded invocation
kind list byte-for-byte and position-for-position. -/
@[simp] theorem kindAt_materializes (actions : List Formal.Action) :
    List.ofFn (kindAt actions) = kinds actions := by
  induction actions with
  | nil => rfl
  | cons action actions inductionHypothesis =>
      change
        List.ofFn (Fin.append (actionKindAt action) (kindAt actions)) =
          actionKinds action ++ kinds actions
      rw [List.ofFn_fin_append, actionKindAt_materializes,
        inductionHypothesis]

theorem kindAt_wellFormed (actions : List Formal.Action)
    (invocation : Fin (Invocations.invocationCount actions)) :
    (kindAt actions invocation).WellFormed := by
  apply kinds_wellFormed actions
  rw [← kindAt_materializes]
  exact (List.mem_ofFn).2 ⟨invocation, rfl⟩

def previousState {logicalWidth invocationCount : Nat}
    (initial : PoseidonSboxPlan.State logicalWidth)
    (output : Fin invocationCount → PoseidonSboxPlan.State logicalWidth)
    (invocation : Fin invocationCount) : PoseidonSboxPlan.State logicalWidth :=
  if first : invocation.val = 0 then
    initial
  else
    output ⟨invocation.val - 1, by
      have invocationBound := invocation.isLt
      omega⟩

/-- Direct invocation input from one selected action kind. Absorptions add
one caller-supplied block form; both squeeze permutations use the prior
output unchanged. -/
def inputState {logicalWidth : Nat} (actions : List Formal.Action)
    (initial : PoseidonSboxPlan.State logicalWidth)
    (output : Fin (Invocations.invocationCount actions) →
      PoseidonSboxPlan.State logicalWidth)
    (blockForm : List Expr → PoseidonSboxPlan.State logicalWidth)
    (invocation : Fin (Invocations.invocationCount actions)) :
    PoseidonSboxPlan.State logicalWidth :=
  let previous := previousState initial output invocation
  match kindAt actions invocation with
  | .absorb block => fun lane =>
      SparseForm.add (previous lane) (blockForm block lane)
  | .squeezeFirst _ => previous
  | .squeezeSecond => previous

end NightstreamFPrime.Export.Stage1.PoseidonActionSchedule
