import NightstreamFPrime.Export.Stage1.NifsFiatShamir
import NightstreamFPrime.Spec.Folding.Nifs.SequentialObservationLaw
import NightstreamFPrime.Lifecycle.Nifs.AdaptiveBinding
import NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingRun
import NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingLaw
import NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingProbability
import NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingWork
import NightstreamFPrime.Export.Stage1.NifsClosure
import NightstreamFPrime.Export.Stage1.NifsProviderLaw
import NightstreamFPrime.Export.Stage1.NifsInvalidSource
import NightstreamFPrime.Lifecycle.Nifs.VerifierErrorBudget
import NightstreamFPrime.Export.Stage1.PiRLCExtractionPrimitives
import NightstreamFPrime.Lifecycle.Nifs.FiatShamirTransfer
import NightstreamFPrime.Export.Stage1.PiCCSStoredSourceProbability
import NightstreamFPrime.Export.Stage1.NifsBinding
import NightstreamFPrime.Export.Stage1.PiDECCommitmentMatrixEntry
import NightstreamFPrime.Export.Stage1.PiDECCommitmentMatrixWork
import NightstreamFPrime.Export.Stage1.PiDECOrdinarySourceWork
import NightstreamFPrime.Layout.MatrixProgram.RetainedWork
import NightstreamFPrime.Layout.MatrixProgram.CoefficientWork
import NightstreamFPrime.Layout.MatrixProgram.SparseWork
import NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.StoredRingPowerInverse
import NightstreamFPrime.Spec.Phi81Relation.PiRLCAlgebra.StoredCommitment
import NightstreamFPrime.Export.Stage1.PiCCSStoredPublicCheck
import NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.StoredRingInverseWork
import NightstreamFPrime.Spec.AjtaiSetupV1.Work
import NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.RingFFrobenius
import NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.StoredRingArithmetic
import NightstreamFPrime.Spec.ProductionRelation.GatePolynomial
import tests.AxiomAudit
import NightstreamFPrime.Lifecycle.NifsProfile
import NightstreamFPrime.Lifecycle.Nifs.StrongExtraction
import NightstreamFPrime.Lifecycle.Nifs.WeakExtraction
import NightstreamFPrime.Lifecycle.Nifs.InteractiveComposition
import NightstreamFPrime.Lifecycle.Nifs.InteractiveCompleteness
import NightstreamFPrime.Lifecycle.Nifs.BaseCompleteness
import NightstreamFPrime.Lifecycle.Nifs.BaseVerifierCompleteness
import NightstreamFPrime.Lifecycle.PiRLC.v1_1.SamplerChain
import NightstreamFPrime.Lifecycle.Nifs.InteractiveWork
import NightstreamFPrime.Lifecycle.Nifs.InteractiveOutput
import NightstreamFPrime.Lifecycle.Nifs.SupportedContinuation
import NightstreamFPrime.Lifecycle.Nifs.SupportedExtraction
import NightstreamFPrime.Lifecycle.Nifs.BindingBridge
import NightstreamFPrime.Lifecycle.Nifs.BindingWork
import NightstreamFPrime.Lifecycle.Nifs.InteractiveAgreement
import NightstreamFPrime.Spec.Folding.Nifs.InteractiveDistribution
import NightstreamFPrime.Spec.Folding.Nifs.InteractivePrefix
import NightstreamFPrime.Spec.Folding.Nifs.PaperAlignedExtraction
import NightstreamFPrime.Spec.Folding.Nifs.PaperCompositionAgreement
import NightstreamFPrime.Spec.Folding.Nifs.PaperCompositionProbability
import NightstreamFPrime.Spec.Folding.Nifs.PaperCompositionWork
import NightstreamFPrime.Spec.Folding.Nifs.PaperStrongCompleteness
import NightstreamFPrime.Spec.Folding.Nifs.PaperCausalReplay
import NightstreamFPrime.Spec.Folding.Nifs.PaperNonInteractive.Completeness
import NightstreamFPrime.Spec.Folding.Nifs.PaperStrongInterface
import NightstreamFPrime.Spec.Folding.Nifs.PaperWeakAgreement
import NightstreamFPrime.Spec.Folding.Nifs.PaperWeakAlgorithm
import NightstreamFPrime.Spec.Folding.Nifs.PaperWeakAbort
import NightstreamFPrime.Spec.Folding.Nifs.PaperWeakCompleteness
import NightstreamFPrime.Spec.Folding.Nifs.PaperWeakExtraction
import NightstreamFPrime.Spec.Folding.Nifs.PaperWeakLaw
import NightstreamFPrime.Spec.Folding.Nifs.PaperWeakOracle
import NightstreamFPrime.Spec.Folding.Nifs.PaperWeakOutput
import NightstreamFPrime.Spec.Folding.Nifs.PaperWeakSuffix
import NightstreamFPrime.Spec.Folding.Nifs.SuffixCoinCoupling
import NightstreamFPrime.Spec.Folding.Nifs.VerifierCoinSpace
import NightstreamFPrime.Spec.Folding.Nifs.VerifierCoinLaw
import NightstreamFPrime.Spec.Folding.Nifs.SequentialOutputLaw
import NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StrongProbability
import NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessProjection
import NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredOneRunExtraction
import NightstreamFPrime.Spec.Folding.PiRLC.PaperForkBinding
import NightstreamFPrime.Spec.Folding.Nifs.StoredAssignmentArithmetic
import NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheck
import NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheckWork
import NightstreamFPrime.Export.Stage1.PiCCSStoredWitnessCheck

import NightstreamFPrime.Lifecycle.Nifs.StoredSuffix
import NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredProbe
import NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheckPrimitives
import NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.StoredRingInverse
import NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.StoredRingInverseCorrect

import NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.RingFPolynomial
import NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.StoredRingInverseUnit
import NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheckEntries

/-! Axiom audits for the selected NIFS profile and interactive composition. -/










#audit_axioms NightstreamFPrime.Spec.ProductionRelation.GatePolynomial.termData_length

#audit_axioms NightstreamFPrime.Spec.ProductionRelation.GatePolynomial.termData_toMonomial




#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.RingFPolynomial.coeff_toPolynomial
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.RingFPolynomial.toPolynomial_injective
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.RingFPolynomial.toPolynomial_zero
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.RingFPolynomial.toPolynomial_one
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.RingFPolynomial.modulus_monic
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.RingFPolynomial.toPolynomial_ringFMul_mod
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.StoredRingInverseUnit.candidate_mul_value
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.StoredRingInverseUnit.candidate_eq_unitInverse
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheckEntries.nativeBarEntry_value
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheckEntries.nativeBarEntry_work_le
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheckEntries.kernelWeight_value
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheckEntries.kernelWeight_work_le
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheckEntries.padEntry_value
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheckEntries.padEntry_work_le
#audit_axioms NightstreamFPrime.Export.Stage1.PiCCSStoredWitnessCheck.padEntry_value

#audit_axioms NightstreamFPrime.Lifecycle.Nifs.StoredSuffix.finish_return_iff
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.StoredSuffix.finish_work_le
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.StoredSuffix.finish_returns_parent
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredProbe.padRead_value
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredProbe.padRead_work
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredProbe.matrixRead_value
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredProbe.matrixRead_work
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheckPrimitives.dotStep_value
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheckPrimitives.dotStep_work
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheckPrimitives.embed_value
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheckPrimitives.embed_work
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheckPrimitives.interpolate_value
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheckPrimitives.interpolate_work
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheckPrimitives.equalF_value
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheckPrimitives.equalF_work
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheckPrimitives.equalK_value
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheckPrimitives.equalK_work
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheckPrimitives.equalK_work_le
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheckPrimitives.norm_value
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheckPrimitives.norm_work
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheckPrimitives.withScalarChecks_correct
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheckPrimitives.withScalarChecks_bounded
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.StoredRingInverse.encode_coeff
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.StoredRingInverse.candidate_coeff
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.StoredRingInverse.modulus_toPolynomial
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.StoredRingInverse.divisor_monic
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.StoredRingInverse.candidatePolynomial_toPolynomial
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.StoredRingInverse.normalized_bezout
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.StoredRingInverseCorrect.modulus_degree
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.StoredRingInverseCorrect.candidatePolynomial_degree_lt
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.StoredRingInverseCorrect.candidatePolynomial_mul_mod
#audit_axioms NightstreamFPrime.Export.Stage1.PiCCSStoredWitnessCheck.publicInputRead_value
#audit_axioms NightstreamFPrime.Export.Stage1.PiCCSStoredWitnessCheck.publicInputRead_work
#audit_axioms NightstreamFPrime.Export.Stage1.PiCCSStoredWitnessCheck.publicInputRead_work_le
#audit_axioms NightstreamFPrime.Export.Stage1.PiCCSStoredWitnessCheck.scalar_finish_source_iff
#audit_axioms NightstreamFPrime.Export.Stage1.PiCCSStoredWitnessCheck.scalar_check_work_le

#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.StoredAssignmentArithmetic.build_value
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.StoredAssignmentArithmetic.build_work_le
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.StoredAssignmentArithmetic.subtract_value
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.StoredAssignmentArithmetic.subtract_work_le
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.StoredAssignmentArithmetic.combine_value
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.StoredAssignmentArithmetic.combine_work_le
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.StoredAssignmentArithmetic.recompose_value
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.StoredAssignmentArithmetic.recompose_work_le
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheck.evaluations_eq_honestAt
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheck.ambientCheck_eq_true_iff
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheck.check_eq_true_iff
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheckWork.check_value
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheckWork.check_work_le
#audit_axioms NightstreamFPrime.Export.Stage1.PiCCSStoredWitnessCheck.statement_eq_key
#audit_axioms NightstreamFPrime.Export.Stage1.PiCCSStoredWitnessCheck.check_eq_true_iff
#audit_axioms NightstreamFPrime.Export.Stage1.PiCCSStoredWitnessCheck.chargedCheck_correct
#audit_axioms NightstreamFPrime.Export.Stage1.PiCCSStoredWitnessCheck.finish_source_iff
#audit_axioms NightstreamFPrime.Export.Stage1.PiCCSStoredWitnessCheck.charged_finish_source_iff

#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.CostedWitnessProjection.projectReads_value
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.CostedWitnessProjection.projectReads_work_le
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessProjection.project_value
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessProjection.project_work_le
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessProjection.reconstruct_project
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.CheckedWitnessExtraction.finishStored_work_le
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.CheckedWitnessExtraction.finishStored_source_iff
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredOneRunExtraction.run_work_le
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredOneRunExtraction.run_source_iff
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredOneRunExtraction.expected_work_bound

#audit_axioms NightstreamFPrime.Lifecycle.NifsProfile.selected_relation
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperCompositionAgreement.paired_executionMean_eq
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperCompositionAgreement.disagreementProbability_eq_pairMean
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperCompositionAgreement.pairMean_mono
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperCompositionAgreement.positive_decoded_disagreement_implies_binding
#audit_axioms NightstreamFPrime.Lifecycle.NifsProfile.selected_matrix
#audit_axioms NightstreamFPrime.Lifecycle.NifsProfile.selected_shape
#audit_axioms NightstreamFPrime.Lifecycle.NifsProfile.selected_arity
#audit_axioms NightstreamFPrime.Lifecycle.NifsProfile.shared_setup
#audit_axioms NightstreamFPrime.Lifecycle.NifsProfile.phases_preserve_relation

#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperStrongInterface.piRlcBatchForProbe_eq_piRlcBatch
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperStrongInterface.piRlcBatchForProbe_same_phi
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperStrongInterface.outputWitnessOfAssignments_at
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperStrongInterface.outputWitnessOfAssignments_ambient
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperStrongCompleteness.exists_causal_honest_strategy
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperStrongCompleteness.exists_honest_piCcs_prover
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperCausalReplay.generated_messages_replay
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperCausalReplay.prover_generated_messages_replay
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperNonInteractive.Completeness.exists_honest_proof_of_sampler_success
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.StrongExtraction.source_success_ge
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.StrongExtraction.successProbability_eq
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.StrongExtraction.probability_and_expected_work
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.WeakExtraction.batchForOutput_eq_probe
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.WeakExtraction.continuation_success_range
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.WeakExtraction.weak_relaxed_success_bound
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.InteractiveComposition.local_weak_bound
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.InteractiveCompleteness.exists_honest_execution
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BaseCompleteness.zeroProof_piCcsCheck
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BaseCompleteness.zeroProof_parentBounded
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.InteractiveComposition.source_success_bound
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.InteractiveComposition.source_success_retry_bound
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.InteractiveOutput.finish_value_eq
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.InteractiveOutput.returnedSourceProbability_eq
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.SupportedContinuation.return_supported
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.SupportedContinuation.extension_eq_on_support
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.SupportedContinuation.extension_eq_on_return
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.SupportedContinuation.offsupport_rawCall_none
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.SupportedContinuation.offsupport_run_eq
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.SupportedExtraction.returned_source_success_bound
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.SupportedExtraction.publicCheck_correct
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.SupportedExtraction.returned_source_bound_with_binding
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.SupportedExtraction.probability_and_expected_work
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.InteractiveWork.totalClock_on_checked_prefix
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.InteractiveWork.call_returns_accepted
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.InteractiveWork.expected_work_polynomial_bound
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BindingBridge.compatible
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.InteractiveAgreement.localBindingProbability_range
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.InteractiveAgreement.local_disagreement_le_binding
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.InteractiveAgreement.disagreement_le_bindingProbability

#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakAbort.rawCall_eq
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakAbort.run_eq
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakAbort.oracle_meanWork
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakAbort.charged_mass
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakAbort.charged_meanWork

#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakSuffix.finish_return_iff
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakSuffix.finish_returns_parent
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakSuffix.finish_work_le
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakOracle.run_work_le
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakOracle.run_returns_parent
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakOracle.law_meanWork
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakOracle.law_response_mean
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakOracle.law_meanWork_le
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakOracle.mass_invalid_parent_zero
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakLaw.mass_nonnegative
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakLaw.mass_total
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakLaw.law_toReal
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakLaw.law_some_positive_iff
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakLaw.law_mean
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakLaw.successProbability_eq_returningProbability
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakLaw.terminal_work_mean
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakExtraction.run_return_iff
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakExtraction.acceptance_eq
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakExtraction.rate_eq_successProbability
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakExtraction.weak_success_bound
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakAlgorithm.Algorithm.oracle_meanWork
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakAlgorithm.Algorithm.oracle_meanWork_le
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakAlgorithm.Algorithm.base_rate
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakAlgorithm.Algorithm.weak_success_bound

#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakAgreement.positive_return_opens_probe
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakOutput.witnessOfList_ofFn
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakOutput.positive_endpoint
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakOutput.valid_mean_eq_returningProbability
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakCompleteness.attempt_eq_publicAttempt
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakCompleteness.publicAccepts_iff
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakCompleteness.honest_complete
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakCompleteness.honest_public_accepts
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakCompleteness.public_parent
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperAlignedExtraction.positive_return_implies_alignedFork

#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.VerifierCoinSpace.coins_request
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.VerifierCoinLaw.verifierMean_eq_requestMean
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.SequentialOutputLaw.context_marginal
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.SequentialOutputLaw.eventProbability_eq
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.SequentialOutputLaw.law_eq_of_suffix_eq_on_return
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.SuffixCoinCoupling.selected_law
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.SuffixCoinCoupling.mean_map
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.SuffixCoinCoupling.selected_mean
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.InteractivePrefix.run_coins
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.InteractivePrefix.run_relay
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.InteractivePrefix.run_checked
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.InteractivePrefix.checked_returns
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.InteractiveDistribution.sequentialMean_range
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.InteractiveDistribution.selected_mean
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.InteractiveDistribution.executionMean_eq_sequentialMean
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperCompositionProbability.relaxedProbability_eq
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperCompositionProbability.sourceProbability_eq
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperCompositionProbability.source_success_ge
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperCompositionProbability.source_success_ge_from_weak
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperCompositionProbability.source_success_ge_retry
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperCompositionProbability.source_success_ge_retry_from_weak
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperCompositionAgreement.pairMean_range
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperCompositionAgreement.successful_disagreement_implies_bindingEvent
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperCompositionAgreement.disagreementProbability_le_bindingProbability
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperCompositionAgreement.bindingProbability_range
#audit_axioms NightstreamFPrime.Spec.Folding.PiRLC.PaperForkBinding.collisionAt
#audit_axioms NightstreamFPrime.Spec.Folding.PiRLC.PaperForkBinding.two_forks_unique_or_collision
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperCompositionWork.finish_work_le
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperCompositionWork.finishMean_le
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperCompositionWork.totalClock_on_prefix
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperCompositionWork.totalClock_le
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperCompositionWork.expected_work_bound
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperCompositionWork.expected_work_polynomial_bound

#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StrongProbability.verifierMean_const
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StrongProbability.verifierMean_mono
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StrongProbability.verifierMean_range
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StrongProbability.verifierMean_add
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StrongProbability.verifierMean_mul_const
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StrongProbability.verifierMean_sum
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StrongProbability.clockMean_fintype
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StrongProbability.clockMean_mul_const
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StrongProbability.clockMean_summable_of_bounded
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StrongProbability.clockMean_le_mul_add_const

#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.BindingOutput.crossDifference
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.BindingOutput.crossDifference_value
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.BindingOutput.crossWork_le_coordinateWork
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.BindingOutput.crossDifference_work_le
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.BindingOutput.candidate
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.BindingOutput.candidate_work_le
#audit_axioms NightstreamFPrime.Spec.Folding.PiRLC.PaperForkExtractionWork.collect_values
#audit_axioms NightstreamFPrime.Spec.Folding.PiRLC.PaperForkExtractionWork.collect_work_le
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperCompositionAgreement.pairMean_mul_const
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperCompositionAgreement.pairMean_const
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperCompositionWork.totalClock_nonnegative
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BindingBridge.subtraction_eq
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BindingReduction.centered
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BindingReduction.centered_value
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BindingReduction.centered_work_le
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BindingReduction.integerVector
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BindingReduction.integerVector_value
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BindingReduction.integerVector_work_le
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BindingReduction.run
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BindingReduction.run_work_le
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BindingReduction.runPair
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BindingReduction.runPair_work_eq
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BindingReduction.runPair_work_le
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BindingReduction.bindingEvent_implies_success
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BindingProbability.coordinateSuccess_range
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BindingProbability.success_implies_coordinate_bound
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BindingProbability.observationSuccess_eq_runPair
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BindingProbability.observationSuccess_range
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BindingProbability.localSuccessProbability_range
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BindingProbability.local_binding_le_success
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BindingProbability.supported_binding_le_success
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.SequentialObservationLaw.supported
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.SequentialObservationLaw.value_hasSum
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.SequentialObservationLaw.pairMean_eq
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.SequentialObservationLaw.outputMean_eq
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.SequentialObservationLaw.retryDisagreement_eq
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBinding.check
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBinding.check_some_eq
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBinding.check_correct
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBinding.checked_suffix_work_eq
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBinding.callClock_eq
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingRun.run
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingRun.retryWork_nil
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingRun.retryWork_cons
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingRun.run_work_eq
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingRun.run_rejected
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingRun.run_firstHit
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingRun.run_exhausted
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingRun.run_work_le
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingRun.coordinateSuccess_firstHit
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingRun.selected_binding_le_success
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingLaw.run_value_erase
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingLaw.run_value_eq_selected
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingLaw.pairLaw_eq
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingLaw.pairLaw_event
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingLaw.pairLaw_zero
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingLaw.pairLaw_event_tendsto
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingLaw.runLaw
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingLaw.runLaw_eq
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingLaw.runLaw_zero
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingLaw.runLaw_event_tendsto
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingLaw.successProbability
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingLaw.successProbability_tendsto
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingProbability.finiteSuccessProbability_range
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingProbability.checkedMean_eq_rate
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingProbability.rate_eq
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingProbability.onePairSuccess_eq
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingProbability.localSuccessProbability_range
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingProbability.successProbability_tendsto
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingProbability.local_retryDisagreement_le_success
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingProbability.retryDisagreement_le_success
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingWork.callThenClock_mean
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingWork.driverMean_le
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingWork.driverMean_uniform_bound
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingWork.expectedWork_range
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingWork.driverMean_tendsto
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingWork.entered_exhaustion_tendsto
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingWork.retryMean_zero_eq_runWork
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingWork.retryMean_succ_eq_runWork
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingWork.driverMean_eq_runWork
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingWork.expected_work_bound
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingWork.prepared_expected_work_bound
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingWork.prepared_expected_work_polynomial_bound
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.SupportedExtraction.returned_source_bound_with_adaptive_msis
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.FiatShamirTransfer.returned_source_bound_with_adaptive_msis
#audit_axioms NightstreamFPrime.Export.Stage1.NifsClosure.source_probability_linear_bound
#audit_axioms NightstreamFPrime.Export.Stage1.NifsProviderLaw.source_probability_linear_bound
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BindingProbability.binding_le_success
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BindingWork.postClock_range
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BindingWork.suffixLaw_eq_workLaw
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BindingWork.postMean_range
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BindingWork.expected_work_bound
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BindingWork.expected_work_polynomial_bound
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.SupportedExtraction.returned_source_bound_with_msis
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.SupportedExtraction.msis_probability_and_expected_work

#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakOracle.pushMass
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperWeakOracle.pushMass_value_hasSum
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.ContextPreparation.run
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.ContextPreparation.run_value
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.ContextPreparation.run_work
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.ContextPreparation.contexts_toReal
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.ContextPreparation.value_hasSum
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.ContextPreparation.summable_iff
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.ContextPreparation.clock_eq_run_work
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.ContextPreparation.expected_work_eq
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BindingProbability.prepared_successProbability_eq
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BindingWork.totalClock_nonnegative
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.BindingWork.prepared_expected_work_polynomial_bound

#audit_axioms NightstreamFPrime.Export.Stage1.PiCCSStoredPublicCheck.check_value
#audit_axioms NightstreamFPrime.Export.Stage1.PiCCSStoredPublicCheck.check_work_le
#audit_axioms NightstreamFPrime.Export.Stage1.PiCCSStoredWitnessCheck.publicCheck_value
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.StoredRingInverseWork.trim_value
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.StoredRingInverseWork.trim_work_le
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.StoredRingInverseWork.encode_value
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.StoredRingInverseWork.encode_work_le
#audit_axioms NightstreamFPrime.Spec.AjtaiSetupV1.Work.elementLanes_value
#audit_axioms NightstreamFPrime.Spec.AjtaiSetupV1.Work.elementLanes_work_le
#audit_axioms NightstreamFPrime.Spec.AjtaiSetupV1.Work.laneCoefficient_value
#audit_axioms NightstreamFPrime.Spec.AjtaiSetupV1.Work.laneCoefficient_work_le
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.RingFPolynomial.degree_modulus
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.RingFPolynomial.image_injective
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.RingFPolynomial.image_one
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.RingFPolynomial.root_pow_mod
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.RingFPolynomial.image_mul
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.RingFFrobenius.quotient_pow_card_pow
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.RingFFrobenius.unit_inverse_product
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.StoredRingArithmetic.multiply_value
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.StoredRingArithmetic.multiply_work_le
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.StoredRingArithmetic.one_value
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.StoredRingArithmetic.one_work_le
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.StoredRingArithmetic.add_value
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.StoredRingArithmetic.add_work_le

#audit_axioms NightstreamFPrime.Spec.Phi81Relation.PiRLCAlgebra.StoredCommitment.row_value
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.PiRLCAlgebra.StoredCommitment.row_work_le

#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.StoredRingPowerInverse.inverse_mul_value
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.StoredRingPowerInverse.inverse_eq_unitInverse
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.EvaluationHomomorphism.StoredRingPowerInverse.inverse_work_le


#audit_axioms NightstreamFPrime.Layout.MatrixProgram.SparseWork.empty_value
#audit_axioms NightstreamFPrime.Layout.MatrixProgram.SparseWork.empty_work
#audit_axioms NightstreamFPrime.Layout.MatrixProgram.SparseWork.singleton_value
#audit_axioms NightstreamFPrime.Layout.MatrixProgram.SparseWork.singleton_work
#audit_axioms NightstreamFPrime.Layout.MatrixProgram.SparseWork.add_value
#audit_axioms NightstreamFPrime.Layout.MatrixProgram.SparseWork.add_work
#audit_axioms NightstreamFPrime.Layout.MatrixProgram.SparseWork.scale_value
#audit_axioms NightstreamFPrime.Layout.MatrixProgram.SparseWork.scale_work
#audit_axioms NightstreamFPrime.Layout.MatrixProgram.SparseWork.coefficient_value
#audit_axioms NightstreamFPrime.Layout.MatrixProgram.SparseWork.coefficient_work_le

#audit_axioms NightstreamFPrime.Layout.MatrixProgram.CoefficientWork.coefficient_value
#audit_axioms NightstreamFPrime.Layout.MatrixProgram.CoefficientWork.coefficient_work_le

#audit_axioms NightstreamFPrime.Layout.MatrixProgram.RetainedWork.form?_value
#audit_axioms NightstreamFPrime.Layout.MatrixProgram.RetainedWork.form?_length
#audit_axioms NightstreamFPrime.Layout.MatrixProgram.RetainedWork.form?_work_le

#audit_axioms NightstreamFPrime.Export.Stage1.PiDECOrdinarySourceWork.commitmentRow_value
#audit_axioms NightstreamFPrime.Export.Stage1.PiDECOrdinarySourceWork.commitmentRow_lengths
#audit_axioms NightstreamFPrime.Export.Stage1.PiDECOrdinarySourceWork.commitmentRow_work_le



#audit_axioms NightstreamFPrime.Export.Stage1.PiDECOrdinarySourceWork.commitmentRow_data

#audit_axioms NightstreamFPrime.Export.Stage1.PiDECCommitmentMatrixWork.commitmentForms_value
#audit_axioms NightstreamFPrime.Export.Stage1.PiDECCommitmentMatrixWork.commitmentForms_lengths
#audit_axioms NightstreamFPrime.Export.Stage1.PiDECCommitmentMatrixWork.commitmentForms_work_le



#audit_axioms NightstreamFPrime.Export.Stage1.PiDECCommitmentMatrixEntry.globalRow_val
#audit_axioms NightstreamFPrime.Export.Stage1.PiDECCommitmentMatrixEntry.entry_value
#audit_axioms NightstreamFPrime.Export.Stage1.PiDECCommitmentMatrixEntry.entry_work_le

#audit_axioms NightstreamFPrime.Export.Stage1.NifsBinding.bindingEvent_to_shortKernel

#audit_axioms NightstreamFPrime.Export.Stage1.PiCCSStoredWitnessCheck.finishValue_source_iff


#audit_axioms NightstreamFPrime.Export.Stage1.PiCCSStoredSourceProbability.storeOutcome_view
#audit_axioms NightstreamFPrime.Export.Stage1.PiCCSStoredSourceProbability.sourceProgram_correct
#audit_axioms NightstreamFPrime.Export.Stage1.PiCCSStoredSourceProbability.finish_value
#audit_axioms NightstreamFPrime.Export.Stage1.PiCCSStoredSourceProbability.returnedSourceProbability_eq_finishValue
#audit_axioms NightstreamFPrime.Export.Stage1.PiCCSStoredSourceProbability.returnedSourceProbability_eq_sourceProbability

#audit_axioms NightstreamFPrime.Lifecycle.Nifs.FiatShamirTransfer.realSuccess_implies_exact_children
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.FiatShamirTransfer.returned_source_bound_with_binding
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.FiatShamirTransfer.returned_source_bound_with_msis
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.FiatShamirTransfer.returned_source_bound_of_msis
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.FiatShamirTransfer.prepared_probability_and_expected_work

#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCExtractionPrimitives.program_correct

#audit_axioms NightstreamFPrime.Lifecycle.Nifs.VerifierErrorBudget.test_error_eq

#audit_axioms NightstreamFPrime.Export.Stage1.NifsFiatShamir.finishValue_probability_and_expected_work
#audit_axioms NightstreamFPrime.Export.Stage1.NifsInvalidSource.source_event_probability_eq_zero
#audit_axioms NightstreamFPrime.Export.Stage1.NifsInvalidSource.real_success_bound_of_invalid_source
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheck.allFin_eq_true
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheck.matrixRow_eq
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.PaperJoint.StoredWitnessCheck.evaluateRows_eq

#audit_axioms NightstreamFPrime.Lifecycle.Nifs.ClaimCheck.evaluation_eq
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.ClaimCheck.check_eq_true_iff
#audit_axioms NightstreamFPrime.Export.Stage1.NifsExtractionProvider.recompose_value
#audit_axioms NightstreamFPrime.Export.Stage1.NifsExtractionProvider.recompose_work_le
#audit_axioms NightstreamFPrime.Export.Stage1.NifsExtractionProvider.suffixProgram_correct
#audit_axioms NightstreamFPrime.Export.Stage1.NifsExtractionProvider.parentChecker_spec
#audit_axioms NightstreamFPrime.Export.Stage1.NifsExtractionProvider.batchAt_eq
#audit_axioms NightstreamFPrime.Export.Stage1.NifsExtractionProvider.continuationAt
#audit_axioms NightstreamFPrime.Export.Stage1.NifsClosure.finishValue_probability_and_expected_work
#audit_axioms NightstreamFPrime.Export.Stage1.NifsProviderLaw.source_law_eq_supported_extension

#audit_axioms NightstreamFPrime.Lifecycle.Nifs.FiatShamirTransfer.FiatShamirModel.of_blockOracle
#audit_axioms NightstreamFPrime.Lifecycle.Nifs.FiatShamirTransfer.samplerTransferError_sum
#audit_axioms NightstreamFPrime.Export.Stage1.NifsClosure.source_probability_linear_bound_with_sampler
