import Lean
import NightstreamFPrime.Export.Stage1.Package
import NightstreamFPrime.Export.Stage1.PackageCompleteness
import NightstreamFPrime.Export.Stage1.PackagePlan
import NightstreamFPrime.Export.Stage1.PiRLCCombinationConformance
import NightstreamFPrime.Export.Stage1.PiRLCFirst54Conformance

/-! Axiom audits for the compact PiRLC Stage 1 export bridge. -/

open Lean Elab Command in
elab "#audit_axioms " decl:ident : command => do
  let name ← liftCoreM <| realizeGlobalConstNoOverloadWithInfo decl
  let axioms ← liftCoreM <| Lean.collectAxioms name
  let allowed : List Name := [``propext, ``Classical.choice, ``Quot.sound]
  let bad := axioms.toList.filter (fun a => !allowed.contains a)
  if bad.isEmpty then
    logInfo m!"{name}: {axioms.toList}"
  else
    throwError m!"{name} depends on disallowed axioms: {bad}"

#audit_axioms NightstreamFPrime.Lifecycle.PiRLC.v1_1.CombinationStep.recipe_eval
#audit_axioms NightstreamFPrime.Lifecycle.PiRLC.v1_1.TranscriptAbsorption.ownedSpec_iff_specHolds
#audit_axioms NightstreamFPrime.Lifecycle.PiRLC.v1_1.DigestWindow.laneAssumptions
#audit_axioms NightstreamFPrime.Lifecycle.PiRLC.v1_1.Sampler.windowAssumptions
#audit_axioms NightstreamFPrime.Lifecycle.PiRLC.v1_1.Sampler.selectorAssumptions
#audit_axioms NightstreamFPrime.Lifecycle.PiRLC.v1_1.SamplerChain.childAssumptions
#audit_axioms NightstreamFPrime.Layout.PiRLC.v1_1.SamplerChain.childInputs
#audit_axioms NightstreamFPrime.Layout.PiRLC.v1_1.Sampler.windowInputs
#audit_axioms NightstreamFPrime.Layout.PiRLC.v1_1.Leaves.TranscriptAbsorption.actions_affine
#audit_axioms NightstreamFPrime.Export.Package.compactRowCountFor_append
#audit_axioms NightstreamFPrime.Export.Stage1.CompactRows.compactConstraintTemplate
#audit_axioms NightstreamFPrime.Export.Stage1.CompactRows.compactConstraintTemplate_rows_length
#audit_axioms NightstreamFPrime.Export.Stage1.CompactRows.compactConstraintTemplate_rows_imply_eval_zero
#audit_axioms NightstreamFPrime.Export.Stage1.CompactRows.compactConstraintTemplate_complete
#audit_axioms NightstreamFPrime.Export.Stage1.CompactRows.compactTemplate_complete
#audit_axioms NightstreamFPrime.Export.Stage1.WitnessProgram.piRlcDigestLaneBatches_eq_fromCircuit
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCSamplerOrdinaryRows.laneInputs
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCSamplerOrdinaryRows.laneConstraints_eq_fromCircuit
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCSamplerOrdinaryRows.laneRows_length
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCSamplerOrdinaryRows.windowRows_length
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCSamplerOrdinaryRows.selectorFinalRows_length
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCSamplerOrdinaryRows.sourceRows_length
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCSamplerOrdinaryRows.rows_length
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCSamplerOrdinaryRows.laneRows_subset_rows
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCSamplerOrdinaryRows.rows_imply_laneSpec
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCSamplerOrdinaryRows.selectorFinalRows_subset_rows
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCSamplerOrdinaryRows.rows_imply_selectorFull
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCSamplerInvocations.entryState_affine
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCSamplerInvocations.entryTrace_state_matches
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCSamplerInvocations.entryTrace_implies_spec
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCSamplerInvocations.windowState_affine
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCSamplerInvocations.windowInvocation_implies_spec
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Conformance.decoderLogicalStart_eq
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Conformance.rejectSourceColumn_eq
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Conformance.remainderSourceColumn_eq
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Templates.firstPositionTemplate_rows_length
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Templates.laterPositionTemplate_rows_length
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Templates.firstValueTemplate_rows_length
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Templates.laterValueTemplate_rows_length
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Templates.firstPositionTemplate_getElem?
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Templates.laterPositionTemplate_getElem?
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Templates.firstValueTemplate_getElem?
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Templates.laterValueTemplate_getElem?
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Templates.firstPositionTemplates_rowCount
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Templates.laterPositionTemplates_rowCount
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Templates.firstValueTemplates_rowCount
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Templates.laterValueTemplates_rowCount
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Invocations.positionInvocation_zero_rowCount
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Invocations.positionInvocation_succ_rowCount
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Invocations.valueInvocation_zero_rowCount
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Invocations.valueInvocation_succ_rowCount
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Invocations.positionInvocations_zero_rowCount
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Invocations.positionInvocations_succ_rowCount
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Invocations.valueInvocations_zero_rowCount
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Invocations.valueInvocations_succ_rowCount
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Invocations.roundInvocations_rowCount
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Invocations.sourceInvocations_rowCount
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Invocations.compactRowCount
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Invocations.positionInvocation_mem
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Invocations.valueInvocation_mem
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Invocations.positionInvocation_zero_template
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Invocations.positionInvocation_succ_template
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Invocations.valueInvocation_zero_template
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Invocations.valueInvocation_succ_template
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Conformance.firstPositionConstraint_eval_eq
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Conformance.laterPositionConstraint_eval_eq
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Conformance.firstValueConstraint_eval_eq
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Conformance.laterValueConstraint_eval_eq
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Conformance.positionInvocation_zero_implies_constraint
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Conformance.positionInvocation_succ_implies_constraint
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Conformance.valueInvocation_zero_implies_constraint
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Conformance.valueInvocation_succ_implies_constraint
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCFirst54Conformance.packageInvocations_imply_spec
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCCombinationConformance.invocationRows_imply_sourceConstraint
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCCombinationConformance.sourceRows_imply_invocationRows
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCCombinationConformance.commitmentInvocationRows_imply_sourceConstraint
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCCombinationConformance.publicInputInvocationRows_imply_sourceConstraint
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCCombinationConformance.evalKInvocationRows_imply_sourceConstraint
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCCombinationConformance.evalAInvocationRows_imply_sourceConstraint
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCCombinationConformance.familyConstraintZeros_imply_prefix
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCCombinationConformance.commitmentFamilyRows_imply_canonical
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCCombinationConformance.publicInputFamilyRows_imply_canonical
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCCombinationConformance.evalKFamilyRows_imply_canonical
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCCombinationConformance.evalAFamilyRows_imply_canonical
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCCombinationInvocations.familyInvocation_mem
#audit_axioms NightstreamFPrime.Export.Stage1.Package.circuitPackage_implies_piRlcSamplerOrdinaryRows
#audit_axioms NightstreamFPrime.Export.Stage1.Package.circuitPackage_implies_piRlcDigestLane
#audit_axioms NightstreamFPrime.Export.Stage1.Package.circuitPackage_implies_piRlcSamplerInvocations
#audit_axioms NightstreamFPrime.Export.Stage1.Package.circuitPackage_implies_piRlcEntry
#audit_axioms NightstreamFPrime.Export.Stage1.Package.circuitPackage_implies_piRlcWindowPermutation
#audit_axioms NightstreamFPrime.Export.Stage1.Package.circuitPackage_implies_piRlcDigestWindow
#audit_axioms NightstreamFPrime.Export.Stage1.Package.circuitPackage_implies_piRlcSamplerPrefix
#audit_axioms NightstreamFPrime.Export.Stage1.Package.circuitPackage_implies_piRlcFirst54Spec
#audit_axioms NightstreamFPrime.Export.Stage1.Package.circuitPackage_implies_piRlcSamplerSpec
#audit_axioms NightstreamFPrime.Export.Stage1.Package.circuitPackage_implies_piRlcSamplerChain
#audit_axioms NightstreamFPrime.Export.Stage1.Package.circuitPackage_implies_piRlcSpecHolds
#audit_axioms NightstreamFPrime.Export.Stage1.Package.circuitPackage_implies_piRlcPhaseHolds
#audit_axioms NightstreamFPrime.Export.Stage1.Package.circuitPackage_implies_piRlcCombinationRows
#audit_axioms NightstreamFPrime.Export.Stage1.Package.circuitPackage_implies_piRlcSpecHolds_of_combinationTemplates
#audit_axioms NightstreamFPrime.Export.Stage1.Package.circuitPackage_implies_piRlcPhaseHolds_of_combinationTemplates
#audit_axioms NightstreamFPrime.Export.Stage1.Package.arithmetic_partition
#audit_axioms NightstreamFPrime.Export.Stage1.Package.circuitPackage_ordinary_rows
#audit_axioms NightstreamFPrime.Export.Stage1.Package.arithmeticRows_imply_packageOrdinary
#audit_axioms NightstreamFPrime.Export.Stage1.Package.phaseArithmeticRows_imply_packageOrdinary
#audit_axioms NightstreamFPrime.Export.Stage1.PackageCompleteness.rowsHold_of_packets
#audit_axioms NightstreamFPrime.Export.Stage1.Package.circuitPackage_compactRowCount
#audit_axioms NightstreamFPrime.Export.Stage1.Package.circuitPackage_row_coverage
#audit_axioms NightstreamFPrime.Export.Stage1.PackagePlan.canonicalFirst54Block_expand
#audit_axioms NightstreamFPrime.Export.Stage1.PackagePlan.canonicalCombinationBlock_expand
#audit_axioms NightstreamFPrime.Export.Stage1.PackagePlan.canonicalCompactBlocks_expand
#audit_axioms NightstreamFPrime.Export.Stage1.PackagePlan.staticPackage_eq
#audit_axioms NightstreamFPrime.Export.Stage1.PackagePlan.canonical_expand
#audit_axioms NightstreamFPrime.Export.Stage1.PackagePlan.canonical_decode_encode
#audit_axioms NightstreamFPrime.Export.Stage1.PermutationPlan.stateOfList_ofFn
#audit_axioms NightstreamFPrime.Export.Stage1.PermutationPlan.ActionShape.toAction_shape
#audit_axioms NightstreamFPrime.Export.Stage1.PermutationPlan.ActionBlock.ofActions_expand
#audit_axioms NightstreamFPrime.Export.Stage1.PermutationPlan.DirectBlock.ofState_expand
#audit_axioms NightstreamFPrime.Export.Stage1.PermutationPlan.statementBlock_expand
#audit_axioms NightstreamFPrime.Export.Stage1.PermutationPlan.challengeBlock_expand
#audit_axioms NightstreamFPrime.Export.Stage1.PermutationPlan.roundBlock_expand
#audit_axioms NightstreamFPrime.Export.Stage1.PermutationPlan.outputBlock_expand
#audit_axioms NightstreamFPrime.Export.Stage1.PermutationPlan.piCcsBlocks_expand
#audit_axioms NightstreamFPrime.Export.Stage1.PermutationPlan.samplerEntryBlock_expand
#audit_axioms NightstreamFPrime.Export.Stage1.PermutationPlan.samplerWindowBlock_expand
#audit_axioms NightstreamFPrime.Export.Stage1.PermutationPlan.samplerSourceBlocks_expand
#audit_axioms NightstreamFPrime.Export.Stage1.PermutationPlan.piRlcSamplerBlocks_expand
#audit_axioms NightstreamFPrime.Export.Stage1.PermutationPlan.canonicalBlocks_expand
