import tests.AxiomAudit
import NightstreamFPrime.Spec.Nebula

/-! Axiom audits for the Nebula memory-phase model (`Spec/Nebula`). -/

#audit_axioms NightstreamFPrime.Spec.Nebula.Plan.romSize_le_ramSize
#audit_axioms NightstreamFPrime.Spec.Nebula.pack_lt
#audit_axioms NightstreamFPrime.Spec.Nebula.pack_injective
#audit_axioms NightstreamFPrime.Spec.Nebula.pack_cast_injective
#audit_axioms NightstreamFPrime.Spec.Nebula.OpSlot.bits_length
#audit_axioms NightstreamFPrime.Spec.Nebula.ScanSlot.bits_length
#audit_axioms NightstreamFPrime.Spec.Nebula.opsLane_injective
#audit_axioms NightstreamFPrime.Spec.Nebula.scanLane_injective
#audit_axioms NightstreamFPrime.Spec.Nebula.CollisionIn.mono
#audit_axioms NightstreamFPrime.Spec.Nebula.chainRoot_nil
#audit_axioms NightstreamFPrime.Spec.Nebula.chainRoot_append
#audit_axioms NightstreamFPrime.Spec.Nebula.chainRoot_eq_or_collision
#audit_axioms NightstreamFPrime.Spec.Nebula.collision_of_frame
#audit_axioms NightstreamFPrime.Spec.Nebula.product_add
#audit_axioms NightstreamFPrime.Spec.Nebula.productEq_iff
#audit_axioms NightstreamFPrime.Spec.Nebula.productEq_of_balanced
#audit_axioms NightstreamFPrime.Spec.Nebula.badChallenges_card
#audit_axioms NightstreamFPrime.Spec.Nebula.badChallenges_frequency
#audit_axioms NightstreamFPrime.Spec.Nebula.GoldilocksFingerprint.card_K
#audit_axioms NightstreamFPrime.Spec.Nebula.GoldilocksFingerprint.goldilocks_badChallenges_frequency
#audit_axioms NightstreamFPrime.Spec.Nebula.bitRow_iff
#audit_axioms NightstreamFPrime.Spec.Nebula.gateRow_eq
#audit_axioms NightstreamFPrime.Spec.Nebula.o4Row_iff
#audit_axioms NightstreamFPrime.Spec.Nebula.o4Row_fresh
#audit_axioms NightstreamFPrime.Spec.Nebula.stepProducts_eq
#audit_axioms NightstreamFPrime.Spec.Nebula.activeOps_length
#audit_axioms NightstreamFPrime.Spec.Nebula.stepMultisets_small
#audit_axioms NightstreamFPrime.Spec.Nebula.accessAll_nil
#audit_axioms NightstreamFPrime.Spec.Nebula.accessAll_append
#audit_axioms NightstreamFPrime.Spec.Nebula.PortAccess.Valid.globalIndex_lt
#audit_axioms NightstreamFPrime.Spec.Nebula.accessAll_congr
#audit_axioms NightstreamFPrime.Spec.Nebula.memoryRoot_congr
#audit_axioms NightstreamFPrime.Spec.Nebula.executes_padIdle
#audit_axioms NightstreamFPrime.Spec.Nebula.snapshot_update
#audit_axioms NightstreamFPrime.Spec.Nebula.eqOn_of_snapshot_eq
#audit_axioms NightstreamFPrime.Spec.Nebula.segment_sequential
#audit_axioms NightstreamFPrime.Spec.Nebula.honest_balanced
#audit_axioms NightstreamFPrime.Spec.Nebula.finalCarry_isSome_iff
#audit_axioms NightstreamFPrime.Spec.Nebula.finalCarry_fields
#audit_axioms NightstreamFPrime.Spec.Nebula.segmentMultisets_read
#audit_axioms NightstreamFPrime.Spec.Nebula.segmentMultisets_write
#audit_axioms NightstreamFPrime.Spec.Nebula.segmentMultisets_initial
#audit_axioms NightstreamFPrime.Spec.Nebula.segmentMultisets_final
#audit_axioms NightstreamFPrime.Spec.Nebula.segmentOps_wt
#audit_axioms NightstreamFPrime.Spec.Nebula.segmentOps_length
#audit_axioms NightstreamFPrime.Spec.Nebula.segmentOps_access
#audit_axioms NightstreamFPrime.Spec.Nebula.chunkTuples_scansOf
#audit_axioms NightstreamFPrime.Spec.Nebula.initialMemory_fits
#audit_axioms NightstreamFPrime.Spec.Nebula.scansOf_shaped
#audit_axioms NightstreamFPrime.Spec.Nebula.memoryLanes_eq
#audit_axioms NightstreamFPrime.Spec.Nebula.scanMemory_scansOf
#audit_axioms NightstreamFPrime.Spec.Nebula.scansOf_scanMemory
#audit_axioms NightstreamFPrime.Spec.Nebula.scans_eq_or_collision
#audit_axioms NightstreamFPrime.Spec.Nebula.ops_eq_or_collision
#audit_axioms NightstreamFPrime.Spec.Nebula.SegmentView.ClosesAt.opsShaped
#audit_axioms NightstreamFPrime.Spec.Nebula.SegmentView.ClosesAt.initialShaped
#audit_axioms NightstreamFPrime.Spec.Nebula.SegmentView.ClosesAt.finalShaped
#audit_axioms NightstreamFPrime.Spec.Nebula.initial_scans_or_collision
#audit_axioms NightstreamFPrime.Spec.Nebula.join_scans_or_collision
#audit_axioms NightstreamFPrime.Spec.Nebula.records_eq_or_collision
#audit_axioms NightstreamFPrime.Spec.Nebula.segment_replays
#audit_axioms NightstreamFPrime.Spec.Nebula.executes_of_replay
#audit_axioms NightstreamFPrime.Spec.Nebula.soundness
#audit_axioms NightstreamFPrime.Spec.Nebula.completeness
#audit_axioms NightstreamFPrime.Spec.Nebula.errors_subset_successes
#audit_axioms NightstreamFPrime.Spec.Nebula.retry_count
#audit_axioms NightstreamFPrime.Spec.Nebula.retry_frequency
#audit_axioms NightstreamFPrime.Spec.Nebula.segment_multisets_card
#audit_axioms NightstreamFPrime.Spec.Nebula.segment_multisets_small
#audit_axioms NightstreamFPrime.Spec.Nebula.segment_fingerprint_bound
