import NightstreamFPrime.Layout.SumCheck.CompactChain
import NightstreamFPrime.Layout.PiCCS.v1_1.GammaPowers
import NightstreamFPrime.Lifecycle.Stage1.Poseidon2HashChainV1Prefix
import NightstreamFPrime.Lifecycle.PiCCS.v1_1.Support.GammaPowers
import NightstreamFPrime.Lifecycle.PiCCS.v1_1.WitnessSupport
import NightstreamFPrime.Layout.Stage1.Poseidon2HashChainCompactWitness
import NightstreamFPrime.Export.Stage1.ApplicationPoseidonSoundness
import tests.AxiomAudit

/-! Kernel and cost gates for the compact PiCCS lowering batch. -/

namespace NightstreamFPrime.Tests.CompactPiCCSLowering

theorem sumcheck_local_coordinates : (504 + 1764) * 41 = 92988 := by decide

theorem sumcheck_local_savings :
    424657 - 2324 = 422333 ∧ 424601 * 41 - 92988 = 17315653 := by decide

end NightstreamFPrime.Tests.CompactPiCCSLowering

#audit_axioms NightstreamFPrime.Gadgets.SumCheck.CompactChain.evaluate_zero
#audit_axioms NightstreamFPrime.Gadgets.SumCheck.CompactChain.evaluate_one
#audit_axioms NightstreamFPrime.Gadgets.SumCheck.CompactChain.booleanSum_eval
#audit_axioms NightstreamFPrime.Gadgets.SumCheck.CompactChain.coefficientSum_varsBelow
#audit_axioms NightstreamFPrime.Gadgets.SumCheck.CompactChain.booleanSum_varsBelow
#audit_axioms NightstreamFPrime.Gadgets.SumCheck.CompactChain.compile_recipes_length
#audit_axioms NightstreamFPrime.Gadgets.SumCheck.CompactChain.compile_checks_length
#audit_axioms NightstreamFPrime.Gadgets.SumCheck.CompactChain.compile_scope
#audit_axioms NightstreamFPrime.Gadgets.SumCheck.CompactChain.compile_chain_iff
#audit_axioms NightstreamFPrime.Gadgets.SumCheck.CompactChain.flatConstraints_opsAt
#audit_axioms NightstreamFPrime.Gadgets.SumCheck.CompactChain.soundness
#audit_axioms NightstreamFPrime.Gadgets.SumCheck.CompactChain.build
#audit_axioms NightstreamFPrime.Gadgets.SumCheck.CompactChain.localLength_eq
#audit_axioms NightstreamFPrime.Layout.SumCheck.CompactChain.compile_output_linear
#audit_axioms NightstreamFPrime.Layout.SumCheck.CompactChain.compile_costs
#audit_axioms NightstreamFPrime.Layout.SumCheck.CompactChain.production_costs
#audit_axioms NightstreamFPrime.Tests.CompactPiCCSLowering.sumcheck_local_coordinates
#audit_axioms NightstreamFPrime.Tests.CompactPiCCSLowering.sumcheck_local_savings
#audit_axioms NightstreamFPrime.Lifecycle.PiCCS.v1_1.GammaPowers.schedule_valid
#audit_axioms NightstreamFPrime.Lifecycle.PiCCS.v1_1.GammaPowers.recipes_length
#audit_axioms NightstreamFPrime.Lifecycle.PiCCS.v1_1.GammaPowers.wire_varsBelow
#audit_axioms NightstreamFPrime.Lifecycle.PiCCS.v1_1.GammaPowers.recipe_varsBelow
#audit_axioms NightstreamFPrime.Lifecycle.PiCCS.v1_1.GammaPowers.recipes_causal
#audit_axioms NightstreamFPrime.Lifecycle.PiCCS.v1_1.GammaPowers.product_sound
#audit_axioms NightstreamFPrime.Lifecycle.PiCCS.v1_1.GammaPowers.wire_sound
#audit_axioms NightstreamFPrime.Lifecycle.PiCCS.v1_1.GammaPowers.soundness
#audit_axioms NightstreamFPrime.Lifecycle.PiCCS.v1_1.GammaPowers.build
#audit_axioms NightstreamFPrime.Layout.PiCCS.v1_1.GammaPowers.transcript_wire_costs
#audit_axioms NightstreamFPrime.Layout.PiCCS.v1_1.GammaPowers.local_coordinate_count
#audit_axioms NightstreamFPrime.Layout.PiCCS.v1_1.GammaPowers.local_savings
#audit_axioms NightstreamFPrime.Lifecycle.Stage1.Poseidon2HashChainV1Prefix.absorbBlocksFast_append
#audit_axioms NightstreamFPrime.Lifecycle.Stage1.Poseidon2HashChainV1Prefix.suffixHash_eq_step

#audit_axioms NightstreamFPrime.Gadgets.SumCheck.CompactChain.compile_cons
#audit_axioms NightstreamFPrime.Lifecycle.PiCCS.v1_1.SumcheckChain.circuit_ops
#audit_axioms NightstreamFPrime.Lifecycle.PiCCS.v1_1.SumcheckChain.semanticOutput_varsBelow
#audit_axioms NightstreamFPrime.Lifecycle.PiCCS.v1_1.FinalIdentity.pointLength_eq
#audit_axioms NightstreamFPrime.Layout.PiCCS.v1_1.GammaPowers.input_costs
#audit_axioms NightstreamFPrime.Lifecycle.PiCCS.v1_1.GammaPowers.localLength_eq
#audit_axioms NightstreamFPrime.Lifecycle.PiCCS.v1_1.GammaPowers.flatConstraints_eq
#audit_axioms NightstreamFPrime.Lifecycle.PiCCS.v1_1.GammaPowers.flatConstraints_length
#audit_axioms NightstreamFPrime.Lifecycle.PiCCS.v1_1.GammaPowers.flatConstraints_varsBelow
#audit_axioms NightstreamFPrime.Lifecycle.PiCCS.v1_1.GammaPowers.wire_varsSatisfy
#audit_axioms NightstreamFPrime.Lifecycle.PiCCS.v1_1.GammaPowers.flatConstraints_varsSatisfy
#audit_axioms NightstreamFPrime.Lifecycle.PiCCS.v1_1.GammaPowers.witnessesFromConstraints

#audit_axioms NightstreamFPrime.Lifecycle.Stage1.Poseidon2HashChainV1Prefix.threePermutations_eq_step
#audit_axioms NightstreamFPrime.Layout.Stage1.Poseidon2HashChainCompact.plan_rowCount
#audit_axioms NightstreamFPrime.Layout.Stage1.Poseidon2HashChainCompact.private_coordinate_count
#audit_axioms NightstreamFPrime.Layout.Stage1.Poseidon2HashChainCompact.soundness

#audit_axioms NightstreamFPrime.Layout.Stage1.Poseidon2HashChainCompact.output_eq_step
#audit_axioms NightstreamFPrime.Layout.Stage1.Poseidon2HashChainCompactWitness.complete_of_encoding
#audit_axioms NightstreamFPrime.Layout.ProductionRelation.PoseidonCompactWitness.source_input
#audit_axioms NightstreamFPrime.Layout.ProductionRelation.PoseidonCompactWitness.source_rows
#audit_axioms NightstreamFPrime.Layout.ProductionRelation.PoseidonCompactWitness.output_eq_permute
#audit_axioms NightstreamFPrime.Layout.ProductionRelation.PoseidonCompactWitness.equations
#audit_axioms NightstreamFPrime.Layout.ProductionRelation.PoseidonCompactWitness.family_member

#audit_axioms NightstreamFPrime.Lifecycle.Stage1.Application.HashChainCircuit.localLength
#audit_axioms NightstreamFPrime.Lifecycle.Stage1.Application.Program.hashChain_spec_iff
#audit_axioms NightstreamFPrime.Lifecycle.Stage1.Application.Program.hashChain_relation_iff
#audit_axioms NightstreamFPrime.Export.Stage1.ApplicationPoseidonRetainedBlock.sourceWidth_bound
#audit_axioms NightstreamFPrime.Export.Stage1.ApplicationPoseidonRetainedBlock.witnessStart_bound
#audit_axioms NightstreamFPrime.Export.Stage1.ApplicationPoseidonRetainedBlock.block_slotCount
#audit_axioms NightstreamFPrime.Export.Stage1.ApplicationPoseidonRetainedBlock.block_coordinateCount
#audit_axioms NightstreamFPrime.Export.Stage1.ApplicationPoseidonRetainedGeometry.completeLogicalWidth_eq
#audit_axioms NightstreamFPrime.Export.Stage1.ApplicationPoseidonRetainedGeometry.plan_rowCount
#audit_axioms NightstreamFPrime.Export.Stage1.ApplicationPoseidonSoundness.input_form_eq_pilot
#audit_axioms NightstreamFPrime.Export.Stage1.ApplicationPoseidonSoundness.output_form_eq_pilot
#audit_axioms NightstreamFPrime.Export.Stage1.ApplicationPoseidonSoundness.rowsZero_implies_step
#audit_axioms NightstreamFPrime.Export.Stage1.ApplicationPoseidonSoundness.complete_of_encoding
