import NightstreamFPrime.Export.Stage1.ApplicationMatrixProgramSemantics
import NightstreamFPrime.Export.Stage1.ApplicationAssignmentSoundness
import NightstreamFPrime.Export.Stage1.Poseidon2HashChainV1Setup
import NightstreamFPrime.Export.Stage1.ApplicationWitness
import tests.AxiomAudit

/-! Axiom gate for the shared application layout and its complete witness. -/

#audit_axioms NightstreamFPrime.Export.Stage1.ApplicationRetainedBlocks.localBlock_kind
#audit_axioms NightstreamFPrime.Export.Stage1.ApplicationRetainedBlocks.localBlock_coordinateCount
#audit_axioms NightstreamFPrime.Export.Stage1.ApplicationRetainedBlocks.source_after_localStart
#audit_axioms NightstreamFPrime.Export.Stage1.ApplicationRetainedBlocks.retainedCoordinateCount_eq
#audit_axioms NightstreamFPrime.Export.Stage1.ApplicationOrdinaryGeometry.completeLogicalWidth_eq
#audit_axioms NightstreamFPrime.Export.Stage1.ApplicationOrdinaryGeometry.completeLogicalWidth_eq_applicationCounts
#audit_axioms NightstreamFPrime.Export.Stage1.ApplicationOrdinaryGeometry.completeLogicalWidth_le_twoPow28_iff
#audit_axioms NightstreamFPrime.Export.Stage1.ApplicationOrdinaryGeometry.carrierWidth_le_twoPow28_iff
#audit_axioms NightstreamFPrime.Export.Stage1.ApplicationOrdinaryGeometry.completeLogicalWidth_le_cube
#audit_axioms NightstreamFPrime.Export.Stage1.ApplicationDirectPlan.plan_rowCount
#audit_axioms NightstreamFPrime.Export.Stage1.ApplicationDirectPlan.inputForm_eq_pilot
#audit_axioms NightstreamFPrime.Export.Stage1.ApplicationDirectPlan.outputForm_eq_pilot
#audit_axioms NightstreamFPrime.Export.Stage1.ApplicationAssignmentSoundness.rowsZero_implies_step
#audit_axioms NightstreamFPrime.Export.Stage1.ApplicationAssignmentSoundness.rowsZero_implies_encodedHolds
#audit_axioms NightstreamFPrime.Export.Stage1.ApplicationMatrixProgram.matrixProgram_rowCount
#audit_axioms NightstreamFPrime.Export.Stage1.ApplicationMatrixProgram.matrixProgram_row?
#audit_axioms NightstreamFPrime.Export.Stage1.Poseidon2HashChainV1Package.ordinaryLocalCount
#audit_axioms NightstreamFPrime.Export.Stage1.Poseidon2HashChainV1Package.selectedApplicationRowCount
#audit_axioms NightstreamFPrime.Export.Stage1.ApplicationWitness.witnessValue
#audit_axioms NightstreamFPrime.Export.Stage1.ApplicationWitness.complete

#audit_axioms NightstreamFPrime.Gadgets.Poseidon2.Formal.witness_agreesOutside
#audit_axioms NightstreamFPrime.Gadgets.Poseidon2.Formal.witness_complete
