import tests.AxiomAudit
import NightstreamFPrime.Export.Stage1.PerApplicationSecurity
import NightstreamFPrime.Layout.Stage1.PiCCSSecurity

/-! Axiom audits for deterministic Stage 1 binding and replay security. -/

#audit_axioms NightstreamFPrime.Layout.Stage1.PiCCSSecurity.contextDigest_identifies_descriptor_or_collision
#audit_axioms NightstreamFPrime.Layout.Stage1.PiCCSSecurity.descriptor_identifies_authority_or_component_collision
#audit_axioms NightstreamFPrime.Layout.Stage1.PiCCSSecurity.contextDigest_identifies_authority_or_collision
#audit_axioms NightstreamFPrime.Layout.Stage1.PiCCSSecurity.stateHash_identifies_statement_or_collision
#audit_axioms NightstreamFPrime.Layout.Stage1.PiCCSSecurity.no_valid_trailing_extension
#audit_axioms NightstreamFPrime.Layout.Stage1.PiCCSSecurity.committed_statement_challenges_identify_or_failure
#audit_axioms NightstreamFPrime.Layout.Stage1.PiCCSSecurity.committed_statement_finalState_identify_or_failure
#audit_axioms NightstreamFPrime.Layout.Stage1.PiCCSSecurity.committed_authority_statement_challenges_identify_or_failure
#audit_axioms NightstreamFPrime.Layout.Stage1.PiCCSSecurity.committed_authority_statement_finalState_identify_or_failure
#audit_axioms NightstreamFPrime.Export.Stage1.PerApplicationSecurity.packageIdentity_identifies_package_authority_or_collision
#audit_axioms NightstreamFPrime.Export.Stage1.PerApplicationSecurity.verificationKeyBinding_identifies_package_authority_or_collision
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.TranscriptReplay.replay_eq_or_challenge_collision
#audit_axioms NightstreamFPrime.Spec.Folding.PiCCS.TranscriptReplay.replay_eq_or_state_collision
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperNonInteractive.piCcsCheck_eq_true_iff_fixedWidthAccepted
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperSecurityComposition.extractedOutputWitness_ambient
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperSecurityComposition.extractedAssignments_ambient
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperSecurityComposition.twoForkExtractions_unique_or_relaxedBindingCollision
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperSecurityComposition.accepted_with_completeFork_extracts_source_or_badEvent
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperSecurityComposition.baseOutput_eq_parentForChallenges
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperSecurityComposition.accepted_with_fork_and_children_extracts_or_failure
#audit_axioms NightstreamFPrime.Spec.Folding.Nifs.PaperSecurityComposition.accepted_implies_securityOutcome
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.PiRLCAlgebra.ForkStrongSet.ring_sub_eq
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.PiRLCAlgebra.ForkStrongSet.ringLaws
#audit_axioms NightstreamFPrime.Spec.Phi81Relation.PiRLCAlgebra.ForkStrongSet.strongSetUnits
#audit_axioms NightstreamFPrime.Export.Stage1.PerApplicationSecurity.replayInput_derive_eq_piCcsExecution
#audit_axioms NightstreamFPrime.Export.Stage1.PerApplicationSecurity.PiCcsOutputAbsorptionCollision
#audit_axioms NightstreamFPrime.Export.Stage1.PerApplicationSecurity.productionStrongSet
#audit_axioms NightstreamFPrime.Export.Stage1.PerApplicationSecurity.packageReplay_identifies_claim_or_failure
#audit_axioms NightstreamFPrime.Export.Stage1.PerApplicationSecurity.packageReplayAndOutput_identifies_claim_or_failure
#audit_axioms NightstreamFPrime.Export.Stage1.PerApplicationSecurity.stepHoldsFor_implies_base_or_securityOutcome
