import NightstreamFPrime.Export.Stage1.PiRLCCombinationInvocationOrigin
import NightstreamFPrime.Export.Stage1.StoredPhysicalPlan
import NightstreamFPrime.Circuit.WitnessSupport
import NightstreamFPrime.Export.Stage1.StoredExecutionSupport
import NightstreamFPrime.Export.Stage1.PiRLCCombinationWitnessReadSupport
import NightstreamFPrime.Lifecycle.PiDEC.v1_1.SignedSplitScalar.Witness
import NightstreamFPrime.Lifecycle.PiDEC.v1_1.PublicInputSplit.Witness
import NightstreamFPrime.Gadgets.Poseidon2.Formal.Witness
import NightstreamFPrime.Export.Stage1.StoredInstructionExecution
import NightstreamFPrime.Export.Stage1.StoredPermutationExecution
import NightstreamFPrime.Export.Stage1.StoredWitnessExecution
import tests.AxiomAudit

#audit_axioms NightstreamFPrime.Export.Stage1.StoredWitnessExecution.write_size
#audit_axioms NightstreamFPrime.Export.Stage1.StoredWitnessExecution.asEnv_write
#audit_axioms NightstreamFPrime.Export.Stage1.StoredWitnessExecution.executeRecipes_size
#audit_axioms NightstreamFPrime.Export.Stage1.StoredWitnessExecution.executeHints_size
#audit_axioms NightstreamFPrime.Export.Stage1.StoredWitnessExecution.executeRecipes_eq
#audit_axioms NightstreamFPrime.Export.Stage1.StoredWitnessExecution.executeHints_eq

#audit_axioms NightstreamFPrime.Export.Stage1.StoredPermutationExecution.execute_size
#audit_axioms NightstreamFPrime.Export.Stage1.StoredPermutationExecution.execute_eq

#audit_axioms NightstreamFPrime.Export.Stage1.StoredInstructionExecution.execute_size
#audit_axioms NightstreamFPrime.Export.Stage1.StoredInstructionExecution.execute_eq

#audit_axioms NightstreamFPrime.Circuit.WitnessBatch.readsSatisfy_arithmetic
#audit_axioms NightstreamFPrime.Circuit.WitnessBatch.readsSatisfy_hinted

#audit_axioms NightstreamFPrime.Export.Stage1.StoredExecutionSupport.write_agree
#audit_axioms NightstreamFPrime.Export.Stage1.StoredExecutionSupport.recipes_agree
#audit_axioms NightstreamFPrime.Export.Stage1.StoredExecutionSupport.hint_eval_eq
#audit_axioms NightstreamFPrime.Export.Stage1.StoredExecutionSupport.hints_agree
#audit_axioms NightstreamFPrime.Export.Stage1.StoredExecutionSupport.instruction_agree
#audit_axioms NightstreamFPrime.Export.Stage1.StoredExecutionSupport.permutation_agree
#audit_axioms NightstreamFPrime.Export.Stage1.StoredExecutionSupport.compact_step_agree
#audit_axioms NightstreamFPrime.Export.Stage1.StoredExecutionSupport.compact_run_agree
#audit_axioms NightstreamFPrime.Export.Stage1.StoredExecutionSupport.compact_agree

#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCCombinationWitnessReadSupport.shiftBatch_readsSatisfy
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCCombinationWitnessReadSupport.piDecBatches_readsSatisfy
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCCombinationWitnessReadSupport.piRlcDigestLaneBatches_readsSatisfy
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCCombinationWitnessReadSupport.piRlcSamplerBatches_readsSatisfy
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCCombinationWitnessReadSupport.runningTransitionBatches_readsSatisfy
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCCombinationWitnessReadSupport.canonicalBlock_readsSatisfy
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCCombinationWitnessReadSupport.selectedApplicationBatches_readsSatisfy

#audit_axioms NightstreamFPrime.Lifecycle.PiDEC.v1_1.SignedSplitScalar.witnesses_main
#audit_axioms NightstreamFPrime.Lifecycle.PiDEC.v1_1.SignedSplitScalar.witnesses_main_readsSatisfy

#audit_axioms NightstreamFPrime.Lifecycle.PiDEC.v1_1.PublicInputSplit.witnesses_main_readsSatisfy

#audit_axioms NightstreamFPrime.Gadgets.Poseidon2.Formal.witnesses_main
#audit_axioms NightstreamFPrime.Gadgets.Poseidon2.Formal.witnesses_main_readsSatisfy

#audit_axioms NightstreamFPrime.Export.Stage1.StoredPhysicalPlan.Plan.rowEvents_induction
#audit_axioms NightstreamFPrime.Gadgets.Range.CanonicalU64.highDifference_varsSatisfy
#audit_axioms NightstreamFPrime.Gadgets.Range.CanonicalU64.flagRecipe_varsSatisfy
#audit_axioms NightstreamFPrime.Gadgets.Range.CanonicalU64.witnessBatches_readsSatisfy
#audit_axioms NightstreamFPrime.Gadgets.Sampling.Candidate16Five.productExpr_varsSatisfy
#audit_axioms NightstreamFPrime.Gadgets.Sampling.Candidate16Five.witnessBatches_readsSatisfy
#audit_axioms NightstreamFPrime.Lifecycle.PiRLC.v1_1.DigestLane.decoderCandidate_varsSatisfy
#audit_axioms NightstreamFPrime.Lifecycle.PiRLC.v1_1.DigestLane.decoderBits_varsSatisfy
#audit_axioms NightstreamFPrime.Lifecycle.PiRLC.v1_1.DigestLane.witnessBatches_readsSatisfy

#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCCombinationInvocationOrigin.canonical_origin
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCCombinationInvocationOrigin.descriptor_template
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCCombinationInvocationOrigin.shifted_origin
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCCombinationInvocationOrigin.shifted_localStart
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCCombinationInvocationOrigin.shifted_scratch_contained
#audit_axioms NightstreamFPrime.Export.Stage1.PiRLCCombinationInvocationOrigin.shifted_inputs_outside_scratch
#audit_axioms NightstreamFPrime.Export.Stage1.StoredCompactRowExecution.execute_size
#audit_axioms NightstreamFPrime.Export.Stage1.StoredCompactRowExecution.execute_agreesOutside
