import NightstreamFPrime.Layout.Stage1.RunningTransitionReducedRows
import NightstreamFPrime.Export.Stage1.RunningTransitionReducedMatrixProgram
import tests.AxiomAudit

#audit_axioms NightstreamFPrime.Layout.Stage1.RunningTransitionReducedRows.rows_iff_logical
#audit_axioms NightstreamFPrime.Layout.Stage1.RunningTransitionReducedRows.muxRow_values
#audit_axioms NightstreamFPrime.Layout.Stage1.RunningTransitionReducedRows.soundness
#audit_axioms NightstreamFPrime.Layout.Stage1.RunningTransitionReducedRows.flag_boolean
#audit_axioms NightstreamFPrime.Layout.Stage1.RunningTransitionReducedRows.extend_agrees
#audit_axioms NightstreamFPrime.Layout.Stage1.RunningTransitionReducedRows.extend_complete
#audit_axioms NightstreamFPrime.Layout.Stage1.RunningTransitionReducedRows.completeness
#audit_axioms NightstreamFPrime.Layout.Stage1.RunningTransitionReducedRows.reconstruct_complete
#audit_axioms NightstreamFPrime.Layout.Stage1.RunningTransitionReducedRows.original_to_reduced
#audit_axioms NightstreamFPrime.Layout.Stage1.RunningTransitionReducedRows.flag_low_norm
#audit_axioms NightstreamFPrime.Layout.Stage1.RunningTransitionReducedRows.row_count
#audit_axioms NightstreamFPrime.Layout.Stage1.RunningTransitionReducedRows.local_geometry

#audit_axioms NightstreamFPrime.Export.Stage1.RunningTransitionReducedMatrixProgram.row_count
#audit_axioms NightstreamFPrime.Export.Stage1.RunningTransitionReducedMatrixProgram.local_coordinate_count
#audit_axioms NightstreamFPrime.Export.Stage1.RunningTransitionReducedMatrixProgram.sourceRow_independent
