import Nightstream.Assurance.Nebula.ProductionPaperReleaseSecurityCountermodels

set_option autoImplicit false

namespace tests.NebulaProductionPaperReleaseSecurityCountermodels

open Nightstream.Assurance.Nebula.ProductionPaperReleaseSecurityCountermodels

#check every_deterministic_event_requires_closure
#check every_computational_event_is_covered
#check every_computational_event_can_have_probability_one

end tests.NebulaProductionPaperReleaseSecurityCountermodels
