import Nightstream.Assurance.Nebula.ProductionPaperReleasePipeline

/-! Regression surface for the direct exact-production F-prime release path. -/

set_option autoImplicit false

namespace tests.NebulaProductionPaperReleasePipeline

open Nightstream.Assurance.Nebula.ProductionPaperReleasePipeline

#check ExtractedLifetime
#check FoldBoundaryFailure
#check RelationBoundaryFailure
#check StagedExtraction
#check ExtractionTrace
#check ExtractionFailure
#check Failure
#check LifetimeFailureAccounting
#check FoldBoundaryFailure.impliesAnyBad
#check RelationBoundaryFailure.impliesAnyBad
#check ExtractionFailure.impliesAnyBad
#check Failure.impliesAnyBad
#check Certificate
#check Certificate.baseChallengeAuthorityExact
#check GeneratedCertificate
#check GeneratedCertificate.recursivePayloadCanonical
#check GeneratedCertificate.rowsAndCarrierFit
#check GeneratedCertificate.terminalRowsAndCarrierFit
#check GeneratedCertificate.verifierKeyIdentityExact
#check Certificate.exactClaimSchedule
#check Certificate.fixedBranchSchedule
#check Certificate.consumerInvocationIndicesExact
#check Certificate.fullStateContinuityExact
#check Certificate.receiptsExact
#check Certificate.exactClaimOpenings
#check Certificate.everyConsumedBundleOpens
#check Certificate.everyConsumedClaimHolds
#check Certificate.everyConsumedClaimSelectsGeneratedCore
#check acceptance_under_staged_refinement_implies_certificate_or_failure
#check acceptance_under_staged_refinement_implies_execution_or_failure
#check acceptance_under_staged_refinement_implies_any_bad_or_execution
#check acceptance_under_staged_refinement_and_no_bad_implies_execution
#check acceptance_under_staged_refinement_implies_wasm_result_or_failure
#check generated_acceptance_under_staged_refinement_implies_certificate_or_failure
#check generated_acceptance_under_staged_refinement_implies_execution_or_failure
#check generated_acceptance_under_staged_refinement_implies_any_bad_or_execution
#check generated_acceptance_under_staged_refinement_and_no_bad_implies_execution
#check generated_acceptance_under_staged_refinement_implies_wasm_result_or_failure

end tests.NebulaProductionPaperReleasePipeline
