import Nightstream.Implementation.Nebula.NIFS.Core.Concrete

set_option autoImplicit false

namespace tests.NebulaProductConcreteNifs

#check Nightstream.Implementation.Nebula.ProductConcreteNifs.RelationArtifact
#check Nightstream.Implementation.Nebula.ProductConcreteNifs.key
#check Nightstream.Implementation.Nebula.ProductConcreteNifs.key_arity_total
#check Nightstream.Implementation.Nebula.ProductConcreteNifs.key_initialTranscriptState
#check Nightstream.Implementation.Nebula.ProductConcreteNifs.key_publicInputState
#check Nightstream.Implementation.Nebula.ProductConcreteNifs.key_matrixSource
#check Nightstream.Implementation.Nebula.ProductConcreteNifs.key_commitment_map

end tests.NebulaProductConcreteNifs
