import Nightstream.Implementation.Nebula.NIFS.Core.ExactConfiguration

set_option autoImplicit false

namespace tests.NebulaProductExactNifsConfiguration

#check Nightstream.Implementation.Nebula.ProductExactNifsConfiguration.configuration
#check Nightstream.Implementation.Nebula.ProductExactNifsConfiguration.selected
#check Nightstream.Implementation.Nebula.ProductExactNifsConfiguration.configuration_decoder_exact
#check Nightstream.Implementation.Nebula.ProductExactNifsConfiguration.configuration_key_exact
#check Nightstream.Implementation.Nebula.ProductExactNifsConfiguration.configuration_samplerCheck_exact
#check Nightstream.Implementation.Nebula.ProductExactNifsConfiguration.accepted_input_has_exact_fields

end tests.NebulaProductExactNifsConfiguration
