import Nightstream.Implementation.Nebula.NIFS.Core.PaperSelection

set_option autoImplicit false

namespace tests.NebulaProductPaperNifsSelection

open Nightstream.Implementation.Nebula.ProductPaperNifsSelection

#check selected
#check selected_verify_block_eq_false_of_sampler_rejected
#check verifyClaim_sound
#check verifyClaim_complete

end tests.NebulaProductPaperNifsSelection
