//! Lean renderer for the bounded one-slot terminal differential corpus.

use std::fmt::Write;

use super::{
    Case, Corpus, EncodeMap, FreshPublicMap, FreshRelationMap, HashInputMap, HashReceiptMap, RunningRelationMap,
    TerminalTraceMap,
};

pub(super) fn render(corpus: &Corpus) -> String {
    let mut out = String::new();
    writeln!(
        out,
        "import Nightstream.Implementation.Rust.CanonicalConformance.OneSlot\n"
    )
    .unwrap();
    writeln!(
        out,
        "/-!\nGenerated by the Rust bounded canonical-terminal drift gate.\n\
         Exact Rust carrier metadata and mutation coordinates are retained in\n\
         `canonical_terminal_cases.json`. This file is the equality quotient\n\
         consumed by the frozen one-slot checker. Link and relation outcomes\n\
         remain receipts, not primitive-refinement theorems. Do not edit by\n\
         hand.\n-/\n"
    )
    .unwrap();
    writeln!(
        out,
        "namespace Nightstream.Implementation.Rust.CanonicalConformance.OneSlot.Generated.Terminal\n\n\
         open Nightstream.Implementation.Rust.CanonicalConformance.OneSlot\n"
    )
    .unwrap();
    writeln!(out, "def corpusSchema : Nat := {}\n", corpus.schema).unwrap();
    let mut names = Vec::with_capacity(corpus.cases.len());
    for case in &corpus.cases {
        let name = lower_camel(&case.name);
        render_case(&mut out, &name, case);
        names.push(name);
    }
    writeln!(out, "def all : List TerminalCase := [{}]\n", names.join(", ")).unwrap();
    writeln!(out, "def honest : List TerminalCase := [honestBase, honestRecursive]\n").unwrap();
    writeln!(
        out,
        "def mutations : List TerminalCase := [{}]\n",
        names[2..].join(", ")
    )
    .unwrap();
    writeln!(
        out,
        "end Nightstream.Implementation.Rust.CanonicalConformance.OneSlot.Generated.Terminal"
    )
    .unwrap();
    out
}

fn render_case(out: &mut String, name: &str, case: &Case) {
    let mapped = &case.mapped;
    writeln!(
        out,
        "def {name} : TerminalCase where\n  verifierKey := {}\n  \
         defaultRunning := {}\n  iteration := {}\n  z0 := {}\n  zi := {}\n  \
         running := {}\n  runningWitness := {}\n  fresh := {}\n  \
         freshWitness := {}\n  pc := {}\n  trace := {}\n  rustAccepted := {}\n",
        atom(mapped.verifier_key),
        atom(mapped.default_running),
        mapped.iteration,
        atom(mapped.z0),
        atom(mapped.zi),
        atom(mapped.running),
        atom(mapped.running_witness),
        atom(mapped.fresh),
        atom(mapped.fresh_witness),
        mapped.pc,
        trace(&mapped.trace),
        bool_text(mapped.rust_accepted),
    )
    .unwrap();
}

fn trace(value: &TerminalTraceMap) -> String {
    match value {
        TerminalTraceMap::Base => ".base".to_owned(),
        TerminalTraceMap::Recursive {
            prior_hash,
            fresh_public,
            encode,
            running_relation,
            fresh_relation,
        } => format!(
            ".recursive {} {} {} {} {}",
            hash_receipt(prior_hash),
            fresh_public_receipt(fresh_public),
            encode_receipt(encode),
            running_relation_receipt(running_relation),
            fresh_relation_receipt(fresh_relation),
        ),
    }
}

fn hash_input(value: &HashInputMap) -> String {
    format!(
        "{{ verifierKey := {}, iteration := {}, z0 := {}, current := {}, running := {}, pc := {} }}",
        atom(value.verifier_key),
        value.iteration,
        atom(value.z0),
        atom(value.current),
        atom(value.running),
        value.pc,
    )
}

fn hash_receipt(value: &HashReceiptMap) -> String {
    format!(
        "{{ input := {}, output := {} }}",
        hash_input(&value.input),
        atom(value.output),
    )
}

fn fresh_public_receipt(value: &FreshPublicMap) -> String {
    format!("{{ input := {}, output := {} }}", atom(value.input), atom(value.output))
}

fn encode_receipt(value: &EncodeMap) -> String {
    format!("{{ input := {}, output := {} }}", atom(value.input), atom(value.output))
}

fn running_relation_receipt(value: &RunningRelationMap) -> String {
    format!(
        "{{ key := {}, value := {}, witness := {}, accepted := {} }}",
        atom(value.key),
        atom(value.value),
        atom(value.witness),
        bool_text(value.accepted),
    )
}

fn fresh_relation_receipt(value: &FreshRelationMap) -> String {
    format!(
        "{{ key := {}, value := {}, witness := {}, accepted := {} }}",
        atom(value.key),
        atom(value.value),
        atom(value.witness),
        bool_text(value.accepted),
    )
}

fn atom(value: u32) -> String {
    format!("⟨{value}⟩")
}

fn bool_text(value: bool) -> &'static str {
    if value {
        "true"
    } else {
        "false"
    }
}

fn lower_camel(value: &str) -> String {
    let mut pieces = value.split('_');
    let mut output = pieces.next().unwrap_or_default().to_owned();
    for piece in pieces {
        let mut characters = piece.chars();
        if let Some(first) = characters.next() {
            output.extend(first.to_uppercase());
            output.extend(characters);
        }
    }
    output
}
