import Nightstream.Implementation.R1CS.Artifacts.PiCcsExecution.Generated.SelectedReceipt

/-!
Public facade for the generated selected-profile `Pi_CCS` execution receipt.

Assurance tier: artifact-checked. The Rust drift test owns the generated bytes;
the handwritten checker owns their meaning.
-/
