//! Opcode selector column map: the per-opcode one-hot selector list and
//! the opcode -> selector-column resolution.

use super::*;

pub const SELECTOR_COLS: [usize; 113] = [
    COL_SEL_NOP,
    COL_SEL_I32_CONST,
    COL_SEL_I64_CONST,
    COL_SEL_REF_FUNC,
    COL_SEL_I32_ADD,
    COL_SEL_I64_ADD,
    COL_SEL_I32_SUB,
    COL_SEL_I64_SUB,
    COL_SEL_I32_LOAD,
    COL_SEL_I32_LOAD8_S,
    COL_SEL_I32_LOAD8_U,
    COL_SEL_I32_LOAD16_S,
    COL_SEL_I32_LOAD16_U,
    COL_SEL_I64_LOAD,
    COL_SEL_I32_STORE,
    COL_SEL_I32_STORE8,
    COL_SEL_I32_STORE16,
    COL_SEL_I64_STORE,
    COL_SEL_MEMORY_SIZE,
    COL_SEL_MEMORY_GROW,
    COL_SEL_TABLE_SIZE,
    COL_SEL_TABLE_GET,
    COL_SEL_TABLE_SET,
    COL_SEL_DROP,
    COL_SEL_BR,
    COL_SEL_BLOCK,
    COL_SEL_LOOP,
    COL_SEL_IF,
    COL_SEL_ELSE,
    COL_SEL_END,
    COL_SEL_UNREACHABLE,
    COL_SEL_I32_CLZ,
    COL_SEL_I32_CTZ,
    COL_SEL_I32_POPCNT,
    COL_SEL_I32_EQZ,
    COL_SEL_I64_EQZ,
    COL_SEL_I32_EQ,
    COL_SEL_I32_NE,
    COL_SEL_I32_LTS,
    COL_SEL_I32_LTU,
    COL_SEL_I32_GTS,
    COL_SEL_I32_GTU,
    COL_SEL_I32_LES,
    COL_SEL_I32_LEU,
    COL_SEL_I32_GES,
    COL_SEL_I32_GEU,
    COL_SEL_I32_AND,
    COL_SEL_I32_OR,
    COL_SEL_I32_XOR,
    COL_SEL_I32_MUL,
    COL_SEL_I64_AND,
    COL_SEL_I64_OR,
    COL_SEL_I64_XOR,
    COL_SEL_I64_MUL,
    COL_SEL_I32_SHL,
    COL_SEL_I32_SHR_U,
    COL_SEL_I32_SHR_S,
    COL_SEL_I32_ROTL,
    COL_SEL_I32_ROTR,
    COL_SEL_I32_DIV_U,
    COL_SEL_I32_DIV_S,
    COL_SEL_I32_REM_U,
    COL_SEL_I32_REM_S,
    COL_SEL_SELECT,
    COL_SEL_BR_IF_EQZ,
    COL_SEL_BR_TABLE,
    COL_SEL_CALL,
    COL_SEL_CALL_INDIRECT,
    COL_SEL_RETURN,
    COL_SEL_LOCAL_GET,
    COL_SEL_LOCAL_SET,
    COL_SEL_LOCAL_TEE,
    COL_SEL_GLOBAL_GET,
    COL_SEL_GLOBAL_SET,
    COL_SEL_I64_EQ,
    COL_SEL_I64_NE,
    COL_SEL_I64_STORE8,
    COL_SEL_I64_STORE16,
    COL_SEL_I64_STORE32,
    COL_SEL_I64_LOAD8_U,
    COL_SEL_I64_LOAD16_U,
    COL_SEL_I64_LOAD32_U,
    COL_SEL_I64_LOAD8_S,
    COL_SEL_I64_LOAD16_S,
    COL_SEL_I64_LOAD32_S,
    COL_SEL_I32_WRAP_I64,
    COL_SEL_I64_EXTEND_I32_U,
    COL_SEL_I64_EXTEND_I32_S,
    COL_SEL_I32_EXTEND8_S,
    COL_SEL_I32_EXTEND16_S,
    COL_SEL_I64_EXTEND8_S,
    COL_SEL_I64_EXTEND16_S,
    COL_SEL_I64_EXTEND32_S,
    COL_SEL_I64_LTS,
    COL_SEL_I64_LTU,
    COL_SEL_I64_GTS,
    COL_SEL_I64_GTU,
    COL_SEL_I64_LES,
    COL_SEL_I64_LEU,
    COL_SEL_I64_GES,
    COL_SEL_I64_GEU,
    COL_SEL_I64_SHL,
    COL_SEL_I64_SHR_S,
    COL_SEL_I64_SHR_U,
    COL_SEL_I64_ROTL,
    COL_SEL_I64_ROTR,
    COL_SEL_I64_DIV_S,
    COL_SEL_I64_DIV_U,
    COL_SEL_I64_REM_S,
    COL_SEL_I64_REM_U,
    COL_SEL_I64_CLZ,
    COL_SEL_I64_CTZ,
    COL_SEL_I64_POPCNT,
];

pub fn selector_col(op: WasmOpcode) -> Option<usize> {
    match op {
        WasmOpcode::Nop => Some(COL_SEL_NOP),
        WasmOpcode::I32Const => Some(COL_SEL_I32_CONST),
        WasmOpcode::I64Const => Some(COL_SEL_I64_CONST),
        WasmOpcode::RefFunc => Some(COL_SEL_REF_FUNC),
        WasmOpcode::I32Add => Some(COL_SEL_I32_ADD),
        WasmOpcode::I64Add => Some(COL_SEL_I64_ADD),
        WasmOpcode::I32Sub => Some(COL_SEL_I32_SUB),
        WasmOpcode::I64Sub => Some(COL_SEL_I64_SUB),
        WasmOpcode::I32Load => Some(COL_SEL_I32_LOAD),
        WasmOpcode::I32Load8S => Some(COL_SEL_I32_LOAD8_S),
        WasmOpcode::I32Load8U => Some(COL_SEL_I32_LOAD8_U),
        WasmOpcode::I32Load16S => Some(COL_SEL_I32_LOAD16_S),
        WasmOpcode::I32Load16U => Some(COL_SEL_I32_LOAD16_U),
        WasmOpcode::I64Load => Some(COL_SEL_I64_LOAD),
        WasmOpcode::I32Store => Some(COL_SEL_I32_STORE),
        WasmOpcode::I32Store8 => Some(COL_SEL_I32_STORE8),
        WasmOpcode::I32Store16 => Some(COL_SEL_I32_STORE16),
        WasmOpcode::I64Store => Some(COL_SEL_I64_STORE),
        WasmOpcode::MemorySize => Some(COL_SEL_MEMORY_SIZE),
        WasmOpcode::MemoryGrow => Some(COL_SEL_MEMORY_GROW),
        WasmOpcode::TableSize => Some(COL_SEL_TABLE_SIZE),
        WasmOpcode::TableGet => Some(COL_SEL_TABLE_GET),
        WasmOpcode::TableSet => Some(COL_SEL_TABLE_SET),
        WasmOpcode::Drop => Some(COL_SEL_DROP),
        WasmOpcode::Br => Some(COL_SEL_BR),
        WasmOpcode::Block => Some(COL_SEL_BLOCK),
        WasmOpcode::Loop => Some(COL_SEL_LOOP),
        WasmOpcode::If => Some(COL_SEL_IF),
        WasmOpcode::Else => Some(COL_SEL_ELSE),
        WasmOpcode::End => Some(COL_SEL_END),
        WasmOpcode::Unreachable => Some(COL_SEL_UNREACHABLE),
        WasmOpcode::I32Clz => Some(COL_SEL_I32_CLZ),
        WasmOpcode::I32Ctz => Some(COL_SEL_I32_CTZ),
        WasmOpcode::I32Popcnt => Some(COL_SEL_I32_POPCNT),
        WasmOpcode::I32Eqz => Some(COL_SEL_I32_EQZ),
        WasmOpcode::I64Eqz => Some(COL_SEL_I64_EQZ),
        WasmOpcode::I32Eq => Some(COL_SEL_I32_EQ),
        WasmOpcode::I32Ne => Some(COL_SEL_I32_NE),
        WasmOpcode::I64Eq => Some(COL_SEL_I64_EQ),
        WasmOpcode::I64Ne => Some(COL_SEL_I64_NE),
        WasmOpcode::I64Store8 => Some(COL_SEL_I64_STORE8),
        WasmOpcode::I64Store16 => Some(COL_SEL_I64_STORE16),
        WasmOpcode::I64Store32 => Some(COL_SEL_I64_STORE32),
        WasmOpcode::I64Load8U => Some(COL_SEL_I64_LOAD8_U),
        WasmOpcode::I64Load16U => Some(COL_SEL_I64_LOAD16_U),
        WasmOpcode::I64Load32U => Some(COL_SEL_I64_LOAD32_U),
        WasmOpcode::I64Load8S => Some(COL_SEL_I64_LOAD8_S),
        WasmOpcode::I64Load16S => Some(COL_SEL_I64_LOAD16_S),
        WasmOpcode::I64Load32S => Some(COL_SEL_I64_LOAD32_S),
        WasmOpcode::I32WrapI64 => Some(COL_SEL_I32_WRAP_I64),
        WasmOpcode::I64ExtendI32U => Some(COL_SEL_I64_EXTEND_I32_U),
        WasmOpcode::I64ExtendI32S => Some(COL_SEL_I64_EXTEND_I32_S),
        WasmOpcode::I32Extend8S => Some(COL_SEL_I32_EXTEND8_S),
        WasmOpcode::I32Extend16S => Some(COL_SEL_I32_EXTEND16_S),
        WasmOpcode::I64Extend8S => Some(COL_SEL_I64_EXTEND8_S),
        WasmOpcode::I64Extend16S => Some(COL_SEL_I64_EXTEND16_S),
        WasmOpcode::I64Extend32S => Some(COL_SEL_I64_EXTEND32_S),
        WasmOpcode::I32LtS => Some(COL_SEL_I32_LTS),
        WasmOpcode::I32LtU => Some(COL_SEL_I32_LTU),
        WasmOpcode::I32GtS => Some(COL_SEL_I32_GTS),
        WasmOpcode::I32GtU => Some(COL_SEL_I32_GTU),
        WasmOpcode::I32LeS => Some(COL_SEL_I32_LES),
        WasmOpcode::I32LeU => Some(COL_SEL_I32_LEU),
        WasmOpcode::I32GeS => Some(COL_SEL_I32_GES),
        WasmOpcode::I32GeU => Some(COL_SEL_I32_GEU),
        WasmOpcode::I32And => Some(COL_SEL_I32_AND),
        WasmOpcode::I32Or => Some(COL_SEL_I32_OR),
        WasmOpcode::I32Xor => Some(COL_SEL_I32_XOR),
        WasmOpcode::I32Mul => Some(COL_SEL_I32_MUL),
        WasmOpcode::I64And => Some(COL_SEL_I64_AND),
        WasmOpcode::I64Or => Some(COL_SEL_I64_OR),
        WasmOpcode::I64Xor => Some(COL_SEL_I64_XOR),
        WasmOpcode::I64Mul => Some(COL_SEL_I64_MUL),
        WasmOpcode::I32Shl => Some(COL_SEL_I32_SHL),
        WasmOpcode::I32ShrU => Some(COL_SEL_I32_SHR_U),
        WasmOpcode::I32ShrS => Some(COL_SEL_I32_SHR_S),
        WasmOpcode::I32Rotl => Some(COL_SEL_I32_ROTL),
        WasmOpcode::I32Rotr => Some(COL_SEL_I32_ROTR),
        WasmOpcode::I32DivU => Some(COL_SEL_I32_DIV_U),
        WasmOpcode::I32DivS => Some(COL_SEL_I32_DIV_S),
        WasmOpcode::I32RemU => Some(COL_SEL_I32_REM_U),
        WasmOpcode::I32RemS => Some(COL_SEL_I32_REM_S),
        WasmOpcode::I64LtS => Some(COL_SEL_I64_LTS),
        WasmOpcode::I64LtU => Some(COL_SEL_I64_LTU),
        WasmOpcode::I64GtS => Some(COL_SEL_I64_GTS),
        WasmOpcode::I64GtU => Some(COL_SEL_I64_GTU),
        WasmOpcode::I64LeS => Some(COL_SEL_I64_LES),
        WasmOpcode::I64LeU => Some(COL_SEL_I64_LEU),
        WasmOpcode::I64GeS => Some(COL_SEL_I64_GES),
        WasmOpcode::I64GeU => Some(COL_SEL_I64_GEU),
        WasmOpcode::I64Shl => Some(COL_SEL_I64_SHL),
        WasmOpcode::I64ShrS => Some(COL_SEL_I64_SHR_S),
        WasmOpcode::I64ShrU => Some(COL_SEL_I64_SHR_U),
        WasmOpcode::I64Rotl => Some(COL_SEL_I64_ROTL),
        WasmOpcode::I64Rotr => Some(COL_SEL_I64_ROTR),
        WasmOpcode::I64DivS => Some(COL_SEL_I64_DIV_S),
        WasmOpcode::I64DivU => Some(COL_SEL_I64_DIV_U),
        WasmOpcode::I64RemS => Some(COL_SEL_I64_REM_S),
        WasmOpcode::I64RemU => Some(COL_SEL_I64_REM_U),
        WasmOpcode::I64Clz => Some(COL_SEL_I64_CLZ),
        WasmOpcode::I64Ctz => Some(COL_SEL_I64_CTZ),
        WasmOpcode::I64Popcnt => Some(COL_SEL_I64_POPCNT),
        WasmOpcode::Select => Some(COL_SEL_SELECT),
        WasmOpcode::BrIf => Some(COL_SEL_BR_IF_EQZ),
        WasmOpcode::BrTable => Some(COL_SEL_BR_TABLE),
        WasmOpcode::Call => Some(COL_SEL_CALL),
        WasmOpcode::CallIndirect => Some(COL_SEL_CALL_INDIRECT),
        WasmOpcode::Return => Some(COL_SEL_RETURN),
        WasmOpcode::LocalGet => Some(COL_SEL_LOCAL_GET),
        WasmOpcode::LocalSet => Some(COL_SEL_LOCAL_SET),
        WasmOpcode::LocalTee => Some(COL_SEL_LOCAL_TEE),
        WasmOpcode::GlobalGet => Some(COL_SEL_GLOBAL_GET),
        WasmOpcode::GlobalSet => Some(COL_SEL_GLOBAL_SET),
        // Call correctness is enforced by Stage 2 (call stack) and Stage 3 (continuity),
        // not by a CCS row constraint. No selector column needed.
        WasmOpcode::Trap | WasmOpcode::Unsupported => None,
    }
}
