import DirectCcsFPrime.ProofSystem.Production.Impl.PublicIO.Exact.DirectParentOnlyProductionConcreteFPrimePriorExactIOLayout

/-!
Typed interface for exact public-IO split discipline.

Spec: `specs/ProofSystem/Production/Impl/PublicIO/Exact/DirectParentOnlyProductionConcreteFPrimePriorExactIOLayout.spec.md`
-/

namespace DirectCcsFPrime

namespace DirectParentOnlyProductionConcreteFPrimePriorExactIOLayoutInterface

abbrev ProductionContext :=
  DirectParentOnlyProductionConcreteFPrimePriorExactIOLayout.ProductionContext

abbrev PublicImage :=
  DirectParentOnlyProductionConcreteFPrimePriorExactIOLayout.PublicImage

abbrev ProofCarryingPriorProof :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOLayout.ProofCarryingPriorProof

abbrev ExactPublicIOLayoutBinding :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOLayout.ExactPublicIOLayoutBinding

abbrev ExactPublicIOTerminalLengthBinding :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOLayout.ExactPublicIOTerminalLengthBinding

abbrev ExactPublicIOTerminalSliceBinding :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOLayout.ExactPublicIOTerminalSliceBinding

abbrev exactPublicIOTerminalLengthBindingOfTerminalSlice :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOLayout.exactPublicIOTerminalLengthBindingOfTerminalSlice

abbrev exactPublicIOLayoutBindingOfTerminalLength :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOLayout.exactPublicIOLayoutBindingOfTerminalLength

abbrev exactPublicIOLayoutBindingOfTerminalSlice :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOLayout.exactPublicIOLayoutBindingOfTerminalSlice

abbrev RuntimeVerifyPriorOfExactPublicIOTerminalLengthSoundness :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOLayout.RuntimeVerifyPriorOfExactPublicIOTerminalLengthSoundness

abbrev certifiedPriorVerifierOfExactPublicIOTerminalLengthSoundness :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOLayout.certifiedPriorVerifierOfExactPublicIOTerminalLengthSoundness

abbrev certifiedPriorVerifierOfExactPublicIOTerminalLengthSoundness_verify :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOLayout.certifiedPriorVerifierOfExactPublicIOTerminalLengthSoundness_verify

abbrev runtimeVerifyPriorOfExactPublicIOTerminalLengthSoundness_boundStatement :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOLayout.runtimeVerifyPriorOfExactPublicIOTerminalLengthSoundness_boundStatement

abbrev runtimeVerifyPriorOfExactPublicIOTerminalLengthSoundness_acceptedOpens :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOLayout.runtimeVerifyPriorOfExactPublicIOTerminalLengthSoundness_acceptedOpens

abbrev runtimeVerifyPriorOfExactPublicIOTerminalLengthSoundness_reaches_prior :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOLayout.runtimeVerifyPriorOfExactPublicIOTerminalLengthSoundness_reaches_prior

abbrev runtimeVerifyPriorOfExactPublicIOTerminalLengthSoundness_cannot_accept_unreachable_prior :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOLayout.runtimeVerifyPriorOfExactPublicIOTerminalLengthSoundness_cannot_accept_unreachable_prior

abbrev runtimeVerifyPriorOfExactPublicIOTerminalLengthSoundness_publicImageInvariants :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOLayout.runtimeVerifyPriorOfExactPublicIOTerminalLengthSoundness_publicImageInvariants

abbrev proofFunctionalOfExactPublicIOTerminalLengthSoundness :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOLayout.proofFunctionalOfExactPublicIOTerminalLengthSoundness

abbrev certifiedSingleTerminalEndToEnd_ofExactPublicIOTerminalLengthSoundnessLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOLayout.certifiedSingleTerminalEndToEnd_ofExactPublicIOTerminalLengthSoundnessLatestStep

abbrev nonAggregatePrivateDecStageFacts_ofExactPublicIOTerminalLengthSoundnessLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOLayout.nonAggregatePrivateDecStageFacts_ofExactPublicIOTerminalLengthSoundnessLatestStep

abbrev section71StageTargetAuditTrail_ofExactPublicIOTerminalLengthSoundnessLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorExactIOLayout.section71StageTargetAuditTrail_ofExactPublicIOTerminalLengthSoundnessLatestStep

end DirectParentOnlyProductionConcreteFPrimePriorExactIOLayoutInterface

end DirectCcsFPrime
