import Nightstream.Implementation.Nebula.Production.Memory.BatchCcsLinkRowsFor

open Nightstream.Implementation.Nebula.ProductionMemoryBatchCcsLinkRowsFor

#check rows_imply_fullMatches
#check ccsPublicPlaced
#check rows_length_exact
