import Nightstream.Implementation.R1CS.FPrimeRecursiveManifestSchema

/-! Generated by `system_decider_r1cs`; do not hand-edit. -/

namespace Nightstream.Implementation.R1CS.FPrimeFullHistoryManifest

def schemaVersion : Nat := 2
def totalRows : Nat := 4076614
def totalColumns : Nat := 3298653
def totalSha256 : String := "ef9b5184d38e966d95d265afe8836c28a946b3df7fb1d5b38aa132a2881a3a7b"
def topLevelFamilies : List FPrimeRecursiveManifest.RowRange :=
  [ { name := "decider.step.base", rowStart := 0, rowEnd := 11321, nonzeroEntries := 83985, sha256 := "16da2a121325b7d84f21a4968b29a14fc09fac3175b76f7940550c0956ef597e" }
  , { name := "decider.step.recursive", rowStart := 11321, rowEnd := 929981, nonzeroEntries := 36698986, sha256 := "5c70b446cae52ec727ae548db417752f0183233f276c8ceaa8de1f5956efba69" }
  , { name := "decider.state_link", rowStart := 929981, rowEnd := 930012, nonzeroEntries := 93, sha256 := "863d77c82dbf4ed31f0faef39973a48923917649e2dff414ce8b6f542221c2f1" }
  , { name := "decider.terminal_fold", rowStart := 930012, rowEnd := 3555185, nonzeroEntries := 83949128, sha256 := "160e93702968256b04db400ebea56e08fb2622e336562001425390880f883350" }
  , { name := "decider.terminal_continuity", rowStart := 3555185, rowEnd := 3770743, nonzeroEntries := 646674, sha256 := "23ad85155805605ba4030816d0e0d80566c47e8eb547f77ce02a5d480d0b4948" }
  , { name := "decider.public_pins", rowStart := 3770743, rowEnd := 3775026, nonzeroEntries := 34020, sha256 := "cf2278d6c8e0d836394c7f17645234dad409be15a83e127772c508062bb7b232" }
  , { name := "decider.terminal_ce", rowStart := 3775026, rowEnd := 4076614, nonzeroEntries := 4464516, sha256 := "a99e6de6b631390cf92b7145387638f7b394a2d5eb02c494003e8a4d934c8ac1" }
  ]

def recursiveFamilies : List FPrimeRecursiveManifest.RowRange :=
  [ { name := "fprime.recursive.prelude", rowStart := 11321, rowEnd := 17497, nonzeroEntries := 46006, sha256 := "82c31403937261e630e2f8fb2988f7c0e297c1ea6d7efd9d0aa6372cde7708e1" }
  , { name := "fprime.recursive.transcript", rowStart := 17497, rowEnd := 30759, nonzeroEntries := 105742, sha256 := "fc3f12b219bc321190c5111dae423624d5afe1d725eafb53b61ef3c3c89a792c" }
  , { name := "fprime.recursive.nifs", rowStart := 30759, rowEnd := 882156, nonzeroEntries := 28713141, sha256 := "4805ae69abc6bb88078e5c79ff87c412ec8ce82b8b101a847535ea160bb5a23c" }
  , { name := "fprime.recursive.prior_link", rowStart := 882156, rowEnd := 887388, nonzeroEntries := 37990, sha256 := "4fc1229348c2925650349f8dd74c1023607328a4c2da48456e8e6dbbe081cc0d" }
  , { name := "fprime.recursive.nebula", rowStart := 887388, rowEnd := 887388, nonzeroEntries := 0, sha256 := "4346f57b3b38c31a807f1b1dfb68757cfc41f6a35ba6be12e4b0728bd0e58eab" }
  , { name := "fprime.recursive.accumulator", rowStart := 887388, rowEnd := 924691, nonzeroEntries := 7757844, sha256 := "465a73e16e64461e346c2a3370368ba5eec506d419775634bbda397c400dac11" }
  , { name := "fprime.recursive.counter", rowStart := 924691, rowEnd := 925213, nonzeroEntries := 2136, sha256 := "cb89b750dd7d8618f0c450c34164a3daf4a7f9b17676822033a80e9315eeaa10" }
  , { name := "fprime.recursive.output", rowStart := 925213, rowEnd := 929981, nonzeroEntries := 36127, sha256 := "8f7d36b9573bdc2153acda7fd666979ea1f50231d77a8e27b25b408f73cde285" }
  ]
def recursiveNifsFamilies : List FPrimeRecursiveManifest.RowRange :=
  [ { name := "nifs.pi_ccs", rowStart := 30759, rowEnd := 273649, nonzeroEntries := 7062315, sha256 := "5ec66497ae858747f57b114cbfcdedafb2a8346067ad48326e235ea7ab24490c" }
  , { name := "nifs.pi_rlc", rowStart := 273649, rowEnd := 871557, nonzeroEntries := 21595026, sha256 := "064f0dd9de8b1fbf214573302488b1e02aa2a15fcf037e3758a25cdbff782834" }
  , { name := "nifs.pi_dec", rowStart := 871557, rowEnd := 882154, nonzeroEntries := 55794, sha256 := "eac4da8cb47d73718083e8021e49a82d1d21f63a9f54dabcc3d66e0c16499a1e" }
  , { name := "nifs.point_binding", rowStart := 882154, rowEnd := 882156, nonzeroEntries := 6, sha256 := "5ca9aa691a070d733dd7393b4fd344400631ed8cfeaf4e600041a686f790c1a2" }
  ]
def recursivePiCcsFamilies : List FPrimeRecursiveManifest.RowRange :=
  [ { name := "nifs.pi_ccs.allocation", rowStart := 30759, rowEnd := 30768, nonzeroEntries := 26, sha256 := "31d0a148cb926037e412347bec06b6053142e68849a178d513b1425d1287036d" }
  , { name := "nifs.pi_ccs.authority", rowStart := 30768, rowEnd := 30834, nonzeroEntries := 138, sha256 := "ff7a9f47535cb5de6f6af5ffb383f27bc67ad0e281a769887a975ac5c7306a8f" }
  , { name := "nifs.pi_ccs.fresh_digests", rowStart := 30834, rowEnd := 208439, nonzeroEntries := 6557503, sha256 := "709ac3ad2094a698c657cf2baae24bd5958f750e1dc3ae91aad5dfe45362acb1" }
  , { name := "nifs.pi_ccs.running_authority", rowStart := 208439, rowEnd := 208439, nonzeroEntries := 0, sha256 := "4346f57b3b38c31a807f1b1dfb68757cfc41f6a35ba6be12e4b0728bd0e58eab" }
  , { name := "nifs.pi_ccs.transcript", rowStart := 208439, rowEnd := 225920, nonzeroEntries := 139407, sha256 := "d9191da170e6ff5c32b16eefcfca3189282d6b5522c034e5b5d0df1bffc632ab" }
  , { name := "nifs.pi_ccs.fe_initial", rowStart := 225920, rowEnd := 225922, nonzeroEntries := 4, sha256 := "ab5aa030a3474a7e842504edb2b063f06ce42923d55eab8ba8f97b089e43ab04" }
  , { name := "nifs.pi_ccs.fe_sumcheck", rowStart := 225922, rowEnd := 240553, nonzeroEntries := 116097, sha256 := "5e58c0596f4c8f7b71aa577d5bb218f598f44fc4b70193a6a278d18ab48e23b0" }
  , { name := "nifs.pi_ccs.nc_sumcheck", rowStart := 240553, rowEnd := 269842, nonzeroEntries := 232309, sha256 := "454c888a1f58226e828ff2f92139ce73cab3e9f5b291c8c01ed8bf2a057cc6c8" }
  , { name := "nifs.pi_ccs.output_binding", rowStart := 269842, rowEnd := 271097, nonzeroEntries := 3764, sha256 := "8663f6162a11e16c3f961c8d0c72d5fb958f5da36b5db74c6def977950e0a100" }
  , { name := "nifs.pi_ccs.fe_terminal", rowStart := 271097, rowEnd := 271876, nonzeroEntries := 3239, sha256 := "620cbaa04f300c632f550be5930bff7a210a0baf400ba9c9361f6f34a0d6681a" }
  , { name := "nifs.pi_ccs.nc_terminal", rowStart := 271876, rowEnd := 273040, nonzeroEntries := 5003, sha256 := "ee106d52c3314240568a9c40f47fe874dbbb3f7a4135d3f162f8a75742085293" }
  , { name := "nifs.pi_ccs.catchup", rowStart := 273040, rowEnd := 273649, nonzeroEntries := 4825, sha256 := "33248567f476d6bffda65396cdca981c067388f42c079b0a401fdf223c07b500" }
  ]
def recursivePiRlcFamilies : List FPrimeRecursiveManifest.RowRange :=
  [ { name := "nifs.pi_rlc.transcript_rhos", rowStart := 273649, rowEnd := 385011, nonzeroEntries := 3134268, sha256 := "21ecfd4d671aad3c1b3832f0b930a65b7631ac45a841dd297047093ea226285c" }
  , { name := "nifs.pi_rlc.shape", rowStart := 385011, rowEnd := 385106, nonzeroEntries := 270, sha256 := "12ff4726ff7de817942ba5e9332cca9909c48e3c8f3a1d8c02b67cd0dcfa48ae" }
  , { name := "nifs.pi_rlc.linear_folds", rowStart := 385106, rowEnd := 385128, nonzeroEntries := 66, sha256 := "d724de012fe58e8ddedcd2df33fbf1bd7e9441db1e243f064abb64d512548a2b" }
  , { name := "nifs.pi_rlc.projection_binding", rowStart := 385128, rowEnd := 860661, nonzeroEntries := 18417261, sha256 := "82d8f07cc4fc13ce4bb014bef8d526db9d915075bb384034a60588b4b6f5b32c" }
  , { name := "nifs.pi_rlc.projection_shared", rowStart := 860661, rowEnd := 861041, nonzeroEntries := 1514, sha256 := "9e3f21cb420b3d617d7d31c428c54415e415e789efb14cf864ab09668058c4bf" }
  , { name := "nifs.pi_rlc.projection_identities", rowStart := 861041, rowEnd := 871557, nonzeroEntries := 41647, sha256 := "87fe58612a7a691acc21f530b61b8296dc22e65cf57318f3f47d3f6b2b92214e" }
  ]
def terminalFamilies : List FPrimeRecursiveManifest.RowRange :=
  [ { name := "terminal.nifs", rowStart := 930012, rowEnd := 3502232, nonzeroEntries := 76144334, sha256 := "823eb492535fd7f785ff432cb01382476c34eaf37c22f7c1c87cedaa6f0319b6" }
  , { name := "terminal.running_link", rowStart := 3502232, rowEnd := 3502236, nonzeroEntries := 12, sha256 := "5a9524a717542f8528db0a4e4caa8e04e4da897b92cc113dd190b4c98f30d25a" }
  , { name := "terminal.parent_link", rowStart := 3502236, rowEnd := 3517633, nonzeroEntries := 46191, sha256 := "626bc8a80492c06cbac6c24b9066f09ce706c58a81014327c309e2365e3c1e14" }
  , { name := "terminal.latest_link", rowStart := 3517633, rowEnd := 3517890, nonzeroEntries := 771, sha256 := "04ffa425a0e31c1fbf9fd722a82712b7e836f62397ea98b11cd5dfc63793ab5e" }
  , { name := "terminal.accumulator", rowStart := 3517890, rowEnd := 3555185, nonzeroEntries := 7757820, sha256 := "3d429bdae4d08d60357ab79e9b29743634ed27540ae2c9ca52cdf683fff442da" }
  ]
def terminalNifsFamilies : List FPrimeRecursiveManifest.RowRange :=
  [ { name := "terminal.transcript", rowStart := 930012, rowEnd := 930020, nonzeroEntries := 24, sha256 := "cc89d7613e68f3f8994a87208cef8397b22710c12c0db05aacd8d0151e89c5d8" }
  , { name := "nifs.pi_ccs", rowStart := 930020, rowEnd := 1655551, nonzeroEntries := 16502958, sha256 := "f47ed2a7e210e494da94bd5fe7fa07aa3a68e45f727a0e2b459d63b999b854e3" }
  , { name := "nifs.pi_rlc", rowStart := 1655551, rowEnd := 3491633, nonzeroEntries := 59585552, sha256 := "621daa2532cce0bd60ce59259bdf1d5a52147b5027fadd410b452a79568c16e6" }
  , { name := "nifs.pi_dec", rowStart := 3491633, rowEnd := 3502230, nonzeroEntries := 55794, sha256 := "fe7f9bce7f536990f3a9d60553bd2c6085c3dd7d2a95880595c05e6f5dd0c4c1" }
  , { name := "nifs.point_binding", rowStart := 3502230, rowEnd := 3502232, nonzeroEntries := 6, sha256 := "3895dd2602d9c6a836baa4667c07a884434bcda659348029431bd4f4dbe0ff28" }
  ]
def terminalPiCcsFamilies : List FPrimeRecursiveManifest.RowRange :=
  [ { name := "nifs.pi_ccs.allocation", rowStart := 930020, rowEnd := 930203, nonzeroEntries := 519, sha256 := "97d070b9e2c3ba7b4b9c1b4adc696a7c8d1229085378ae0ff236b6ba75b53beb" }
  , { name := "nifs.pi_ccs.authority", rowStart := 930203, rowEnd := 941790, nonzeroEntries := 57864, sha256 := "afd21ee8d0574880525e0b473aa55918404ba745d59475454c20319da6821cb0" }
  , { name := "nifs.pi_ccs.fresh_digests", rowStart := 941790, rowEnd := 1119395, nonzeroEntries := 6557503, sha256 := "d4c3a124518ef86978bd658aebef064f08d9bdc23f3ebf701af8bfcdf02e0df7" }
  , { name := "nifs.pi_ccs.running_authority", rowStart := 1119395, rowEnd := 1347874, nonzeroEntries := 8599814, sha256 := "9af2aa74ee11aa9943d3730efb51908682aad44d65f51e3544a26c78470faeda" }
  , { name := "nifs.pi_ccs.transcript", rowStart := 1347874, rowEnd := 1365967, nonzeroEntries := 144254, sha256 := "71fa6a5472e909ebc55db807c00fc710c92ae6de1c4daafed7cf0db21d0db1db" }
  , { name := "nifs.pi_ccs.fe_initial", rowStart := 1365967, rowEnd := 1380610, nonzeroEntries := 66624, sha256 := "a607a000d6e3e9b73deb7e51ee78d772c2a9d31d459f88db262fe0a68d8337e4" }
  , { name := "nifs.pi_ccs.fe_sumcheck", rowStart := 1380610, rowEnd := 1395241, nonzeroEntries := 116097, sha256 := "9ec3c2a972c1b87be4844fa973e4968e186754521473d99a6ae11a8653032274" }
  , { name := "nifs.pi_ccs.nc_sumcheck", rowStart := 1395241, rowEnd := 1424530, nonzeroEntries := 232309, sha256 := "9c59a2e71ca4a144bcdd3ba8838f5dde83ab440a8b96f3c568367a28510f2fd3" }
  , { name := "nifs.pi_ccs.output_binding", rowStart := 1424530, rowEnd := 1634049, nonzeroEntries := 628542, sha256 := "2d62a36a1ee0d1d78173bcd43045e4acc1df4c6f27748f8bd9a95bd9ba5e8aa9" }
  , { name := "nifs.pi_ccs.fe_terminal", rowStart := 1634049, rowEnd := 1648892, nonzeroEntries := 67456, sha256 := "618fbb9c0635d0dcbf1d737c1ce5aed293cf29655d37851cc89dd27f9ed9de14" }
  , { name := "nifs.pi_ccs.nc_terminal", rowStart := 1648892, rowEnd := 1654886, nonzeroEntries := 26983, sha256 := "fe648b03001b72428f6bce1785812c7f52d5af650a4d39486f9fa894dfc3bcba" }
  , { name := "nifs.pi_ccs.catchup", rowStart := 1654886, rowEnd := 1655551, nonzeroEntries := 4993, sha256 := "7a937d21f3d9e25acd65f6185a0f38b911b251ed5b25dcde19ebf9da2e5b40bc" }
  ]
def terminalPiRlcFamilies : List FPrimeRecursiveManifest.RowRange :=
  [ { name := "nifs.pi_rlc.transcript_rhos", rowStart := 1655551, rowEnd := 2953021, nonzeroEntries := 40919652, sha256 := "0fab994f9c95a9c9623621449bc9d3314394fab1469f0b1726a107b7f8916bc8" }
  , { name := "nifs.pi_rlc.shape", rowStart := 2953021, rowEnd := 2953186, nonzeroEntries := 480, sha256 := "c1941de032a45ad4e483400af8ee2c0101d677941ef1facbbd5ea40bcdea8ef3" }
  , { name := "nifs.pi_rlc.linear_folds", rowStart := 2953186, rowEnd := 2953516, nonzeroEntries := 990, sha256 := "352d7836d9f04674295b3df4b3333eaed09921802809bf589af829be3f0bf0e7" }
  , { name := "nifs.pi_rlc.projection_binding", rowStart := 2953516, rowEnd := 3429049, nonzeroEntries := 18417261, sha256 := "7d0fb6bc4a682d3ff13f1ee7a9833085fd0549c031dcf02c435224d4bfd3de68" }
  , { name := "nifs.pi_rlc.projection_shared", rowStart := 3429049, rowEnd := 3430941, nonzeroEntries := 7520, sha256 := "f81a49be72752ddd0d2027d98657196d5c8a5ba5621c8d69f0153361babd5124" }
  , { name := "nifs.pi_rlc.projection_identities", rowStart := 3430941, rowEnd := 3491633, nonzeroEntries := 239649, sha256 := "15a4d53ecd899f7b6d905cac11ae52396b6732b01d1bf039403a6f47430cc17f" }
  ]

end Nightstream.Implementation.R1CS.FPrimeFullHistoryManifest
