//! Owns WASM opcode taxonomy and stable lookup ids.

use rwasm::Opcode as ConcreteOpcode;

#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash)]
pub enum WasmOpcodeClass {
    System,
    ControlFlow,
    Numeric,
    Compare,
    Unknown,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash)]
pub enum WasmShoutOpcode {
    I32Clz,
    I32Ctz,
    I32Eqz,
    I64Eqz,
    I32Eq,
    I32Ne,
    I32LtS,
    I32LtU,
    I32GtS,
    I32GtU,
    I32LeS,
    I32LeU,
    I32GeS,
    I32GeU,
    I32And,
    I32Or,
    I32Xor,
    I32Mul,
    I64And,
    I64Or,
    I64Xor,
    I64Mul,
    I32Shl,
    I32ShrU,
    I32ShrS,
    I32Rotl,
    I32Rotr,
    I32DivU,
    I32DivS,
    I32RemU,
    I32RemS,
}

impl WasmShoutOpcode {
    pub fn all() -> [Self; 31] {
        [
            Self::I32Clz,
            Self::I32Ctz,
            Self::I32Eqz,
            Self::I64Eqz,
            Self::I32Eq,
            Self::I32Ne,
            Self::I32LtS,
            Self::I32LtU,
            Self::I32GtS,
            Self::I32GtU,
            Self::I32LeS,
            Self::I32LeU,
            Self::I32GeS,
            Self::I32GeU,
            Self::I32And,
            Self::I32Or,
            Self::I32Xor,
            Self::I32Mul,
            Self::I64And,
            Self::I64Or,
            Self::I64Xor,
            Self::I64Mul,
            Self::I32Shl,
            Self::I32ShrU,
            Self::I32ShrS,
            Self::I32Rotl,
            Self::I32Rotr,
            Self::I32DivU,
            Self::I32DivS,
            Self::I32RemU,
            Self::I32RemS,
        ]
    }

    pub fn name(self) -> &'static str {
        match self {
            Self::I32Clz => "i32_clz",
            Self::I32Ctz => "i32_ctz",
            Self::I32Eqz => "i32_eqz",
            Self::I64Eqz => "i64_eqz",
            Self::I32Eq => "i32_eq",
            Self::I32Ne => "i32_ne",
            Self::I32LtS => "i32_lt_s",
            Self::I32LtU => "i32_lt_u",
            Self::I32GtS => "i32_gt_s",
            Self::I32GtU => "i32_gt_u",
            Self::I32LeS => "i32_le_s",
            Self::I32LeU => "i32_le_u",
            Self::I32GeS => "i32_ge_s",
            Self::I32GeU => "i32_ge_u",
            Self::I32And => "i32_and",
            Self::I32Or => "i32_or",
            Self::I32Xor => "i32_xor",
            Self::I32Mul => "i32_mul",
            Self::I64And => "i64_and",
            Self::I64Or => "i64_or",
            Self::I64Xor => "i64_xor",
            Self::I64Mul => "i64_mul",
            Self::I32Shl => "i32_shl",
            Self::I32ShrU => "i32_shr_u",
            Self::I32ShrS => "i32_shr_s",
            Self::I32Rotl => "i32_rotl",
            Self::I32Rotr => "i32_rotr",
            Self::I32DivU => "i32_div_u",
            Self::I32DivS => "i32_div_s",
            Self::I32RemU => "i32_rem_u",
            Self::I32RemS => "i32_rem_s",
        }
    }

    pub fn to_shout_id(self) -> u32 {
        const BASE: u32 = 10_000;
        let offset = match self {
            Self::I32Clz => 5,
            Self::I32Ctz => 6,
            Self::I32Eqz => 0,
            Self::I64Eqz => 33,
            Self::I32Eq => 1,
            Self::I32Ne => 2,
            Self::I32LtS => 3,
            Self::I32LtU => 4,
            Self::I32GtS => 7,
            Self::I32GtU => 8,
            Self::I32LeS => 9,
            Self::I32LeU => 10,
            Self::I32GeS => 11,
            Self::I32GeU => 12,
            Self::I32And => 21,
            Self::I32Or => 22,
            Self::I32Xor => 23,
            Self::I32Mul => 16,
            Self::I64And => 34,
            Self::I64Or => 35,
            Self::I64Xor => 36,
            Self::I64Mul => 37,
            Self::I32Shl => 24,
            Self::I32ShrU => 25,
            Self::I32ShrS => 26,
            Self::I32Rotl => 31,
            Self::I32Rotr => 32,
            Self::I32DivU => 27,
            Self::I32DivS => 28,
            Self::I32RemU => 29,
            Self::I32RemS => 30,
        };
        BASE + offset
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash, PartialOrd, Ord)]
pub enum WasmOpcode {
    Nop,
    I32Const,
    I64Const,
    RefFunc,
    I32Add,
    I64Add,
    I32Sub,
    I64Sub,
    I32Load,
    I32Load8S,
    I32Load8U,
    I32Load16S,
    I32Load16U,
    I64Load,
    I32Store,
    I32Store8,
    I32Store16,
    I64Store,
    MemorySize,
    MemoryGrow,
    TableSize,
    TableGet,
    TableSet,
    Drop,
    Br,
    Block,
    Loop,
    If,
    Else,
    End,
    Unreachable,
    I32Clz,
    I32Ctz,
    I32Popcnt,
    I32Eqz,
    I64Eqz,
    I32Eq,
    I32Ne,
    I32LtS,
    I32LtU,
    I32GtS,
    I32GtU,
    I32LeS,
    I32LeU,
    I32GeS,
    I32GeU,
    I32And,
    I32Or,
    I32Xor,
    I32Mul,
    I64And,
    I64Or,
    I64Xor,
    I64Mul,
    I32Shl,
    I32ShrU,
    I32ShrS,
    I32Rotl,
    I32Rotr,
    I32DivU,
    I32DivS,
    I32RemU,
    I32RemS,
    Select,
    BrIf,
    BrTable,
    Call,
    CallIndirect,
    Return,
    LocalGet,
    LocalSet,
    LocalTee,
    GlobalGet,
    GlobalSet,
    Trap,
    Unsupported,
}

impl WasmOpcode {
    pub fn supported() -> [Self; 74] {
        [
            Self::Nop,
            Self::I32Const,
            Self::I64Const,
            Self::RefFunc,
            Self::I32Add,
            Self::I64Add,
            Self::I32Sub,
            Self::I64Sub,
            Self::I32Load,
            Self::I32Load8S,
            Self::I32Load8U,
            Self::I32Load16S,
            Self::I32Load16U,
            Self::I64Load,
            Self::I32Store,
            Self::I32Store8,
            Self::I32Store16,
            Self::I64Store,
            Self::MemorySize,
            Self::MemoryGrow,
            Self::TableSize,
            Self::TableGet,
            Self::TableSet,
            Self::Drop,
            Self::Br,
            Self::Block,
            Self::Loop,
            Self::If,
            Self::Else,
            Self::End,
            Self::Unreachable,
            Self::I32Clz,
            Self::I32Ctz,
            Self::I32Popcnt,
            Self::I32Eqz,
            Self::I64Eqz,
            Self::I32Eq,
            Self::I32Ne,
            Self::I32LtS,
            Self::I32LtU,
            Self::I32GtS,
            Self::I32GtU,
            Self::I32LeS,
            Self::I32LeU,
            Self::I32GeS,
            Self::I32GeU,
            Self::I32And,
            Self::I32Or,
            Self::I32Xor,
            Self::I32Mul,
            Self::I64And,
            Self::I64Or,
            Self::I64Xor,
            Self::I64Mul,
            Self::I32Shl,
            Self::I32ShrU,
            Self::I32ShrS,
            Self::I32Rotl,
            Self::I32Rotr,
            Self::I32DivU,
            Self::I32DivS,
            Self::I32RemU,
            Self::I32RemS,
            Self::Select,
            Self::BrIf,
            Self::BrTable,
            Self::Call,
            Self::CallIndirect,
            Self::Return,
            Self::LocalGet,
            Self::LocalSet,
            Self::LocalTee,
            Self::GlobalGet,
            Self::GlobalSet,
        ]
    }

    pub fn selector_index(self) -> Option<usize> {
        match self {
            Self::Nop => Some(0),
            Self::I32Const => Some(1),
            Self::I64Const => Some(2),
            Self::RefFunc => Some(3),
            Self::I32Add => Some(4),
            Self::I64Add => Some(5),
            Self::I32Sub => Some(6),
            Self::I64Sub => Some(7),
            Self::I32Load => Some(8),
            Self::I32Load8S => Some(9),
            Self::I32Load8U => Some(10),
            Self::I32Load16S => Some(11),
            Self::I32Load16U => Some(12),
            Self::I64Load => Some(13),
            Self::I32Store => Some(14),
            Self::I32Store8 => Some(15),
            Self::I32Store16 => Some(16),
            Self::I64Store => Some(17),
            Self::MemorySize => Some(18),
            Self::MemoryGrow => Some(19),
            Self::TableSize => Some(20),
            Self::TableGet => Some(21),
            Self::TableSet => Some(22),
            Self::Drop => Some(23),
            Self::Br => Some(24),
            Self::Block => Some(25),
            Self::Loop => Some(26),
            Self::If => Some(27),
            Self::Else => Some(28),
            Self::End => Some(29),
            Self::Unreachable => Some(30),
            Self::I32Clz => Some(31),
            Self::I32Ctz => Some(32),
            Self::I32Popcnt => Some(33),
            Self::I32Eqz => Some(34),
            Self::I64Eqz => Some(35),
            Self::I32Eq => Some(36),
            Self::I32Ne => Some(37),
            Self::I32LtS => Some(38),
            Self::I32LtU => Some(39),
            Self::I32GtS => Some(40),
            Self::I32GtU => Some(41),
            Self::I32LeS => Some(42),
            Self::I32LeU => Some(43),
            Self::I32GeS => Some(44),
            Self::I32GeU => Some(45),
            Self::I32And => Some(46),
            Self::I32Or => Some(47),
            Self::I32Xor => Some(48),
            Self::I32Mul => Some(49),
            Self::I64And => Some(50),
            Self::I64Or => Some(51),
            Self::I64Xor => Some(52),
            Self::I64Mul => Some(53),
            Self::I32Shl => Some(54),
            Self::I32ShrU => Some(55),
            Self::I32ShrS => Some(56),
            Self::I32Rotl => Some(57),
            Self::I32Rotr => Some(58),
            Self::I32DivU => Some(59),
            Self::I32DivS => Some(60),
            Self::I32RemU => Some(61),
            Self::I32RemS => Some(62),
            Self::Select => Some(63),
            Self::BrIf => Some(64),
            Self::BrTable => Some(65),
            Self::Call => Some(66),
            Self::CallIndirect => Some(67),
            Self::Return => Some(68),
            Self::LocalGet => Some(69),
            Self::LocalSet => Some(70),
            Self::LocalTee => Some(71),
            Self::GlobalGet => Some(72),
            Self::GlobalSet => Some(73),
            Self::Trap | Self::Unsupported => None,
        }
    }

    pub fn name(self) -> &'static str {
        match self {
            Self::Nop => "nop",
            Self::I32Const => "i32_const",
            Self::I64Const => "i64_const",
            Self::RefFunc => "ref_func",
            Self::I32Add => "i32_add",
            Self::I64Add => "i64_add",
            Self::I32Sub => "i32_sub",
            Self::I64Sub => "i64_sub",
            Self::I32Load => "i32_load",
            Self::I32Load8S => "i32_load8_s",
            Self::I32Load8U => "i32_load8_u",
            Self::I32Load16S => "i32_load16_s",
            Self::I32Load16U => "i32_load16_u",
            Self::I64Load => "i64_load",
            Self::I32Store => "i32_store",
            Self::I32Store8 => "i32_store8",
            Self::I32Store16 => "i32_store16",
            Self::I64Store => "i64_store",
            Self::MemorySize => "memory_size",
            Self::MemoryGrow => "memory_grow",
            Self::TableSize => "table_size",
            Self::TableGet => "table_get",
            Self::TableSet => "table_set",
            Self::Drop => "drop",
            Self::Br => "br",
            Self::Block => "block",
            Self::Loop => "loop",
            Self::If => "if",
            Self::Else => "else",
            Self::End => "end",
            Self::Unreachable => "unreachable",
            Self::I32Clz => "i32_clz",
            Self::I32Ctz => "i32_ctz",
            Self::I32Popcnt => "i32_popcnt",
            Self::I32Eqz => "i32_eqz",
            Self::I64Eqz => "i64_eqz",
            Self::I32Eq => "i32_eq",
            Self::I32Ne => "i32_ne",
            Self::I32LtS => "i32_lt_s",
            Self::I32LtU => "i32_lt_u",
            Self::I32GtS => "i32_gt_s",
            Self::I32GtU => "i32_gt_u",
            Self::I32LeS => "i32_le_s",
            Self::I32LeU => "i32_le_u",
            Self::I32GeS => "i32_ge_s",
            Self::I32GeU => "i32_ge_u",
            Self::I32And => "i32_and",
            Self::I32Or => "i32_or",
            Self::I32Xor => "i32_xor",
            Self::I32Mul => "i32_mul",
            Self::I64And => "i64_and",
            Self::I64Or => "i64_or",
            Self::I64Xor => "i64_xor",
            Self::I64Mul => "i64_mul",
            Self::I32Shl => "i32_shl",
            Self::I32ShrU => "i32_shr_u",
            Self::I32ShrS => "i32_shr_s",
            Self::I32Rotl => "i32_rotl",
            Self::I32Rotr => "i32_rotr",
            Self::I32DivU => "i32_div_u",
            Self::I32DivS => "i32_div_s",
            Self::I32RemU => "i32_rem_u",
            Self::I32RemS => "i32_rem_s",
            Self::Select => "select",
            Self::BrIf => "br_if",
            Self::BrTable => "br_table",
            Self::Call => "call",
            Self::CallIndirect => "call_indirect",
            Self::Return => "return",
            Self::LocalGet => "local_get",
            Self::LocalSet => "local_set",
            Self::LocalTee => "local_tee",
            Self::GlobalGet => "global_get",
            Self::GlobalSet => "global_set",
            Self::Trap => "trap",
            Self::Unsupported => "unsupported",
        }
    }

    pub fn from_concrete(op: ConcreteOpcode) -> Self {
        match op {
            ConcreteOpcode::Unreachable => Self::Unreachable,
            ConcreteOpcode::I32Const(_) => Self::I32Const,
            ConcreteOpcode::RefFunc(_) => Self::RefFunc,
            ConcreteOpcode::I32Add => Self::I32Add,
            ConcreteOpcode::I32Sub => Self::I32Sub,
            ConcreteOpcode::I32Load(_) => Self::I32Load,
            ConcreteOpcode::I32Load8S(_) => Self::I32Load8S,
            ConcreteOpcode::I32Load8U(_) => Self::I32Load8U,
            ConcreteOpcode::I32Load16S(_) => Self::I32Load16S,
            ConcreteOpcode::I32Load16U(_) => Self::I32Load16U,
            ConcreteOpcode::I32Store(_) => Self::I32Store,
            ConcreteOpcode::I32Store8(_) => Self::I32Store8,
            ConcreteOpcode::I32Store16(_) => Self::I32Store16,
            ConcreteOpcode::MemorySize => Self::MemorySize,
            ConcreteOpcode::MemoryGrow => Self::MemoryGrow,
            ConcreteOpcode::TableSize(_) => Self::TableSize,
            ConcreteOpcode::TableGet(_) => Self::TableGet,
            ConcreteOpcode::TableSet(_) => Self::TableSet,
            ConcreteOpcode::Drop => Self::Drop,
            ConcreteOpcode::Br(_) => Self::Br,
            ConcreteOpcode::I32Clz => Self::I32Clz,
            ConcreteOpcode::I32Ctz => Self::I32Ctz,
            ConcreteOpcode::I32Popcnt => Self::I32Popcnt,
            ConcreteOpcode::I32Eqz => Self::I32Eqz,
            ConcreteOpcode::I32Eq => Self::I32Eq,
            ConcreteOpcode::I32Ne => Self::I32Ne,
            ConcreteOpcode::I32LtS => Self::I32LtS,
            ConcreteOpcode::I32LtU => Self::I32LtU,
            ConcreteOpcode::I32GtS => Self::I32GtS,
            ConcreteOpcode::I32GtU => Self::I32GtU,
            ConcreteOpcode::I32LeS => Self::I32LeS,
            ConcreteOpcode::I32LeU => Self::I32LeU,
            ConcreteOpcode::I32GeS => Self::I32GeS,
            ConcreteOpcode::I32GeU => Self::I32GeU,
            ConcreteOpcode::I32And => Self::I32And,
            ConcreteOpcode::I32Or => Self::I32Or,
            ConcreteOpcode::I32Xor => Self::I32Xor,
            ConcreteOpcode::I32Mul => Self::I32Mul,
            ConcreteOpcode::I32Shl => Self::I32Shl,
            ConcreteOpcode::I32ShrU => Self::I32ShrU,
            ConcreteOpcode::I32ShrS => Self::I32ShrS,
            ConcreteOpcode::I32Rotl => Self::I32Rotl,
            ConcreteOpcode::I32Rotr => Self::I32Rotr,
            ConcreteOpcode::I32DivU => Self::I32DivU,
            ConcreteOpcode::I32DivS => Self::I32DivS,
            ConcreteOpcode::I32RemU => Self::I32RemU,
            ConcreteOpcode::I32RemS => Self::I32RemS,
            ConcreteOpcode::Select => Self::Select,
            ConcreteOpcode::BrIfEqz(_) => Self::BrIf,
            ConcreteOpcode::BrTable(_) => Self::BrTable,
            ConcreteOpcode::CallInternal(_) => Self::Call,
            ConcreteOpcode::CallIndirect(_) => Self::CallIndirect,
            ConcreteOpcode::Return => Self::Return,
            ConcreteOpcode::LocalGet(_) => Self::LocalGet,
            ConcreteOpcode::LocalSet(_) => Self::LocalSet,
            ConcreteOpcode::LocalTee(_) => Self::LocalTee,
            ConcreteOpcode::GlobalGet(_) => Self::GlobalGet,
            ConcreteOpcode::GlobalSet(_) => Self::GlobalSet,
            ConcreteOpcode::Trap(_) => Self::Trap,
            _ => Self::Unsupported,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct WasmOpcodeInfo {
    pub opcode: WasmOpcode,
    pub code: u16,
    pub name: &'static str,
    pub class: WasmOpcodeClass,
    pub stack_reads: u8,
    pub stack_writes: u8,
    pub uses_shout: bool,
    pub shout_opcode: Option<WasmShoutOpcode>,
}

pub fn opcode_info_from_concrete(op: ConcreteOpcode) -> WasmOpcodeInfo {
    let wasm_opcode = WasmOpcode::from_concrete(op);
    opcode_info_from_code(opcode_code(wasm_opcode))
}

pub fn opcode_info_from_code(code: u16) -> WasmOpcodeInfo {
    use WasmOpcode as Op;
    use WasmOpcodeClass as Class;
    use WasmShoutOpcode as Shout;

    let op = opcode_from_code(code);
    match op {
        Op::Nop => info(op, code, Class::System, 0, 0, false, None),
        Op::I32Const => info(op, code, Class::Numeric, 0, 1, false, None),
        Op::I64Const => info(op, code, Class::Numeric, 0, 1, false, None),
        Op::RefFunc => info(op, code, Class::System, 0, 1, false, None),
        Op::I32Add => info(op, code, Class::Numeric, 2, 1, false, None),
        Op::I64Add => info(op, code, Class::Numeric, 2, 1, false, None),
        Op::I32Sub => info(op, code, Class::Numeric, 2, 1, false, None),
        Op::I64Sub => info(op, code, Class::Numeric, 2, 1, false, None),
        Op::I32Load => info(op, code, Class::System, 1, 1, false, None),
        Op::I32Load8S => info(op, code, Class::System, 1, 1, false, None),
        Op::I32Load8U => info(op, code, Class::System, 1, 1, false, None),
        Op::I32Load16S => info(op, code, Class::System, 1, 1, false, None),
        Op::I32Load16U => info(op, code, Class::System, 1, 1, false, None),
        Op::I64Load => info(op, code, Class::System, 1, 1, false, None),
        Op::I32Store => info(op, code, Class::System, 2, 0, false, None),
        Op::I32Store8 => info(op, code, Class::System, 2, 0, false, None),
        Op::I32Store16 => info(op, code, Class::System, 2, 0, false, None),
        Op::I64Store => info(op, code, Class::System, 2, 0, false, None),
        Op::MemorySize => info(op, code, Class::System, 0, 1, false, None),
        Op::MemoryGrow => info(op, code, Class::System, 1, 1, false, None),
        Op::TableSize => info(op, code, Class::System, 0, 1, false, None),
        Op::TableGet => info(op, code, Class::System, 1, 1, false, None),
        Op::TableSet => info(op, code, Class::System, 2, 0, false, None),
        Op::Drop => info(op, code, Class::System, 1, 0, false, None),
        Op::Br => info(op, code, Class::ControlFlow, 0, 0, false, None),
        Op::Block => info(op, code, Class::ControlFlow, 0, 0, false, None),
        Op::Loop => info(op, code, Class::ControlFlow, 0, 0, false, None),
        Op::If => info(op, code, Class::ControlFlow, 1, 0, false, None),
        Op::Else => info(op, code, Class::ControlFlow, 0, 0, false, None),
        Op::End => info(op, code, Class::ControlFlow, 0, 0, false, None),
        Op::Unreachable => info(op, code, Class::System, 0, 0, false, None),
        Op::I32Clz => info(op, code, Class::Numeric, 1, 1, true, Some(Shout::I32Clz)),
        Op::I32Ctz => info(op, code, Class::Numeric, 1, 1, true, Some(Shout::I32Ctz)),
        Op::I32Popcnt => info(op, code, Class::Numeric, 1, 1, false, None),
        Op::I32Eqz => info(op, code, Class::Compare, 1, 1, true, Some(Shout::I32Eqz)),
        Op::I64Eqz => info(op, code, Class::Compare, 1, 1, true, Some(Shout::I64Eqz)),
        Op::I32Eq => info(op, code, Class::Compare, 2, 1, true, Some(Shout::I32Eq)),
        Op::I32Ne => info(op, code, Class::Compare, 2, 1, true, Some(Shout::I32Ne)),
        Op::I32LtS => info(op, code, Class::Compare, 2, 1, true, Some(Shout::I32LtS)),
        Op::I32LtU => info(op, code, Class::Compare, 2, 1, true, Some(Shout::I32LtU)),
        Op::I32GtS => info(op, code, Class::Compare, 2, 1, true, Some(Shout::I32GtS)),
        Op::I32GtU => info(op, code, Class::Compare, 2, 1, true, Some(Shout::I32GtU)),
        Op::I32LeS => info(op, code, Class::Compare, 2, 1, true, Some(Shout::I32LeS)),
        Op::I32LeU => info(op, code, Class::Compare, 2, 1, true, Some(Shout::I32LeU)),
        Op::I32GeS => info(op, code, Class::Compare, 2, 1, true, Some(Shout::I32GeS)),
        Op::I32GeU => info(op, code, Class::Compare, 2, 1, true, Some(Shout::I32GeU)),
        Op::I32And => info(op, code, Class::Numeric, 2, 1, true, Some(Shout::I32And)),
        Op::I32Or => info(op, code, Class::Numeric, 2, 1, true, Some(Shout::I32Or)),
        Op::I32Xor => info(op, code, Class::Numeric, 2, 1, true, Some(Shout::I32Xor)),
        Op::I32Mul => info(op, code, Class::Numeric, 2, 1, true, Some(Shout::I32Mul)),
        Op::I64And => info(op, code, Class::Numeric, 2, 1, true, Some(Shout::I64And)),
        Op::I64Or => info(op, code, Class::Numeric, 2, 1, true, Some(Shout::I64Or)),
        Op::I64Xor => info(op, code, Class::Numeric, 2, 1, true, Some(Shout::I64Xor)),
        Op::I64Mul => info(op, code, Class::Numeric, 2, 1, true, Some(Shout::I64Mul)),
        Op::I32Shl => info(op, code, Class::Numeric, 2, 1, true, Some(Shout::I32Shl)),
        Op::I32ShrU => info(op, code, Class::Numeric, 2, 1, true, Some(Shout::I32ShrU)),
        Op::I32ShrS => info(op, code, Class::Numeric, 2, 1, true, Some(Shout::I32ShrS)),
        Op::I32Rotl => info(op, code, Class::Numeric, 2, 1, true, Some(Shout::I32Rotl)),
        Op::I32Rotr => info(op, code, Class::Numeric, 2, 1, true, Some(Shout::I32Rotr)),
        // These could later be implemented efficiently with arithmetic/remainder constraints,
        // but they stay shout-routed for now until the lookup path is actually enforced.
        Op::I32DivU => info(op, code, Class::Numeric, 2, 1, true, Some(Shout::I32DivU)),
        Op::I32DivS => info(op, code, Class::Numeric, 2, 1, true, Some(Shout::I32DivS)),
        Op::I32RemU => info(op, code, Class::Numeric, 2, 1, true, Some(Shout::I32RemU)),
        Op::I32RemS => info(op, code, Class::Numeric, 2, 1, true, Some(Shout::I32RemS)),
        Op::Select => info(op, code, Class::ControlFlow, 3, 1, false, None),
        Op::BrIf => info(op, code, Class::ControlFlow, 1, 0, false, None),
        Op::BrTable => info(op, code, Class::ControlFlow, 1, 0, false, None),
        // Call: operand-stack reads/writes are 0 here; param passing and result
        // return are tracked via call_stack_push/pop and aux param-init rows in the IR.
        Op::Call => info(op, code, Class::ControlFlow, 0, 0, false, None),
        Op::CallIndirect => info(op, code, Class::ControlFlow, 0, 0, false, None),
        Op::Return => info(op, code, Class::System, 0, 0, false, None),
        // stack_reads/writes are the operand stack effects only; local memory accesses
        // are tracked separately via local_read_value / local_write_value in the IR.
        Op::LocalGet => info(op, code, Class::System, 0, 1, false, None),
        Op::LocalSet => info(op, code, Class::System, 1, 0, false, None),
        Op::LocalTee => info(op, code, Class::System, 1, 1, false, None),
        // stack_reads/writes are the operand stack effects only; global memory accesses
        // are tracked separately via global_read_value / global_write_value in the IR.
        Op::GlobalGet => info(op, code, Class::System, 0, 1, false, None),
        Op::GlobalSet => info(op, code, Class::System, 1, 0, false, None),
        Op::Trap => info(op, code, Class::System, 0, 0, false, None),
        Op::Unsupported => info(op, code, Class::Unknown, 0, 0, false, None),
    }
}

pub fn opcode_code(op: WasmOpcode) -> u16 {
    // Canonical WebAssembly binary opcode bytes:
    // https://webassembly.github.io/spec/core/binary/instructions.html
    match op {
        WasmOpcode::Nop => 0x01,
        WasmOpcode::I32Const => 0x41,
        WasmOpcode::I64Const => 0x42,
        WasmOpcode::RefFunc => 0xD2,
        WasmOpcode::I32Add => 0x6A,
        WasmOpcode::I64Add => 0x7C,
        WasmOpcode::I32Sub => 0x6B,
        WasmOpcode::I64Sub => 0x7D,
        WasmOpcode::I32Load => 0x28,
        WasmOpcode::I32Load8S => 0x2C,
        WasmOpcode::I32Load8U => 0x2D,
        WasmOpcode::I32Load16S => 0x2E,
        WasmOpcode::I32Load16U => 0x2F,
        WasmOpcode::I64Load => 0x29,
        WasmOpcode::I32Store => 0x36,
        WasmOpcode::I32Store8 => 0x3A,
        WasmOpcode::I32Store16 => 0x3B,
        WasmOpcode::I64Store => 0x37,
        WasmOpcode::MemorySize => 0x3F,
        WasmOpcode::MemoryGrow => 0x40,
        WasmOpcode::TableSize => 0xFC10,
        WasmOpcode::TableGet => 0x25,
        WasmOpcode::TableSet => 0x26,
        WasmOpcode::Drop => 0x1A,
        WasmOpcode::Br => 0x0C,
        WasmOpcode::Block => 0x02,
        WasmOpcode::Loop => 0x03,
        WasmOpcode::If => 0x04,
        WasmOpcode::Else => 0x05,
        WasmOpcode::End => 0x0B,
        WasmOpcode::Unreachable => 0x00,
        WasmOpcode::I32Clz => 0x67,
        WasmOpcode::I32Ctz => 0x68,
        WasmOpcode::I32Popcnt => 0x69,
        WasmOpcode::I32Eqz => 0x45,
        WasmOpcode::I64Eqz => 0x50,
        WasmOpcode::I32Eq => 0x46,
        WasmOpcode::I32Ne => 0x47,
        WasmOpcode::I32LtS => 0x48,
        WasmOpcode::I32LtU => 0x49,
        WasmOpcode::I32GtS => 0x4A,
        WasmOpcode::I32GtU => 0x4B,
        WasmOpcode::I32LeS => 0x4C,
        WasmOpcode::I32LeU => 0x4D,
        WasmOpcode::I32GeS => 0x4E,
        WasmOpcode::I32GeU => 0x4F,
        WasmOpcode::I32And => 0x71,
        WasmOpcode::I32Or => 0x72,
        WasmOpcode::I32Xor => 0x73,
        WasmOpcode::I32Mul => 0x6C,
        WasmOpcode::I64And => 0x83,
        WasmOpcode::I64Or => 0x84,
        WasmOpcode::I64Xor => 0x85,
        WasmOpcode::I64Mul => 0x7E,
        WasmOpcode::I32Shl => 0x74,
        WasmOpcode::I32ShrS => 0x75,
        WasmOpcode::I32ShrU => 0x76,
        WasmOpcode::I32Rotl => 0x77,
        WasmOpcode::I32Rotr => 0x78,
        WasmOpcode::I32DivS => 0x6D,
        WasmOpcode::I32DivU => 0x6E,
        WasmOpcode::I32RemS => 0x6F,
        WasmOpcode::I32RemU => 0x70,
        WasmOpcode::Select => 0x1B,
        WasmOpcode::BrIf => 0x0D,
        WasmOpcode::BrTable => 0x0E,
        WasmOpcode::Call => 0x10,
        WasmOpcode::CallIndirect => 0x11,
        WasmOpcode::Return => 0x0F,
        WasmOpcode::LocalGet => 0x20,
        WasmOpcode::LocalSet => 0x21,
        WasmOpcode::LocalTee => 0x22,
        WasmOpcode::GlobalGet => 0x23,
        WasmOpcode::GlobalSet => 0x24,
        WasmOpcode::Trap => 0xFFFE,
        WasmOpcode::Unsupported => 0xFF,
    }
}

fn opcode_from_code(code: u16) -> WasmOpcode {
    match code {
        x if x == opcode_code(WasmOpcode::Nop) => WasmOpcode::Nop,
        x if x == opcode_code(WasmOpcode::I32Const) => WasmOpcode::I32Const,
        x if x == opcode_code(WasmOpcode::I64Const) => WasmOpcode::I64Const,
        x if x == opcode_code(WasmOpcode::RefFunc) => WasmOpcode::RefFunc,
        x if x == opcode_code(WasmOpcode::I32Add) => WasmOpcode::I32Add,
        x if x == opcode_code(WasmOpcode::I64Add) => WasmOpcode::I64Add,
        x if x == opcode_code(WasmOpcode::I32Sub) => WasmOpcode::I32Sub,
        x if x == opcode_code(WasmOpcode::I64Sub) => WasmOpcode::I64Sub,
        x if x == opcode_code(WasmOpcode::I32Load) => WasmOpcode::I32Load,
        x if x == opcode_code(WasmOpcode::I32Load8S) => WasmOpcode::I32Load8S,
        x if x == opcode_code(WasmOpcode::I32Load8U) => WasmOpcode::I32Load8U,
        x if x == opcode_code(WasmOpcode::I32Load16S) => WasmOpcode::I32Load16S,
        x if x == opcode_code(WasmOpcode::I32Load16U) => WasmOpcode::I32Load16U,
        x if x == opcode_code(WasmOpcode::I64Load) => WasmOpcode::I64Load,
        x if x == opcode_code(WasmOpcode::I32Store) => WasmOpcode::I32Store,
        x if x == opcode_code(WasmOpcode::I32Store8) => WasmOpcode::I32Store8,
        x if x == opcode_code(WasmOpcode::I32Store16) => WasmOpcode::I32Store16,
        x if x == opcode_code(WasmOpcode::I64Store) => WasmOpcode::I64Store,
        x if x == opcode_code(WasmOpcode::MemorySize) => WasmOpcode::MemorySize,
        x if x == opcode_code(WasmOpcode::MemoryGrow) => WasmOpcode::MemoryGrow,
        x if x == opcode_code(WasmOpcode::TableSize) => WasmOpcode::TableSize,
        x if x == opcode_code(WasmOpcode::TableGet) => WasmOpcode::TableGet,
        x if x == opcode_code(WasmOpcode::TableSet) => WasmOpcode::TableSet,
        x if x == opcode_code(WasmOpcode::Drop) => WasmOpcode::Drop,
        x if x == opcode_code(WasmOpcode::Br) => WasmOpcode::Br,
        x if x == opcode_code(WasmOpcode::Block) => WasmOpcode::Block,
        x if x == opcode_code(WasmOpcode::Loop) => WasmOpcode::Loop,
        x if x == opcode_code(WasmOpcode::If) => WasmOpcode::If,
        x if x == opcode_code(WasmOpcode::Else) => WasmOpcode::Else,
        x if x == opcode_code(WasmOpcode::End) => WasmOpcode::End,
        x if x == opcode_code(WasmOpcode::Unreachable) => WasmOpcode::Unreachable,
        x if x == opcode_code(WasmOpcode::I32Clz) => WasmOpcode::I32Clz,
        x if x == opcode_code(WasmOpcode::I32Ctz) => WasmOpcode::I32Ctz,
        x if x == opcode_code(WasmOpcode::I32Popcnt) => WasmOpcode::I32Popcnt,
        x if x == opcode_code(WasmOpcode::I32Eqz) => WasmOpcode::I32Eqz,
        x if x == opcode_code(WasmOpcode::I64Eqz) => WasmOpcode::I64Eqz,
        x if x == opcode_code(WasmOpcode::I32Eq) => WasmOpcode::I32Eq,
        x if x == opcode_code(WasmOpcode::I32Ne) => WasmOpcode::I32Ne,
        x if x == opcode_code(WasmOpcode::I32LtS) => WasmOpcode::I32LtS,
        x if x == opcode_code(WasmOpcode::I32LtU) => WasmOpcode::I32LtU,
        x if x == opcode_code(WasmOpcode::I32GtS) => WasmOpcode::I32GtS,
        x if x == opcode_code(WasmOpcode::I32GtU) => WasmOpcode::I32GtU,
        x if x == opcode_code(WasmOpcode::I32LeS) => WasmOpcode::I32LeS,
        x if x == opcode_code(WasmOpcode::I32LeU) => WasmOpcode::I32LeU,
        x if x == opcode_code(WasmOpcode::I32GeS) => WasmOpcode::I32GeS,
        x if x == opcode_code(WasmOpcode::I32GeU) => WasmOpcode::I32GeU,
        x if x == opcode_code(WasmOpcode::I32And) => WasmOpcode::I32And,
        x if x == opcode_code(WasmOpcode::I32Or) => WasmOpcode::I32Or,
        x if x == opcode_code(WasmOpcode::I32Xor) => WasmOpcode::I32Xor,
        x if x == opcode_code(WasmOpcode::I32Mul) => WasmOpcode::I32Mul,
        x if x == opcode_code(WasmOpcode::I64And) => WasmOpcode::I64And,
        x if x == opcode_code(WasmOpcode::I64Or) => WasmOpcode::I64Or,
        x if x == opcode_code(WasmOpcode::I64Xor) => WasmOpcode::I64Xor,
        x if x == opcode_code(WasmOpcode::I64Mul) => WasmOpcode::I64Mul,
        x if x == opcode_code(WasmOpcode::I32Shl) => WasmOpcode::I32Shl,
        x if x == opcode_code(WasmOpcode::I32ShrU) => WasmOpcode::I32ShrU,
        x if x == opcode_code(WasmOpcode::I32ShrS) => WasmOpcode::I32ShrS,
        x if x == opcode_code(WasmOpcode::I32Rotl) => WasmOpcode::I32Rotl,
        x if x == opcode_code(WasmOpcode::I32Rotr) => WasmOpcode::I32Rotr,
        x if x == opcode_code(WasmOpcode::I32DivU) => WasmOpcode::I32DivU,
        x if x == opcode_code(WasmOpcode::I32DivS) => WasmOpcode::I32DivS,
        x if x == opcode_code(WasmOpcode::I32RemU) => WasmOpcode::I32RemU,
        x if x == opcode_code(WasmOpcode::I32RemS) => WasmOpcode::I32RemS,
        x if x == opcode_code(WasmOpcode::Select) => WasmOpcode::Select,
        x if x == opcode_code(WasmOpcode::BrIf) => WasmOpcode::BrIf,
        x if x == opcode_code(WasmOpcode::BrTable) => WasmOpcode::BrTable,
        x if x == opcode_code(WasmOpcode::Call) => WasmOpcode::Call,
        x if x == opcode_code(WasmOpcode::CallIndirect) => WasmOpcode::CallIndirect,
        x if x == opcode_code(WasmOpcode::Return) => WasmOpcode::Return,
        x if x == opcode_code(WasmOpcode::LocalGet) => WasmOpcode::LocalGet,
        x if x == opcode_code(WasmOpcode::LocalSet) => WasmOpcode::LocalSet,
        x if x == opcode_code(WasmOpcode::LocalTee) => WasmOpcode::LocalTee,
        x if x == opcode_code(WasmOpcode::GlobalGet) => WasmOpcode::GlobalGet,
        x if x == opcode_code(WasmOpcode::GlobalSet) => WasmOpcode::GlobalSet,
        x if x == opcode_code(WasmOpcode::Trap) => WasmOpcode::Trap,
        _ => WasmOpcode::Unsupported,
    }
}

fn info(
    opcode: WasmOpcode,
    code: u16,
    class: WasmOpcodeClass,
    stack_reads: u8,
    stack_writes: u8,
    uses_shout: bool,
    shout_opcode: Option<WasmShoutOpcode>,
) -> WasmOpcodeInfo {
    WasmOpcodeInfo {
        opcode,
        code,
        name: opcode.name(),
        class,
        stack_reads,
        stack_writes,
        uses_shout,
        shout_opcode,
    }
}
