import Nightstream.Implementation.Nebula.Production.FPrime.Lifetime.CompactChainLifetimeFor

/-! Regression surface for exact compact-chain extraction over the full
delayed F-prime lifetime. -/

set_option autoImplicit false

namespace tests.NebulaProductionPaperCompactChainLifetimeFor

open Nightstream.Implementation.Nebula.ProductionPaperCompactChainLifetimeFor

#check ClaimLifetime.LaneStepExact
#check ClaimLifetime.HeadersExact
#check ClaimLifetime.ClaimExact
#check ClaimLifetime.LaneStepExact.ofRows
#check ClaimLifetime.LaneStepExact.after_eq_next
#check ClaimLifetime.PrecommitLane
#check ClaimLifetime.HeadersExact.lane_root_eq_hash_header
#check ClaimLifetime.ClaimExact.laneStep_of_suffix
#check ClaimLifetime.recursive_claim_exact
#check ClaimLifetime.terminal_claim_exact
#check ClaimLifetime.base_headers_exact
#check ClaimLifetime.Schedule.everyReceiptExact
#check ClaimLifetime.Schedule.everyClaimExact
#check ClaimLifetime.Schedule.candidateExact
#check ClaimLifetime.Lifetime.compactExact
#check RootRun
#check rootRun_of_consumes_to_closed
#check ClaimLifetime.SegmentExact
#check ClaimLifetime.VerifiedBundleSequence
#check ClaimLifetime.VerifiedBundleSequence.length_exact
#check ClaimLifetime.VerifiedBundleSequence.pairedBundles
#check ClaimLifetime.VerifiedBundleSequence.pairedBundles_get_fst
#check ClaimLifetime.VerifiedBundleSequence.CanonicallyIndexed
#check ClaimLifetime.VerifiedBundleSequence.commitmentVector
#check ClaimLifetime.VerifiedBundleSequence.framedSequence
#check ClaimLifetime.VerifiedBundleSequence.ofFn_commitmentVector_eq
#check ClaimLifetime.VerifiedBundleSequence.chainRoot_framedSequence
#check ClaimLifetime.VerifiedBundleSequence.pairedBundles_canonicallyIndexed
#check ClaimLifetime.VerifiedBundleSequence.run_eq_root
#check ClaimLifetime.VerifiedBundleSequence.of_claims
#check ClaimLifetime.SegmentPrecommitExact
#check ClaimLifetime.SegmentPrecommitExact.laneBundles
#check ClaimLifetime.SegmentPrecommitExact.suffix_step_at
#check ClaimLifetime.SegmentPrecommitExact.laneBundles_canonicallyIndexed
#check ClaimLifetime.SegmentPrecommitExact.laneSequence
#check ClaimLifetime.SegmentPrecommitExact.knownPrecommit
#check ClaimLifetime.SegmentPrecommitExact.knownPrecommit_root
#check ClaimLifetime.SegmentPrecommitExact.knownPrecommit_correct
#check ClaimLifetime.SegmentExact.precommitExact
#check ClaimLifetime.segment_exact
#check ClaimLifetime.ChainExact
#check ClaimLifetime.ChainExact.ofRows
#check ClaimLifetime.PrecommitChainExact
#check ClaimLifetime.ChainExact.precommitExact
#check SemanticLifetime.LifetimeExtraction.compactChain
#check SemanticLifetime.LifetimeExtraction.precommitChain

end tests.NebulaProductionPaperCompactChainLifetimeFor
