import DirectCcsFPrime.ProofSystem.Production.Impl.SuperNeoReuse.DirectParentOnlyProductionSuperNeoReusePriorOpening

/-!
Typed interface for compressed-prior openings over the Section 7.1-backed
parent-only production context.

Spec: `specs/ProofSystem/Production/Impl/SuperNeoReuse/DirectParentOnlyProductionSuperNeoReusePriorOpening.spec.md`
-/

namespace DirectCcsFPrime

namespace DirectParentOnlyProductionSuperNeoReusePriorOpeningInterface

abbrev ProductionContext :=
  DirectParentOnlyProductionSuperNeoReusePriorOpening.ProductionContext

abbrev PriorAuthorityOpener :=
  @DirectParentOnlyProductionSuperNeoReusePriorOpening.PriorAuthorityOpener

abbrev VerifyWithAuthorityOpener :=
  @DirectParentOnlyProductionSuperNeoReusePriorOpening.VerifyWithAuthorityOpener

abbrev PriorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionSuperNeoReusePriorOpening.PriorVerifierAuthorityOpening

abbrev AcceptedTerminalWithAuthorityOpener :=
  @DirectParentOnlyProductionSuperNeoReusePriorOpening.AcceptedTerminalWithAuthorityOpener

abbrev AcceptedTerminalWithPriorVerifier :=
  @DirectParentOnlyProductionSuperNeoReusePriorOpening.AcceptedTerminalWithPriorVerifier

abbrev soundVerifier_of_authority_opener :=
  @DirectParentOnlyProductionSuperNeoReusePriorOpening.soundVerifier_of_authority_opener

abbrev soundVerifier_of_priorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionSuperNeoReusePriorOpening.soundVerifier_of_priorVerifierAuthorityOpening

abbrev proofFunctional_of_authority_opener :=
  @DirectParentOnlyProductionSuperNeoReusePriorOpening.proofFunctional_of_authority_opener

abbrev soundVerifier_of_authority_opener_proofFunctional :=
  @DirectParentOnlyProductionSuperNeoReusePriorOpening.soundVerifier_of_authority_opener_proofFunctional

abbrev proofFunctional_of_priorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionSuperNeoReusePriorOpening.proofFunctional_of_priorVerifierAuthorityOpening

abbrev soundVerifier_of_priorVerifierAuthorityOpening_proofFunctional :=
  @DirectParentOnlyProductionSuperNeoReusePriorOpening.soundVerifier_of_priorVerifierAuthorityOpening_proofFunctional

abbrev verifyWithAuthorityOpener_openAuthority_ne_none :=
  @DirectParentOnlyProductionSuperNeoReusePriorOpening.verifyWithAuthorityOpener_openAuthority_ne_none

abbrev verifyWithAuthorityOpener_opened_authority_accepts_of_open :=
  @DirectParentOnlyProductionSuperNeoReusePriorOpening.verifyWithAuthorityOpener_opened_authority_accepts_of_open

abbrev authority_opener_reaches_prior :=
  @DirectParentOnlyProductionSuperNeoReusePriorOpening.authority_opener_reaches_prior

abbrev authority_opener_cannot_accept_unreachable_prior :=
  @DirectParentOnlyProductionSuperNeoReusePriorOpening.authority_opener_cannot_accept_unreachable_prior

abbrev priorVerifierAuthorityOpening_opened_authority :=
  @DirectParentOnlyProductionSuperNeoReusePriorOpening.priorVerifierAuthorityOpening_opened_authority

abbrev priorVerifierAuthorityOpening_openAuthority_ne_none :=
  @DirectParentOnlyProductionSuperNeoReusePriorOpening.priorVerifierAuthorityOpening_openAuthority_ne_none

abbrev priorVerifierAuthorityOpening_opened_authority_accepts_of_open :=
  @DirectParentOnlyProductionSuperNeoReusePriorOpening.priorVerifierAuthorityOpening_opened_authority_accepts_of_open

abbrev priorVerifierAuthorityOpening_reaches_prior :=
  @DirectParentOnlyProductionSuperNeoReusePriorOpening.priorVerifierAuthorityOpening_reaches_prior

abbrev priorVerifierAuthorityOpening_cannot_accept_unreachable_prior :=
  @DirectParentOnlyProductionSuperNeoReusePriorOpening.priorVerifierAuthorityOpening_cannot_accept_unreachable_prior

abbrev audited_public_endpoint_with_stage_audit_of_authority_opener :=
  @DirectParentOnlyProductionSuperNeoReusePriorOpening.audited_public_endpoint_with_stage_audit_of_authority_opener

abbrev audited_public_endpoint_with_stage_audit_of_priorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionSuperNeoReusePriorOpening.audited_public_endpoint_with_stage_audit_of_priorVerifierAuthorityOpening

abbrev terminal_prior_pair_functional_for_same_proof_of_authority_opener :=
  @DirectParentOnlyProductionSuperNeoReusePriorOpening.terminal_prior_pair_functional_for_same_proof_of_authority_opener

abbrev terminal_prior_pair_functional_for_same_proof_of_priorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionSuperNeoReusePriorOpening.terminal_prior_pair_functional_for_same_proof_of_priorVerifierAuthorityOpening

abbrev terminal_next_image_functional_for_same_proof_of_authority_opener :=
  @DirectParentOnlyProductionSuperNeoReusePriorOpening.terminal_next_image_functional_for_same_proof_of_authority_opener

abbrev terminal_next_image_functional_for_same_proof_of_priorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionSuperNeoReusePriorOpening.terminal_next_image_functional_for_same_proof_of_priorVerifierAuthorityOpening

end DirectParentOnlyProductionSuperNeoReusePriorOpeningInterface

end DirectCcsFPrime
