import DirectCcsFPrime.ProofSystem.Production.Impl.SuperNeoReuse.DirectParentOnlyProductionSuperNeoReuse

/-!
Typed interface for the Section 7.1-backed parent-only production context.

Spec: `specs/ProofSystem/Production/Impl/SuperNeoReuse/DirectParentOnlyProductionSuperNeoReuse.spec.md`
-/

namespace DirectCcsFPrime

namespace DirectParentOnlyProductionSuperNeoReuseInterface

abbrev ProductionContext :=
  DirectParentOnlyProductionSuperNeoReuse.ProductionContext

abbrev toProductionContext :=
  @DirectParentOnlyProductionSuperNeoReuse.ProductionContext.toProductionContext

abbrev SoundPriorVerifier :=
  @DirectParentOnlyProductionSuperNeoReuse.ProductionContext.SoundPriorVerifier

abbrev AcceptedTerminal :=
  @DirectParentOnlyProductionSuperNeoReuse.ProductionContext.AcceptedTerminal

abbrev AlternateLatestStep :=
  @DirectParentOnlyProductionSuperNeoReuse.ProductionContext.AlternateLatestStep

abbrev AuditedPublicEndpointWithStageAudit :=
  @DirectParentOnlyProductionSuperNeoReuse.ProductionContext.AuditedPublicEndpointWithStageAudit

abbrev Section71StageTargetAudit :=
  @DirectParentOnlyProductionSuperNeoReuse.ProductionContext.Section71StageTargetAudit

abbrev TerminalSection71StageTargetAuditTrail :=
  @DirectParentOnlyProductionSuperNeoReuse.ProductionContext.TerminalSection71StageTargetAuditTrail

abbrev piCCSStrong_of_compute :=
  @DirectParentOnlyProductionSuperNeoReuse.ProductionContext.piCCSStrong_of_compute

abbrev piRLCWeak_of_compute :=
  @DirectParentOnlyProductionSuperNeoReuse.ProductionContext.piRLCWeak_of_compute

abbrev piDECKnowledge_of_piCCS_compute :=
  @DirectParentOnlyProductionSuperNeoReuse.ProductionContext.piDECKnowledge_of_piCCS_compute

abbrev piDECKnowledge_of_piRLC_compute :=
  @DirectParentOnlyProductionSuperNeoReuse.ProductionContext.piDECKnowledge_of_piRLC_compute

abbrev section71_stage_target_audit_of_parent_source_stage_audit :=
  @DirectParentOnlyProductionSuperNeoReuse.ProductionContext.section71_stage_target_audit_of_parent_source_stage_audit

abbrev terminal_section71_stage_target_audit_trail_of_audited_public_endpoint :=
  @DirectParentOnlyProductionSuperNeoReuse.ProductionContext.terminal_section71_stage_target_audit_trail_of_audited_public_endpoint

abbrev audited_public_endpoint_with_stage_audit_of_sound_verifier :=
  @DirectParentOnlyProductionSuperNeoReuse.ProductionContext.audited_public_endpoint_with_stage_audit_of_sound_verifier

abbrev terminal_section71_stage_target_audit_trail_of_sound_verifier :=
  @DirectParentOnlyProductionSuperNeoReuse.ProductionContext.terminal_section71_stage_target_audit_trail_of_sound_verifier

end DirectParentOnlyProductionSuperNeoReuseInterface

end DirectCcsFPrime
