//! Compact selective-row renderer for the selected projection certificate.
//!
//! Owns: deterministic serialization of the 14 stage leaves and 139 interval
//! fragments already validated by the compiler audit.
//!
//! Does not own: rewrite semantics, matrices, column ownership, or authority.
//!
//! Emits constraints: no.
//!
//! | Payload | Count |
//! |---|---:|
//! | source stage leaves | 14 |
//! | lowering fragments | 139 |
//! | emitted selective rows | 1,254 |

use std::fmt::Write as _;
use std::ops::Range;

use neo_fold_clean::frontends::r1cs_f_prime::ivc::{
    PiRlcYZcolProjectionLoweringDisposition, PiRlcYZcolProjectionRowMappingAudit,
};
use neo_fold_clean::frontends::r1cs_f_prime::SelectiveRewriteKind;

use super::GeneratedLeanFile;

const GENERATED_PATH: &str =
    "formal/nightstream-lean/Nightstream/Implementation/R1CS/Artifacts/FPrimeSelectiveFixedPoint/PiRlcProjection/YZcol/Generated/SelectiveRows.lean";
const IMPORT_ROOT: &str =
    "Nightstream.Implementation.R1CS.Artifacts.FPrimeSelectiveFixedPoint.PiRlcProjection.YZcol.Selective.Schema";
const NAMESPACE: &str =
    "Nightstream.Implementation.R1CS.FPrimeSelectiveFixedPoint.PiRlcProjection.YZcol.Generated.SelectiveRows";

fn lean_range(rows: Range<usize>) -> String {
    format!("{{ start := {}, stop := {} }}", rows.start, rows.end)
}

fn lean_ranges(ranges: &[Range<usize>]) -> String {
    format!(
        "[{}]",
        ranges
            .iter()
            .cloned()
            .map(lean_range)
            .collect::<Vec<_>>()
            .join(", ")
    )
}

fn lean_disposition(disposition: PiRlcYZcolProjectionLoweringDisposition) -> String {
    match disposition {
        PiRlcYZcolProjectionLoweringDisposition::Retained => ".retained".to_owned(),
        PiRlcYZcolProjectionLoweringDisposition::Rewrite { id, kind } => {
            let kind = match kind {
                SelectiveRewriteKind::PolynomialEvaluation => ".polynomialEvaluation",
                SelectiveRewriteKind::ProductSum => ".productSum",
                SelectiveRewriteKind::LinearDefinition => ".linearDefinition",
                other => unreachable!("validated projection rewrite kind {other:?}"),
            };
            format!(".rewrite {} {kind}", id.index())
        }
    }
}

pub(super) fn render(audit: &PiRlcYZcolProjectionRowMappingAudit) -> GeneratedLeanFile {
    assert_eq!(audit.leaves().len(), 14, "exact stage-leaf count");
    assert_eq!(
        audit
            .leaves()
            .iter()
            .map(|leaf| leaf.fragments().len())
            .sum::<usize>(),
        139,
        "exact lowering-fragment count"
    );
    assert_eq!(audit.source_row_count(), 5_724, "selected source-row count");
    assert_eq!(audit.emitted_row_count(), 1_254, "selected emitted-row count");

    let mut contents = String::new();
    writeln!(contents, "import {IMPORT_ROOT}\n").expect("render import");
    contents.push_str(
        "/-! Generated by `active_selective_fixed_point_projection_artifact_matches_retained_certificate`; do not hand-edit.\n\n",
    );
    contents.push_str(
        "Owns: exact compact source-to-selective interval ownership for the 14 selected projection stage leaves.\n\n",
    );
    contents.push_str(
        "Does not own: rewrite semantics, final matrix coefficients, column ownership, selector truth, transcript authority, or row removal.\n\n",
    );
    contents.push_str("Emits constraints: no.\n\n");
    contents
        .push_str("| Source rows | Selective rows | Fragments |\n|---:|---:|---:|\n| 5,724 | 1,254 | 139 |\n-/\n\n");
    writeln!(contents, "namespace {NAMESPACE}\n").expect("render namespace");
    contents.push_str("def artifact : Selective.Artifact :=\n");
    writeln!(
        contents,
        "  {{ sourceArmRowCount := {},\n    finalRelationRowCount := {},\n    steadyArmRows := {},\n    leaves :=\n    [",
        audit.source_arm_row_count(),
        audit.final_relation_row_count(),
        lean_range(audit.steady_arm_rows())
    )
    .expect("render artifact header");
    for (leaf_index, leaf) in audit.leaves().iter().enumerate() {
        if leaf_index != 0 {
            contents.push(',');
        }
        writeln!(
            contents,
            "{{ stagePath := \"{}\",\n       sourceRows := {},\n       fragments :=\n       [",
            leaf.stage_path(),
            lean_ranges(leaf.source_rows())
        )
        .expect("render stage leaf");
        for (fragment_index, fragment) in leaf.fragments().iter().enumerate() {
            if fragment_index != 0 {
                contents.push_str("        ,");
            }
            writeln!(
                contents,
                "{{ sourceRows := {}, emittedRows := {}, disposition := {} }}",
                lean_ranges(fragment.source_rows()),
                lean_range(fragment.emitted_rows()),
                lean_disposition(fragment.disposition())
            )
            .expect("render selective fragment");
        }
        contents.push_str("       ] }\n");
    }
    contents.push_str("    ] }\n\n");
    writeln!(contents, "end {NAMESPACE}").expect("render namespace end");
    GeneratedLeanFile {
        relative_path: GENERATED_PATH.to_owned(),
        contents,
    }
}
