//! Stable-stage renderer for the selected cross-branch projection certificate.
//!
//! Owns: exact export of the 14 Rust source-stage leaf paths consumed by the
//! handwritten Lean ownership schema.
//!
//! Does not own: row equations, counts, selective lowering, or semantics.
//!
//! Emits constraints: no.
//!
//! | Branch | Leaves |
//! |---|---:|
//! | `projection_shared` | 2 |
//! | `identities.y_zcol.limb0` | 6 |
//! | `identities.y_zcol.limb1` | 6 |

use std::collections::HashSet;
use std::fmt::Write as _;

use neo_fold_clean::paper::reductions::pi_rlc_circuit::stage;

use super::GeneratedLeanFile;

const GENERATED_PATH: &str =
    "formal/nightstream-lean/Nightstream/Implementation/R1CS/Artifacts/FPrimeSelectiveFixedPoint/PiRlcProjection/YZcol/Generated/StagePaths.lean";
const IMPORT_ROOT: &str =
    "Nightstream.Implementation.R1CS.Artifacts.FPrimeSelectiveFixedPoint.PiRlcProjection.YZcol.Schema";
const NAMESPACE: &str =
    "Nightstream.Implementation.R1CS.FPrimeSelectiveFixedPoint.PiRlcProjection.YZcol.Generated.StagePaths";

fn limb_paths(limb: usize) -> [&'static str; 6] {
    match limb {
        0 => [
            stage::IDENTITIES_Y_ZCOL_EVALUATIONS_INPUTS_LIMB0,
            stage::IDENTITIES_Y_ZCOL_K_PRODUCTS_RHO_TIMES_INPUT_LIMB0,
            stage::IDENTITIES_Y_ZCOL_EVALUATIONS_OUTPUT_LIMB0,
            stage::IDENTITIES_Y_ZCOL_EVALUATIONS_QUOTIENT_LIMB0,
            stage::IDENTITIES_Y_ZCOL_K_PRODUCTS_QUOTIENT_TIMES_PHI_LIMB0,
            stage::IDENTITIES_Y_ZCOL_FINAL_LIMB_CHECKS_LIMB0,
        ],
        1 => [
            stage::IDENTITIES_Y_ZCOL_EVALUATIONS_INPUTS_LIMB1,
            stage::IDENTITIES_Y_ZCOL_K_PRODUCTS_RHO_TIMES_INPUT_LIMB1,
            stage::IDENTITIES_Y_ZCOL_EVALUATIONS_OUTPUT_LIMB1,
            stage::IDENTITIES_Y_ZCOL_EVALUATIONS_QUOTIENT_LIMB1,
            stage::IDENTITIES_Y_ZCOL_K_PRODUCTS_QUOTIENT_TIMES_PHI_LIMB1,
            stage::IDENTITIES_Y_ZCOL_FINAL_LIMB_CHECKS_LIMB1,
        ],
        _ => unreachable!("two-limb projection certificate"),
    }
}

fn render_limb(contents: &mut String, limb: usize) {
    let [inputs, products, output, quotient, quotient_phi, checks] = limb_paths(limb);
    writeln!(
        contents,
        "      {{ inputEvaluations := \"{inputs}\",\n        rhoTimesInput := \"{products}\",\n        outputEvaluation := \"{output}\",\n        quotientEvaluation := \"{quotient}\",\n        quotientTimesPhi := \"{quotient_phi}\",\n        finalChecks := \"{checks}\" }}{}",
        if limb == 0 { "," } else { "" }
    )
    .expect("render limb stage paths");
}

pub(super) fn render() -> GeneratedLeanFile {
    let mut paths = vec![
        stage::PROJECTION_SHARED_BETA_LADDER,
        stage::PROJECTION_SHARED_RHO_EVALUATIONS,
    ];
    paths.extend(limb_paths(0));
    paths.extend(limb_paths(1));
    assert_eq!(paths.len(), 14, "exact physical stage-leaf count");
    assert_eq!(
        paths.iter().copied().collect::<HashSet<_>>().len(),
        paths.len(),
        "physical stage paths must be unique"
    );

    let mut contents = String::new();
    writeln!(contents, "import {IMPORT_ROOT}\n").expect("render import");
    contents.push_str(
        "/-! Generated by `active_selective_fixed_point_projection_artifact_matches_retained_certificate`; do not hand-edit.\n\n",
    );
    contents.push_str(
        "Owns: exact stable Rust stage paths for the 14 source-R1CS leaves in the selected cross-branch certificate.\n\n",
    );
    contents.push_str(
        "Does not own: equations, source-row counts, fresh columns, selective lowering, costs, or semantics.\n\n",
    );
    contents.push_str("Emits constraints: no.\n\n");
    contents.push_str(
        "| Branch | Leaf count |\n|---|---:|\n| `nifs.pi_rlc.verify.projection_shared` | 2 |\n| `nifs.pi_rlc.verify.identities.y_zcol` | 12 |\n-/\n\n",
    );
    writeln!(contents, "namespace {NAMESPACE}\n").expect("render namespace");
    writeln!(contents, "def paths : SourceStagePaths :=").expect("render definition");
    writeln!(
        contents,
        "  {{ shared :=\n      {{ betaLadder := \"{}\",\n        rhoEvaluations := \"{}\" }},\n    limbs :=\n    [",
        stage::PROJECTION_SHARED_BETA_LADDER,
        stage::PROJECTION_SHARED_RHO_EVALUATIONS
    )
    .expect("render shared stage paths");
    render_limb(&mut contents, 0);
    render_limb(&mut contents, 1);
    contents.push_str("    ] }\n\n");
    writeln!(contents, "end {NAMESPACE}").expect("render namespace end");

    GeneratedLeanFile {
        relative_path: GENERATED_PATH.to_owned(),
        contents,
    }
}
