import Nightstream.Implementation.Nebula.NIFS.PiRLC.AlgebraSoundFor

set_option autoImplicit false

namespace tests.NebulaProductPiRlcAlgebraSoundFor

open Nightstream.Implementation.Nebula.ProductPiRlcAlgebraSoundFor

#check decodeInputPublic_eq_reference
#check decodeInputEvaluations_eq_reference
#check typedEquations_of_rows

end tests.NebulaProductPiRlcAlgebraSoundFor
