import Nightstream.Implementation.Nebula.NIFS.PiRLC.TranscriptSemantics

/-! Regression surface for the exact V2 PiRLC candidate transcript. -/

set_option autoImplicit false

namespace tests.NebulaProductPiRlcTranscriptSemantics

#check Nightstream.Implementation.Nebula.ProductPiRlcTranscriptRows.CandidateIndex.flat_injective
#check Nightstream.Implementation.Nebula.ProductPiRlcTranscriptRows.candidateFields_injective
#check Nightstream.Implementation.Nebula.ProductPiRlcTranscriptRows.aggregateRowCount_eq
#check Nightstream.Implementation.Nebula.ProductPiRlcTranscriptRows.candidate_windows_disjoint
#check Nightstream.Implementation.Nebula.ProductPiRlcTranscriptSemantics.candidate_rows_sound
#check Nightstream.Implementation.Nebula.ProductPiRlcTranscriptSemantics.all_candidates_sound

end tests.NebulaProductPiRlcTranscriptSemantics
