//! Exact Lean artifacts for the production SIS field encoding.
//!
//! Owns: deterministic generation and drift checks for the canonical source
//! fixture and its isolated gadget-native shared-slot lowering.
//!
//! Does not own: shifted-ternary semantics, row-removal proofs, or SIS
//! commitment binding.
//!
//! Emits constraints: no. It executes the production builders and records
//! their checked structure.
//!
//! Authority boundary: the shared-slot artifact is rendered only after the
//! runtime reader validates the exact CCS gate polynomial, matrices, aliases,
//! 123 logical retained obligations, 103 physical rows, and 123 omitted
//! obligations. Generated bytes are evidence, not authority by themselves.
//!
//! | Child artifact | Mathematical content | Emits constraints? | Rust owner | Lean owner |
//! |---|---|---:|---|---|
//! | shifted-ternary source | all 124 canonical rows plus one Phi81 coordinate | no | `render` | `ShiftedTernarySound` |
//! | shared-slot production | exact 20 residual-pair rows, one ordinary tail, 82 product rows, polynomial terms, and aliases | no | `render_shared_slots` | `ShiftedTernarySharedSlots` |

#[path = "lean_artifact_support.rs"]
mod lean_artifact_support;

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use lean_artifact_support::{lean_nat_list, lean_rows, lean_witness, sha256_hex, SCHEMA_VERSION};
use neo_ajtai::commit_row_major_seeded;
use neo_ccs::{Mat, SparsePoly};
use neo_fold_clean::engine::r1cs_circuit::{R1csBuilder, Var};
use neo_fold_clean::frontends::f_prime::gadget_native::{
    encode_r1cs_gadget_native, BalancedTernarySharedSlotPlan, GadgetNativeCenteredFamily, GadgetNativeConstraintRow,
    GadgetNativeCoordinateGateRoles as Roles, GadgetNativeCoordinateRowAudit,
};
use neo_fold_clean::frontends::r1cs_f_prime::{
    build_multi_branch_selective_low_norm_r1cs_with_alignment, lower_field_r1cs, SelectiveEmittedRowFamily,
    SelectiveRowArtifact,
};
use neo_fold_clean::paper::reductions::accumulator_sis_circuit::{enforce_commit_fields, SisAccumulatorConfig};
use neo_math::{D, F};
use p3_field::{PrimeCharacteristicRing, PrimeField64};

const CONFIG: SisAccumulatorConfig = SisAccumulatorConfig {
    seed: [0xA7; 32],
    kappa: 1,
    domain: 0x5349_5354_4553_5431,
};
const SAMPLE: u64 = F::ORDER_U64 / 2;
const ARTIFACT_REL_PATH: &str =
    "/../../formal/nightstream-lean/Nightstream/Implementation/R1CS/Artifacts/ShiftedTernary/Generated/ShiftedTernaryArtifact.lean";
const SHARED_SLOTS_ARTIFACT_REL_PATH: &str =
    "/../../formal/nightstream-lean/Nightstream/Implementation/R1CS/Artifacts/ShiftedTernary/Generated/ShiftedTernarySharedSlotsArtifact.lean";
const SELECTIVE_ARTIFACT_REL_PATH: &str =
    "/../../formal/nightstream-lean/Nightstream/Implementation/R1CS/Artifacts/ShiftedTernary/Generated/ShiftedTernarySelectiveArtifact.lean";
const SHARED_SLOTS_SCHEMA_VERSION: u64 = 3;
const SELECTIVE_SCHEMA_VERSION: u64 = 1;
// Independent artifact-side copy of the four production gate coordinates.
// The runtime row reader also checks these against the concrete CCS
// polynomial before returning any row to this generator.
const PRODUCTION_POLYNOMIAL_ARITY: usize = 56;
const SELECTOR_MATRIX: usize = 0;
const CENTERED_UNIT_MATRIX: usize = 2;
const PRODUCT_LEFT_MATRIX: usize = 3;
const PRODUCT_RIGHT_MATRIX: usize = 21;
const PRODUCT_OUT_MATRIX: usize = 39;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
struct CenteredPairRow {
    row: usize,
    left: usize,
    right: usize,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
struct CenteredTailRow {
    row: usize,
    column: usize,
}

fn build(value: u64) -> (R1csBuilder, Var, Vec<Var>) {
    let mut builder = R1csBuilder::new();
    builder.enable_encoding_trace();
    let field = builder.alloc(F::from_u64(value));
    let commitment = enforce_commit_fields(&mut builder, CONFIG, &[field]).expect("one-field SIS commitment");
    (builder, field, commitment.data)
}

fn forged() -> R1csBuilder {
    let (mut builder, field, commitment_columns) = build(SAMPLE);
    let modulus = F::ORDER_U64 as u128;
    let shift = (3u128.pow(41) - 1) / 2;
    let canonical_n = (SAMPLE as u128 + shift) % modulus;
    let mut remaining = canonical_n + modulus;
    assert!(remaining < 3u128.pow(41));
    let digits: [F; 41] = core::array::from_fn(|_| {
        let trit = remaining % 3;
        remaining /= 3;
        match trit {
            0 => -F::ONE,
            1 => F::ZERO,
            2 => F::ONE,
            _ => unreachable!("base-3 digit"),
        }
    });
    assert_eq!(remaining, 0);

    let digit_columns = builder
        .balanced_ternary_digit_columns(field)
        .expect("balanced ternary audit");
    let negative_start = digit_columns[40] + 1;
    let borrow_start = negative_start + 41;
    for (index, (&column, &digit)) in digit_columns.iter().zip(&digits).enumerate() {
        builder.tamper_witness(column, digit);
        builder.tamper_witness(negative_start + index, if digit == -F::ONE { F::ONE } else { F::ZERO });
    }

    let mut bound = F::ORDER_U64 - 1;
    let mut borrow = false;
    for (index, &digit) in digits.iter().enumerate() {
        let trit = if digit == -F::ONE {
            0
        } else if digit == F::ZERO {
            1
        } else {
            2
        };
        let next = trit + u64::from(borrow) > bound % 3;
        bound /= 3;
        if index + 1 < 41 {
            builder.tamper_witness(borrow_start + index, if next { F::ONE } else { F::ZERO });
        } else {
            assert!(next);
        }
        borrow = next;
    }

    let mut message = Mat::zero(D, 1, F::ZERO);
    for (row, digit) in digits.into_iter().enumerate() {
        message[(row, 0)] = digit;
    }
    let forged_commitment = commit_row_major_seeded(CONFIG.seed, D, CONFIG.kappa, 1, &message);
    for (column, value) in commitment_columns.iter().zip(forged_commitment.data) {
        builder.tamper_witness(column.col(), value);
    }
    builder
}

fn lean_seed_rows(rows: &[Vec<[u8; 32]>]) -> String {
    let rows = rows
        .iter()
        .map(|chunks| {
            let chunks = chunks
                .iter()
                .map(|seed| {
                    let bytes = seed.iter().map(u8::to_string).collect::<Vec<_>>();
                    format!("[{}]", bytes.join(", "))
                })
                .collect::<Vec<_>>();
            format!("[{}]", chunks.join(", "))
        })
        .collect::<Vec<_>>();
    format!("[{}]", rows.join(", "))
}

fn render(builder: &R1csBuilder, field: Var, commitment: &[Var], forged_witness: &[F]) -> String {
    let digit_columns = builder
        .balanced_ternary_digit_columns(field)
        .expect("balanced ternary audit");
    let negative_columns = (digit_columns[40] + 1..digit_columns[40] + 42).collect::<Vec<_>>();
    let borrow_columns = (digit_columns[40] + 42..digit_columns[40] + 82).collect::<Vec<_>>();
    let block = builder
        .seeded_phi81_a_blocks()
        .first()
        .expect("one seeded Phi81 block");
    assert_eq!(builder.seeded_phi81_a_blocks().len(), 1);
    assert_eq!(block.row_end(), builder.rows());
    let payload = format!(
        "def fieldCol : Nat := {}\n\
         def commitmentDCol : Nat := 2\n\
         def commitmentKappaCol : Nat := 3\n\
         def commitmentCols : List Nat := {}\n\
         def commitmentBlock : SeededPhi81.Block :=\n\
         \x20\x20{{ rowStart := {}\n\
         \x20\x20\x20\x20wordStarts := {}\n\
         \x20\x20\x20\x20wordWidth := {}\n\
         \x20\x20\x20\x20kappa := {}\n\
         \x20\x20\x20\x20messageCols := {}\n\
         \x20\x20\x20\x20outputColumns := {}\n\
         \x20\x20\x20\x20superneoTransformedColumns := {}\n\
         \x20\x20\x20\x20schedule :=\n\
         \x20\x20\x20\x20\x20\x20{{ chunkSize := {}\n\
         \x20\x20\x20\x20\x20\x20\x20\x20seedsByOutput := {}\n\
         \x20\x20\x20\x20\x20\x20\x20\x20rejectionFuel := 16 }} }}\n\
         def digitCols : List Nat := {}\n\
         def negativeCols : List Nat := {}\n\
         def borrowCols : List Nat := {}\n\
         def rowCount : Nat := {}\n\
         def colCount : Nat := {}\n\
         def rows : List Row :=\n  {}\n\n\
         {}\n\
         {}",
        field.col(),
        lean_nat_list(commitment.iter().map(|column| column.col())),
        block.row_start(),
        lean_nat_list(block.word_starts().iter().copied()),
        block.word_width(),
        block.kappa(),
        block.message_cols(),
        lean_nat_list(commitment.iter().map(|column| column.col())),
        block.has_superneo_transformed_columns(),
        block.chunk_size(),
        lean_seed_rows(block.chunk_seeds_by_row()),
        lean_nat_list(digit_columns),
        lean_nat_list(negative_columns),
        lean_nat_list(borrow_columns),
        builder.rows(),
        builder.cols(),
        lean_rows(builder),
        lean_witness("honestWitness", builder.witness()),
        lean_witness("forgedWitness", forged_witness),
    );
    let mut rendered = String::new();
    rendered.push_str("import Nightstream.Implementation.R1CS.Core.SeededPhi81\n\n");
    rendered.push_str("/-! Generated exact one-field shifted-base-3/SIS artifact. Do not hand-edit. -/\n\n");
    rendered.push_str("namespace Nightstream.Implementation.R1CS.ShiftedTernary\n\n");
    writeln!(rendered, "def schemaVersion : Nat := {SCHEMA_VERSION}").expect("render");
    writeln!(rendered, "def payloadSha256 : String := \"{}\"", sha256_hex(&payload)).expect("render");
    rendered.push_str(&payload);
    rendered.push_str("\n\nend Nightstream.Implementation.R1CS.ShiftedTernary\n");
    rendered
}

fn lean_field_terms(terms: &[(usize, F)]) -> String {
    let terms = terms
        .iter()
        .map(|&(column, coefficient)| format!("({column}, {})", coefficient.as_canonical_u64()))
        .collect::<Vec<_>>();
    format!("[{}]", terms.join(", "))
}

fn lean_centered_pair_rows(rows: &[CenteredPairRow]) -> String {
    let rows = rows
        .iter()
        .map(|row| format!("({}, {}, {})", row.row, row.left, row.right))
        .collect::<Vec<_>>();
    format!("[{}]", rows.join(", "))
}

fn lean_centered_tail_rows(rows: &[CenteredTailRow]) -> String {
    let rows = rows
        .iter()
        .map(|row| format!("({}, {})", row.row, row.column))
        .collect::<Vec<_>>();
    format!("[{}]", rows.join(", "))
}

#[derive(Clone, Debug, PartialEq, Eq)]
struct ArtifactRow {
    a: Vec<(usize, F)>,
    b: Vec<(usize, F)>,
    c: Vec<(usize, F)>,
}

fn lean_constraint_rows(rows: &[ArtifactRow]) -> String {
    let lean_terms = |terms: &[(usize, F)]| {
        let terms = terms
            .iter()
            .map(|&(column, coefficient)| format!("({column}, {})", coefficient.as_canonical_u64()))
            .collect::<Vec<_>>();
        format!("[{}]", terms.join(", "))
    };
    let rows = rows
        .iter()
        .map(|row| {
            format!(
                "⟨{}, {}, {}⟩",
                lean_terms(&row.a),
                lean_terms(&row.b),
                lean_terms(&row.c)
            )
        })
        .collect::<Vec<_>>();
    format!("[{}]", rows.join(",\n   "))
}

fn lean_polynomial_specialization(polynomial: &SparsePoly<F>, active_variables: &[usize]) -> String {
    let terms = polynomial
        .terms()
        .iter()
        .filter(|term| {
            term.coeff != F::ZERO
                && term
                    .exps
                    .iter()
                    .enumerate()
                    .all(|(variable, &power)| power == 0 || active_variables.contains(&variable))
        })
        .map(|term| {
            let powers = term
                .exps
                .iter()
                .enumerate()
                .filter_map(|(variable, &power)| (power != 0).then_some(format!("({variable}, {power})")))
                .collect::<Vec<_>>();
            format!("({}, [{}])", term.coeff.as_canonical_u64(), powers.join(", "))
        })
        .collect::<Vec<_>>();
    format!("[{}]", terms.join(", "))
}

fn source_expansion(plan: &BalancedTernarySharedSlotPlan, column: usize) -> Vec<(usize, F)> {
    if column == 0 {
        return vec![(plan.one_column(), F::ONE)];
    }
    if column == plan.source_field_column() {
        return plan.field_terms().to_vec();
    }
    for (sources, targets) in [
        (plan.source_digit_columns().as_slice(), plan.digit_columns().as_slice()),
        (
            plan.source_negative_columns().as_slice(),
            plan.negative_columns().as_slice(),
        ),
        (
            plan.source_borrow_columns().as_slice(),
            plan.borrow_columns().as_slice(),
        ),
    ] {
        if let Some(index) = sources.iter().position(|&source| source == column) {
            return vec![(targets[index], F::ONE)];
        }
    }
    panic!("source row references unowned column {column}")
}

fn expand_terms(plan: &BalancedTernarySharedSlotPlan, terms: &[(usize, F)]) -> Vec<(usize, F)> {
    terms
        .iter()
        .flat_map(|&(column, scale)| {
            source_expansion(plan, column)
                .into_iter()
                .map(move |(target, coefficient)| (target, scale * coefficient))
        })
        .collect()
}

fn normalize_terms(terms: &[(usize, F)]) -> Vec<(usize, F)> {
    let mut normalized = BTreeMap::new();
    for &(column, coefficient) in terms {
        *normalized.entry(column).or_insert(F::ZERO) += coefficient;
    }
    normalized
        .into_iter()
        .filter(|(_, coefficient)| *coefficient != F::ZERO)
        .collect()
}

fn source_expanded_rows(
    source: &neo_fold_clean::engine::r1cs_circuit::R1csSnapshot,
    plan: &BalancedTernarySharedSlotPlan,
) -> Vec<ArtifactRow> {
    plan.source_rows()
        .map(|row| ArtifactRow {
            a: expand_terms(plan, source.a_row(row)),
            b: expand_terms(plan, source.b_row(row)),
            c: expand_terms(plan, source.c_row(row)),
        })
        .collect()
}

fn actual_rows(rows: &[GadgetNativeConstraintRow]) -> Vec<ArtifactRow> {
    rows.iter()
        .map(|row| ArtifactRow {
            a: row.a().to_vec(),
            b: row.b().to_vec(),
            c: row.c().to_vec(),
        })
        .collect()
}

fn render_shared_slots(builder: &R1csBuilder) -> String {
    let source = builder.snapshot();
    let encoded =
        encode_r1cs_gadget_native(&source, builder.encoding_trace(), &[]).expect("production shared-slot lowering");
    let [plan] = encoded.plan.balanced_ternary_openings() else {
        panic!("one balanced-ternary production plan")
    };
    let [opening] = builder.encoding_trace().balanced_ternary_openings() else {
        panic!("one balanced-ternary source trace")
    };
    let retained_product_rows = encoded
        .balanced_ternary_rows(0)
        .expect("exact retained production rows and gate polynomial");
    let source_expanded_rows = source_expanded_rows(&source, plan);
    let retained_source_expanded_rows = plan
        .retained_source_rows()
        .iter()
        .map(|&row| source_expanded_rows[row - plan.source_rows().start].clone())
        .collect::<Vec<_>>();
    let retained_product_rows = actual_rows(&retained_product_rows);
    assert_eq!(plan.source_field_column(), opening.field_col);
    assert_eq!(plan.source_digit_columns(), &opening.digit_cols);
    assert_eq!(plan.source_negative_columns(), &opening.negative_cols);
    assert_eq!(plan.source_borrow_columns(), &opening.borrow_cols);
    assert_eq!(
        plan.source_rows(),
        opening.digit_rows.start..opening.transition_rows.end
    );
    assert_eq!(plan.source_rows().len(), 124);
    assert_eq!(plan.retained_source_rows().len(), 82);
    assert_eq!(plan.retained_encoded_rows().len(), 82);
    assert_eq!(retained_product_rows.len(), 82);
    assert_eq!(plan.retained_obligation_count(), 123);
    assert_eq!(plan.retained_physical_row_count(), 103);
    assert_eq!(plan.omitted_obligation_count(), 123);
    assert_eq!(encoded.structure.f.arity(), PRODUCTION_POLYNOMIAL_ARITY);
    for (expanded, production) in retained_source_expanded_rows
        .iter()
        .zip(&retained_product_rows)
    {
        assert_eq!(normalize_terms(&expanded.a), production.a);
        assert_eq!(normalize_terms(&expanded.b), production.b);
        assert_eq!(normalize_terms(&expanded.c), production.c);
    }

    let centered_rows = plan.centered_unit_rows();
    let centered_row_ids = centered_rows
        .iter()
        .copied()
        .collect::<std::collections::BTreeSet<_>>();
    let digit_columns = plan
        .digit_columns()
        .iter()
        .copied()
        .collect::<std::collections::BTreeSet<_>>();
    let mut pairs = Vec::new();
    let mut tails = Vec::new();
    for row in encoded.plan.coordinate_gate_schedule().rows() {
        if !centered_row_ids.contains(&row.row()) {
            continue;
        }
        match *row {
            GadgetNativeCoordinateRowAudit::CenteredUnitPair {
                row,
                family: GadgetNativeCenteredFamily::SisOpening,
                left,
                right,
            } => {
                assert!(digit_columns.contains(&left));
                assert!(digit_columns.contains(&right));
                pairs.push(CenteredPairRow { row, left, right });
            }
            GadgetNativeCoordinateRowAudit::CenteredUnitTail {
                row,
                family: GadgetNativeCenteredFamily::SisOpening,
                coordinate,
            } => {
                assert!(digit_columns.contains(&coordinate));
                tails.push(CenteredTailRow {
                    row,
                    column: coordinate,
                });
            }
            _ => panic!("balanced opening row is not centered"),
        }
    }
    assert_eq!((pairs.len(), tails.len()), (20, 1));
    let physical_rows = pairs
        .iter()
        .map(|row| row.row)
        .chain(tails.iter().map(|row| row.row))
        .collect::<Vec<_>>();
    assert_eq!(physical_rows.len(), centered_row_ids.len());
    assert_eq!(
        physical_rows
            .iter()
            .copied()
            .collect::<std::collections::BTreeSet<_>>(),
        centered_row_ids
    );
    assert_eq!(
        physical_rows.len(),
        physical_rows
            .iter()
            .copied()
            .collect::<std::collections::BTreeSet<_>>()
            .len()
    );
    let scheduled_coordinates = pairs
        .iter()
        .flat_map(|row| [row.left, row.right])
        .chain(tails.iter().map(|row| row.column))
        .collect::<Vec<_>>();
    assert_eq!(scheduled_coordinates, plan.digit_columns());
    assert_eq!(
        scheduled_coordinates.len(),
        scheduled_coordinates
            .iter()
            .copied()
            .collect::<std::collections::BTreeSet<_>>()
            .len()
    );
    let expanded_row_ids = pairs
        .iter()
        .flat_map(|row| [row.row, row.row])
        .chain(tails.iter().map(|row| row.row))
        .collect::<Vec<_>>();
    assert_eq!(expanded_row_ids, centered_rows);

    let source_rows = plan.source_rows().collect::<Vec<_>>();
    let retained_source_rows = plan.retained_source_rows();
    let retained_encoded_rows = plan.retained_encoded_rows();
    let indicator_definition_source_rows = plan.indicator_definition_source_rows();
    let indicator_support_source_rows = plan.indicator_support_source_rows();
    let transition_source_rows = plan.transition_source_rows().collect::<Vec<_>>();
    let encoded_for = |rows: &[usize]| {
        rows.iter()
            .map(|&row| {
                plan.encoded_row_for_source(row)
                    .expect("retained source row")
            })
            .collect::<Vec<_>>()
    };
    let omitted_source_rows = indicator_support_source_rows
        .iter()
        .copied()
        .chain(std::iter::once(plan.reconstruction_source_row()))
        .collect::<Vec<_>>();
    let payload = format!(
        "def sourceFieldCol : Nat := {}\n\
         def sourceDigitCols : List Nat := {}\n\
         def sourceNegativeCols : List Nat := {}\n\
         def sourceBorrowCols : List Nat := {}\n\
         def oneColumn : Nat := {}\n\
         def digitColumns : List Nat := {}\n\
         def negativeColumns : List Nat := {}\n\
         def borrowColumns : List Nat := {}\n\
         def fieldTerms : List (Nat × Nat) := {}\n\
         def sourceRows : List Nat := {}\n\
         def retainedSourceRows : List Nat := {}\n\
         def retainedEncodedRows : List Nat := {}\n\
         def retainedRowMap : List (Nat × Nat) := retainedSourceRows.zip retainedEncodedRows\n\
         def omittedSourceRows : List Nat := {}\n\
         def centeredPairRows : List (Nat × Nat × Nat) := {}\n\
         def centeredTailRows : List (Nat × Nat) := {}\n\
         def omittedNegativeBitnessColumns : List Nat := {}\n\
         def omittedBorrowBitnessColumns : List Nat := {}\n\
         def indicatorDefinitionSourceRows : List Nat := {}\n\
         def indicatorDefinitionEncodedRows : List Nat := {}\n\
         def indicatorSupportSourceRows : List Nat := {}\n\
         def reconstructionSourceRow : Nat := {}\n\
         def transitionSourceRows : List Nat := {}\n\
         def transitionEncodedRows : List Nat := {}\n\
         def retainedObligationCount : Nat := {}\n\
         def retainedPhysicalRowCount : Nat := {}\n\
         def omittedObligationCount : Nat := {}\n\
         def productionPolynomialArity : Nat := {}\n\
         def selectorRole : Nat := {}\n\
         def centeredUnitTailRole : Nat := {}\n\
         def centeredPairLeftRole : Nat := {}\n\
         def centeredPairRightRole : Nat := {}\n\
         def productLeftRole : Nat := {}\n\
         def productRightRole : Nat := {}\n\
         def productOutRole : Nat := {}\n\
         def centeredTailPolynomialTerms : List (Nat × List (Nat × Nat)) := {}\n\
         def centeredPairPolynomialTerms : List (Nat × List (Nat × Nat)) := {}\n\
         def singleProductPolynomialTerms : List (Nat × List (Nat × Nat)) := {}\n\
         def productionRowCount : Nat := {}\n\
         def productionColCount : Nat := {}\n\
         def sourceExpandedRows : List Row :=\n  {}\n\
         def retainedSourceExpandedRows : List Row :=\n  {}\n\
         def retainedProductRows : List Row :=\n  {}",
        plan.source_field_column(),
        lean_nat_list(plan.source_digit_columns().iter().copied()),
        lean_nat_list(plan.source_negative_columns().iter().copied()),
        lean_nat_list(plan.source_borrow_columns().iter().copied()),
        plan.one_column(),
        lean_nat_list(plan.digit_columns().iter().copied()),
        lean_nat_list(plan.negative_columns().iter().copied()),
        lean_nat_list(plan.borrow_columns().iter().copied()),
        lean_field_terms(plan.field_terms()),
        lean_nat_list(source_rows),
        lean_nat_list(retained_source_rows.iter().copied()),
        lean_nat_list(retained_encoded_rows.iter().copied()),
        lean_nat_list(omitted_source_rows),
        lean_centered_pair_rows(&pairs),
        lean_centered_tail_rows(&tails),
        lean_nat_list(plan.omitted_negative_bitness_columns().iter().copied()),
        lean_nat_list(plan.omitted_borrow_bitness_columns().iter().copied()),
        lean_nat_list(indicator_definition_source_rows.iter().copied()),
        lean_nat_list(encoded_for(&indicator_definition_source_rows)),
        lean_nat_list(indicator_support_source_rows.iter().copied()),
        plan.reconstruction_source_row(),
        lean_nat_list(transition_source_rows.iter().copied()),
        lean_nat_list(encoded_for(&transition_source_rows)),
        plan.retained_obligation_count(),
        plan.retained_physical_row_count(),
        plan.omitted_obligation_count(),
        encoded.structure.f.arity(),
        Roles::SELECTOR,
        Roles::CENTERED_UNIT_TAIL,
        Roles::CENTERED_PAIR_LEFT,
        Roles::CENTERED_PAIR_RIGHT,
        PRODUCT_LEFT_MATRIX,
        PRODUCT_RIGHT_MATRIX,
        PRODUCT_OUT_MATRIX,
        lean_polynomial_specialization(&encoded.structure.f, &[SELECTOR_MATRIX, CENTERED_UNIT_MATRIX]),
        lean_polynomial_specialization(
            &encoded.structure.f,
            &[Roles::SELECTOR, Roles::CENTERED_PAIR_LEFT, Roles::CENTERED_PAIR_RIGHT],
        ),
        lean_polynomial_specialization(
            &encoded.structure.f,
            &[
                SELECTOR_MATRIX,
                PRODUCT_LEFT_MATRIX,
                PRODUCT_RIGHT_MATRIX,
                PRODUCT_OUT_MATRIX,
            ],
        ),
        encoded.structure.n,
        encoded.structure.m,
        lean_constraint_rows(&source_expanded_rows),
        lean_constraint_rows(&retained_source_expanded_rows),
        lean_constraint_rows(&retained_product_rows),
    );
    let mut rendered = String::new();
    rendered.push_str("import Nightstream.Implementation.R1CS.Core.Semantics\n\n");
    rendered.push_str(
        "/-! Generated file: exact gadget-native shared-slot layout. Do not hand-edit.\n\nOwns: physical centered pair/tail rows, active gate roles and polynomial\nspecializations, retained product rows, and structural slot aliases.\n\nDoes not own: semantic row-removal proofs, witness authority, SIS binding, or\nany complete F-prime cost claim.\n\nEmits constraints: no. Rust replays production matrices before rendering.\n\nAuthority boundary: generated bytes are evidence only; Lean consumers prove\nwhat the replayed rows mean under a verifier-fixed selector and nonresidue.\n\n| Child | Mathematical obligation | Rust source | Lean consumer |\n|---|---|---|---|\n| centered pair/tail rows | exact 41-coordinate schedule | coordinate gate audit | `SharedSlots` |\n| active polynomial terms | exact pair, tail, and product equations | production CCS polynomial | `SharedSlots` |\n| retained product rows | exact 82 reduced R1CS rows | production CCS matrices | `SharedSlots` |\n| shared aliases | field/digit structural identity | balanced opening plan | `SharedSlots` |\n-/\n\n",
    );
    rendered.push_str("namespace Nightstream.Implementation.R1CS.ShiftedTernarySharedSlotsArtifact\n\n");
    writeln!(rendered, "def schemaVersion : Nat := {SHARED_SLOTS_SCHEMA_VERSION}").expect("render");
    writeln!(rendered, "def payloadSha256 : String := \"{}\"", sha256_hex(&payload)).expect("render");
    rendered.push_str(&payload);
    rendered.push_str("\n\nend Nightstream.Implementation.R1CS.ShiftedTernarySharedSlotsArtifact\n");
    rendered
}

fn lean_sparse_polynomial_terms(polynomial: &SparsePoly<F>) -> String {
    let terms = polynomial
        .terms()
        .iter()
        .map(|term| {
            format!(
                "({}, {})",
                term.coeff.as_canonical_u64(),
                lean_nat_list(term.exps.iter().map(|&power| power as usize))
            )
        })
        .collect::<Vec<_>>();
    format!("[{}]", terms.join(",\n   "))
}

fn lean_selective_rows(rows: &[SelectiveRowArtifact]) -> String {
    let rows = rows
        .iter()
        .map(|row| {
            let ports = row
                .matrix_row()
                .ports()
                .iter()
                .map(|terms| {
                    lean_field_terms(
                        &terms
                            .iter()
                            .map(|term| (term.column(), term.coefficient()))
                            .collect::<Vec<_>>(),
                    )
                })
                .collect::<Vec<_>>();
            format!("[{}]", ports.join(", "))
        })
        .collect::<Vec<_>>();
    format!("[{}]", rows.join(",\n   "))
}

fn render_selective() -> String {
    let (builder, _, _) = build(SAMPLE);
    let lowered = lower_field_r1cs(builder, &[]).expect("lower selective shifted-ternary fixture");
    let (shape, assignment) = lowered.into_parts();
    let relation = build_multi_branch_selective_low_norm_r1cs_with_alignment(&[shape.clone(), shape], 0, D, 0)
        .expect("compile selective shifted-ternary fixture");
    let encoded = relation
        .encode(0, &assignment)
        .expect("encode selected arm");
    assert!(relation.is_satisfied(&encoded), "selected honest arm");

    let snapshot = relation
        .selective_snapshot()
        .expect("checked selective snapshot");
    let [opening] = snapshot.compiler_audit().canonical_openings()[0].as_slice() else {
        panic!("one memoized opening in selected arm")
    };
    assert_eq!(opening.digit_coordinates().len(), 41);
    assert_eq!(opening.borrow_coordinates().len(), 20);
    assert_eq!(opening.coordinate_count(), 61);
    assert_eq!(opening.emitted_rows().len(), 21);
    let coordinates = opening
        .digit_coordinates()
        .iter()
        .chain(opening.borrow_coordinates())
        .copied()
        .collect::<BTreeSet<_>>();
    assert_eq!(coordinates.len(), 61, "all compact coordinates are distinct");

    let rows = opening
        .emitted_rows()
        .map(|row| {
            snapshot
                .materialize_row(row)
                .expect("materialize final canonical row")
        })
        .collect::<Vec<_>>();
    assert!(rows.iter().all(|row| {
        row.family() == SelectiveEmittedRowFamily::ShiftedTernaryCanonical
            && row.arm() == Some(0)
            && row.matrix_row().ports().len() == 13
    }));
    assert_eq!(snapshot.structure().f.arity(), 13);
    assert_eq!(snapshot.structure().f.terms().len(), 66);

    let payload = format!(
        "def structureRowCount : Nat := {}\n\
         def structureColumnCount : Nat := {}\n\
         def selectorColumn : Nat := {}\n\
         def sourceField : Nat := {}\n\
         def digitCoordinates : List Nat := {}\n\
         def borrowCoordinates : List Nat := {}\n\
         def canonicalRows : List Nat := {}\n\
         def polynomialTerms : List (Nat × List Nat) :=\n  {}\n\
         def rowPorts : List (List (List (Nat × Nat))) :=\n  {}",
        snapshot.structure().n,
        snapshot.structure().m,
        snapshot.selector_cols()[0],
        opening.source_field(),
        lean_nat_list(opening.digit_coordinates().iter().copied()),
        lean_nat_list(opening.borrow_coordinates().iter().copied()),
        lean_nat_list(opening.emitted_rows()),
        lean_sparse_polynomial_terms(&snapshot.structure().f),
        lean_selective_rows(&rows),
    );
    let mut rendered = String::new();
    rendered.push_str("import Nightstream.Implementation.R1CS.Core.Semantics\n\n");
    rendered.push_str(
        "/-! Generated exact selective shifted-ternary row artifact. Do not hand-edit.\n\n\
Owns: one final 61-coordinate opening, its 21 physical rows, and the exact\n\
13-port/66-term polynomial read from the compiled selective structure.\n\n\
Does not own: row semantics, Split-NC truth, or production-profile multiplicity.\n\n\
Emits constraints: no. Rust validates the checked compiler snapshot before rendering.\n-/\n\n",
    );
    rendered.push_str("namespace Nightstream.Implementation.R1CS.ShiftedTernarySelectiveArtifact\n\n");
    writeln!(rendered, "def schemaVersion : Nat := {SELECTIVE_SCHEMA_VERSION}").expect("render");
    writeln!(rendered, "def payloadSha256 : String := \"{}\"", sha256_hex(&payload)).expect("render");
    rendered.push_str(&payload);
    rendered.push_str("\n\nend Nightstream.Implementation.R1CS.ShiftedTernarySelectiveArtifact\n");
    rendered
}

#[test]
fn honest_and_forged_boundaries_are_pinned() {
    let (builder, _, _) = build(SAMPLE);
    assert_eq!((builder.rows(), builder.cols()), (180, 180));
    assert!(builder.is_satisfied());
    assert!(builder.unconstrained_columns().is_empty());
    let forged = forged();
    assert_eq!(forged.first_unsatisfied_row(), Some(125));
}

#[test]
fn shifted_ternary_artifact_matches_committed_file() {
    let (builder, field, commitment) = build(SAMPLE);
    let forged = forged();
    let emitted = render(&builder, field, &commitment, forged.witness());
    let path = format!("{}{}", env!("CARGO_MANIFEST_DIR"), ARTIFACT_REL_PATH);
    let committed = std::fs::read_to_string(&path).unwrap_or_default();
    if committed != emitted {
        let expected = format!("{path}.expected");
        std::fs::write(&expected, emitted).expect("write shifted-ternary artifact");
        panic!("shifted-ternary Lean artifact drifted; wrote {expected}");
    }
}

#[test]
fn shifted_ternary_shared_slots_artifact_matches_committed_file() {
    let (builder, _, _) = build(SAMPLE);
    let emitted = render_shared_slots(&builder);
    let path = format!("{}{}", env!("CARGO_MANIFEST_DIR"), SHARED_SLOTS_ARTIFACT_REL_PATH);
    let committed = std::fs::read_to_string(&path).unwrap_or_default();
    if committed != emitted {
        let expected = format!("{path}.expected");
        std::fs::write(&expected, emitted).expect("write shifted-ternary shared-slot artifact");
        panic!("shifted-ternary shared-slot Lean artifact drifted; wrote {expected}");
    }
}

#[test]
fn shifted_ternary_selective_artifact_matches_committed_file() {
    let emitted = render_selective();
    let path = format!("{}{}", env!("CARGO_MANIFEST_DIR"), SELECTIVE_ARTIFACT_REL_PATH);
    let committed = std::fs::read_to_string(&path).unwrap_or_default();
    if committed != emitted {
        let expected = format!("{path}.expected");
        std::fs::write(&expected, emitted).expect("write shifted-ternary selective artifact");
        panic!("shifted-ternary selective Lean artifact drifted; wrote {expected}");
    }
}

#[test]
#[ignore = "deliberately rewrites reviewed generated Lean artifacts"]
fn regenerate_shifted_ternary_selective_artifact() {
    let path = format!("{}{}", env!("CARGO_MANIFEST_DIR"), SELECTIVE_ARTIFACT_REL_PATH);
    std::fs::write(path, render_selective()).expect("write shifted-ternary selective artifact");
}
