import Nightstream.Implementation.NebulaV2.NIFS.PiRLC.TranscriptSemantics

/-! Regression surface for the exact V2 PiRLC candidate transcript. -/

set_option autoImplicit false

namespace tests.NebulaV2ProductPiRlcTranscriptSemantics

#check Nightstream.Implementation.NebulaV2.ProductPiRlcTranscriptRows.CandidateIndex.flat_injective
#check Nightstream.Implementation.NebulaV2.ProductPiRlcTranscriptRows.candidateFields_injective
#check Nightstream.Implementation.NebulaV2.ProductPiRlcTranscriptRows.aggregateRowCount_eq
#check Nightstream.Implementation.NebulaV2.ProductPiRlcTranscriptRows.candidate_windows_disjoint
#check Nightstream.Implementation.NebulaV2.ProductPiRlcTranscriptSemantics.candidate_rows_sound
#check Nightstream.Implementation.NebulaV2.ProductPiRlcTranscriptSemantics.all_candidates_sound

end tests.NebulaV2ProductPiRlcTranscriptSemantics
