import Nightstream.Implementation.Nebula.Production.Artifact.RelationDimensions

/-! Surface checks for the shared augmented-relation dimension gate. -/

set_option autoImplicit false

namespace tests.NebulaProductionRelationDimensions

open Nightstream.Implementation.Nebula
open Nightstream.Implementation.Nebula.ProductionRelationDimensions

#check Artifact.relationRowVariables_exceed_25
#check Artifact.relationRowVariables_minimum
#check Artifact.selected_exponent_core_included
#check Artifact.selected_exponent_core_count_fits
#check Artifact.selected_exponent_core_satisfied
#check Artifact.terminalProgram
#check Artifact.terminalProgram_fold
#check Artifact.terminal_program_included
#check Artifact.terminal_program_count_fits
#check Artifact.terminal_program_satisfied
#check Artifact.terminal_rows_and_columns_fit
#check Artifact.terminal_columns_scoped
#check Artifact.source_and_nifs_exact
#check Artifact.terminal_opening_exact
#check Artifact.nifsShape_ne_reference25
#check Artifact.runningFieldCoordinates_exceed_reference
#check Artifact.nifsPublicFrameFields_exceed_reference
#check splitExponentFit_accepts_incompatible_e1
#check ProductionRecursiveCoreManifestFor.length_only_accepts_zero_row_substitution
#check terminalLengthOnly_accepts_zero_row_substitution
#check terminalRowCapacityOnly_does_not_imply_rectangularCapacity

end tests.NebulaProductionRelationDimensions
