import DirectCcsFPrime.DirectParentOnlyProductionConcreteFPrimePriorRawProductionRuntimeAuthority

/-!
Thin interface for exact-runtime verifier wrappers.

This file owns the exact public-IO opening, terminal-slice, authority
certificate, and runtime-authority exports. It deliberately leaves compressed
verifier soundness to the compressed-soundness interface.
-/

namespace DirectCcsFPrime

namespace DirectParentOnlyProductionConcreteFPrimePriorRawProductionExactRuntimeInterface

export DirectParentOnlyProductionConcreteFPrimePriorRawProduction (
  acceptedTerminalWithSoundVerifierOfProductionExactLatestStep
  ProductionExactTerminalLengthBinding
  runtimeExactPublicIOOpeningSurfaceOfProductionExact
  runtimeVerifyPriorOfProductionExact_toRuntimeExactPublicIOOpening
  runtimeVerifyPriorOfProductionExact_viaRuntimeExactPublicIOOpening_acceptedOpens
  certifiedPriorVerifierOfProductionExactRuntimeExactPublicIOOpening
  certifiedPriorVerifierOfProductionExactRuntimeExactPublicIOOpening_verify
  certifiedPriorVerifierOfProductionExactRuntimeExactPublicIOOpening_accepts
  soundVerifierOfProductionExactRuntimeExactPublicIOOpening
  soundVerifierOfProductionExactRuntimeExactPublicIOOpening_accepts_iff
  acceptedTerminalWithSoundVerifierOfProductionExactRuntimeExactPublicIOOpeningLatestStep
  certifiedSingleTerminalEndToEnd_ofProductionExactRuntimeExactPublicIOOpeningLatestStep
  nonAggregatePrivateDecStageFacts_ofProductionExactRuntimeExactPublicIOOpeningLatestStep
  section71StageTargetAuditTrail_ofProductionExactRuntimeExactPublicIOOpeningLatestStep
  productionExactTerminalEndToEnd_ofRuntimeVerifyPriorLatestStep
  runtimeVerifyPriorOfProductionExact_openAuthority_ne_none
  runtimeVerifyPriorOfProductionExact_openedAuthority_accepts_of_open
  runtimeVerifyPriorOfProductionExact_bindsOpenedAuthoritySteps
  runtimeVerifyPriorOfProductionExact_bindsOpenedAuthorityImage
  runtimeVerifyPriorOfProductionExact_cannot_accept_without_opening
  runtimeVerifyPriorOfProductionExact_cannot_accept_unreachable_prior
  runtimeVerifyPriorOfProductionExact_publicImageInvariants
  soundVerifierOfProductionExact_opensToFoldedAuthority
  soundVerifierOfProductionExact_openedAuthority_accepts_of_open
  soundVerifierOfProductionExact_bindsOpenedAuthoritySteps
  soundVerifierOfProductionExact_bindsOpenedAuthorityImage
  soundVerifierOfProductionExact_openAuthority_ne_none
  soundVerifierOfProductionExact_cannot_accept_without_opening
  soundVerifierOfProductionExact_reaches_prior
  soundVerifierOfProductionExact_publicImageInvariants
  soundVerifierOfProductionExact_cannot_accept_unreachable_prior
  soundVerifierOfProductionExact_proofFunctional
  nonAggregatePrivateDecStageFacts_ofProductionExactLatestStep
  section71StageTargetAuditTrail_ofProductionExactLatestStep
  ProductionExactTerminalSliceBinding
  productionExactTerminalLengthBindingOfTerminalSlice
  ProductionExactAuthorityCertificate
  productionExactPriorOpeningSurfaceOfAuthorityCertificate
  runtimeVerifyPriorOfProductionExactAuthorityCertificate_acceptedOpens
  runtimeExactPublicIOOpeningSurfaceOfProductionExactTerminalSlice
  certifiedPriorVerifierOfProductionExactTerminalSlice
  certifiedPriorVerifierOfProductionExactTerminalSlice_accepts
  soundVerifierOfProductionExactTerminalSlice
  soundVerifierOfProductionExactTerminalSlice_accepts_iff
  runtimeVerifyPriorOfProductionExact_viaTerminalSlice_acceptedOpens
  acceptedTerminalWithSoundVerifierOfProductionExactTerminalSliceLatestStep
  certifiedSingleTerminalEndToEnd_ofProductionExactTerminalSliceLatestStep
  nonAggregatePrivateDecStageFacts_ofProductionExactTerminalSliceLatestStep
  section71StageTargetAuditTrail_ofProductionExactTerminalSliceLatestStep
  runtimeExactPublicIOOpeningSurfaceOfProductionExactAuthorityCertificateTerminalSlice
  certifiedPriorVerifierOfProductionExactAuthorityCertificateTerminalSlice
  certifiedPriorVerifierOfProductionExactAuthorityCertificateTerminalSlice_accepts
  soundVerifierOfProductionExactAuthorityCertificateTerminalSlice
  soundVerifierOfProductionExactAuthorityCertificateTerminalSlice_accepts_iff
  acceptedTerminalWithSoundVerifierOfProductionExactAuthorityCertificateTerminalSliceLatestStep
  certifiedSingleTerminalEndToEnd_ofProductionExactAuthorityCertificateTerminalSliceLatestStep
  nonAggregatePrivateDecStageFacts_ofProductionExactAuthorityCertificateTerminalSliceLatestStep
  section71StageTargetAuditTrail_ofProductionExactAuthorityCertificateTerminalSliceLatestStep
  ProductionExactRuntimeAuthoritySoundness
  productionExactAuthorityCertificateOfRuntimeAuthoritySoundness
  productionExactPriorOpeningSurfaceOfRuntimeAuthoritySoundness
  runtimeVerifyPriorOfProductionExactRuntimeAuthoritySoundness_acceptedOpens
  concreteRuntimeExactPublicIOSurfaceOfProductionExactRuntimeAuthoritySoundness
  runtimeVerifyPriorOfProductionExactRuntimeAuthoritySoundness_toConcreteRuntimeExactPublicIO
  runtimeVerifyPriorOfProductionExactRuntimeAuthoritySoundness_concreteRuntimeExactPublicIOEvidence
  certifiedPriorVerifierOfProductionExactRuntimeAuthoritySoundnessConcreteExact
  certifiedPriorVerifierOfProductionExactRuntimeAuthoritySoundnessConcreteExact_accepts
  soundVerifierOfProductionExactRuntimeAuthoritySoundnessConcreteExact
  soundVerifierOfProductionExactRuntimeAuthoritySoundnessConcreteExact_accepts_iff
  acceptedTerminalWithSoundVerifierOfProductionExactRuntimeAuthoritySoundnessConcreteExactLatestStep
  certifiedSingleTerminalEndToEnd_ofProductionExactRuntimeAuthoritySoundnessConcreteExactLatestStep
  nonAggregatePrivateDecStageFacts_ofProductionExactRuntimeAuthoritySoundnessConcreteExactLatestStep
  section71StageTargetAuditTrail_ofProductionExactRuntimeAuthoritySoundnessConcreteExactLatestStep
  runtimeExactPublicIOOpeningSurfaceOfProductionExactRuntimeAuthoritySoundnessTerminalSlice
  certifiedPriorVerifierOfProductionExactRuntimeAuthoritySoundnessTerminalSlice
  certifiedPriorVerifierOfProductionExactRuntimeAuthoritySoundnessTerminalSlice_accepts
  soundVerifierOfProductionExactRuntimeAuthoritySoundnessTerminalSlice
  soundVerifierOfProductionExactRuntimeAuthoritySoundnessTerminalSlice_accepts_iff
  acceptedTerminalWithSoundVerifierOfProductionExactRuntimeAuthoritySoundnessTerminalSliceLatestStep
  certifiedSingleTerminalEndToEnd_ofProductionExactRuntimeAuthoritySoundnessTerminalSliceLatestStep
  nonAggregatePrivateDecStageFacts_ofProductionExactRuntimeAuthoritySoundnessTerminalSliceLatestStep
  section71StageTargetAuditTrail_ofProductionExactRuntimeAuthoritySoundnessTerminalSliceLatestStep
)

end DirectParentOnlyProductionConcreteFPrimePriorRawProductionExactRuntimeInterface

end DirectCcsFPrime
