import DirectCcsFPrime.DirectParentOnlyProductionConcreteFPrimePriorRawIO
import DirectCcsFPrime.DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundVerifier

/-!
Typed interface for raw public-IO authority consequences in the concrete prior
F' verifier.

Spec: `specs/DirectParentOnlyProductionConcreteFPrimePriorRawIO.spec.md`
-/

namespace DirectCcsFPrime

namespace DirectParentOnlyProductionConcreteFPrimePriorRawIOInterface

abbrev ProductionContext :=
  DirectParentOnlyProductionConcreteFPrimePriorRawIO.ProductionContext

abbrev PublicImage :=
  DirectParentOnlyProductionConcreteFPrimePriorRawIO.PublicImage

abbrev ProofCarryingPriorProof :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIO.ProofCarryingPriorProof

abbrev ConcreteRuntimeRawPublicIOSurface :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIO.ConcreteRuntimeRawPublicIOSurface

abbrev RuntimeVerifyPriorOfRawPublicIO :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIO.RuntimeVerifyPriorOfRawPublicIO

abbrev AcceptedRawPublicIOEvidence :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIO.AcceptedRawPublicIOEvidence

abbrev authorityOpenerOfRawPublicIO :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIO.authorityOpenerOfRawPublicIO

abbrev runtimeVerifyPriorOfRawPublicIO_acceptedOpens :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIO.runtimeVerifyPriorOfRawPublicIO_acceptedOpens

abbrev runtimeVerifyPriorOfRawPublicIO_evidence :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIO.runtimeVerifyPriorOfRawPublicIO_evidence

abbrev runtimeVerifyPriorOfRawPublicIO_openedAuthority_accepts_of_open :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIO.runtimeVerifyPriorOfRawPublicIO_openedAuthority_accepts_of_open

abbrev runtimeVerifyPriorOfRawPublicIO_reaches_prior :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIO.runtimeVerifyPriorOfRawPublicIO_reaches_prior

abbrev certifiedPriorVerifierOfRawPublicIO :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIO.certifiedPriorVerifierOfRawPublicIO

abbrev certifiedPriorVerifierOfRawPublicIO_verify :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIO.certifiedPriorVerifierOfRawPublicIO_verify

abbrev runtimeVerifyPriorOfRawPublicIO_openAuthority_ne_none :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIO.runtimeVerifyPriorOfRawPublicIO_openAuthority_ne_none

abbrev runtimeVerifyPriorOfRawPublicIO_cannot_accept_unreachable_prior :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIO.runtimeVerifyPriorOfRawPublicIO_cannot_accept_unreachable_prior

abbrev runtimeVerifyPriorOfRawPublicIO_publicImageInvariants :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIO.runtimeVerifyPriorOfRawPublicIO_publicImageInvariants

abbrev proofFunctionalOfRawPublicIO :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIO.proofFunctionalOfRawPublicIO

abbrev soundVerifierOfRawPublicIO :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundVerifier.soundVerifierOfRawPublicIO

abbrev soundVerifierOfRawPublicIO_accepts_iff :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundVerifier.soundVerifierOfRawPublicIO_accepts_iff

abbrev soundVerifierOfRawPublicIO_opensToFoldedAuthority :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundVerifier.soundVerifierOfRawPublicIO_opensToFoldedAuthority

abbrev soundVerifierOfRawPublicIO_reaches_prior :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundVerifier.soundVerifierOfRawPublicIO_reaches_prior

abbrev soundVerifierOfRawPublicIO_publicImageInvariants :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundVerifier.soundVerifierOfRawPublicIO_publicImageInvariants

abbrev soundVerifierOfRawPublicIO_cannot_accept_unreachable_prior :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundVerifier.soundVerifierOfRawPublicIO_cannot_accept_unreachable_prior

abbrev soundVerifierOfRawPublicIO_proofFunctional :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundVerifier.soundVerifierOfRawPublicIO_proofFunctional

abbrev soundVerifierOfRawPublicIO_sameProof :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundVerifier.soundVerifierOfRawPublicIO_sameProof

abbrev acceptedTerminalWithSoundVerifierOfRawPublicIOLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundVerifier.acceptedTerminalWithSoundVerifierOfRawPublicIOLatestStep

abbrev certifiedSingleTerminalEndToEnd_ofRawPublicIOLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIO.certifiedSingleTerminalEndToEnd_ofRawPublicIOLatestStep

abbrev nonAggregatePrivateDecStageFacts_ofRawPublicIOLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIO.nonAggregatePrivateDecStageFacts_ofRawPublicIOLatestStep

abbrev section71StageTargetAuditTrail_ofRawPublicIOLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIO.section71StageTargetAuditTrail_ofRawPublicIOLatestStep

end DirectParentOnlyProductionConcreteFPrimePriorRawIOInterface

end DirectCcsFPrime
