import DirectCcsFPrime.DirectParentOnlyProductionConcreteFPrimePriorRawProductionExactAccepted

/-!
Thin interface for exact verifier acceptance and its audit package.

This is the smallest surface needed to inspect what concrete exact verifier
acceptance checks before any runtime-authority or terminal-slice wrappers are
introduced.
-/

namespace DirectCcsFPrime

namespace DirectParentOnlyProductionConcreteFPrimePriorRawProductionExactAcceptedInterface

export DirectParentOnlyProductionConcreteFPrimePriorRawProduction (
  ExactTerminalBoundaryPublicIO
  ProductionExactPriorVerifierChecks
  rawProductionVerifierChecksOfExact
  ProductionExactVerifierAccepted
  productionExactVerifierAccepted_compactImageReplay
  productionExactVerifierAccepted_construction2BoundaryReplay
  productionExactVerifierAccepted_poseidon2TranscriptReplay
  productionExactVerifierAccepted_proofIvcPublicImage_eq_canonical
  productionExactVerifierAccepted_proofPublicImage_eq
  productionExactVerifierAccepted_proofStepCount_eq
  productionExactVerifierAccepted_publishedStatementValid
  productionExactVerifierAccepted_expectedIvcPublicImage_eq_canonical
  productionExactVerifierAccepted_finalClaimsCanonical
  productionExactVerifierAccepted_finalClaimsBindPublicImage
  productionExactVerifierAccepted_finalCeVerifierAccepts
  productionExactVerifierAccepted_compressedProofDigestReplay
  productionExactVerifierAccepted_bindingDigestReplay
  productionExactVerifierAccepted_statementPublicValid
  productionExactVerifierAccepted_construction2Boundary_eq
  productionExactVerifierAccepted_terminalVerifierPublicIO_eq
  productionExactVerifierAccepted_terminalPublicValues_eq
  productionExactVerifierAccepted_boundaryPublicValues_eq
  ProductionExactVerifierAcceptedAudit
  productionExactVerifierAccepted_audit
  productionExactVerifierAccepted_of_audit
  productionExactVerifierAccepted_sameProofStatement
  productionExactVerifierAccepted_sameProofPublicIO
  productionExactVerifierAcceptedAudit_sameProofStatement
  productionExactVerifierAcceptedAudit_sameProofPublicIO
  ProductionExactBoundStatementAccepted
  productionExactBoundStatementAccepted_ofAccepted
  ProductionExactPriorOpeningSurface
  RuntimeVerifyPriorOfProductionExact
  AcceptedProductionExactEvidence
  runtimeVerifyPriorOfProductionExact_boundStatement
  runtimeVerifyPriorOfProductionExact_acceptedOpens
  runtimeVerifyPriorOfProductionExact_evidence
  certifiedPriorVerifierOfProductionExact
  certifiedPriorVerifierOfProductionExact_verify
  soundVerifierOfProductionExact
  soundVerifierOfProductionExact_accepts_iff
  runtimeVerifyPriorOfProductionExact_reaches_prior
  proofFunctionalOfProductionExact
  soundVerifierOfProductionExact_sameProof
  certifiedSingleTerminalEndToEnd_ofProductionExactLatestStep
)

end DirectParentOnlyProductionConcreteFPrimePriorRawProductionExactAcceptedInterface

end DirectCcsFPrime
