import DirectCcsFPrime.DirectParentOnlyProductionConcreteFPrimePriorBackendOpening
import DirectCcsFPrime.DirectParentOnlyProductionConcreteFPrimePriorBackendOpeningSoundVerifier

/-!
Typed interface for the backend-shaped exact public-IO opening verifier.

Spec: `specs/DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.spec.md`
-/

namespace DirectCcsFPrime

namespace DirectParentOnlyProductionConcreteFPrimePriorBackendOpeningInterface

abbrev ProductionContext :=
  DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.ProductionContext

abbrev PublicImage :=
  DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.PublicImage

abbrev ProofCarryingPriorProof :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.ProofCarryingPriorProof

abbrev ExactTerminalBoundaryPublicIO :=
  DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.ExactTerminalBoundaryPublicIO

abbrev ConcreteExactPublicIOVerifierChecks :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.ConcreteExactPublicIOVerifierChecks

abbrev ExactPublicIOBoundStatementAccepted :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.ExactPublicIOBoundStatementAccepted

abbrev ConcreteExactPublicIOOpeningSurface :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.ConcreteExactPublicIOOpeningSurface

abbrev ConcreteRuntimeExactPublicIOOpeningSurface :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.ConcreteRuntimeExactPublicIOOpeningSurface

abbrev exactPublicIOVerifierChecksOfRuntimeExactPublicIOOpening :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.exactPublicIOVerifierChecksOfRuntimeExactPublicIOOpening

abbrev RuntimeVerifyPriorOfRuntimeExactPublicIOChecks :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.RuntimeVerifyPriorOfRuntimeExactPublicIOChecks

abbrev terminalLengthBindingOfRuntimeExactPublicIOOpening :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.terminalLengthBindingOfRuntimeExactPublicIOOpening

abbrev exactPublicIOOpeningSurfaceOfRuntimeExactPublicIOOpening :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.exactPublicIOOpeningSurfaceOfRuntimeExactPublicIOOpening

abbrev RuntimeVerifyPriorOfRuntimeExactPublicIOOpening :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.RuntimeVerifyPriorOfRuntimeExactPublicIOOpening

abbrev certifiedPriorVerifierOfRuntimeExactPublicIOOpening :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.certifiedPriorVerifierOfRuntimeExactPublicIOOpening

abbrev runtimeVerifyPriorOfRuntimeExactPublicIOOpening_ofExactPublicIOChecks :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.runtimeVerifyPriorOfRuntimeExactPublicIOOpening_ofExactPublicIOChecks

abbrev runtimeVerifyPriorOfRuntimeExactPublicIOOpening_acceptedOpens :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.runtimeVerifyPriorOfRuntimeExactPublicIOOpening_acceptedOpens

abbrev runtimeVerifyPriorOfRuntimeExactPublicIOOpening_openedAuthority_accepts_of_open :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.runtimeVerifyPriorOfRuntimeExactPublicIOOpening_openedAuthority_accepts_of_open

abbrev runtimeVerifyPriorOfRuntimeExactPublicIOOpening_cannot_accept_without_opening :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.runtimeVerifyPriorOfRuntimeExactPublicIOOpening_cannot_accept_without_opening

abbrev runtimeVerifyPriorOfRuntimeExactPublicIOOpening_reaches_prior :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.runtimeVerifyPriorOfRuntimeExactPublicIOOpening_reaches_prior

abbrev proofFunctionalOfRuntimeExactPublicIOOpening :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.proofFunctionalOfRuntimeExactPublicIOOpening

abbrev runtimeVerifyPriorOfRuntimeExactPublicIOOpening_publicImageInvariants :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.runtimeVerifyPriorOfRuntimeExactPublicIOOpening_publicImageInvariants

abbrev runtimeVerifyPriorOfRuntimeExactPublicIOOpening_cannot_accept_unreachable_prior :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.runtimeVerifyPriorOfRuntimeExactPublicIOOpening_cannot_accept_unreachable_prior

abbrev runtimeVerifyPriorOfRuntimeExactPublicIOChecks_acceptedOpens :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.runtimeVerifyPriorOfRuntimeExactPublicIOChecks_acceptedOpens

abbrev runtimeVerifyPriorOfRuntimeExactPublicIOChecks_openedAuthority_accepts_of_open :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.runtimeVerifyPriorOfRuntimeExactPublicIOChecks_openedAuthority_accepts_of_open

abbrev runtimeVerifyPriorOfRuntimeExactPublicIOChecks_cannot_accept_without_opening :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.runtimeVerifyPriorOfRuntimeExactPublicIOChecks_cannot_accept_without_opening

abbrev runtimeVerifyPriorOfRuntimeExactPublicIOChecks_reaches_prior :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.runtimeVerifyPriorOfRuntimeExactPublicIOChecks_reaches_prior

abbrev runtimeVerifyPriorOfRuntimeExactPublicIOChecks_publicImageInvariants :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.runtimeVerifyPriorOfRuntimeExactPublicIOChecks_publicImageInvariants

abbrev runtimeVerifyPriorOfRuntimeExactPublicIOChecks_cannot_accept_unreachable_prior :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.runtimeVerifyPriorOfRuntimeExactPublicIOChecks_cannot_accept_unreachable_prior

abbrev proofFunctionalOfRuntimeExactPublicIOChecks :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.proofFunctionalOfRuntimeExactPublicIOChecks

abbrev certifiedPriorVerifierOfRuntimeExactPublicIOChecks :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpeningSoundVerifier.certifiedPriorVerifierOfRuntimeExactPublicIOChecks

abbrev certifiedPriorVerifierOfRuntimeExactPublicIOChecks_verify :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpeningSoundVerifier.certifiedPriorVerifierOfRuntimeExactPublicIOChecks_verify

abbrev soundVerifierOfRuntimeExactPublicIOChecks :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpeningSoundVerifier.soundVerifierOfRuntimeExactPublicIOChecks

abbrev soundVerifierOfRuntimeExactPublicIOChecks_accepts_iff :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpeningSoundVerifier.soundVerifierOfRuntimeExactPublicIOChecks_accepts_iff

abbrev soundVerifierOfRuntimeExactPublicIOChecks_opensToFoldedAuthority :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpeningSoundVerifier.soundVerifierOfRuntimeExactPublicIOChecks_opensToFoldedAuthority

abbrev soundVerifierOfRuntimeExactPublicIOChecks_proofFunctional :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpeningSoundVerifier.soundVerifierOfRuntimeExactPublicIOChecks_proofFunctional

abbrev soundVerifierOfRuntimeExactPublicIOChecks_sameProof :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpeningSoundVerifier.soundVerifierOfRuntimeExactPublicIOChecks_sameProof

abbrev acceptedTerminalWithSoundVerifierOfRuntimeExactPublicIOChecksLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpeningSoundVerifier.acceptedTerminalWithSoundVerifierOfRuntimeExactPublicIOChecksLatestStep

abbrev certifiedSingleTerminalEndToEnd_ofRuntimeExactPublicIOOpeningLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.certifiedSingleTerminalEndToEnd_ofRuntimeExactPublicIOOpeningLatestStep

abbrev nonAggregatePrivateDecStageFacts_ofRuntimeExactPublicIOOpeningLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.nonAggregatePrivateDecStageFacts_ofRuntimeExactPublicIOOpeningLatestStep

abbrev section71StageTargetAuditTrail_ofRuntimeExactPublicIOOpeningLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.section71StageTargetAuditTrail_ofRuntimeExactPublicIOOpeningLatestStep

abbrev certifiedSingleTerminalEndToEnd_ofRuntimeExactPublicIOChecksLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.certifiedSingleTerminalEndToEnd_ofRuntimeExactPublicIOChecksLatestStep

abbrev nonAggregatePrivateDecStageFacts_ofRuntimeExactPublicIOChecksLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.nonAggregatePrivateDecStageFacts_ofRuntimeExactPublicIOChecksLatestStep

abbrev section71StageTargetAuditTrail_ofRuntimeExactPublicIOChecksLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.section71StageTargetAuditTrail_ofRuntimeExactPublicIOChecksLatestStep

abbrev runtimeExactPublicIOOpeningSurfaceOfExactRuntimeSoundAndLayout :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.runtimeExactPublicIOOpeningSurfaceOfExactRuntimeSoundAndLayout

abbrev runtimeVerifyPriorOfExactRuntimeSoundAndLayout_toRuntimeExactPublicIOOpening :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.runtimeVerifyPriorOfExactRuntimeSoundAndLayout_toRuntimeExactPublicIOOpening

abbrev runtimeVerifyPriorOfExactRuntimeSoundAndLayout_acceptedOpens :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackendOpening.runtimeVerifyPriorOfExactRuntimeSoundAndLayout_acceptedOpens

end DirectParentOnlyProductionConcreteFPrimePriorBackendOpeningInterface

end DirectCcsFPrime
