import DirectCcsFPrime.DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness

/-!
Typed interface for the split raw public-IO soundness certificate.

Spec: `specs/DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.spec.md`
-/

namespace DirectCcsFPrime

namespace DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundnessInterface

abbrev ProductionContext :=
  DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.ProductionContext

abbrev PublicImage :=
  DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.PublicImage

abbrev ProofCarryingPriorProof :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.ProofCarryingPriorProof

abbrev ConcreteRawPublicIOVerifierChecks :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.ConcreteRawPublicIOVerifierChecks

abbrev RawPublicIOVerifierAccepted :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.RawPublicIOVerifierAccepted

abbrev RawPublicIOBoundStatementAccepted :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.RawPublicIOBoundStatementAccepted

abbrev ConcreteRawPublicIOSoundnessSurface :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.ConcreteRawPublicIOSoundnessSurface

abbrev rawPublicIOVerifierChecksOfRuntimeRawPublicIO :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.rawPublicIOVerifierChecksOfRuntimeRawPublicIO

abbrev rawPublicIOSoundnessSurfaceOfRuntimeRawPublicIO :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.rawPublicIOSoundnessSurfaceOfRuntimeRawPublicIO

abbrev ExactPublicIOLayoutBinding :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.ExactPublicIOLayoutBinding

abbrev rawPublicIOVerifierChecksOfExactPublicIO :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.rawPublicIOVerifierChecksOfExactPublicIO

abbrev rawPublicIOSoundnessSurfaceOfExactPublicIO :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.rawPublicIOSoundnessSurfaceOfExactPublicIO

abbrev runtimeRawPublicIOSurfaceOfSoundness :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.runtimeRawPublicIOSurfaceOfSoundness

abbrev RuntimeVerifyPriorOfRawPublicIOSoundness :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.RuntimeVerifyPriorOfRawPublicIOSoundness

abbrev RuntimeVerifyPriorOfExactPublicIORawSoundness :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.RuntimeVerifyPriorOfExactPublicIORawSoundness

abbrev runtimeVerifyPriorOfRawPublicIOSoundness_ofRuntimeRawPublicIO :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.runtimeVerifyPriorOfRawPublicIOSoundness_ofRuntimeRawPublicIO

abbrev runtimeVerifyPriorOfRawPublicIOSoundness_boundStatement :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.runtimeVerifyPriorOfRawPublicIOSoundness_boundStatement

abbrev runtimeVerifyPriorOfRawPublicIO_boundStatement :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.runtimeVerifyPriorOfRawPublicIO_boundStatement

abbrev runtimeVerifyPriorOfRawPublicIOSoundness_acceptedOpens :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.runtimeVerifyPriorOfRawPublicIOSoundness_acceptedOpens

abbrev certifiedPriorVerifierOfRawPublicIOSoundness :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.certifiedPriorVerifierOfRawPublicIOSoundness

abbrev certifiedPriorVerifierOfRawPublicIOSoundness_verify :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.certifiedPriorVerifierOfRawPublicIOSoundness_verify

abbrev certifiedPriorVerifierOfExactPublicIORawSoundness :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.certifiedPriorVerifierOfExactPublicIORawSoundness

abbrev certifiedPriorVerifierOfExactPublicIORawSoundness_verify :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.certifiedPriorVerifierOfExactPublicIORawSoundness_verify

abbrev runtimeVerifyPriorOfRawPublicIOSoundness_reaches_prior :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.runtimeVerifyPriorOfRawPublicIOSoundness_reaches_prior

abbrev proofFunctionalOfRawPublicIOSoundness :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.proofFunctionalOfRawPublicIOSoundness

abbrev runtimeVerifyPriorOfRawPublicIOSoundness_cannot_accept_unreachable_prior :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.runtimeVerifyPriorOfRawPublicIOSoundness_cannot_accept_unreachable_prior

abbrev runtimeVerifyPriorOfRawPublicIOSoundness_publicImageInvariants :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.runtimeVerifyPriorOfRawPublicIOSoundness_publicImageInvariants

abbrev runtimeVerifyPriorOfExactPublicIORawSoundness_boundStatement :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.runtimeVerifyPriorOfExactPublicIORawSoundness_boundStatement

abbrev runtimeVerifyPriorOfExactPublicIORawSoundness_acceptedOpens :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.runtimeVerifyPriorOfExactPublicIORawSoundness_acceptedOpens

abbrev runtimeVerifyPriorOfExactPublicIORawSoundness_reaches_prior :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.runtimeVerifyPriorOfExactPublicIORawSoundness_reaches_prior

abbrev runtimeVerifyPriorOfExactPublicIORawSoundness_cannot_accept_unreachable_prior :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.runtimeVerifyPriorOfExactPublicIORawSoundness_cannot_accept_unreachable_prior

abbrev runtimeVerifyPriorOfExactPublicIORawSoundness_publicImageInvariants :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.runtimeVerifyPriorOfExactPublicIORawSoundness_publicImageInvariants

abbrev proofFunctionalOfExactPublicIORawSoundness :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.proofFunctionalOfExactPublicIORawSoundness

abbrev certifiedSingleTerminalEndToEnd_ofRawPublicIOSoundnessLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.certifiedSingleTerminalEndToEnd_ofRawPublicIOSoundnessLatestStep

abbrev nonAggregatePrivateDecStageFacts_ofRawPublicIOSoundnessLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.nonAggregatePrivateDecStageFacts_ofRawPublicIOSoundnessLatestStep

abbrev section71StageTargetAuditTrail_ofRawPublicIOSoundnessLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.section71StageTargetAuditTrail_ofRawPublicIOSoundnessLatestStep

abbrev certifiedSingleTerminalEndToEnd_ofExactPublicIORawSoundnessLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.certifiedSingleTerminalEndToEnd_ofExactPublicIORawSoundnessLatestStep

abbrev nonAggregatePrivateDecStageFacts_ofExactPublicIORawSoundnessLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.nonAggregatePrivateDecStageFacts_ofExactPublicIORawSoundnessLatestStep

abbrev section71StageTargetAuditTrail_ofExactPublicIORawSoundnessLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.section71StageTargetAuditTrail_ofExactPublicIORawSoundnessLatestStep

abbrev certifiedSingleTerminalEndToEnd_ofRuntimeRawPublicIOSoundnessLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.certifiedSingleTerminalEndToEnd_ofRuntimeRawPublicIOSoundnessLatestStep

abbrev nonAggregatePrivateDecStageFacts_ofRuntimeRawPublicIOSoundnessLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.nonAggregatePrivateDecStageFacts_ofRuntimeRawPublicIOSoundnessLatestStep

abbrev section71StageTargetAuditTrail_ofRuntimeRawPublicIOSoundnessLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundness.section71StageTargetAuditTrail_ofRuntimeRawPublicIOSoundnessLatestStep

end DirectParentOnlyProductionConcreteFPrimePriorRawIOSoundnessInterface

end DirectCcsFPrime
