import DirectCcsFPrime.DirectParentOnlyProductionSuperNeoReuseReplayEndpoint

/-!
Typed interface for the Section 7.1-backed concrete-verifier replay endpoint.

Spec: `specs/DirectParentOnlyProductionSuperNeoReuseReplayEndpoint.spec.md`
-/

namespace DirectCcsFPrime

namespace DirectParentOnlyProductionSuperNeoReuseReplayEndpointInterface

abbrev ProductionContext :=
  DirectParentOnlyProductionSuperNeoReuseReplayEndpoint.ProductionContext

abbrev PriorAuthorityOpener :=
  @DirectParentOnlyProductionSuperNeoReuseReplayEndpoint.PriorAuthorityOpener

abbrev PriorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionSuperNeoReuseReplayEndpoint.PriorVerifierAuthorityOpening

abbrev AcceptedTerminalWithAuthorityOpener :=
  @DirectParentOnlyProductionSuperNeoReuseReplayEndpoint.AcceptedTerminalWithAuthorityOpener

abbrev AcceptedTerminalWithPriorVerifier :=
  @DirectParentOnlyProductionSuperNeoReuseReplayEndpoint.AcceptedTerminalWithPriorVerifier

abbrev SameProofReplayEndpoint :=
  @DirectParentOnlyProductionSuperNeoReuseReplayEndpoint.SameProofReplayEndpoint

abbrev PointwiseChildReplayBinding :=
  @DirectParentOnlyProductionSuperNeoReuseReplayEndpoint.PointwiseChildReplayBinding

abbrev ComputedStageReplayEvidence :=
  @DirectParentOnlyProductionSuperNeoReuseReplayEndpoint.ComputedStageReplayEvidence

abbrev pointwise_child_replay_binding_of_same_proof_replay_endpoint :=
  @DirectParentOnlyProductionSuperNeoReuseReplayEndpoint.pointwise_child_replay_binding_of_same_proof_replay_endpoint

abbrev computed_stage_replay_evidence_of_pointwise_child_replay_binding :=
  @DirectParentOnlyProductionSuperNeoReuseReplayEndpoint.computed_stage_replay_evidence_of_pointwise_child_replay_binding

abbrev computed_stage_replay_evidence_of_same_proof_replay_endpoint :=
  @DirectParentOnlyProductionSuperNeoReuseReplayEndpoint.computed_stage_replay_evidence_of_same_proof_replay_endpoint

abbrev piCCS_dec_knowledge_of_computed_stage_replay_evidence :=
  @DirectParentOnlyProductionSuperNeoReuseReplayEndpoint.piCCS_dec_knowledge_of_computed_stage_replay_evidence

abbrev piRLC_dec_knowledge_of_computed_stage_replay_evidence :=
  @DirectParentOnlyProductionSuperNeoReuseReplayEndpoint.piRLC_dec_knowledge_of_computed_stage_replay_evidence

abbrev pointwise_child_table_unique_of_pointwise_child_replay_binding :=
  @DirectParentOnlyProductionSuperNeoReuseReplayEndpoint.pointwise_child_table_unique_of_pointwise_child_replay_binding

abbrev same_proof_replay_endpoint_of_authority_opener :=
  @DirectParentOnlyProductionSuperNeoReuseReplayEndpoint.same_proof_replay_endpoint_of_authority_opener

abbrev pointwise_child_replay_binding_of_authority_opener :=
  @DirectParentOnlyProductionSuperNeoReuseReplayEndpoint.pointwise_child_replay_binding_of_authority_opener

abbrev pointwise_child_table_unique_of_authority_opener :=
  @DirectParentOnlyProductionSuperNeoReuseReplayEndpoint.pointwise_child_table_unique_of_authority_opener

abbrev authority_opener_replay_audit_package :=
  @DirectParentOnlyProductionSuperNeoReuseReplayEndpoint.authority_opener_replay_audit_package

abbrev same_proof_replay_endpoint_of_priorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionSuperNeoReuseReplayEndpoint.same_proof_replay_endpoint_of_priorVerifierAuthorityOpening

abbrev pointwise_child_replay_binding_of_priorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionSuperNeoReuseReplayEndpoint.pointwise_child_replay_binding_of_priorVerifierAuthorityOpening

abbrev pointwise_child_table_unique_of_priorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionSuperNeoReuseReplayEndpoint.pointwise_child_table_unique_of_priorVerifierAuthorityOpening

abbrev concrete_verifier_replay_audit_package_of_priorVerifierAuthorityOpening :=
  @DirectParentOnlyProductionSuperNeoReuseReplayEndpoint.concrete_verifier_replay_audit_package_of_priorVerifierAuthorityOpening

end DirectParentOnlyProductionSuperNeoReuseReplayEndpointInterface

end DirectCcsFPrime
