import DirectCcsFPrime.DirectParentOnlyProductionConcreteFPrimePriorRawProductionCompressedSoundness

/-!
Thin interface for compressed exact prior-verifier soundness.

This surface is the F' authority bridge from concrete exact verifier acceptance
to opened folded authority for the same `(steps, image)` pair.
-/

namespace DirectCcsFPrime

namespace DirectParentOnlyProductionConcreteFPrimePriorRawProductionCompressedSoundnessInterface

export DirectParentOnlyProductionConcreteFPrimePriorRawProduction (
  ProductionExactCompressedVerifierSoundness
  productionExactCompressedVerifierSoundness_acceptedAuditOpens
  productionExactCompressedVerifierSoundness_acceptedVerifierOpens
  productionExactVerifierAcceptedOfOpeningSurface_acceptedOpens
  productionExactCompressedVerifierSoundnessOfOpeningSurface
  productionExactCompressedVerifierSoundnessOfAuthorityCertificate
  productionExactAuthorityCertificateOfCompressedVerifierSoundness
  productionExactCompressedVerifierSoundnessOfAuthorityCertificate_acceptedVerifierOpens
  productionExactCompressedVerifierSoundnessOfAuthorityCertificate_acceptedAuditOpens
  productionExactRuntimeAuthoritySoundnessOfCompressedVerifierSoundness
  productionExactPriorOpeningSurfaceOfCompressedVerifierSoundness
  runtimeVerifyPriorOfProductionExactCompressedVerifierSoundness_acceptedOpens
  concreteRuntimeExactPublicIOSurfaceOfProductionExactCompressedVerifierSoundness
  runtimeVerifyPriorOfProductionExactCompressedVerifierSoundness_toConcreteRuntimeExactPublicIO
  runtimeVerifyPriorOfProductionExactCompressedVerifierSoundness_concreteRuntimeExactPublicIOEvidence
  certifiedPriorVerifierOfProductionExactCompressedVerifierSoundnessConcreteExact
  certifiedPriorVerifierOfProductionExactCompressedVerifierSoundnessConcreteExact_accepts
  certifiedPriorVerifierOfProductionExactCompressedVerifierSoundnessConcreteExact_acceptsVerifierAccepted
  soundVerifierOfProductionExactCompressedVerifierSoundnessConcreteExact
  soundVerifierOfProductionExactCompressedVerifierSoundnessConcreteExact_accepts_iff
  soundVerifierOfProductionExactCompressedVerifierSoundnessConcreteExact_acceptsVerifierAccepted
  soundVerifierOfProductionExactCompressedVerifierSoundnessConcreteExact_opensToFoldedAuthority
  soundVerifierOfProductionExactCompressedVerifierSoundnessConcreteExact_proofFunctional
  soundVerifierOfProductionExactCompressedVerifierSoundnessConcreteExact_sameProof
  productionExactCompressedVerifierSoundness_openAuthority_ne_none
  productionExactCompressedVerifierSoundness_openedAuthority_accepts_ofAccepted
  productionExactCompressedVerifierSoundness_bindsOpenedAuthoritySteps
  productionExactCompressedVerifierSoundness_bindsOpenedAuthorityImage
  productionExactCompressedVerifierSoundness_cannot_accept_without_opening
  productionExactCompressedVerifierSoundness_reaches_prior
  productionExactCompressedVerifierSoundness_publicImageInvariants
  productionExactCompressedVerifierSoundness_cannot_accept_unreachable_prior
  acceptedTerminalWithSoundVerifierOfProductionExactCompressedVerifierSoundnessConcreteExactLatestStep
  acceptedTerminalWithSoundVerifierOfProductionExactVerifierAcceptedCompressedVerifierSoundnessLatestStep
  certifiedSingleTerminalEndToEnd_ofProductionExactCompressedVerifierSoundnessConcreteExactLatestStep
  certifiedSingleTerminalEndToEnd_ofProductionExactVerifierAcceptedCompressedVerifierSoundnessLatestStep
  nonAggregatePrivateDecStageFacts_ofProductionExactCompressedVerifierSoundnessConcreteExactLatestStep
  nonAggregatePrivateDecStageFacts_ofProductionExactVerifierAcceptedCompressedVerifierSoundnessLatestStep
  section71StageTargetAuditTrail_ofProductionExactCompressedVerifierSoundnessConcreteExactLatestStep
  section71StageTargetAuditTrail_ofProductionExactVerifierAcceptedCompressedVerifierSoundnessLatestStep
)

end DirectParentOnlyProductionConcreteFPrimePriorRawProductionCompressedSoundnessInterface

end DirectCcsFPrime
