import DirectCcsFPrime.DirectParentOnlyProductionConcreteFPrimePriorRawProductionAuditSoundness

/-!
Thin interface for audit-first compressed verifier soundness consequences.
-/

namespace DirectCcsFPrime

namespace DirectParentOnlyProductionConcreteFPrimePriorRawProductionAuditSoundnessInterface

export DirectParentOnlyProductionConcreteFPrimePriorRawProduction (
  certifiedPriorVerifierOfProductionExactCompressedVerifierSoundnessConcreteExact_acceptsAudit
  soundVerifierOfProductionExactCompressedVerifierSoundnessConcreteExact_acceptsAudit
  productionExactCompressedVerifierSoundness_openAuthority_ne_none_ofAudit
  productionExactCompressedVerifierSoundness_openedAuthority_accepts_ofAudit
  productionExactCompressedVerifierSoundness_reaches_prior_ofAudit
  productionExactCompressedVerifierSoundness_publicImageInvariants_ofAudit
  productionExactCompressedVerifierSoundness_cannot_accept_unreachable_prior_ofAudit
  acceptedTerminalWithSoundVerifierOfProductionExactAuditCompressedVerifierSoundnessLatestStep
  certifiedSingleTerminalEndToEnd_ofProductionExactAuditCompressedVerifierSoundnessLatestStep
)

end DirectParentOnlyProductionConcreteFPrimePriorRawProductionAuditSoundnessInterface

end DirectCcsFPrime
