import DirectCcsFPrime.DirectTerminalSoundness

/-!
Typed interface for terminal direct CCS F' soundness composition.

Spec: `specs/DirectTerminalSoundness.spec.md`
-/

namespace DirectCcsFPrime

namespace DirectTerminalSoundnessInterface

abbrev AccHandle :=
  @DirectTerminalSoundness.AccHandle

abbrev AccumulatorStep :=
  @DirectTerminalSoundness.AccumulatorStep

abbrev Transition :=
  @DirectTerminalSoundness.Transition

abbrev Authority :=
  @DirectTerminalSoundness.Authority

abbrev terminal_reaches_final :=
  @DirectTerminalSoundness.terminal_reaches_final

abbrev terminal_reaches_final_and_latest_accumulator_functional :=
  @DirectTerminalSoundness.terminal_reaches_final_and_latest_accumulator_functional

abbrev terminal_reaches_final_and_latest_accumulator_functional_of_computed_stages :=
  @DirectTerminalSoundness.terminal_reaches_final_and_latest_accumulator_functional_of_computed_stages

abbrev terminal_reaches_final_and_latest_accumulator_functional_of_computed_stages_and_statement_commitment :=
  @DirectTerminalSoundness.terminal_reaches_final_and_latest_accumulator_functional_of_computed_stages_and_statement_commitment

abbrev terminal_reaches_final_and_latest_accumulator_functional_of_computed_stages_statement_commitment_and_assignment_opening :=
  @DirectTerminalSoundness.terminal_reaches_final_and_latest_accumulator_functional_of_computed_stages_statement_commitment_and_assignment_opening

abbrev terminal_reaches_final_and_latest_accumulator_functional_of_computed_stages_statement_commitment_assignment_opening_and_ajtai_binding :=
  @DirectTerminalSoundness.terminal_reaches_final_and_latest_accumulator_functional_of_computed_stages_statement_commitment_assignment_opening_and_ajtai_binding

abbrev terminal_reaches_final_and_latest_accumulator_functional_of_computed_stages_statement_commitment_assignment_opening_and_msis :=
  @DirectTerminalSoundness.terminal_reaches_final_and_latest_accumulator_functional_of_computed_stages_statement_commitment_assignment_opening_and_msis

abbrev terminal_reaches_final_and_latest_accumulator_functional_of_computed_stages_statement_commitment_ajtai_backed_commit_map_and_msis :=
  @DirectTerminalSoundness.terminal_reaches_final_and_latest_accumulator_functional_of_computed_stages_statement_commitment_ajtai_backed_commit_map_and_msis

end DirectTerminalSoundnessInterface

end DirectCcsFPrime
