import DirectCcsFPrime.DirectStageSemanticsContextual

/-!
Interface for verified direct CCS SuperNeo stage computations.

Spec: `specs/DirectStageSemantics.spec.md`
-/

namespace DirectCcsFPrime

namespace DirectStageSemanticsInterface

abbrev VerifiedStageComputations :=
  DirectStageSemantics.VerifiedStageComputations

abbrev ReusedStageComputations :=
  DirectStageSemantics.ReusedStageComputations

abbrev ContextualPiCCSOut :=
  DirectStageSemantics.ContextualPiCCSOut

abbrev ContextualReusedStageComputations :=
  DirectStageSemantics.ContextualReusedStageComputations

abbrev ReusedStageComputations_toVerified :=
  @DirectStageSemantics.ReusedStageComputations.toVerified

abbrev ContextualReusedStageComputations_toReused :=
  @DirectStageSemantics.ContextualReusedStageComputations.toReused

abbrev piCCSStrong :=
  @DirectStageSemantics.VerifiedStageComputations.piCCSStrong

abbrev piRLCWeak :=
  @DirectStageSemantics.VerifiedStageComputations.piRLCWeak

abbrev VerifiedPiCCS :=
  @DirectStageSemantics.VerifiedStageComputations.VerifiedPiCCS

abbrev VerifiedPiRLC :=
  @DirectStageSemantics.VerifiedStageComputations.VerifiedPiRLC

abbrev verifiedPiCCS_of_compute :=
  @DirectStageSemantics.VerifiedStageComputations.verifiedPiCCS_of_compute

abbrev verifiedPiRLC_of_compute :=
  @DirectStageSemantics.VerifiedStageComputations.verifiedPiRLC_of_compute

abbrev piCCSFunctional :=
  @DirectStageSemantics.VerifiedStageComputations.piCCSFunctional

abbrev piRLCFunctional :=
  @DirectStageSemantics.VerifiedStageComputations.piRLCFunctional

abbrev terminal_soundness_of_verified_stage_program_and_msis_of_prior_authority_sound :=
  @DirectStageSemantics.terminal_soundness_of_verified_stage_program_and_msis_of_prior_authority_sound

abbrev terminal_soundness_of_verified_stage_program_and_msis_of_compressed_prior_verifier_sound :=
  @DirectStageSemantics.terminal_soundness_of_verified_stage_program_and_msis_of_compressed_prior_verifier_sound

abbrev terminal_soundness_of_verified_stage_program_and_msis_of_compressed_prior_verifier_sound_with_public_image_invariants :=
  @DirectStageSemantics.terminal_soundness_of_verified_stage_program_and_msis_of_compressed_prior_verifier_sound_with_public_image_invariants

abbrev terminal_soundness_of_reused_stage_program_and_msis_of_compressed_prior_verifier_sound_with_public_image_invariants :=
  @DirectStageSemantics.terminal_soundness_of_reused_stage_program_and_msis_of_compressed_prior_verifier_sound_with_public_image_invariants

abbrev terminal_soundness_of_contextual_reused_stage_program_and_msis_of_prior_authority_sound_with_public_image_invariants :=
  @DirectStageSemantics.terminal_soundness_of_contextual_reused_stage_program_and_msis_of_prior_authority_sound_with_public_image_invariants

abbrev terminal_soundness_of_contextual_reused_stage_program_and_msis_of_compressed_prior_verifier_sound_with_public_image_invariants :=
  @DirectStageSemantics.terminal_soundness_of_contextual_reused_stage_program_and_msis_of_compressed_prior_verifier_sound_with_public_image_invariants

abbrev terminal_soundness_of_contextual_reused_stage_program_and_msis_of_sound_verifier_with_public_image_invariants :=
  @DirectStageSemantics.terminal_soundness_of_contextual_reused_stage_program_and_msis_of_sound_verifier_with_public_image_invariants

abbrev terminal_soundness_of_contextual_reused_stage_program_and_msis_of_parent_hash_and_sound_verifier_with_public_image_invariants :=
  @DirectStageSemantics.terminal_soundness_of_contextual_reused_stage_program_and_msis_of_parent_hash_and_sound_verifier_with_public_image_invariants

abbrev terminal_soundness_of_verified_stage_program_and_msis :=
  @DirectStageSemantics.terminal_soundness_of_verified_stage_program_and_msis

abbrev terminal_soundness_of_verified_stage_program_and_msis_with_public_image_invariants :=
  @DirectStageSemantics.terminal_soundness_of_verified_stage_program_and_msis_with_public_image_invariants

abbrev terminal_soundness_of_reused_stage_program_and_msis_with_public_image_invariants :=
  @DirectStageSemantics.terminal_soundness_of_reused_stage_program_and_msis_with_public_image_invariants

abbrev terminal_soundness_of_contextual_reused_stage_program_and_msis_with_public_image_invariants :=
  @DirectStageSemantics.terminal_soundness_of_contextual_reused_stage_program_and_msis_with_public_image_invariants

end DirectStageSemanticsInterface

end DirectCcsFPrime
