import DirectCcsFPrime.DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier

/-!
Typed interface for the Section 7.1-backed certified compressed verifier.

Spec: `specs/DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.spec.md`
-/

namespace DirectCcsFPrime

namespace DirectParentOnlyProductionSuperNeoReuseCertifiedVerifierInterface

abbrev ProductionContext :=
  DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.ProductionContext

abbrev CertifiedPriorVerifier :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier

abbrev CertifiedPriorVerifier.AcceptedTerminal :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.AcceptedTerminal

abbrev CertifiedPriorVerifier.AlternateLatestStep :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.AlternateLatestStep

abbrev CertifiedPriorVerifier.ComputedStageEndpointEvidence :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.ComputedStageEndpointEvidence

abbrev CertifiedPriorVerifier.ExplicitReplayNoSwapEvidence :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.ExplicitReplayNoSwapEvidence

abbrev CertifiedPriorVerifier.ofAcceptedOpens :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.ofAcceptedOpens

abbrev CertifiedPriorVerifier.ofAcceptedOpens_verify :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.ofAcceptedOpens_verify

abbrev CertifiedPriorVerifier.soundVerifier :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.soundVerifier

abbrev CertifiedPriorVerifier.soundVerifier_accepts_iff :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.soundVerifier_accepts_iff

abbrev CertifiedPriorVerifier.verifyAcceptsIff :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.verifyAcceptsIff

abbrev CertifiedPriorVerifier.acceptedTerminalWithSoundVerifier :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.acceptedTerminalWithSoundVerifier

abbrev CertifiedPriorVerifier.proofFunctional :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.proofFunctional

abbrev CertifiedPriorVerifier.sameProofFunctional :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.sameProofFunctional

abbrev CertifiedPriorVerifier.soundVerifierProofFunctional :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.soundVerifierProofFunctional

abbrev CertifiedPriorVerifier.openedAuthority :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.openedAuthority

abbrev CertifiedPriorVerifier.priorAuthority :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.priorAuthority

abbrev CertifiedPriorVerifier.openAuthority_ne_none :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.openAuthority_ne_none

abbrev CertifiedPriorVerifier.priorProofOpens :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.priorProofOpens

abbrev CertifiedPriorVerifier.openedAuthority_accepts_of_open :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.openedAuthority_accepts_of_open

abbrev CertifiedPriorVerifier.priorAuthorityAccepts :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.priorAuthorityAccepts

abbrev CertifiedPriorVerifier.reaches_prior :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.reaches_prior

abbrev CertifiedPriorVerifier.priorReachable :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.priorReachable

abbrev CertifiedPriorVerifier.cannot_accept_unreachable_prior :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.cannot_accept_unreachable_prior

abbrev CertifiedPriorVerifier.rejectsUnreachablePrior :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.rejectsUnreachablePrior

abbrev CertifiedPriorVerifier.auditedPublicEndpointWithStageAudit :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.auditedPublicEndpointWithStageAudit

abbrev CertifiedPriorVerifier.terminalEndpointAudit :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.terminalEndpointAudit

abbrev CertifiedPriorVerifier.computedStageEndpointEvidence :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.computedStageEndpointEvidence

abbrev CertifiedPriorVerifier.terminalStageEvidence :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.terminalStageEvidence

abbrev CertifiedPriorVerifier.terminalAuditPackage :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.terminalAuditPackage

abbrev CertifiedPriorVerifier.terminalAudit :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.terminalAudit

abbrev CertifiedPriorVerifier.terminalAuditPackage_ofAcceptedOpens :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.terminalAuditPackage_ofAcceptedOpens

abbrev CertifiedPriorVerifier.terminalAuditOfAcceptedOpens :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.terminalAuditOfAcceptedOpens

abbrev CertifiedPriorVerifier.terminalPointwiseChildTableUnique :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.terminalPointwiseChildTableUnique

abbrev CertifiedPriorVerifier.terminalChildNoSwap :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.terminalChildNoSwap

abbrev CertifiedPriorVerifier.terminalPointwiseChildTableUnique_ofAcceptedOpens :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.terminalPointwiseChildTableUnique_ofAcceptedOpens

abbrev CertifiedPriorVerifier.terminalChildNoSwapOfAcceptedOpens :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.terminalChildNoSwapOfAcceptedOpens

abbrev CertifiedPriorVerifier.sameProofReplayEndpoint :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.sameProofReplayEndpoint

abbrev CertifiedPriorVerifier.sameProofReplay :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.sameProofReplay

abbrev CertifiedPriorVerifier.pointwiseChildReplayBinding :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.pointwiseChildReplayBinding

abbrev CertifiedPriorVerifier.childReplayBinding :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.childReplayBinding

abbrev CertifiedPriorVerifier.computedStageReplayEvidence :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.computedStageReplayEvidence

abbrev CertifiedPriorVerifier.replayStageEvidence :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.replayStageEvidence

abbrev CertifiedPriorVerifier.explicitReplayNoSwapEvidence_of_computedStageReplayEvidence :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.explicitReplayNoSwapEvidence_of_computedStageReplayEvidence

abbrev CertifiedPriorVerifier.noSwapFromReplayEvidence :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.noSwapFromReplayEvidence

abbrev CertifiedPriorVerifier.pointwiseChildTableUnique :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.pointwiseChildTableUnique

abbrev CertifiedPriorVerifier.replayChildNoSwap :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.replayChildNoSwap

abbrev CertifiedPriorVerifier.pointwiseChildTableUnique_ofAcceptedOpens :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.pointwiseChildTableUnique_ofAcceptedOpens

abbrev CertifiedPriorVerifier.replayChildNoSwapOfAcceptedOpens :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.replayChildNoSwapOfAcceptedOpens

abbrev CertifiedPriorVerifier.replayAuditPackage :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.replayAuditPackage

abbrev CertifiedPriorVerifier.replayAudit :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.replayAudit

abbrev CertifiedPriorVerifier.replayAuditPackage_ofAcceptedOpens :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.replayAuditPackage_ofAcceptedOpens

abbrev CertifiedPriorVerifier.replayAuditOfAcceptedOpens :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.replayAuditOfAcceptedOpens

abbrev CertifiedPriorVerifier.replayAuditPackageWithExplicitNoSwap_ofAcceptedOpens :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.replayAuditPackageWithExplicitNoSwap_ofAcceptedOpens

abbrev CertifiedPriorVerifier.replayAuditWithNoSwapOfAcceptedOpens :=
  @DirectParentOnlyProductionSuperNeoReuseCertifiedVerifier.CertifiedPriorVerifier.replayAuditWithNoSwapOfAcceptedOpens

end DirectParentOnlyProductionSuperNeoReuseCertifiedVerifierInterface

end DirectCcsFPrime
