//! Lean renderer for the exact native public-link source program.

use std::fmt::Write;

use neo_fold_clean::paper::f_prime::r1cs::{
    f_prime_public_input_link_program, FPrimePublicInputLayout, FPrimePublicInputLinkInstruction,
};

const SCHEMA: u32 = 1;

pub fn checked_canonical_public_link_program() -> String {
    let program = f_prime_public_input_link_program(FPrimePublicInputLayout::plain());
    assert_eq!(program.len(), 6);
    assert_eq!(
        program
            .iter()
            .copied()
            .map(FPrimePublicInputLinkInstruction::scalar_obligation_count)
            .sum::<usize>(),
        273,
    );
    render(&program)
}

fn render(program: &[FPrimePublicInputLinkInstruction; 6]) -> String {
    let mut out = String::new();
    writeln!(
        out,
        "import Nightstream.Implementation.Rust.CanonicalConformance.NativeStep.\
         CanonicalPublicInputLinkProgram\n"
    )
    .unwrap();
    writeln!(
        out,
        "/-!\nGenerated by the Rust native public-link program drift gate.\n\
         This is the exact six-instruction value interpreted by production.\n\
         It is program data, not protocol authority. Do not edit by hand.\n-/\n"
    )
    .unwrap();
    writeln!(
        out,
        "namespace Nightstream.Implementation.Rust.CanonicalConformance.NativeStep.\
         Generated.CanonicalPublicInputLinkProgram\n\n\
         open Nightstream.Implementation.Rust.CanonicalConformance.NativeStep.\
         CanonicalPublicInputLinkProgram\n"
    )
    .unwrap();
    writeln!(out, "def schema : Nat := {SCHEMA}\n").unwrap();
    writeln!(out, "def plain : Program :=\n  [").unwrap();
    for (index, instruction) in program.iter().enumerate() {
        let separator = if index + 1 == program.len() { "" } else { "," };
        writeln!(out, "    {}{separator}", lean_instruction(*instruction)).unwrap();
    }
    writeln!(out, "  ]\n").unwrap();
    writeln!(
        out,
        "end Nightstream.Implementation.Rust.CanonicalConformance.NativeStep.\
         Generated.CanonicalPublicInputLinkProgram"
    )
    .unwrap();
    out
}

fn lean_instruction(instruction: FPrimePublicInputLinkInstruction) -> String {
    match instruction {
        FPrimePublicInputLinkInstruction::ExpectedPublicInputLen { expected } => {
            format!(".expectedPublicInputLen {expected}")
        }
        FPrimePublicInputLinkInstruction::ClaimMIn { expected } => {
            format!(".claimMIn {expected}")
        }
        FPrimePublicInputLinkInstruction::ClaimXLen { expected } => {
            format!(".claimXLen {expected}")
        }
        FPrimePublicInputLinkInstruction::AffineOne { claim_index } => {
            format!(".affineOne {claim_index}")
        }
        FPrimePublicInputLinkInstruction::BodyRange {
            expected_offset,
            claim_offset,
            len,
        } => {
            format!(".bodyRange {expected_offset} {claim_offset} {len}")
        }
        FPrimePublicInputLinkInstruction::PaddingZeroRange { claim_offset, len } => {
            format!(".paddingZeroRange {claim_offset} {len}")
        }
    }
}
