//! Lean renderer for the exact native `state_x_out` preimage program.

use std::fmt::Write;

use neo_fold_clean::paper::digest::{state_x_out_preimage_program, StateXOutDigestMode, StateXOutPreimageInstruction};

const SCHEMA: u32 = 1;

pub fn checked_state_x_out_programs() -> String {
    let stateless_plain = state_x_out_preimage_program(StateXOutDigestMode::Stateless, false);
    let stateless_nebula = state_x_out_preimage_program(StateXOutDigestMode::Stateless, true);
    let stateful_plain = state_x_out_preimage_program(StateXOutDigestMode::Stateful, false);
    let stateful_nebula = state_x_out_preimage_program(StateXOutDigestMode::Stateful, true);

    assert_program(&stateless_plain, 8, 23);
    assert_program(&stateless_nebula, 10, 28);
    assert_program(&stateful_plain, 9, 27);
    assert_program(&stateful_nebula, 11, 32);

    render([
        ("statelessPlain", stateless_plain),
        ("statelessNebula", stateless_nebula),
        ("statefulPlain", stateful_plain),
        ("statefulNebula", stateful_nebula),
    ])
}

fn assert_program(program: &[StateXOutPreimageInstruction], instruction_count: usize, field_count: usize) {
    assert_eq!(program.len(), instruction_count);
    assert_eq!(
        program
            .iter()
            .copied()
            .map(StateXOutPreimageInstruction::field_count)
            .sum::<usize>(),
        field_count,
    );
}

fn render(programs: [(&str, Vec<StateXOutPreimageInstruction>); 4]) -> String {
    let mut out = String::new();
    writeln!(
        out,
        "import Nightstream.Implementation.Rust.CanonicalConformance.NativeStep.StateXOutProgram\n"
    )
    .unwrap();
    writeln!(
        out,
        "/-!\nGenerated by the Rust `state_x_out` source-program drift gate.\n\
         These are exact program values, not protocol authority. Do not edit by hand.\n-/\n"
    )
    .unwrap();
    writeln!(
        out,
        "namespace Nightstream.Implementation.Rust.CanonicalConformance.NativeStep.\
         Generated.StateXOutProgram\n\n\
         open Nightstream.Implementation.Rust.CanonicalConformance.NativeStep.\
         StateXOutProgram\n"
    )
    .unwrap();
    writeln!(out, "def schema : Nat := {SCHEMA}\n").unwrap();
    for (name, program) in programs {
        writeln!(out, "def {name} : Program :=\n  [").unwrap();
        for (index, instruction) in program.iter().enumerate() {
            let separator = if index + 1 == program.len() { "" } else { "," };
            writeln!(out, "    {}{separator}", lean_instruction(*instruction)).unwrap();
        }
        writeln!(out, "  ]\n").unwrap();
    }
    writeln!(
        out,
        "end Nightstream.Implementation.Rust.CanonicalConformance.NativeStep.\
         Generated.StateXOutProgram"
    )
    .unwrap();
    out
}

fn lean_instruction(instruction: StateXOutPreimageInstruction) -> String {
    match instruction {
        StateXOutPreimageInstruction::Domain { value } => {
            format!(".domain {value}")
        }
        StateXOutPreimageInstruction::VerifierDigest => ".verifierDigest".to_owned(),
        StateXOutPreimageInstruction::PiCcsHeader => ".piCcsHeader".to_owned(),
        StateXOutPreimageInstruction::ChunkCountHalves => ".chunkCountHalves".to_owned(),
        StateXOutPreimageInstruction::StepCountHalves => ".stepCountHalves".to_owned(),
        StateXOutPreimageInstruction::PcHalves => ".pcHalves".to_owned(),
        StateXOutPreimageInstruction::CurrentBoundary => ".currentBoundary".to_owned(),
        StateXOutPreimageInstruction::SemanticState => ".semanticState".to_owned(),
        StateXOutPreimageInstruction::Construction2Accumulator => ".construction2Accumulator".to_owned(),
        StateXOutPreimageInstruction::NebulaPresentMarker { value } => {
            format!(".nebulaPresentMarker {value}")
        }
        StateXOutPreimageInstruction::NebulaDigest => ".nebulaDigest".to_owned(),
    }
}
