//! Lean renderer for the exact terminal-link R1CS source program.

use std::fmt::Write;

use neo_fold_clean::paper::f_prime::r1cs::{
    f_prime_terminal_link_program, FPrimePublicInputLayout, FPrimeTerminalLinkInstruction,
};

const SCHEMA: u32 = 1;

pub fn checked_terminal_link_program() -> String {
    let program = f_prime_terminal_link_program(FPrimePublicInputLayout::plain());
    assert_eq!(program.len(), 3);
    assert_eq!(
        program
            .iter()
            .copied()
            .map(FPrimeTerminalLinkInstruction::scalar_obligation_count)
            .sum::<usize>(),
        270,
    );
    render(&program)
}

fn render(program: &[FPrimeTerminalLinkInstruction; 3]) -> String {
    let mut out = String::new();
    writeln!(
        out,
        "import Nightstream.Implementation.Rust.CanonicalConformance.TerminalLink.Program\n"
    )
    .unwrap();
    writeln!(
        out,
        "/-!\nGenerated by the Rust terminal-link program drift gate.\n\
         This is the exact three-instruction value expanded for every fresh claim.\n\
         It is program data, not protocol authority. Do not edit by hand.\n-/\n"
    )
    .unwrap();
    writeln!(
        out,
        "namespace Nightstream.Implementation.Rust.CanonicalConformance.TerminalLink.\
         Generated.Program\n\n\
         open Nightstream.Implementation.Rust.CanonicalConformance.TerminalLink.Program\n"
    )
    .unwrap();
    writeln!(out, "def schema : Nat := {SCHEMA}\n").unwrap();
    writeln!(out, "def plain : Program :=\n  [").unwrap();
    for (index, instruction) in program.iter().enumerate() {
        let separator = if index + 1 == program.len() { "" } else { "," };
        writeln!(out, "    {}{separator}", lean_instruction(*instruction)).unwrap();
    }
    writeln!(out, "  ]\n").unwrap();
    writeln!(
        out,
        "end Nightstream.Implementation.Rust.CanonicalConformance.TerminalLink.\
         Generated.Program"
    )
    .unwrap();
    out
}

fn lean_instruction(instruction: FPrimeTerminalLinkInstruction) -> String {
    match instruction {
        FPrimeTerminalLinkInstruction::AffineOne { claim_offset } => {
            format!(".affineOne {claim_offset}")
        }
        FPrimeTerminalLinkInstruction::BodyRange {
            claim_offset,
            producer_offset,
            len,
        } => {
            format!(".bodyRange {claim_offset} {producer_offset} {len}")
        }
        FPrimeTerminalLinkInstruction::PaddingZeroRange { claim_offset, len } => {
            format!(".paddingZeroRange {claim_offset} {len}")
        }
    }
}
