//! Lean renderer for an exact two-claim production terminal-link row capture.

#[allow(dead_code)]
#[path = "../../gadgets/lean_artifact_support.rs"]
mod lean_artifact_support;

use std::fmt::Write;

use lean_artifact_support::lean_rows;
use neo_fold_clean::engine::decider::__test_isolation::enforce_terminal_latest_link_against;
use neo_fold_clean::paper::f_prime::r1cs::{F_PRIME_ENC_INST_BITS, F_PRIME_SUPERNEO_PUBLIC_INPUT_LEN};
use neo_math::F;
use p3_field::PrimeCharacteristicRing;

const SCHEMA: u32 = 1;
const BATCH_SIZE: usize = 2;

pub fn checked_terminal_link_rows_two() -> String {
    let producer_bits = (0..F_PRIME_ENC_INST_BITS)
        .map(|bit| F::from_u64((bit % 2) as u64))
        .collect::<Vec<_>>();
    let mut claim = Vec::with_capacity(F_PRIME_SUPERNEO_PUBLIC_INPUT_LEN);
    claim.push(F::ONE);
    claim.extend(producer_bits.iter().copied());
    claim.resize(F_PRIME_SUPERNEO_PUBLIC_INPUT_LEN, F::ZERO);
    let fresh = vec![claim.clone(), claim];
    let builder = enforce_terminal_latest_link_against(&producer_bits, &fresh).expect("emit two-claim terminal link");

    assert_eq!(builder.rows(), BATCH_SIZE * F_PRIME_SUPERNEO_PUBLIC_INPUT_LEN);
    assert_eq!(
        builder.cols(),
        1 + F_PRIME_ENC_INST_BITS + BATCH_SIZE * F_PRIME_SUPERNEO_PUBLIC_INPUT_LEN
    );
    assert!(builder.unconstrained_columns().is_empty());
    assert!(builder.is_satisfied());

    render(&builder)
}

fn render(builder: &neo_fold_clean::engine::r1cs_circuit::R1csBuilder) -> String {
    let mut out = String::new();
    writeln!(out, "import Nightstream.Implementation.R1CS.Core.Semantics\n").unwrap();
    writeln!(
        out,
        "/-!\nGenerated by the production terminal-link row drift gate.\n\
         The rows come from the private production emitter through its test-only\n\
         isolation wrapper. This bounded capture is artifact evidence, not protocol\n\
         authority or a universal theorem about compiled Rust. Do not edit by hand.\n-/\n"
    )
    .unwrap();
    writeln!(
        out,
        "namespace Nightstream.Implementation.Rust.CanonicalConformance.TerminalLink.\
         Generated.RowsTwo\n\n\
         open Nightstream.Implementation.R1CS\n"
    )
    .unwrap();
    writeln!(out, "def schema : Nat := {SCHEMA}").unwrap();
    writeln!(out, "def batchSize : Nat := {BATCH_SIZE}").unwrap();
    writeln!(out, "def rowCount : Nat := {}", builder.rows()).unwrap();
    writeln!(out, "def columnCount : Nat := {}", builder.cols()).unwrap();
    writeln!(out, "def rows : List Row :=\n  {}\n", lean_rows(builder)).unwrap();
    writeln!(
        out,
        "end Nightstream.Implementation.Rust.CanonicalConformance.TerminalLink.\
         Generated.RowsTwo"
    )
    .unwrap();
    out
}
