import Nightstream.Implementation.NebulaV2.NIFS.Core.Concrete

set_option autoImplicit false

namespace tests.NebulaV2ProductConcreteNifs

#check Nightstream.Implementation.NebulaV2.ProductConcreteNifs.RelationArtifact
#check Nightstream.Implementation.NebulaV2.ProductConcreteNifs.key
#check Nightstream.Implementation.NebulaV2.ProductConcreteNifs.key_arity_total
#check Nightstream.Implementation.NebulaV2.ProductConcreteNifs.key_initialTranscriptState
#check Nightstream.Implementation.NebulaV2.ProductConcreteNifs.key_publicInputState
#check Nightstream.Implementation.NebulaV2.ProductConcreteNifs.key_matrixSource
#check Nightstream.Implementation.NebulaV2.ProductConcreteNifs.key_commitment_map

end tests.NebulaV2ProductConcreteNifs
