import Nightstream.Implementation.NebulaV2.NIFS.Core.ExactConfiguration

set_option autoImplicit false

namespace tests.NebulaV2ProductExactNifsConfiguration

#check Nightstream.Implementation.NebulaV2.ProductExactNifsConfiguration.configuration
#check Nightstream.Implementation.NebulaV2.ProductExactNifsConfiguration.selected
#check Nightstream.Implementation.NebulaV2.ProductExactNifsConfiguration.configuration_decoder_exact
#check Nightstream.Implementation.NebulaV2.ProductExactNifsConfiguration.configuration_key_exact
#check Nightstream.Implementation.NebulaV2.ProductExactNifsConfiguration.configuration_samplerCheck_exact
#check Nightstream.Implementation.NebulaV2.ProductExactNifsConfiguration.accepted_input_has_exact_fields

end tests.NebulaV2ProductExactNifsConfiguration
