import Nightstream.Implementation.NebulaV2.NIFS.Core.PaperSelection

set_option autoImplicit false

namespace tests.NebulaV2ProductPaperNifsSelection

open Nightstream.Implementation.NebulaV2.ProductPaperNifsSelection

#check selected
#check selected_verify_block_eq_false_of_sampler_rejected
#check verifyClaim_sound
#check verifyClaim_complete

end tests.NebulaV2ProductPaperNifsSelection
