import Nightstream.Implementation.Nebula.Production.NIFS.PiRLC.ParentBridgeFor

set_option autoImplicit false

namespace tests.NebulaProductionProductPiRlcParentBridgeFor

open Nightstream.Implementation.Nebula.ProductionProductPiRlcParentBridgeFor

#check challenges_eq_selected
#check parentFields_of_rows

end tests.NebulaProductionProductPiRlcParentBridgeFor
