import Nightstream.Implementation.R1CS.Canonical.KSplitNcFeInitial
import Nightstream.Implementation.R1CS.Canonical.KSplitNcFeTerminal
import Nightstream.Implementation.R1CS.Canonical.KSplitNcNcEndpoint
import Nightstream.Implementation.R1CS.Canonical.KSplitNcOperational

/-!
Contract: compose the four verifier-owned Split-NC endpoint computations.

The transcript owns every challenge column and every final SumCheck point.
`AuthorityColumns` owns only direct reads of the public PiCCS input and raw
output message.  Its decoding relation is intended to be constructed by the
selected call-frame codec; it contains no verifier result, endpoint equation,
or acceptance proposition.

Satisfaction of `rows` constructs `KSplitNcOperational.EndpointAgrees`.
Thus the operational verifier no longer accepts its four endpoint equations
as caller data.
-/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace Nightstream.Implementation.R1CS.Canonical.KSplitNcEndpoints

open Nightstream.Implementation.R1CS
open Nightstream.Implementation.R1CS.Canonical.KMul
open Nightstream.Implementation.Lowering.FPrimeFixedOne.Encoding.KFixedPhaseSemanticOccurrence
open Nightstream.SuperNeo
open Nightstream.SuperNeo.Concrete
open Nightstream.SuperNeo.Folding.PiCCS.OutputClaims
open Nightstream.SuperNeo.Folding.PiCCS.PaperJoint
open Nightstream.SuperNeo.Folding.PiCCS.SplitNc
open Nightstream.SuperNeo.Folding.PiCCS.SplitNc.Verifier
open Nightstream.SuperNeo.Folding.PiCCS.SplitNc.Verifier.Protocol.TranscriptAuthority.BlockLane

private abbrev KColumns :=
  Nightstream.Implementation.R1CS.ProjectionProgram.KColumns

/-- Direct physical views of the semantic values not generated by the
Fiat--Shamir transcript. -/
structure AuthorityColumns (shape : SemanticShape) where
  priorPoint : Fin shape.rowVariables → Carried
  claimedYRing :
    Fin shape.runningCount → Fin shape.matrixCount →
      Fin ringDegree → Carried
  outputYRing :
    Fin shape.sourceCount → Fin shape.matrixCount →
      Fin ringDegree → Carried
  outputYZcol :
    Fin shape.sourceCount → Fin ringDegree → Carried

/-- All endpoint-row inputs around one exact transcript occurrence. -/
structure Input
    {shape : SemanticShape}
    (polynomialInput : PublicInput shape) (domains : Domains) where
  transcript : KSplitNcTranscript.Input polynomialInput domains
  authority : AuthorityColumns shape
  frameBase : Nat

/-- Select one carried extension value from an exact-width transcript list. -/
def carriedAt
    {count : Nat}
    (columns : List KColumns) (length : columns.length = count)
    (index : Fin count) : Carried :=
  carried
    (columns.get
      ⟨index.val, by
        rw [length]
        exact index.isLt⟩)

theorem decoded_carriedAt
    {count : Nat}
    (columns : List KColumns) (length : columns.length = count)
    (assignment : Nat → Nat) (index : Fin count) :
    KPointEquality.decoded assignment
        (carriedAt columns length index) =
      (KSplitNcTranscriptSemantics.decodedColumnList assignment columns).get
        ⟨index.val, by
          rw [KSplitNcTranscriptSemantics.decodedColumnList_length, length]
          exact index.isLt⟩ := by
  unfold carriedAt KPointEquality.decoded
  rw [decodeCarried_carried]
  simp [KSplitNcTranscriptSemantics.decodedColumnList,
    KSplitNcTranscriptSemantics.decodedColumns]

@[simp] theorem feRowChallenges_length
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : KSplitNcTranscript.Input polynomialInput domains) :
    (KSplitNcTranscript.feRowReplay input).challenges.length =
      shape.rowVariables := by
  unfold KSplitNcTranscript.feRowReplay
  rw [KSplitNcTranscript.replayRounds_challenges_length]
  simp

@[simp] theorem feLaneChallenges_length
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : KSplitNcTranscript.Input polynomialInput domains) :
    (KSplitNcTranscript.feLaneReplay input).challenges.length =
      domains.laneVariables := by
  unfold KSplitNcTranscript.feLaneReplay
  rw [KSplitNcTranscript.replayRounds_challenges_length]
  simp

@[simp] theorem ncBlockChallenges_length
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : KSplitNcTranscript.Input polynomialInput domains) :
    (KSplitNcTranscript.ncBlockReplay input).challenges.length =
      domains.blockVariables := by
  unfold KSplitNcTranscript.ncBlockReplay
  rw [KSplitNcTranscript.replayRounds_challenges_length]
  simp [Domains.nc]

@[simp] theorem ncLaneChallenges_length
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : KSplitNcTranscript.Input polynomialInput domains) :
    (KSplitNcTranscript.ncLaneReplay input).challenges.length =
      domains.laneVariables := by
  unfold KSplitNcTranscript.ncLaneReplay
  rw [KSplitNcTranscript.replayRounds_challenges_length]
  simp [Domains.nc]

def coreAlpha
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : Input polynomialInput domains) :
    Fin domains.laneVariables → Carried :=
  carriedAt (KSplitNcTranscript.coreReplay input.transcript).alpha
    (KSplitNcTranscript.Core.alpha_length
      (KSplitNcTranscript.coreReplay input.transcript))

def coreBetaA
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : Input polynomialInput domains) :
    Fin domains.laneVariables → Carried :=
  carriedAt (KSplitNcTranscript.coreReplay input.transcript).betaA
    (KSplitNcTranscript.Core.betaA_length
      (KSplitNcTranscript.coreReplay input.transcript))

def coreBetaR
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : Input polynomialInput domains) :
    Fin shape.rowVariables → Carried :=
  carriedAt (KSplitNcTranscript.coreReplay input.transcript).betaR
    (KSplitNcTranscript.Core.betaR_length
      (KSplitNcTranscript.coreReplay input.transcript))

def coreBetaBlock
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : Input polynomialInput domains) :
    Fin domains.blockVariables → Carried :=
  carriedAt (KSplitNcTranscript.coreReplay input.transcript).betaBlock
    (KSplitNcTranscript.Core.betaBlock_length
      (KSplitNcTranscript.coreReplay input.transcript))

def feRowPoint
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : Input polynomialInput domains) :
    Fin shape.rowVariables → Carried :=
  carriedAt (KSplitNcTranscript.feRowReplay input.transcript).challenges
    (feRowChallenges_length input.transcript)

def feLanePoint
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : Input polynomialInput domains) :
    Fin domains.laneVariables → Carried :=
  carriedAt (KSplitNcTranscript.feLaneReplay input.transcript).challenges
    (feLaneChallenges_length input.transcript)

def ncBlockPoint
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : Input polynomialInput domains) :
    Fin domains.blockVariables → Carried :=
  carriedAt (KSplitNcTranscript.ncBlockReplay input.transcript).challenges
    (ncBlockChallenges_length input.transcript)

def ncLanePoint
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : Input polynomialInput domains) :
    Fin domains.laneVariables → Carried :=
  carriedAt (KSplitNcTranscript.ncLaneReplay input.transcript).challenges
    (ncLaneChallenges_length input.transcript)

def feInitialInput
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : Input polynomialInput domains) :
    KSplitNcFeInitial.Input shape domains.fe where
  gamma := carried (KSplitNcTranscript.coreReplay input.transcript).gamma
  alpha := coreAlpha input
  claimedYRing := input.authority.claimedYRing
  initial := carried input.transcript.fe.initial
  frameBase := input.frameBase

def feTerminalBase
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : Input polynomialInput domains) : Nat :=
  input.frameBase +
    KSplitNcFeInitial.allocationWidth (feInitialInput input)

def feTerminalInput
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : Input polynomialInput domains) :
    KSplitNcFeTerminal.Input polynomialInput domains.fe where
  gamma := carried (KSplitNcTranscript.coreReplay input.transcript).gamma
  alpha := coreAlpha input
  betaA := coreBetaA input
  betaR := coreBetaR input
  pointLane := feLanePoint input
  pointRow := feRowPoint input
  priorPoint := input.authority.priorPoint
  messageYRing := input.authority.outputYRing
  terminal := carried input.transcript.fe.terminal
  frameBase := feTerminalBase input

def ncBase
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : Input polynomialInput domains) : Nat :=
  feTerminalBase input +
    KSplitNcFeTerminal.allocationWidth (feTerminalInput input)

def ncInput
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : Input polynomialInput domains) :
    KSplitNcNcEndpoint.Input shape domains.nc where
  gamma := carried (KSplitNcTranscript.coreReplay input.transcript).gamma
  betaBlock := coreBetaBlock input
  betaA := coreBetaA input
  pointBlock := ncBlockPoint input
  pointLane := ncLanePoint input
  messageYZcol := input.authority.outputYZcol
  initial := carried input.transcript.nc.initial
  terminal := carried input.transcript.nc.terminal
  frameBase := ncBase input

def rowGroups
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : Input polynomialInput domains) : List (List Row) :=
  [
    KSplitNcFeInitial.rows (feInitialInput input),
    KSplitNcFeTerminal.rows (feTerminalInput input),
    KSplitNcNcEndpoint.rows (ncInput input)
  ]

def rows
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : Input polynomialInput domains) : List Row :=
  (rowGroups input).flatten

theorem rows_length
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : Input polynomialInput domains) :
    (rows input).length =
      (KSplitNcFeInitial.rows (feInitialInput input)).length +
        (KSplitNcFeTerminal.rows (feTerminalInput input)).length +
        (KSplitNcNcEndpoint.rows (ncInput input)).length := by
  simp [rows, rowGroups]
  omega

/-- Exact compact endpoint allocation.  The three endpoint subprograms are
placed by their allocated widths, never by their larger row counts. -/
def allocationWidth
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : Input polynomialInput domains) : Nat :=
  KSplitNcFeInitial.allocationWidth (feInitialInput input) +
    KSplitNcFeTerminal.allocationWidth (feTerminalInput input) +
      KSplitNcNcEndpoint.allocationWidth (ncInput input)

/-- Ordered endpoint auxiliary interval. -/
def columns
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : Input polynomialInput domains) : List Nat :=
  (List.range (allocationWidth input)).map
    (fun offset => input.frameBase + offset)

theorem columns_length
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : Input polynomialInput domains) :
    (columns input).length = allocationWidth input := by
  simp [columns]

theorem columns_nodup
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : Input polynomialInput domains) :
    (columns input).Nodup := by
  unfold columns
  exact LinCombNormal.nodup_map _ _ (fun left right equal => by omega)
    List.nodup_range

theorem rows_length_eq_allocationWidth_add_eight
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : Input polynomialInput domains) :
    (rows input).length = allocationWidth input + 8 := by
  rw [rows_length,
    KSplitNcFeInitial.rows_length_eq_allocationWidth_add_two,
    KSplitNcFeTerminal.rows_length_eq_allocationWidth_add_two,
    KSplitNcNcEndpoint.rows_length_eq_allocationWidth_add_four]
  unfold allocationWidth
  omega

/-- Exact semantic binding supplied later by the selected whole-frame codec.
No field is an endpoint equation or verifier result. -/
structure DecodedAuthority
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : Input polynomialInput domains)
    (assignment : Nat → Nat)
    (message : OutputMessage shape) : Prop where
  priorPoint :
    ∀ coordinate,
      KPointEquality.decoded assignment
          (input.authority.priorPoint coordinate) =
        polynomialInput.priorPoint.coordinates.get
          ⟨coordinate.val, by
            rw [polynomialInput.priorPoint.dimension]
            exact coordinate.isLt⟩
  claimedYRing :
    ∀ running matrix lane,
      KPointEquality.decoded assignment
          (input.authority.claimedYRing running matrix lane) =
        polynomialInput.claimedYRing running matrix lane
  outputYRing :
    ∀ source matrix lane,
      KPointEquality.decoded assignment
          (input.authority.outputYRing source matrix lane) =
        message.yRing source matrix lane
  outputYZcol :
    ∀ source lane,
      KPointEquality.decoded assignment
          (input.authority.outputYZcol source lane) =
        message.yZcol source lane

theorem satisfies_group
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : Input polynomialInput domains)
    (assignment : Nat → Nat)
    (satisfied : Satisfies (rows input) assignment)
    (group : List Row) (member : group ∈ rowGroups input) :
    Satisfies group assignment := by
  intro row rowMember
  exact satisfied row (List.mem_flatten.2 ⟨group, member, rowMember⟩)

def decodedPointOf
    {count : Nat}
    (values : Fin count → Carried) (assignment : Nat → Nat) :
    CubePoint K count where
  coordinates := List.ofFn fun index =>
    KPointEquality.decoded assignment (values index)
  dimension := by simp

private theorem cubePoint_eq_of_coordinates_eq
    {count : Nat} (left right : CubePoint K count)
    (coordinates : left.coordinates = right.coordinates) :
    left = right := by
  cases left
  cases right
  simp_all

theorem decoded_carried
    (assignment : Nat → Nat) (columns : KColumns) :
    KPointEquality.decoded assignment (carried columns) =
      KSplitNcTranscriptSemantics.decodedColumns assignment columns := by
  unfold KPointEquality.decoded
  rw [decodeCarried_carried]
  rfl

theorem decodedPointOf_carriedAt_eq
    {count : Nat}
    (columns : List KColumns) (length : columns.length = count)
    (assignment : Nat → Nat) :
    decodedPointOf (carriedAt columns length) assignment =
      {
        coordinates :=
          KSplitNcTranscriptSemantics.decodedColumnList assignment columns
        dimension := by
          rw [
            KSplitNcTranscriptSemantics.decodedColumnList_length, length]
      } := by
  apply cubePoint_eq_of_coordinates_eq
  unfold decodedPointOf
  apply List.ext_getElem
  · rw [List.length_ofFn,
      KSplitNcTranscriptSemantics.decodedColumnList_length]
    exact length.symm
  · intro index leftBound rightBound
    have indexLt : index < count := by simpa using leftBound
    simp only [List.getElem_ofFn]
    exact decoded_carriedAt columns length assignment ⟨index, indexLt⟩

theorem feInitial_decoder_eq
    (assignment : Nat → Nat) (value : Carried) :
    KSplitNcFeInitial.decoded assignment value =
      KPointEquality.decoded assignment value := by
  unfold KSplitNcFeInitial.decoded
  apply KConcreteBridge.ofConcrete_injective
  rw [KBooleanMleSemantics.ofConcrete_decodeCarried,
    KPointEquality.ofConcrete_decoded]

theorem feInitialAlpha_eq_core
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : Input polynomialInput domains)
    (assignment : Nat → Nat) :
    KSplitNcFeInitial.decodedAlpha (feInitialInput input) assignment =
      decodedPointOf (coreAlpha input) assignment := by
  apply cubePoint_eq_of_coordinates_eq
  simp only [KSplitNcFeInitial.decodedAlpha,
    KSplitNcFeInitial.alphaCoordinates,
    KBooleanMleSemantics.decodePoint, decodedPointOf,
    List.map_ofFn, Function.comp_apply]
  apply congrArg List.ofFn
  funext coordinate
  exact feInitial_decoder_eq assignment (coreAlpha input coordinate)

theorem decodedPointOf_carriedAt_eq_of_coordinates
    {count : Nat}
    (columns : List KColumns) (length : columns.length = count)
    (assignment : Nat → Nat) (point : CubePoint K count)
    (coordinates :
      KSplitNcTranscriptSemantics.decodedColumnList assignment columns =
        point.coordinates) :
    decodedPointOf (carriedAt columns length) assignment = point := by
  apply cubePoint_eq_of_coordinates_eq
  rw [decodedPointOf_carriedAt_eq]
  exact coordinates

theorem coreAlpha_eq
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (constants : Poseidon2Schedule.Constants)
    (assignment : Nat → Nat)
    (input : Input polynomialInput domains)
    (pre :
      KSplitNcTranscriptSemantics.PreAgrees assignment
        (KSplitNcTranscript.replay input.transcript)
        (KSplitNcTranscriptPhases.semanticPre
          constants assignment input.transcript)) :
    decodedPointOf (coreAlpha input) assignment =
      (KSplitNcTranscriptPhases.semanticPre
        constants assignment input.transcript).challenges.alpha := by
  apply decodedPointOf_carriedAt_eq_of_coordinates
  exact pre.alpha

theorem coreBetaA_eq
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (constants : Poseidon2Schedule.Constants)
    (assignment : Nat → Nat)
    (input : Input polynomialInput domains)
    (pre :
      KSplitNcTranscriptSemantics.PreAgrees assignment
        (KSplitNcTranscript.replay input.transcript)
        (KSplitNcTranscriptPhases.semanticPre
          constants assignment input.transcript)) :
    decodedPointOf (coreBetaA input) assignment =
      (KSplitNcTranscriptPhases.semanticPre
        constants assignment input.transcript).challenges.betaA := by
  apply decodedPointOf_carriedAt_eq_of_coordinates
  exact pre.betaA

theorem coreBetaR_eq
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (constants : Poseidon2Schedule.Constants)
    (assignment : Nat → Nat)
    (input : Input polynomialInput domains)
    (pre :
      KSplitNcTranscriptSemantics.PreAgrees assignment
        (KSplitNcTranscript.replay input.transcript)
        (KSplitNcTranscriptPhases.semanticPre
          constants assignment input.transcript)) :
    decodedPointOf (coreBetaR input) assignment =
      (KSplitNcTranscriptPhases.semanticPre
        constants assignment input.transcript).challenges.betaR := by
  apply decodedPointOf_carriedAt_eq_of_coordinates
  exact pre.betaR

theorem coreBetaBlock_eq
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (constants : Poseidon2Schedule.Constants)
    (assignment : Nat → Nat)
    (input : Input polynomialInput domains)
    (pre :
      KSplitNcTranscriptSemantics.PreAgrees assignment
        (KSplitNcTranscript.replay input.transcript)
        (KSplitNcTranscriptPhases.semanticPre
          constants assignment input.transcript)) :
    decodedPointOf (coreBetaBlock input) assignment =
      (KSplitNcTranscriptPhases.semanticPre
        constants assignment input.transcript).challenges.betaBlock := by
  apply decodedPointOf_carriedAt_eq_of_coordinates
  exact pre.betaBlock

theorem coreGamma_eq
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (constants : Poseidon2Schedule.Constants)
    (assignment : Nat → Nat)
    (input : Input polynomialInput domains)
    (pre :
      KSplitNcTranscriptSemantics.PreAgrees assignment
        (KSplitNcTranscript.replay input.transcript)
        (KSplitNcTranscriptPhases.semanticPre
          constants assignment input.transcript)) :
    KPointEquality.decoded assignment
        (carried (KSplitNcTranscript.coreReplay input.transcript).gamma) =
      (KSplitNcTranscriptPhases.semanticPre
        constants assignment input.transcript).challenges.gamma := by
  rw [decoded_carried]
  exact pre.gamma

theorem decodedLeft_eq_decodedPointOf
    {count : Nat}
    (input : KPointEquality.Input count) (assignment : Nat → Nat) :
    KPointEquality.decodedLeft input assignment =
      decodedPointOf input.left assignment := by
  apply cubePoint_eq_of_coordinates_eq
  simp only [KPointEquality.decodedLeft, KPointEquality.indices,
    decodedPointOf, List.map_ofFn]
  apply congrArg List.ofFn
  funext coordinate
  rfl

theorem decodedRight_eq_decodedPointOf
    {count : Nat}
    (input : KPointEquality.Input count) (assignment : Nat → Nat) :
    KPointEquality.decodedRight input assignment =
      decodedPointOf input.right assignment := by
  apply cubePoint_eq_of_coordinates_eq
  simp only [KPointEquality.decodedRight, KPointEquality.indices,
    decodedPointOf, List.map_ofFn]
  apply congrArg List.ofFn
  funext coordinate
  rfl

theorem feRowPoint_eq_decoded
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : Input polynomialInput domains) (assignment : Nat → Nat) :
    decodedPointOf (feRowPoint input) assignment =
      (KSplitNcTranscriptPhases.decodedFePoint
        assignment input.transcript).row := by
  apply decodedPointOf_carriedAt_eq_of_coordinates
  rfl

theorem feLanePoint_eq_decoded
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : Input polynomialInput domains) (assignment : Nat → Nat) :
    decodedPointOf (feLanePoint input) assignment =
      (KSplitNcTranscriptPhases.decodedFePoint
        assignment input.transcript).lane := by
  apply decodedPointOf_carriedAt_eq_of_coordinates
  rfl

theorem ncBlockPoint_eq_decoded
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : Input polynomialInput domains) (assignment : Nat → Nat) :
    decodedPointOf (ncBlockPoint input) assignment =
      (KSplitNcTranscriptPhases.decodedNcPoint
        assignment input.transcript).block := by
  apply decodedPointOf_carriedAt_eq_of_coordinates
  rfl

theorem ncLanePoint_eq_decoded
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : Input polynomialInput domains) (assignment : Nat → Nat) :
    decodedPointOf (ncLanePoint input) assignment =
      (KSplitNcTranscriptPhases.decodedNcPoint
        assignment input.transcript).lane := by
  apply decodedPointOf_carriedAt_eq_of_coordinates
  rfl

private theorem feCoins_eq_of_fields
    {shape : SemanticShape} {domain : FlatNcDomain}
    (left right : Polynomial.Fe.Coins shape domain)
    (alpha : left.alpha = right.alpha)
    (betaA : left.betaA = right.betaA)
    (betaR : left.betaR = right.betaR)
    (gamma : left.gamma = right.gamma) :
    left = right := by
  cases left
  cases right
  simp_all

private theorem ncCoins_eq_of_fields
    {domain : BlockNcDomain}
    (left right : Polynomial.Nc.BlockLane.Mixing.Coins domain)
    (betaBlock : left.betaBlock = right.betaBlock)
    (betaA : left.betaA = right.betaA)
    (gamma : left.gamma = right.gamma) :
    left = right := by
  cases left
  cases right
  simp_all

theorem authorityPriorPoint_eq
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    {message : OutputMessage shape}
    (input : Input polynomialInput domains) (assignment : Nat → Nat)
    (authority : DecodedAuthority input assignment message) :
    decodedPointOf input.authority.priorPoint assignment =
      polynomialInput.priorPoint := by
  apply cubePoint_eq_of_coordinates_eq
  unfold decodedPointOf
  apply List.ext_getElem
  · rw [List.length_ofFn, polynomialInput.priorPoint.dimension]
  · intro index leftBound rightBound
    simp only [List.getElem_ofFn]
    have indexLt : index < shape.rowVariables := by
      simpa using leftBound
    exact authority.priorPoint ⟨index, indexLt⟩

theorem feTerminal_publicInput_eq
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    {message : OutputMessage shape}
    (input : Input polynomialInput domains) (assignment : Nat → Nat)
    (authority : DecodedAuthority input assignment message) :
    KSplitNcFeTerminal.decodedPublicInput
        (feTerminalInput input) assignment =
      polynomialInput := by
  apply PublicInput.ext
  · rfl
  · rw [KSplitNcFeTerminal.decodedPublicInput,
      decodedRight_eq_decodedPointOf]
    exact authorityPriorPoint_eq input assignment authority
  · rfl

theorem feTerminal_coins_eq
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (constants : Poseidon2Schedule.Constants)
    (assignment : Nat → Nat)
    (input : Input polynomialInput domains)
    (pre :
      KSplitNcTranscriptSemantics.PreAgrees assignment
        (KSplitNcTranscript.replay input.transcript)
        (KSplitNcTranscriptPhases.semanticPre
          constants assignment input.transcript)) :
    KSplitNcFeTerminal.decodedCoins
        (feTerminalInput input) assignment =
      (KSplitNcTranscriptPhases.semanticPre
        constants assignment input.transcript).challenges.feCoins := by
  apply feCoins_eq_of_fields
  · rw [KSplitNcFeTerminal.decodedCoins,
      decodedRight_eq_decodedPointOf]
    exact coreAlpha_eq constants assignment input pre
  · change
      KPointEquality.decodedRight
          (KSplitNcFeTerminal.freshLaneEqualityInput
            (feTerminalInput input)) assignment = _
    rw [decodedRight_eq_decodedPointOf]
    exact coreBetaA_eq constants assignment input pre
  · change
      KPointEquality.decodedRight
          (KSplitNcFeTerminal.freshRowEqualityInput
            (feTerminalInput input)) assignment = _
    rw [decodedRight_eq_decodedPointOf]
    exact coreBetaR_eq constants assignment input pre
  · exact coreGamma_eq constants assignment input pre

theorem feTerminal_point_eq
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : Input polynomialInput domains) (assignment : Nat → Nat) :
    KSplitNcFeTerminal.decodedPoint
        (feTerminalInput input) assignment =
      KSplitNcTranscriptPhases.decodedFePoint
        assignment input.transcript := by
  apply Polynomial.Fe.Point.ext
  · rw [KSplitNcFeTerminal.decodedPoint,
      decodedLeft_eq_decodedPointOf]
    exact feRowPoint_eq_decoded input assignment
  · change
      KPointEquality.decodedLeft
          (KSplitNcFeTerminal.freshLaneEqualityInput
            (feTerminalInput input)) assignment = _
    rw [decodedLeft_eq_decodedPointOf]
    exact feLanePoint_eq_decoded input assignment

theorem ncCoins_eq
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (constants : Poseidon2Schedule.Constants)
    (assignment : Nat → Nat)
    (input : Input polynomialInput domains)
    (pre :
      KSplitNcTranscriptSemantics.PreAgrees assignment
        (KSplitNcTranscript.replay input.transcript)
        (KSplitNcTranscriptPhases.semanticPre
          constants assignment input.transcript)) :
    KSplitNcNcEndpoint.decodedCoins (ncInput input) assignment =
      (KSplitNcTranscriptPhases.semanticPre
        constants assignment input.transcript).challenges.ncCoins := by
  apply ncCoins_eq_of_fields
  · rw [KSplitNcNcEndpoint.decodedCoins,
      decodedRight_eq_decodedPointOf]
    exact coreBetaBlock_eq constants assignment input pre
  · change
      KPointEquality.decodedRight
          (KSplitNcNcEndpoint.laneEqualityInput (ncInput input))
          assignment = _
    rw [decodedRight_eq_decodedPointOf]
    exact coreBetaA_eq constants assignment input pre
  · exact coreGamma_eq constants assignment input pre

theorem ncPoint_eq
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : Input polynomialInput domains) (assignment : Nat → Nat) :
    KSplitNcNcEndpoint.decodedPoint (ncInput input) assignment =
      KSplitNcTranscriptPhases.decodedNcPoint
        assignment input.transcript := by
  apply Polynomial.Nc.BlockLane.Point.ext
  · rw [KSplitNcNcEndpoint.decodedPoint,
      decodedLeft_eq_decodedPointOf]
    exact ncBlockPoint_eq_decoded input assignment
  · change
      KPointEquality.decodedLeft
          (KSplitNcNcEndpoint.laneEqualityInput (ncInput input))
          assignment = _
    rw [decodedLeft_eq_decodedPointOf]
    exact ncLanePoint_eq_decoded input assignment

theorem ncLaneTable_eq_of_yZcol
    {shape : SemanticShape} {domain : BlockNcDomain}
    (left right : Claims shape)
    (yZcol : ∀ source lane, left.yZcol source lane = right.yZcol source lane)
    (source : Fin shape.sourceCount) :
    Polynomial.Nc.BlockLane.Terminal.laneTable
        (domain := domain) left source =
      Polynomial.Nc.BlockLane.Terminal.laneTable right source := by
  unfold Polynomial.Nc.BlockLane.Terminal.laneTable
  apply congrArg BooleanTable.tabulate
  funext vertex
  unfold Polynomial.Nc.BlockLane.Terminal.paddedYZcol
  split
  · exact yZcol source _
  · rfl

theorem ncTerminal_eq_of_yZcol
    {shape : SemanticShape} {domain : BlockNcDomain}
    (left right : Claims shape)
    (yZcol : ∀ source lane, left.yZcol source lane = right.yZcol source lane)
    (coins : Polynomial.Nc.BlockLane.Mixing.Coins domain)
    (point : Polynomial.Nc.BlockLane.Point domain) :
    Polynomial.Nc.BlockLane.Terminal.terminalFromMessage left coins point =
      Polynomial.Nc.BlockLane.Terminal.terminalFromMessage
        right coins point := by
  unfold Polynomial.Nc.BlockLane.Terminal.terminalFromMessage
  apply congrArg
  unfold Polynomial.Nc.BlockLane.Terminal.mixedRangeAt
  apply FiniteSumAlgebra.sumMap_congr
  intro source member
  apply congrArg
  unfold Polynomial.Nc.BlockLane.Terminal.rangeAt
  have laneTable :=
    ncLaneTable_eq_of_yZcol
      (domain := domain) left right yZcol source
  unfold Polynomial.Nc.BlockLane.Terminal.valueAt
  rw [laneTable]

/-- Every verifier-owned endpoint equation is derived from physical rows,
the exact transcript replay, and direct decoding of the selected public
inputs.  No endpoint equation or acceptance proposition is a premise. -/
theorem endpointAgrees_of_rows
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (profile : Polynomial.Fe.SupportedProfile shape domains.fe)
    (constants : Poseidon2Schedule.Constants)
    (assignment : Nat → Nat)
    (constantWire : assignment 0 = 1)
    (input : Input polynomialInput domains)
    (message : OutputMessage shape)
    (transcriptValid :
      SymbolicDuplexSemantics.Valid
        input.transcript.transcriptBase constants assignment
        (KSplitNcTranscript.outputBuilder input.transcript))
    (authority : DecodedAuthority input assignment message)
    (satisfied : Satisfies (rows input) assignment) :
    KSplitNcOperational.EndpointAgrees
      profile constants assignment input.transcript message := by
  have feInitialSatisfied :
      Satisfies
        (KSplitNcFeInitial.rows (feInitialInput input)) assignment :=
    satisfies_group input assignment satisfied _ (by simp [rowGroups])
  have feTerminalSatisfied :
      Satisfies
        (KSplitNcFeTerminal.rows (feTerminalInput input)) assignment :=
    satisfies_group input assignment satisfied _ (by simp [rowGroups])
  have ncSatisfied :
      Satisfies (KSplitNcNcEndpoint.rows (ncInput input)) assignment :=
    satisfies_group input assignment satisfied _ (by simp [rowGroups])
  have pre :
      KSplitNcTranscriptSemantics.PreAgrees assignment
        (KSplitNcTranscript.replay input.transcript)
        (KSplitNcTranscriptPhases.semanticPre
          constants assignment input.transcript) := by
    simpa only [KSplitNcTranscriptPhases.semanticPre] using
      KSplitNcTranscriptSemantics.decoded_preSumcheck
        constants assignment constantWire input.transcript transcriptValid
  have feInitialLocal :=
    KSplitNcFeInitial.rows_sound profile polynomialInput
      (feInitialInput input) assignment constantWire
      (fun running matrix lane =>
        (feInitial_decoder_eq assignment
          (input.authority.claimedYRing running matrix lane)).trans
            (authority.claimedYRing running matrix lane))
      feInitialSatisfied
  have feInitialGamma :
      KSplitNcFeInitial.decoded assignment
          (feInitialInput input).gamma =
        (KSplitNcTranscriptPhases.semanticPre
          constants assignment input.transcript).challenges.gamma := by
    rw [feInitial_decoder_eq]
    exact coreGamma_eq constants assignment input pre
  have feInitial :
      KSplitNcTranscriptSemantics.decodedColumns
          assignment input.transcript.fe.initial =
        KSplitNcTranscriptPhases.semanticFeInitial
          profile constants assignment input.transcript := by
    calc
      KSplitNcTranscriptSemantics.decodedColumns
          assignment input.transcript.fe.initial =
          KPointEquality.decoded assignment
            (carried input.transcript.fe.initial) :=
        (decoded_carried assignment input.transcript.fe.initial).symm
      _ =
          KSplitNcFeInitial.decoded assignment
            (carried input.transcript.fe.initial) :=
        (feInitial_decoder_eq assignment
          (carried input.transcript.fe.initial)).symm
      _ =
          Polynomial.Fe.initial profile polynomialInput
            (KSplitNcFeInitial.decodedCoins
              (feInitialInput input) assignment) :=
        feInitialLocal
      _ =
          KSplitNcTranscriptPhases.semanticFeInitial
            profile constants assignment input.transcript := by
        unfold KSplitNcTranscriptPhases.semanticFeInitial
          KSplitNcFeInitial.decodedCoins Polynomial.Fe.initial
        rw [feInitialAlpha_eq_core,
          coreAlpha_eq constants assignment input pre,
          feInitialGamma]
        rfl
  have feReplay :=
    KSplitNcTranscriptPhases.decoded_fe
      profile constants assignment constantWire input.transcript
      transcriptValid feInitial
  have ncReplay :=
    KSplitNcTranscriptPhases.decoded_nc
      profile constants assignment constantWire input.transcript
      transcriptValid feInitial
  have feTerminalLocal :=
    KSplitNcFeTerminal.rows_sound profile
      (feTerminalInput input) assignment constantWire feTerminalSatisfied
  have feYRing :
      (KSplitNcFeTerminal.decodedMessage
        (feTerminalInput input) assignment).yRing = message.yRing := by
    funext source matrix lane
    exact authority.outputYRing source matrix lane
  have feTerminal :
      KSplitNcTranscriptSemantics.decodedColumns
          assignment input.transcript.fe.terminal =
        Polynomial.Fe.terminalFromMessage profile polynomialInput
          (KSplitNcTranscriptPhases.semanticPre
            constants assignment input.transcript).challenges.feCoins
          (KSplitNcTranscriptPhases.semanticFeExecution
            profile constants assignment input.transcript).challengePoint
          message := by
    calc
      KSplitNcTranscriptSemantics.decodedColumns
          assignment input.transcript.fe.terminal =
          KSplitNcFeTerminal.decoded assignment
            (feTerminalInput input).terminal := by
        change
          KSplitNcTranscriptSemantics.decodedColumns
              assignment input.transcript.fe.terminal =
            KPointEquality.decoded assignment
              (carried input.transcript.fe.terminal)
        exact (decoded_carried
          assignment input.transcript.fe.terminal).symm
      _ =
          Polynomial.Fe.terminalFromMessage profile
            (KSplitNcFeTerminal.decodedPublicInput
              (feTerminalInput input) assignment)
            (KSplitNcFeTerminal.decodedCoins
              (feTerminalInput input) assignment)
            (KSplitNcFeTerminal.decodedPoint
              (feTerminalInput input) assignment)
            (KSplitNcFeTerminal.decodedMessage
              (feTerminalInput input) assignment) :=
        feTerminalLocal
      _ =
          Polynomial.Fe.terminalFromMessage profile polynomialInput
            (KSplitNcTranscriptPhases.semanticPre
              constants assignment input.transcript).challenges.feCoins
            (KSplitNcTranscriptPhases.decodedFePoint
              assignment input.transcript)
            (KSplitNcFeTerminal.decodedMessage
              (feTerminalInput input) assignment) := by
        rw [feTerminal_publicInput_eq input assignment authority,
          feTerminal_coins_eq constants assignment input pre,
          feTerminal_point_eq input assignment]
      _ =
          Polynomial.Fe.terminalFromMessage profile polynomialInput
            (KSplitNcTranscriptPhases.semanticPre
              constants assignment input.transcript).challenges.feCoins
            (KSplitNcTranscriptPhases.decodedFePoint
              assignment input.transcript) message := by
        unfold Polynomial.Fe.terminalFromMessage
        rw [feYRing]
      _ = _ := by rw [feReplay.point]
  have ncLocal :=
    KSplitNcNcEndpoint.rows_sound
      (ncInput input) assignment constantWire ncSatisfied
  have ncMessageYZcol :
      ∀ source lane,
        (KSplitNcNcEndpoint.decodedMessage
            (ncInput input) assignment).yZcol source lane =
          message.yZcol source lane := by
    intro source lane
    exact authority.outputYZcol source lane
  have ncTerminal :
      KSplitNcTranscriptSemantics.decodedColumns
          assignment input.transcript.nc.terminal =
        Polynomial.Nc.BlockLane.Terminal.terminalFromMessage message
          (KSplitNcTranscriptPhases.semanticPre
            constants assignment input.transcript).challenges.ncCoins
          (KSplitNcTranscriptPhases.semanticNcExecution
            profile constants assignment input.transcript).challengePoint := by
    calc
      KSplitNcTranscriptSemantics.decodedColumns
          assignment input.transcript.nc.terminal =
          KSplitNcNcEndpoint.decoded assignment
            (ncInput input).terminal := by
        change
          KSplitNcTranscriptSemantics.decodedColumns
              assignment input.transcript.nc.terminal =
            KPointEquality.decoded assignment
              (carried input.transcript.nc.terminal)
        exact (decoded_carried
          assignment input.transcript.nc.terminal).symm
      _ =
          Polynomial.Nc.BlockLane.Terminal.terminalFromMessage
            (KSplitNcNcEndpoint.decodedMessage
              (ncInput input) assignment)
            (KSplitNcNcEndpoint.decodedCoins
              (ncInput input) assignment)
            (KSplitNcNcEndpoint.decodedPoint
              (ncInput input) assignment) :=
        ncLocal.2
      _ =
          Polynomial.Nc.BlockLane.Terminal.terminalFromMessage
            (KSplitNcNcEndpoint.decodedMessage
              (ncInput input) assignment)
            (KSplitNcTranscriptPhases.semanticPre
              constants assignment input.transcript).challenges.ncCoins
            (KSplitNcTranscriptPhases.decodedNcPoint
              assignment input.transcript) := by
        rw [ncCoins_eq constants assignment input pre,
          ncPoint_eq input assignment]
      _ =
          Polynomial.Nc.BlockLane.Terminal.terminalFromMessage message
            (KSplitNcTranscriptPhases.semanticPre
              constants assignment input.transcript).challenges.ncCoins
            (KSplitNcTranscriptPhases.decodedNcPoint
              assignment input.transcript) :=
        ncTerminal_eq_of_yZcol _ _ ncMessageYZcol _ _
      _ = _ := by rw [ncReplay.point]
  exact {
    feInitial := feInitial
    feTerminal := feTerminal
    ncInitial := by
      calc
        KSplitNcTranscriptSemantics.decodedColumns
            assignment input.transcript.nc.initial =
            KSplitNcNcEndpoint.decoded assignment
              (ncInput input).initial := by
          change
            KSplitNcTranscriptSemantics.decodedColumns
                assignment input.transcript.nc.initial =
              KPointEquality.decoded assignment
                (carried input.transcript.nc.initial)
          exact (decoded_carried
            assignment input.transcript.nc.initial).symm
        _ = Polynomial.Nc.BlockLane.InitialSum.claimedInitial := ncLocal.1
    ncTerminal := ncTerminal
  }

end Nightstream.Implementation.R1CS.Canonical.KSplitNcEndpoints
