import Nightstream.Implementation.R1CS.Canonical.KSplitNcTranscript
import Nightstream.Implementation.R1CS.Canonical.KSplitNcTranscriptSemantics
import Nightstream.Implementation.R1CS.Canonical.SymbolicDuplexPhysical
import Nightstream.Implementation.R1CS.Canonical.SymbolicDuplexPlacement

/-!
Contract: physical placement and source ownership for the operational
Split-NC transcript replay.

The replay may absorb only caller-owned expressions below `transcriptBase`
and output columns of earlier local permutations.  This module proves that
the complete `outputBuilder` preserves that invariant.  It does not decide
which outer codec supplies the caller-owned expressions.
-/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace Nightstream.Implementation.R1CS.Canonical.KSplitNcTranscriptPlacement

open Nightstream.Implementation.R1CS.Canonical.LinCombNormal
open Nightstream.Implementation.R1CS.Canonical.Poseidon2Core
open Nightstream.Implementation.R1CS.Canonical.SymbolicDuplexHonest
open Nightstream.Implementation.R1CS.Canonical.SymbolicDuplexPlacement
open Nightstream.SuperNeo
open Nightstream.SuperNeo.Folding.PiCCS.SplitNc
open Nightstream.SuperNeo.Folding.PiCCS.SplitNc.Verifier
open Nightstream.SuperNeo.Folding.PiCCS.SplitNc.Verifier.Protocol.TranscriptAuthority.BlockLane

/-- Exactly the externally supplied transcript expressions.  Challenge
columns generated by squeezes are intentionally absent: their ownership is
derived from the builder. -/
structure InputInPrefix
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : KSplitNcTranscript.Input polynomialInput domains) : Prop where
  positive : 0 < input.transcriptBase
  prior :
    ∀ lane : Fin width,
      ValueInPrefix input.transcriptBase (input.priorLanes lane)
  statement :
    ∀ value ∈ input.statementFields,
      ValueInPrefix input.transcriptBase value
  output :
    ∀ value ∈ input.outputFields,
      ValueInPrefix input.transcriptBase value
  feInitial :
    ∀ value ∈ KSplitNcTranscript.carriedFields
        (Nightstream.Implementation.Lowering.FPrimeFixedOne.Encoding.KFixedPhaseSemanticOccurrence.carried
          input.fe.initial),
      ValueInPrefix input.transcriptBase value
  feRow :
    ∀ round ∈ List.ofFn input.fe.rowRounds,
      ∀ value ∈ KSplitNcTranscript.roundFields round,
        ValueInPrefix input.transcriptBase value
  feLane :
    ∀ round ∈ List.ofFn input.fe.laneRounds,
      ∀ value ∈ KSplitNcTranscript.roundFields round,
        ValueInPrefix input.transcriptBase value
  ncBlock :
    ∀ round ∈ List.ofFn input.nc.blockRounds,
      ∀ value ∈ KSplitNcTranscript.roundFields round,
        ValueInPrefix input.transcriptBase value
  ncLane :
    ∀ round ∈ List.ofFn input.nc.laneRounds,
      ∀ value ∈ KSplitNcTranscript.roundFields round,
        ValueInPrefix input.transcriptBase value

private structure Invariant
    (base : Nat) (builder : SymbolicDuplex.Builder) : Prop where
  placed : WellPlaced base builder
  owned : WellOwned base builder

private theorem before_of_prefix
    {base : Nat} (positive : 0 < base)
    {value : LinCombNormal.LinComb}
    (inPrefix : ValueInPrefix base value) :
    ValueBefore base value := by
  intro column mentioned
  have below := inPrefix column mentioned
  simp only [SymbolicDuplexHonest.outputBase,
    SymbolicDuplexHonest.callBase]
  omega

private theorem word_prefix
    {base value : Nat} (positive : 0 < base) :
    ValueInPrefix base (KSplitNcTranscript.word value) := by
  intro column mentioned
  have same : column = 0 := by
    simpa [KSplitNcTranscript.word, Mentions] using mentioned
  omega

private theorem tagged_prefix
    {base : Nat} (positive : 0 < base)
    (tag : KSplitNcPoseidonSchedule.Tag)
    (payload : List LinCombNormal.LinComb)
    (payloadPrefix :
      ∀ value ∈ payload, ValueInPrefix base value) :
    ∀ value ∈ KSplitNcTranscript.taggedFields tag payload,
      ValueInPrefix base value := by
  intro value member
  unfold KSplitNcTranscript.taggedFields at member
  rcases List.mem_cons.1 member with rfl | member
  · exact word_prefix positive
  rcases List.mem_cons.1 member with rfl | member
  · exact word_prefix positive
  exact payloadPrefix value member

private theorem absorbTagged_invariant
    (base : Nat) (tag : KSplitNcPoseidonSchedule.Tag)
    (payload : List LinCombNormal.LinComb)
    (builder : SymbolicDuplex.Builder)
    (positive : 0 < base)
    (invariant : Invariant base builder)
    (payloadPrefix :
      ∀ value ∈ payload, ValueInPrefix base value) :
    Invariant base
      (KSplitNcTranscript.absorbTagged base tag payload builder) := by
  have allPrefix := tagged_prefix positive tag payload payloadPrefix
  constructor
  · unfold KSplitNcTranscript.absorbTagged
    exact absorbMany_wellPlaced base _ builder invariant.placed
      (fun value member =>
        before_of_prefix positive (allPrefix value member))
  · unfold KSplitNcTranscript.absorbTagged
    exact absorbMany_wellOwned base _ builder invariant.owned allPrefix

private theorem squeeze_invariant
    (base : Nat) (builder : SymbolicDuplex.Builder)
    (positive : 0 < base)
    (invariant : Invariant base builder) :
    Invariant base (KSplitNcTranscript.squeeze base builder).2 := by
  constructor
  · unfold KSplitNcTranscript.squeeze
    exact gate_wellPlaced base builder positive invariant.placed
  · unfold KSplitNcTranscript.squeeze
    exact gate_wellOwned base builder positive invariant.owned

private theorem squeezeMany_invariant
    (base : Nat) (positive : 0 < base) :
    ∀ (count : Nat) (builder : SymbolicDuplex.Builder),
      Invariant base builder →
        Invariant base
          (KSplitNcTranscript.squeezeMany base count builder).2
  | 0, _, invariant => invariant
  | count + 1, builder, invariant => by
      unfold KSplitNcTranscript.squeezeMany
      exact squeezeMany_invariant base positive count _
        (squeeze_invariant base builder positive invariant)

private theorem sampleVector_invariant
    (base : Nat) (tag : KSplitNcPoseidonSchedule.Tag)
    (count : Nat) (builder : SymbolicDuplex.Builder)
    (positive : 0 < base)
    (invariant : Invariant base builder) :
    Invariant base
      (KSplitNcTranscript.sampleVector base tag count builder).2 := by
  unfold KSplitNcTranscript.sampleVector
  exact squeezeMany_invariant base positive count _
    (absorbTagged_invariant base tag [] builder positive invariant
      (by simp))

private theorem deriveCore_invariant
    (base : Nat) (shape : SemanticShape) (domains : Domains)
    (builder : SymbolicDuplex.Builder)
    (positive : 0 < base)
    (invariant : Invariant base builder) :
    Invariant base
      (KSplitNcTranscript.deriveCore base shape domains builder).builder := by
  let alpha :=
    KSplitNcTranscript.sampleVector base .alpha
      domains.laneVariables builder
  have alphaInvariant : Invariant base alpha.2 :=
    sampleVector_invariant base .alpha domains.laneVariables builder
      positive invariant
  let betaA :=
    KSplitNcTranscript.sampleVector base .betaA
      domains.laneVariables alpha.2
  have betaAInvariant : Invariant base betaA.2 :=
    sampleVector_invariant base .betaA domains.laneVariables alpha.2
      positive alphaInvariant
  let betaR :=
    KSplitNcTranscript.sampleVector base .betaR
      shape.rowVariables betaA.2
  have betaRInvariant : Invariant base betaR.2 :=
    sampleVector_invariant base .betaR shape.rowVariables betaA.2
      positive betaAInvariant
  let gamma :=
    KSplitNcTranscript.squeeze base
      (KSplitNcTranscript.absorbTagged base .gamma [] betaR.2)
  have gammaInvariant : Invariant base gamma.2 :=
    squeeze_invariant base _ positive
      (absorbTagged_invariant base .gamma [] betaR.2 positive
        betaRInvariant (by simp))
  let betaBlock :=
    KSplitNcTranscript.sampleVector base .betaBlock
      domains.blockVariables gamma.2
  have betaBlockInvariant : Invariant base betaBlock.2 :=
    sampleVector_invariant base .betaBlock domains.blockVariables gamma.2
      positive gammaInvariant
  simpa only [KSplitNcTranscript.deriveCore, alpha, betaA, betaR, gamma,
    betaBlock] using betaBlockInvariant

private theorem replayRounds_invariant
    {degree : Nat}
    (base : Nat) (tag : KSplitNcPoseidonSchedule.Tag)
    (positive : 0 < base) :
    ∀
      (rounds :
        List
          (Nightstream.Implementation.Lowering.FPrimeFixedOne.Encoding.KFixedPhaseSemanticOccurrence.RoundColumns
            degree))
      (builder : SymbolicDuplex.Builder),
      Invariant base builder →
      (∀ round ∈ rounds, ∀ value ∈ KSplitNcTranscript.roundFields round,
        ValueInPrefix base value) →
        Invariant base
          (KSplitNcTranscript.replayRounds base tag rounds builder).builder
  | [], _, invariant, _ => invariant
  | round :: rounds, builder, invariant, allPrefix => by
      unfold KSplitNcTranscript.replayRounds
      let absorbed :=
        KSplitNcTranscript.absorbTagged base tag
          (KSplitNcTranscript.roundFields round) builder
      have absorbedInvariant : Invariant base absorbed :=
        absorbTagged_invariant base tag _ builder positive invariant
          (fun value member => allPrefix round (by simp) value member)
      let sampled := KSplitNcTranscript.squeeze base absorbed
      have sampledInvariant : Invariant base sampled.2 :=
        squeeze_invariant base absorbed positive absorbedInvariant
      exact replayRounds_invariant base tag positive rounds sampled.2
        sampledInvariant
        (fun other otherMember value valueMember =>
          allPrefix other (by simp [otherMember]) value valueMember)

private theorem initial_invariant
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : KSplitNcTranscript.Input polynomialInput domains)
    (sources : InputInPrefix input) :
    Invariant input.transcriptBase
      (KSplitNcTranscript.initialBuilder input) := by
  constructor
  · unfold KSplitNcTranscript.initialBuilder
    exact start_wellPlaced input.transcriptBase input.priorLanes
      input.priorAbsorbed
      (fun lane column mentioned =>
        before_of_prefix sources.positive
          (sources.prior lane) column mentioned)
  · unfold KSplitNcTranscript.initialBuilder
    exact start_wellOwned input.transcriptBase input.priorLanes
      input.priorAbsorbed sources.prior

/-- Complete placement and ownership of the selected transcript replay. -/
theorem outputBuilder_invariant
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (input : KSplitNcTranscript.Input polynomialInput domains)
    (sources : InputInPrefix input) :
    WellPlaced input.transcriptBase
        (KSplitNcTranscript.outputBuilder input) ∧
      WellOwned input.transcriptBase
        (KSplitNcTranscript.outputBuilder input) := by
  let statementInvariant :=
    absorbTagged_invariant input.transcriptBase .statement
      input.statementFields (KSplitNcTranscript.initialBuilder input)
      sources.positive (initial_invariant input sources) sources.statement
  let coreInvariant :=
    deriveCore_invariant input.transcriptBase shape domains
      (KSplitNcTranscript.statementBuilder input)
      sources.positive statementInvariant
  let producerAbsorbed :=
    absorbTagged_invariant input.transcriptBase .producerBeta []
      (KSplitNcTranscript.coreReplay input).builder sources.positive
      coreInvariant (by simp)
  let producerInvariant :=
    squeeze_invariant input.transcriptBase _ sources.positive producerAbsorbed
  let batchAbsorbed :=
    absorbTagged_invariant input.transcriptBase .batchWeight []
      (KSplitNcTranscript.producerSample input).2 sources.positive
      producerInvariant (by simp)
  let batchInvariant :=
    squeeze_invariant input.transcriptBase _ sources.positive batchAbsorbed
  let feEntryInvariant :=
    absorbTagged_invariant input.transcriptBase .feEntry
      (KSplitNcTranscript.carriedFields
        (Nightstream.Implementation.Lowering.FPrimeFixedOne.Encoding.KFixedPhaseSemanticOccurrence.carried
          input.fe.initial))
      (KSplitNcTranscript.batchSample input).2 sources.positive
      batchInvariant sources.feInitial
  let feRowInvariant :=
    replayRounds_invariant input.transcriptBase .feRound sources.positive
      (List.ofFn input.fe.rowRounds)
      (KSplitNcTranscript.feEntryBuilder input) feEntryInvariant sources.feRow
  let feLaneInvariant :=
    replayRounds_invariant input.transcriptBase .feRound sources.positive
      (List.ofFn input.fe.laneRounds)
      (KSplitNcTranscript.feRowReplay input).builder feRowInvariant
      sources.feLane
  let ncEntryInvariant :=
    absorbTagged_invariant input.transcriptBase .ncEntry []
      (KSplitNcTranscript.feLaneReplay input).builder sources.positive
      feLaneInvariant (by simp)
  let ncBlockInvariant :=
    replayRounds_invariant input.transcriptBase .ncRound sources.positive
      (List.ofFn input.nc.blockRounds)
      (KSplitNcTranscript.ncEntryBuilder input) ncEntryInvariant
      sources.ncBlock
  let ncLaneInvariant :=
    replayRounds_invariant input.transcriptBase .ncRound sources.positive
      (List.ofFn input.nc.laneRounds)
      (KSplitNcTranscript.ncBlockReplay input).builder ncBlockInvariant
      sources.ncLane
  let outputInvariant :=
    absorbTagged_invariant input.transcriptBase .output input.outputFields
      (KSplitNcTranscript.ncLaneReplay input).builder sources.positive
      ncLaneInvariant sources.output
  exact ⟨outputInvariant.placed, outputInvariant.owned⟩

/-- Every transcript-row operand is in the authoritative prefix or the exact
local permutation allocation. -/
theorem rows_conservation
    {shape : SemanticShape}
    {polynomialInput : PublicInput shape}
    {domains : Domains}
    (constants : Poseidon2Schedule.Constants)
    (input : KSplitNcTranscript.Input polynomialInput domains)
    (sources : InputInPrefix input)
    (row : Nightstream.Implementation.R1CS.Row)
    (member : row ∈ KSplitNcTranscript.rows constants input)
    (column : Nat)
    (mentioned :
      Mentions row.a column ∨ Mentions row.b column ∨
        Mentions row.c column) :
    column < input.transcriptBase ∨
      column ∈ SymbolicDuplexPhysical.temporaryColumns
        input.transcriptBase
        (KSplitNcTranscript.replay input).afterOutput.entries.length := by
  have invariant := outputBuilder_invariant input sources
  exact SymbolicDuplexPhysical.rows_conservation
    input.transcriptBase constants
    (KSplitNcTranscript.outputBuilder input)
    sources.positive invariant.1 invariant.2 row
    (by simpa [KSplitNcTranscript.rows, KSplitNcTranscript.replay] using member)
    column mentioned

private theorem squeezed_entry_mem
    (base : Nat) (builder : SymbolicDuplex.Builder) :
    let before :=
      SymbolicDuplex.absorb base SymbolicDuplex.one builder
    ({ call := before.entries.length, state := before.lanes } :
        SymbolicDuplex.Entry) ∈
      (KSplitNcTranscript.squeeze base builder).2.entries := by
  simp [KSplitNcTranscript.squeeze, SymbolicDuplex.gate,
    SymbolicDuplex.permute]

/-- A squeezed extension value lies inside any later well-placed builder that
contains the squeeze.  This is the physical source bound used by the numeric
SumCheck and endpoint programs. -/
theorem squeezeColumns_below_of_extends
    (base : Nat) (builder final : SymbolicDuplex.Builder)
    (placed : WellPlaced base final)
    (extension :
      SymbolicDuplexSemantics.Extends
        (KSplitNcTranscript.squeeze base builder).2 final) :
    let columns := KSplitNcTranscript.squeezeColumns base builder
    columns.c0 < base + final.entries.length * SymbolicDuplex.stride ∧
      columns.c1 < base + final.entries.length * SymbolicDuplex.stride := by
  let before := SymbolicDuplex.absorb base SymbolicDuplex.one builder
  let entry : SymbolicDuplex.Entry :=
    { call := before.entries.length, state := before.lanes }
  have inSqueeze :
      entry ∈ (KSplitNcTranscript.squeeze base builder).2.entries := by
    simpa only [entry, before] using squeezed_entry_mem base builder
  have inFinal : entry ∈ final.entries := extension entry inSqueeze
  have callMember : entry.call ∈ final.entries.map SymbolicDuplex.Entry.call :=
    List.mem_map.2 ⟨entry, inFinal, rfl⟩
  rw [placed.calls] at callMember
  have callLt : entry.call < final.entries.length :=
    List.mem_range.1 callMember
  have nextCallLe :
      before.entries.length * SymbolicDuplex.stride +
          SymbolicDuplex.stride ≤
        final.entries.length * SymbolicDuplex.stride := by
    have scaled :=
      Nat.mul_le_mul_right SymbolicDuplex.stride
        (Nat.succ_le_iff.2 (by
          simpa only [entry] using callLt))
    simpa only [Nat.succ_mul] using scaled
  have laneZero : (0 : Nat) < width := by decide
  have laneOne : (1 : Nat) < width := by decide
  have zeroLtStride : (0 : Nat) < SymbolicDuplex.stride := by decide
  have oneLtStride : (1 : Nat) < SymbolicDuplex.stride := by decide
  constructor
  · change
      (SymbolicDuplex.layoutAt base before.entries.length).outputPort
          ⟨0, laneZero⟩ <
        base + final.entries.length * SymbolicDuplex.stride
    simp only [SymbolicDuplex.layoutAt,
      SymbolicDuplexHonest.outputBase, SymbolicDuplexHonest.callBase]
    change before.entries.length < final.entries.length at callLt
    omega
  · change
      (SymbolicDuplex.layoutAt base before.entries.length).outputPort
          ⟨1, laneOne⟩ <
        base + final.entries.length * SymbolicDuplex.stride
    simp only [SymbolicDuplex.layoutAt,
      SymbolicDuplexHonest.outputBase, SymbolicDuplexHonest.callBase]
    change before.entries.length < final.entries.length at callLt
    omega

/-- Every extension value emitted by an exact squeeze vector lies in any
later well-placed builder containing the complete vector. -/
theorem squeezeMany_columns_below_of_extends
    (base count : Nat) (builder final : SymbolicDuplex.Builder)
    (placed : WellPlaced base final)
    (extension :
      SymbolicDuplexSemantics.Extends
        (KSplitNcTranscript.squeezeMany base count builder).2 final) :
    ∀ columns ∈
        (KSplitNcTranscript.squeezeMany base count builder).1,
      columns.c0 < base + final.entries.length * SymbolicDuplex.stride ∧
        columns.c1 < base + final.entries.length * SymbolicDuplex.stride := by
  induction count generalizing builder with
  | zero =>
      intro columns member
      simp [KSplitNcTranscript.squeezeMany] at member
  | succ count inductionHypothesis =>
      let sampled := KSplitNcTranscript.squeeze base builder
      let rest := KSplitNcTranscript.squeezeMany base count sampled.2
      intro columns member
      change columns ∈ sampled.1 :: rest.1 at member
      rcases List.mem_cons.1 member with rfl | inRest
      · have sampledExtendsRest :
          SymbolicDuplexSemantics.Extends sampled.2 rest.2 :=
          KSplitNcTranscriptSemantics.squeezeMany_extends
            base count sampled.2
        exact squeezeColumns_below_of_extends base builder final placed
          ((by
            simpa only [sampled, rest, KSplitNcTranscript.squeezeMany]
              using sampledExtendsRest.trans extension) :
            SymbolicDuplexSemantics.Extends sampled.2 final)
      · exact inductionHypothesis sampled.2 extension columns inRest

/-- A tagged sampled vector inherits the same exact finite support bound. -/
theorem sampleVector_columns_below_of_extends
    (base : Nat) (tag : KSplitNcPoseidonSchedule.Tag)
    (count : Nat) (builder final : SymbolicDuplex.Builder)
    (placed : WellPlaced base final)
    (extension :
      SymbolicDuplexSemantics.Extends
        (KSplitNcTranscript.sampleVector base tag count builder).2 final) :
    ∀ columns ∈
        (KSplitNcTranscript.sampleVector base tag count builder).1,
      columns.c0 < base + final.entries.length * SymbolicDuplex.stride ∧
        columns.c1 < base + final.entries.length * SymbolicDuplex.stride := by
  unfold KSplitNcTranscript.sampleVector at extension ⊢
  exact squeezeMany_columns_below_of_extends
    base count
    (KSplitNcTranscript.absorbTagged base tag [] builder)
    final placed extension

/-- Exact support of all five core challenge families. -/
structure CoreColumnsBelow
    {shape : SemanticShape} {domains : Domains}
    (core : KSplitNcTranscript.Core shape domains)
    (boundary : Nat) : Prop where
  alpha :
    ∀ columns ∈ core.alpha,
      columns.c0 < boundary ∧ columns.c1 < boundary
  betaA :
    ∀ columns ∈ core.betaA,
      columns.c0 < boundary ∧ columns.c1 < boundary
  betaR :
    ∀ columns ∈ core.betaR,
      columns.c0 < boundary ∧ columns.c1 < boundary
  gamma : core.gamma.c0 < boundary ∧ core.gamma.c1 < boundary
  betaBlock :
    ∀ columns ∈ core.betaBlock,
      columns.c0 < boundary ∧ columns.c1 < boundary

/-- All core challenge columns lie in any later well-placed builder extending
the complete core derivation. -/
theorem deriveCore_columns_below_of_extends
    (base : Nat) (shape : SemanticShape) (domains : Domains)
    (builder final : SymbolicDuplex.Builder)
    (placed : WellPlaced base final)
    (extension :
      SymbolicDuplexSemantics.Extends
        (KSplitNcTranscript.deriveCore base shape domains builder).builder
        final) :
    CoreColumnsBelow
      (KSplitNcTranscript.deriveCore base shape domains builder)
      (base + final.entries.length * SymbolicDuplex.stride) := by
  let alpha :=
    KSplitNcTranscript.sampleVector base .alpha
      domains.laneVariables builder
  let betaA :=
    KSplitNcTranscript.sampleVector base .betaA
      domains.laneVariables alpha.2
  let betaR :=
    KSplitNcTranscript.sampleVector base .betaR
      shape.rowVariables betaA.2
  let gammaEntered :=
    KSplitNcTranscript.absorbTagged base .gamma [] betaR.2
  let gamma := KSplitNcTranscript.squeeze base gammaEntered
  let betaBlock :=
    KSplitNcTranscript.sampleVector base .betaBlock
      domains.blockVariables gamma.2
  have alphaToFinal :
      SymbolicDuplexSemantics.Extends alpha.2 final :=
    (KSplitNcTranscriptSemantics.sampleVector_extends
        base .betaA domains.laneVariables alpha.2).trans
      ((KSplitNcTranscriptSemantics.sampleVector_extends
          base .betaR shape.rowVariables betaA.2).trans
        ((KSplitNcTranscriptSemantics.sampleScalar_extends
            base .gamma betaR.2).trans
          ((KSplitNcTranscriptSemantics.sampleVector_extends
              base .betaBlock domains.blockVariables gamma.2).trans
            (by
              simpa only [alpha, betaA, betaR, gammaEntered, gamma, betaBlock,
                KSplitNcTranscript.deriveCore] using extension))))
  have betaAToFinal :
      SymbolicDuplexSemantics.Extends betaA.2 final :=
    (KSplitNcTranscriptSemantics.sampleVector_extends
        base .betaR shape.rowVariables betaA.2).trans
      ((KSplitNcTranscriptSemantics.sampleScalar_extends
          base .gamma betaR.2).trans
        ((KSplitNcTranscriptSemantics.sampleVector_extends
            base .betaBlock domains.blockVariables gamma.2).trans
          (by
            simpa only [alpha, betaA, betaR, gammaEntered, gamma, betaBlock,
              KSplitNcTranscript.deriveCore] using extension)))
  have betaRToFinal :
      SymbolicDuplexSemantics.Extends betaR.2 final :=
    (KSplitNcTranscriptSemantics.sampleScalar_extends
        base .gamma betaR.2).trans
      ((KSplitNcTranscriptSemantics.sampleVector_extends
          base .betaBlock domains.blockVariables gamma.2).trans
        (by
          simpa only [alpha, betaA, betaR, gammaEntered, gamma, betaBlock,
            KSplitNcTranscript.deriveCore] using extension))
  have gammaToFinal :
      SymbolicDuplexSemantics.Extends gamma.2 final :=
    (KSplitNcTranscriptSemantics.sampleVector_extends
        base .betaBlock domains.blockVariables gamma.2).trans
      (by
        simpa only [alpha, betaA, betaR, gammaEntered, gamma, betaBlock,
          KSplitNcTranscript.deriveCore] using extension)
  refine {
    alpha := ?_
    betaA := ?_
    betaR := ?_
    gamma := ?_
    betaBlock := ?_
  }
  · simpa only [KSplitNcTranscript.deriveCore, alpha, betaA, betaR,
      gammaEntered, gamma, betaBlock] using
      sampleVector_columns_below_of_extends
        base .alpha domains.laneVariables builder final placed alphaToFinal
  · simpa only [KSplitNcTranscript.deriveCore, alpha, betaA, betaR,
      gammaEntered, gamma, betaBlock] using
      sampleVector_columns_below_of_extends
        base .betaA domains.laneVariables alpha.2 final placed betaAToFinal
  · simpa only [KSplitNcTranscript.deriveCore, alpha, betaA, betaR,
      gammaEntered, gamma, betaBlock] using
      sampleVector_columns_below_of_extends
        base .betaR shape.rowVariables betaA.2 final placed betaRToFinal
  · simpa only [KSplitNcTranscript.deriveCore, alpha, betaA, betaR,
      gammaEntered, gamma, betaBlock] using
      squeezeColumns_below_of_extends
        base gammaEntered final placed gammaToFinal
  · simpa only [KSplitNcTranscript.deriveCore, alpha, betaA, betaR,
      gammaEntered, gamma, betaBlock] using
      sampleVector_columns_below_of_extends
        base .betaBlock domains.blockVariables gamma.2 final placed extension

/-- Every challenge emitted by a replayed fixed-phase message lies within a
later well-placed builder containing the complete replay. -/
theorem replayRounds_challenges_below_of_extends
    {degree : Nat}
    (base : Nat) (tag : KSplitNcPoseidonSchedule.Tag)
    (rounds :
      List
        (Nightstream.Implementation.Lowering.FPrimeFixedOne.Encoding.KFixedPhaseSemanticOccurrence.RoundColumns
          degree))
    (builder final : SymbolicDuplex.Builder)
    (placed : WellPlaced base final)
    (extension :
      SymbolicDuplexSemantics.Extends
        (KSplitNcTranscript.replayRounds base tag rounds builder).builder
        final) :
    ∀ columns ∈
        (KSplitNcTranscript.replayRounds base tag rounds builder).challenges,
      columns.c0 < base + final.entries.length * SymbolicDuplex.stride ∧
        columns.c1 < base + final.entries.length * SymbolicDuplex.stride := by
  induction rounds generalizing builder with
  | nil =>
      intro columns member
      simp [KSplitNcTranscript.replayRounds] at member
  | cons round rounds inductionHypothesis =>
      let absorbed :=
        KSplitNcTranscript.absorbTagged base tag
          (KSplitNcTranscript.roundFields round) builder
      let sampled := KSplitNcTranscript.squeeze base absorbed
      let rest :=
        KSplitNcTranscript.replayRounds base tag rounds sampled.2
      intro columns member
      change columns ∈ sampled.1 :: rest.challenges at member
      rcases List.mem_cons.1 member with rfl | inRest
      · have sampledExtendsRest :
          SymbolicDuplexSemantics.Extends sampled.2 rest.builder := by
          exact KSplitNcTranscriptSemantics.replayRounds_extends
            base tag rounds sampled.2
        have sampledExtendsFinal :
            SymbolicDuplexSemantics.Extends sampled.2 final :=
          sampledExtendsRest.trans extension
        exact squeezeColumns_below_of_extends
          base absorbed final placed sampledExtendsFinal
      · exact inductionHypothesis sampled.2 extension
          columns inRest

end Nightstream.Implementation.R1CS.Canonical.KSplitNcTranscriptPlacement
