import DirectCcsFPrime.ProofSystem.Production.Impl.RawProduction.DirectParentOnlyProductionConcreteFPrimePriorRawProductionExact

/-!
Thin interface for the raw production prior-verifier surface.

This file owns only the raw public-IO verifier names and raw verifier
consequences. Exact terminal IO, runtime authority, and compressed verifier
soundness are exported by sibling interfaces.
-/

namespace DirectCcsFPrime

namespace DirectParentOnlyProductionConcreteFPrimePriorRawProductionRawInterface

export DirectParentOnlyProductionConcreteFPrimePriorRawProduction (
  ProductionContext
  PublicImage
  ProofCarryingPriorProof
  ProductionRawPriorVerifierChecks
  ProductionCompactImageReplay
  ProductionConstruction2BoundaryReplay
  ProductionPoseidon2TranscriptReplay
  rawPublicIOVerifierChecksOfProduction
  ProductionRawVerifierAccepted
  ProductionRawBoundStatementAccepted
  productionRawBoundStatementAccepted_ofRawBoundStatement
  ProductionRawPriorOpeningSurface
  productionReplayBindsProofStatement
  rawPublicIOOpeningSurfaceOfProduction
  RuntimeVerifyPriorOfProductionRaw
  AcceptedProductionRawEvidence
  runtimeVerifyPriorOfProductionRaw_boundStatement
  runtimeVerifyPriorOfProductionRaw_evidence
  certifiedPriorVerifierOfProductionRaw
  certifiedPriorVerifierOfProductionRaw_verify
  runtimeVerifyPriorOfProductionRaw_acceptedOpens
  runtimeVerifyPriorOfProductionRaw_reaches_prior
  runtimeVerifyPriorOfProductionRaw_cannot_accept_unreachable_prior
  runtimeVerifyPriorOfProductionRaw_publicImageInvariants
  proofFunctionalOfProductionRaw
  soundVerifierOfProductionRaw
  soundVerifierOfProductionRaw_accepts_iff
  soundVerifierOfProductionRaw_opensToFoldedAuthority
  soundVerifierOfProductionRaw_openedAuthority_accepts_of_open
  soundVerifierOfProductionRaw_bindsOpenedAuthoritySteps
  soundVerifierOfProductionRaw_bindsOpenedAuthorityImage
  soundVerifierOfProductionRaw_openAuthority_ne_none
  soundVerifierOfProductionRaw_cannot_accept_without_opening
  soundVerifierOfProductionRaw_reaches_prior
  soundVerifierOfProductionRaw_publicImageInvariants
  soundVerifierOfProductionRaw_cannot_accept_unreachable_prior
  soundVerifierOfProductionRaw_proofFunctional
  soundVerifierOfProductionRaw_sameProof
  certifiedSingleTerminalEndToEnd_ofProductionRawLatestStep
  acceptedTerminalWithSoundVerifierOfProductionRawLatestStep
  runtimeVerifyPriorOfProductionRaw_openAuthority_ne_none
  runtimeVerifyPriorOfProductionRaw_openedAuthority_accepts_of_open
  runtimeVerifyPriorOfProductionRaw_bindsOpenedAuthoritySteps
  runtimeVerifyPriorOfProductionRaw_bindsOpenedAuthorityImage
  runtimeVerifyPriorOfProductionRaw_cannot_accept_without_opening
  nonAggregatePrivateDecStageFacts_ofProductionRawLatestStep
  section71StageTargetAuditTrail_ofProductionRawLatestStep
)

end DirectParentOnlyProductionConcreteFPrimePriorRawProductionRawInterface

end DirectCcsFPrime
