//! Exact optimized NIFS evidence for the fixed F-prime carrier fixture.
//!
//! Owns: the legacy carrier counterexample (`1 x 257` all-zero R1CS),
//! deterministic preprocessing seed 41, canonical fixed-k zero accumulator,
//! one honest zero witness, one witness changed only at the first completed
//! Phi81 carrier coordinate, and a drift-checked Lean data export.
//!
//! Does not own: independent NC semantics, a general Pi_CCS/NIFS refinement,
//! F-prime acceptance, a production relation choice, R1CS lowering, constraint
//! removal, or constraint counts.
//!
//! | Protocol | Phase | Family | Exported evidence |
//! |---|---|---|---|
//! | F-prime / NIFS | fixed carrier | verifier-owned CCS structure | exact rows, columns, arity, degree, public width, and structure digest |
//! | Pi_CCS | fresh witness | completed Phi81 carrier | logical views agree; full views differ only from coordinate 257 onward |
//! | Pi_CCS | initial accumulator | canonical fixed-k zero | exact running-claim count |
//! | Pi_CCS | optimized prove / verify | public API | both exact claims verify under the same fixed structure and transcript schedule |
//! | NIFS | optimized prove / verify | fixed Construction-2 API | exact prover/verifier outcomes for both claims |
//! | F-prime | recursive NIFS.V | repaired physical carrier boundary | exact rejection outcome for a linked 257-wide input with the same bad tail |
//! | implementation refinement | Rust to Lean | artifact drift | exact generated bytes or a review-only `.expected` file |

use neo_ccs::traits::SModuleHomomorphism;
use neo_ccs::Mat;
use neo_fold_clean::engine::transcript::Transcript;
use neo_fold_clean::frontends::direct_ccs::{self, R1cs};
use neo_fold_clean::frontends::r1cs_f_prime::{
    semantic_state_digest_fields, FullFPrimeContext, FullFPrimeRelation, R1csShape,
};
use neo_fold_clean::paper::construction2::RunningInstance;
use neo_fold_clean::paper::digest::{
    digest32_as_fields, digest_fields_as_digest32, f_prime_chunk_public_digest,
    f_prime_chunk_public_digest_for_uniform_shape, state_x_out_digest_with_mode, structure_digest, AccumulatorHandle,
    StateXOutDigestMode,
};
use neo_fold_clean::paper::f_prime::r1cs::{
    encode_f_prime_public_input, FPrimePublicInputLayout, FPrimeRecursiveInputs, FPrimeStateIn, FPrimeStepConfig,
    F_PRIME_ENC_INST_BITS, F_PRIME_PUBLIC_INPUT_LEN,
};
use neo_fold_clean::paper::f_prime::source_image::{BitRange, FPrimeSourceImage, Word64Image};
use neo_fold_clean::paper::nifs::circuit::NifsVCircuitMessages;
use neo_fold_clean::paper::nifs::{prove_fixed, verify_fixed, FixedNifsAccumulator};
use neo_fold_clean::paper::reductions::pi_ccs;
use neo_fold_clean::CcsInstance;
use neo_math::{KExtensions, D, F, K};
use neo_reductions::common::{decode_superneo_coeffs_from_witness_mat, decode_z_from_witness_mat};
use p3_field::{PrimeCharacteristicRing, PrimeField64};

const PREPROCESS_SEED: u64 = 41;
const FIRST_COMPLETED_TAIL: usize = F_PRIME_PUBLIC_INPUT_LEN;
const FIRST_TAIL_BLOCK: usize = FIRST_COMPLETED_TAIL / D;
const FIRST_TAIL_LANE: usize = FIRST_COMPLETED_TAIL % D;
const TAIL_VALUE: u64 = 2;
const F_PRIME_TRANSCRIPT_LABEL: &[u8] = b"neo.test.fixed_carrier_nifs/step/v1";
const ARTIFACT_REL_PATH: &str = "/../../formal/nightstream-lean/Nightstream/Implementation/R1CS/Artifacts/FPrimeFullHistory/Generated/FPrimeFixedCarrierNifsArtifact.lean";

struct Snapshot {
    relation_rows: usize,
    relation_columns: usize,
    relation_arity: usize,
    relation_degree: u32,
    public_input_len: usize,
    nc_bound: u32,
    packed_rows: usize,
    packed_columns: usize,
    canonical_running_count: usize,
    structure_digest: [u64; 4],
    zero_packed_storage: Vec<u64>,
    tail_packed_storage: Vec<u64>,
    zero_logical_decode: Vec<(u64, u64)>,
    tail_logical_decode: Vec<(u64, u64)>,
    zero_full_decode: Vec<(u64, u64)>,
    tail_full_decode: Vec<(u64, u64)>,
    fresh_public_inputs_equal: bool,
    commitments_differ: bool,
    zero_pi_ccs_accepted: bool,
    tail_pi_ccs_accepted: bool,
    zero_nifs_proved: bool,
    zero_nifs_verified: bool,
    tail_nifs_proved: bool,
    tail_nifs_verified: bool,
    linked_public_input: Vec<u64>,
    linked_tail_full_decode: Vec<(u64, u64)>,
    linked_tail_nifs_proved: bool,
    linked_tail_nifs_verified: bool,
    linked_recursive_f_prime_built: bool,
    linked_recursive_f_prime_satisfied: bool,
}

struct LinkedFPrimeOutcome {
    public_input: Vec<u64>,
    tail_full_decode: Vec<(u64, u64)>,
    nifs_proved: bool,
    nifs_verified: bool,
    recursive_f_prime_built: bool,
    recursive_f_prime_satisfied: bool,
}

struct RecursiveSource {
    image: FPrimeSourceImage,
    chunk_count: Word64Image,
    step_count: Word64Image,
    pc: Word64Image,
    prior_x_out: BitRange,
    x_out: BitRange,
}

fn fixed_carrier_r1cs() -> R1cs {
    R1cs {
        a: Mat::zero(1, F_PRIME_PUBLIC_INPUT_LEN, F::ZERO),
        b: Mat::zero(1, F_PRIME_PUBLIC_INPUT_LEN, F::ZERO),
        c: Mat::zero(1, F_PRIME_PUBLIC_INPUT_LEN, F::ZERO),
        m_in: F_PRIME_PUBLIC_INPUT_LEN,
    }
}

fn fibonacci_step_r1cs() -> R1csShape {
    // z = [1, a, b, next_a, next_b]
    // b * 1 = next_a
    // (a + b) * 1 = next_b
    let mut a = Mat::zero(2, 5, F::ZERO);
    let mut b = Mat::zero(2, 5, F::ZERO);
    let mut c = Mat::zero(2, 5, F::ZERO);
    a[(0, 2)] = F::ONE;
    b[(0, 0)] = F::ONE;
    c[(0, 3)] = F::ONE;
    a[(1, 1)] = F::ONE;
    a[(1, 2)] = F::ONE;
    b[(1, 0)] = F::ONE;
    c[(1, 4)] = F::ONE;
    R1cs { a, b, c, m_in: 1 }.into()
}

fn f_prime_step_config(prep: &neo_fold_clean::Preprocessing) -> FPrimeStepConfig<'_> {
    FPrimeStepConfig {
        nifs: prep
            .nifs_v_circuit_config()
            .expect("fixed NIFS.V circuit config"),
        b: prep.params.b(),
        transcript_label: F_PRIME_TRANSCRIPT_LABEL,
        public_input_layout: FPrimePublicInputLayout::plain(),
        nebula: None,
        state_x_out_digest_mode: StateXOutDigestMode::Stateful,
    }
}

fn canonical_accumulator_digest(prep: &neo_fold_clean::Preprocessing) -> [F; 4] {
    let zero = RunningInstance::canonical_zero(&prep.params, prep.structure(), F_PRIME_PUBLIC_INPUT_LEN)
        .expect("canonical fixed-k accumulator");
    AccumulatorHandle::from_running_parts(&zero.claims, zero.parent_authority.as_ref()).digest_fields()
}

fn uniform_chunk_digest(prep: &neo_fold_clean::Preprocessing, start_index: u64) -> [F; 4] {
    f_prime_chunk_public_digest_for_uniform_shape(
        start_index,
        1,
        D,
        prep.params.kappa() as usize,
        F_PRIME_PUBLIC_INPUT_LEN,
    )
}

fn native_x_out(
    state: &FPrimeStateIn,
    chunk_digest: [F; 4],
    semantic_state: [F; 4],
    construction2_acc: [F; 4],
    chunk_count: u64,
    step_count: u64,
) -> [F; 4] {
    digest32_as_fields(state_x_out_digest_with_mode(
        StateXOutDigestMode::Stateful,
        digest_fields_as_digest32(state.vk_fs_digest),
        state.pi_ccs_header_bundle,
        &state.pi_ccs_header_bundle,
        chunk_count,
        step_count,
        digest_fields_as_digest32(state.z_0),
        digest_fields_as_digest32(chunk_digest),
        state.pc,
        digest_fields_as_digest32(semantic_state),
        digest_fields_as_digest32(construction2_acc),
        digest_fields_as_digest32(chunk_digest),
        None,
    ))
}

fn append_f_prime_context(tr: &mut Transcript, state: &FPrimeStateIn, chunk_digest: [F; 4]) {
    tr.append_fields(b"f_prime/vk_fs", &state.vk_fs_digest);
    tr.append_fields(b"f_prime/pi_ccs_header", &state.pi_ccs_header_bundle);
    tr.append_fields(b"f_prime/chunk_count_in", &[F::from_u64(state.chunk_count_in)]);
    tr.append_fields(b"f_prime/step_count_in", &[F::from_u64(state.step_count_in)]);
    tr.append_fields(b"f_prime/z_0", &state.z_0);
    tr.append_fields(b"f_prime/z_i_in", &state.z_i_in);
    tr.append_fields(b"f_prime/pc", &[F::from_u64(state.pc)]);
    tr.append_fields(b"f_prime/semantic_state_in", &state.semantic_state_digest_in);
    tr.append_fields(b"f_prime/acc_digest_in", &state.acc_digest_in);
    tr.append_fields(b"f_prime/public_trace_in", &state.public_trace_in);
    tr.append_fields(b"f_prime/chunk_digest", &chunk_digest);
}

fn recursive_source(state: &FPrimeStateIn, prior_x_out: [F; 4], x_out: [F; 4]) -> RecursiveSource {
    let mut image = FPrimeSourceImage::new();
    let chunk_count = image.push_u64_le(state.chunk_count_in);
    let step_count = image.push_u64_le(state.step_count_in);
    let pc = image.push_u64_le(state.pc);
    let prior_public = image.push_f_prime_public_input(prior_x_out);
    let prior_x_out = BitRange::new(prior_public.start() + 1, F_PRIME_ENC_INST_BITS);
    let x_out = image.push_enc_inst(x_out);
    RecursiveSource {
        image,
        chunk_count,
        step_count,
        pc,
        prior_x_out,
        x_out,
    }
}

fn extension_pairs(values: &[K]) -> Vec<(u64, u64)> {
    values.iter().map(KExtensions::to_limbs_u64).collect()
}

fn optimized_pi_ccs_accepts(
    prep: &neo_fold_clean::Preprocessing,
    running: &RunningInstance,
    fresh: CcsInstance,
) -> bool {
    let fresh_claim = fresh.claim.clone();
    let mut prover_transcript = Transcript::session();
    let proof = match pi_ccs::prove(
        &mut prover_transcript,
        &prep.params,
        prep.structure(),
        prep.optimized_cache(),
        &prep.log,
        vec![fresh],
        running,
    ) {
        Ok(proof) => proof,
        Err(_) => return false,
    };

    let verifier_running = running.claims_only();
    let mut verifier_transcript = Transcript::session();
    pi_ccs::verify(
        &mut verifier_transcript,
        &prep.params,
        prep.structure(),
        prep.optimized_cache(),
        core::slice::from_ref(&fresh_claim),
        &verifier_running,
        &proof,
    )
    .is_ok()
}

fn optimized_nifs_outcome(
    prep: &neo_fold_clean::Preprocessing,
    running: &FixedNifsAccumulator,
    fresh: CcsInstance,
) -> (bool, bool) {
    let fresh_claim = fresh.claim.clone();
    let mut prover_transcript = Transcript::session();
    let (_next, proof) = match prove_fixed(
        &mut prover_transcript,
        &prep.params,
        prep.structure(),
        prep.optimized_cache(),
        &prep.log,
        prep.mix_rhos_commits(),
        prep.combine_b_pows(),
        fresh,
        running,
    ) {
        Ok(output) => output,
        Err(_) => return (false, false),
    };

    let verifier_running = match FixedNifsAccumulator::from_verifier_running(
        &prep.params,
        prep.structure(),
        prep.combine_b_pows(),
        running.running().claims_only(),
    ) {
        Ok(running) => running,
        Err(_) => return (true, false),
    };
    let mut verifier_transcript = Transcript::session();
    let verified = verify_fixed(
        &mut verifier_transcript,
        &prep.params,
        prep.structure(),
        prep.optimized_cache(),
        prep.mix_rhos_commits(),
        prep.combine_b_pows(),
        &fresh_claim,
        &verifier_running,
        &proof,
    )
    .is_ok();
    (true, verified)
}

fn linked_recursive_f_prime_outcome(prep: &neo_fold_clean::Preprocessing, carrier: &R1cs) -> LinkedFPrimeOutcome {
    let application = fibonacci_step_r1cs();
    let application_assignment = [F::ONE, F::from_u64(5), F::from_u64(8), F::from_u64(8), F::from_u64(13)];
    let semantic_in = semantic_state_digest_fields(&application_assignment[1..3]);
    let semantic_out = semantic_state_digest_fields(&application_assignment[3..5]);
    let context = FullFPrimeContext::derive(&prep.params, prep.structure(), &prep.log, semantic_in)
        .expect("fixed F-prime verifier context");
    let relation = FullFPrimeRelation::new(context, f_prime_step_config(prep), &application, vec![1, 2], vec![3, 4])
        .expect("fixed full F-prime relation");

    let zero = FixedNifsAccumulator::canonical_zero(
        &prep.params,
        prep.structure(),
        prep.combine_b_pows(),
        F_PRIME_PUBLIC_INPUT_LEN,
    )
    .expect("fixed-k zero accumulator");
    let zero_digest = canonical_accumulator_digest(prep);
    let prior_chunk_digest = uniform_chunk_digest(prep, 0);
    let state = FPrimeStateIn {
        vk_fs_digest: context.vk_fs_digest(),
        pi_ccs_header_bundle: context.pi_ccs_header_bundle(),
        chunk_count_in: 1,
        step_count_in: 1,
        z_0: semantic_in,
        z_i_in: prior_chunk_digest,
        pc: 1,
        semantic_state_digest_in: semantic_in,
        acc_digest_in: zero_digest,
        public_trace_in: prior_chunk_digest,
        nebula: None,
    };
    let prior_x_out = native_x_out(&state, prior_chunk_digest, semantic_in, zero_digest, 1, 1);
    let public_input = encode_f_prime_public_input(prior_x_out);
    let mut fresh =
        direct_ccs::build_instance(prep, carrier, &public_input).expect("linked fixed-carrier CCS instance");
    fresh.witness.Z[(FIRST_TAIL_LANE, FIRST_TAIL_BLOCK)] = F::from_u64(TAIL_VALUE);
    fresh.claim.c = prep.log.commit(&fresh.witness.Z);
    let tail_full_decode = decode_superneo_coeffs_from_witness_mat(&fresh.witness.Z, F_PRIME_PUBLIC_INPUT_LEN)
        .expect("linked tail full-carrier decode");
    let fresh_claim = fresh.claim.clone();
    let fresh_claims = [fresh_claim.clone()];
    let chunk_digest = f_prime_chunk_public_digest(state.step_count_in, &fresh_claims);

    let mut prover_transcript = Transcript::with_label(F_PRIME_TRANSCRIPT_LABEL);
    append_f_prime_context(&mut prover_transcript, &state, chunk_digest);
    let (next, proof) = match prove_fixed(
        &mut prover_transcript,
        &prep.params,
        prep.structure(),
        prep.optimized_cache(),
        &prep.log,
        prep.mix_rhos_commits(),
        prep.combine_b_pows(),
        fresh,
        &zero,
    ) {
        Ok(output) => output,
        Err(_) => {
            return LinkedFPrimeOutcome {
                public_input: public_input
                    .iter()
                    .map(PrimeField64::as_canonical_u64)
                    .collect(),
                tail_full_decode: extension_pairs(&tail_full_decode),
                nifs_proved: false,
                nifs_verified: false,
                recursive_f_prime_built: false,
                recursive_f_prime_satisfied: false,
            };
        }
    };

    let verifier_zero = FixedNifsAccumulator::from_verifier_running(
        &prep.params,
        prep.structure(),
        prep.combine_b_pows(),
        zero.running().claims_only(),
    )
    .expect("verifier-side zero accumulator");
    let mut verifier_transcript = Transcript::with_label(F_PRIME_TRANSCRIPT_LABEL);
    append_f_prime_context(&mut verifier_transcript, &state, chunk_digest);
    let nifs_verified = verify_fixed(
        &mut verifier_transcript,
        &prep.params,
        prep.structure(),
        prep.optimized_cache(),
        prep.mix_rhos_commits(),
        prep.combine_b_pows(),
        &fresh_claim,
        &verifier_zero,
        &proof,
    )
    .is_ok();

    let next_digest =
        AccumulatorHandle::from_running_parts(next.claims(), next.running().parent_authority.as_ref()).digest_fields();
    let expected_x_out = native_x_out(&state, chunk_digest, semantic_out, next_digest, 2, 2);
    let source = recursive_source(&state, prior_x_out, expected_x_out);
    let messages = NifsVCircuitMessages {
        fresh: &fresh_claims,
        running: zero.claims(),
        running_parent_authority: zero.running().parent_authority.as_ref(),
        running_pending_projection: zero.running().pending_projection(),
        pi_ccs: &proof.pi_ccs,
        combined: &proof.pi_rlc.combined,
        children: next.claims(),
    };
    let inputs = FPrimeRecursiveInputs {
        state,
        chunk_digest,
        semantic_state_digest_out: semantic_out,
        acc_digest_out: next_digest,
        nifs_msg: messages,
        rows_in_chunk: 1,
        source_image: &source.image,
        chunk_count_in_word: source.chunk_count,
        step_count_in_word: source.step_count,
        pc_word: source.pc,
        prior_x_out_bits: source.prior_x_out,
        public_x_out_bits: source.x_out,
    };
    let execution = relation.build_recursive(&inputs, &application_assignment);
    let (recursive_f_prime_built, recursive_f_prime_satisfied) = match execution {
        Ok(execution) => (true, execution.is_satisfied()),
        Err(_) => (false, false),
    };

    LinkedFPrimeOutcome {
        public_input: public_input
            .iter()
            .map(PrimeField64::as_canonical_u64)
            .collect(),
        tail_full_decode: extension_pairs(&tail_full_decode),
        nifs_proved: true,
        nifs_verified,
        recursive_f_prime_built,
        recursive_f_prime_satisfied,
    }
}

fn capture() -> Snapshot {
    let r1cs = fixed_carrier_r1cs();
    let prep = direct_ccs::preprocess_seeded(&r1cs, PREPROCESS_SEED).expect("fixed carrier preprocessing");
    let zero_assignment = vec![F::ZERO; F_PRIME_PUBLIC_INPUT_LEN];
    let zero = direct_ccs::build_instance(&prep, &r1cs, &zero_assignment).expect("zero fixed-carrier instance");
    let mut tail = zero.clone();
    tail.witness.Z[(FIRST_TAIL_LANE, FIRST_TAIL_BLOCK)] = F::from_u64(TAIL_VALUE);
    tail.claim.c = prep.log.commit(&tail.witness.Z);

    let running = RunningInstance::canonical_zero(&prep.params, prep.structure(), F_PRIME_PUBLIC_INPUT_LEN)
        .expect("canonical fixed-k zero accumulator");
    let fixed_running = FixedNifsAccumulator::canonical_zero(
        &prep.params,
        prep.structure(),
        prep.combine_b_pows(),
        F_PRIME_PUBLIC_INPUT_LEN,
    )
    .expect("canonical fixed Construction-2 accumulator");

    let zero_logical_decode = decode_z_from_witness_mat(prep.params.inner(), &zero.witness.Z, F_PRIME_PUBLIC_INPUT_LEN)
        .expect("zero logical decode");
    let tail_logical_decode = decode_z_from_witness_mat(prep.params.inner(), &tail.witness.Z, F_PRIME_PUBLIC_INPUT_LEN)
        .expect("tail logical decode");
    let zero_full_decode = decode_superneo_coeffs_from_witness_mat(&zero.witness.Z, F_PRIME_PUBLIC_INPUT_LEN)
        .expect("zero full-carrier decode");
    let tail_full_decode = decode_superneo_coeffs_from_witness_mat(&tail.witness.Z, F_PRIME_PUBLIC_INPUT_LEN)
        .expect("tail full-carrier decode");
    let (zero_nifs_proved, zero_nifs_verified) = optimized_nifs_outcome(&prep, &fixed_running, zero.clone());
    let (tail_nifs_proved, tail_nifs_verified) = optimized_nifs_outcome(&prep, &fixed_running, tail.clone());
    let linked = linked_recursive_f_prime_outcome(&prep, &r1cs);

    Snapshot {
        relation_rows: prep.structure().n,
        relation_columns: prep.structure().m,
        relation_arity: prep.structure().t(),
        relation_degree: prep.structure().max_degree(),
        public_input_len: prep.public_input_len.expect("fixed public width"),
        nc_bound: prep.params.b(),
        packed_rows: zero.witness.Z.rows(),
        packed_columns: zero.witness.Z.cols(),
        canonical_running_count: running.claims.len(),
        structure_digest: structure_digest(prep.structure()).map(|value| value.as_canonical_u64()),
        zero_packed_storage: zero
            .witness
            .Z
            .as_slice()
            .iter()
            .map(PrimeField64::as_canonical_u64)
            .collect(),
        tail_packed_storage: tail
            .witness
            .Z
            .as_slice()
            .iter()
            .map(PrimeField64::as_canonical_u64)
            .collect(),
        zero_logical_decode: extension_pairs(&zero_logical_decode),
        tail_logical_decode: extension_pairs(&tail_logical_decode),
        zero_full_decode: extension_pairs(&zero_full_decode),
        tail_full_decode: extension_pairs(&tail_full_decode),
        fresh_public_inputs_equal: zero.claim.x == tail.claim.x,
        commitments_differ: zero.claim.c != tail.claim.c,
        zero_pi_ccs_accepted: optimized_pi_ccs_accepts(&prep, &running, zero),
        tail_pi_ccs_accepted: optimized_pi_ccs_accepts(&prep, &running, tail),
        zero_nifs_proved,
        zero_nifs_verified,
        tail_nifs_proved,
        tail_nifs_verified,
        linked_public_input: linked.public_input,
        linked_tail_full_decode: linked.tail_full_decode,
        linked_tail_nifs_proved: linked.nifs_proved,
        linked_tail_nifs_verified: linked.nifs_verified,
        linked_recursive_f_prime_built: linked.recursive_f_prime_built,
        linked_recursive_f_prime_satisfied: linked.recursive_f_prime_satisfied,
    }
}

fn render_nat_list(values: &[u64]) -> String {
    if values.iter().all(|value| *value == 0) {
        return format!("List.replicate {} 0", values.len());
    }
    let nonzero: Vec<(usize, u64)> = values
        .iter()
        .copied()
        .enumerate()
        .filter(|(_, value)| *value != 0)
        .collect();
    if let [(index, value)] = nonzero.as_slice() {
        return format!("(List.replicate {} 0).set {index} {value}", values.len());
    }
    format!(
        "[{}]",
        values
            .iter()
            .map(u64::to_string)
            .collect::<Vec<_>>()
            .join(", ")
    )
}

fn render_extension_list(values: &[(u64, u64)]) -> String {
    if values.iter().all(|value| *value == (0, 0)) {
        return format!("List.replicate {} (0, 0)", values.len());
    }
    let nonzero: Vec<(usize, (u64, u64))> = values
        .iter()
        .copied()
        .enumerate()
        .filter(|(_, value)| *value != (0, 0))
        .collect();
    if let [(index, (c0, c1))] = nonzero.as_slice() {
        return format!("(List.replicate {} (0, 0)).set {index} ({c0}, {c1})", values.len());
    }
    format!(
        "[{}]",
        values
            .iter()
            .map(|(c0, c1)| format!("({c0}, {c1})"))
            .collect::<Vec<_>>()
            .join(", ")
    )
}

fn render_bool(value: bool) -> &'static str {
    if value {
        "true"
    } else {
        "false"
    }
}

fn emit_lean(snapshot: &Snapshot) -> String {
    format!(
        "import Nightstream.SuperNeo.Concrete.Algebra\n\n\
/-!\nGENERATED FILE - do not edit by hand.\n\n\
Exact outputs of the current fixed F-prime carrier fixture: the `1 x 257`\n\
all-zero R1CS translated by the direct-CCS frontend, preprocessing seed 41,\n\
and a canonical fixed-k zero accumulator. The tail witness differs only at\n\
completed Phi81 carrier coordinate 257.\n\n\
Regenerated and drift-checked by\n\
`cargo test -p neo-fold-clean --release --test f_prime_fixed_carrier_nifs_lean_artifact`.\n\n\
This is implementation evidence, not semantic authority. It does not prove a\n\
general Pi_CCS/NIFS refinement, F-prime acceptance, or permission to remove rows.\n\
-/\n\n\
namespace Nightstream.Implementation.R1CS.FPrimeFixedCarrierNifsArtifact\n\n\
def preprocessSeed : Nat := {PREPROCESS_SEED}\n\
def ringDegree : Nat := {D}\n\
def relationRows : Nat := {}\n\
def relationColumns : Nat := {}\n\
def relationArity : Nat := {}\n\
def relationDegree : Nat := {}\n\
def publicInputLen : Nat := {}\n\
def ncBound : Nat := {}\n\
def packedRows : Nat := {}\n\
def packedColumns : Nat := {}\n\
def firstCompletedTail : Nat := {FIRST_COMPLETED_TAIL}\n\
def firstTailBlock : Nat := {FIRST_TAIL_BLOCK}\n\
def firstTailLane : Nat := {FIRST_TAIL_LANE}\n\
def tailValue : Nat := {TAIL_VALUE}\n\
def canonicalRunningCount : Nat := {}\n\n\
def structureDigest : List Nat := [{}, {}, {}, {}]\n\n\
def freshPublicInputsEqual : Bool := {}\n\
def commitmentsDiffer : Bool := {}\n\
def zeroPiCcsAccepted : Bool := {}\n\
def tailPiCcsAccepted : Bool := {}\n\n\
def zeroNifsProved : Bool := {}\n\
def zeroNifsVerified : Bool := {}\n\
def tailNifsProved : Bool := {}\n\
def tailNifsVerified : Bool := {}\n\n\
def linkedTailNifsProved : Bool := {}\n\
def linkedTailNifsVerified : Bool := {}\n\
def linkedRecursiveFPrimeBuilt : Bool := {}\n\
def linkedRecursiveFPrimeSatisfied : Bool := {}\n\n\
def zeroPackedStorage : List Nat :=\n  {}\n\n\
def tailPackedStorage : List Nat :=\n  {}\n\n\
def zeroLogicalDecode : List (Nat × Nat) :=\n  {}\n\n\
def tailLogicalDecode : List (Nat × Nat) :=\n  {}\n\n\
def zeroFullDecode : List (Nat × Nat) :=\n  {}\n\n\
def tailFullDecode : List (Nat × Nat) :=\n  {}\n\n\
def linkedPublicInput : List Nat :=\n  {}\n\n\
def linkedTailFullDecode : List (Nat × Nat) :=\n  {}\n\n\
end Nightstream.Implementation.R1CS.FPrimeFixedCarrierNifsArtifact\n",
        snapshot.relation_rows,
        snapshot.relation_columns,
        snapshot.relation_arity,
        snapshot.relation_degree,
        snapshot.public_input_len,
        snapshot.nc_bound,
        snapshot.packed_rows,
        snapshot.packed_columns,
        snapshot.canonical_running_count,
        snapshot.structure_digest[0],
        snapshot.structure_digest[1],
        snapshot.structure_digest[2],
        snapshot.structure_digest[3],
        render_bool(snapshot.fresh_public_inputs_equal),
        render_bool(snapshot.commitments_differ),
        render_bool(snapshot.zero_pi_ccs_accepted),
        render_bool(snapshot.tail_pi_ccs_accepted),
        render_bool(snapshot.zero_nifs_proved),
        render_bool(snapshot.zero_nifs_verified),
        render_bool(snapshot.tail_nifs_proved),
        render_bool(snapshot.tail_nifs_verified),
        render_bool(snapshot.linked_tail_nifs_proved),
        render_bool(snapshot.linked_tail_nifs_verified),
        render_bool(snapshot.linked_recursive_f_prime_built),
        render_bool(snapshot.linked_recursive_f_prime_satisfied),
        render_nat_list(&snapshot.zero_packed_storage),
        render_nat_list(&snapshot.tail_packed_storage),
        render_extension_list(&snapshot.zero_logical_decode),
        render_extension_list(&snapshot.tail_logical_decode),
        render_extension_list(&snapshot.zero_full_decode),
        render_extension_list(&snapshot.tail_full_decode),
        render_nat_list(&snapshot.linked_public_input),
        render_extension_list(&snapshot.linked_tail_full_decode),
    )
}

#[test]
fn fixed_carrier_nifs_lean_artifact_matches_runtime() {
    assert_eq!(D, 54, "the artifact is specialized to Phi81");
    assert_eq!(F_PRIME_PUBLIC_INPUT_LEN, 257);
    assert_eq!(FIRST_COMPLETED_TAIL, 257);
    assert_eq!(FIRST_TAIL_BLOCK, 4);
    assert_eq!(FIRST_TAIL_LANE, 41);

    let snapshot = capture();
    assert_eq!(snapshot.relation_rows, 1);
    assert_eq!(snapshot.relation_columns, 257);
    assert_eq!(snapshot.relation_arity, 3);
    assert_eq!(snapshot.relation_degree, 2);
    assert_eq!(snapshot.public_input_len, 257);
    assert_eq!(snapshot.nc_bound, 2);
    assert_eq!(snapshot.packed_rows, 54);
    assert_eq!(snapshot.packed_columns, 5);
    assert!(snapshot.fresh_public_inputs_equal);
    assert!(snapshot.commitments_differ);
    assert_eq!(snapshot.zero_logical_decode, snapshot.tail_logical_decode);
    assert_ne!(snapshot.zero_full_decode, snapshot.tail_full_decode);
    assert_eq!(snapshot.tail_full_decode[FIRST_COMPLETED_TAIL], (TAIL_VALUE, 0));
    assert!(snapshot.zero_pi_ccs_accepted);
    assert!(snapshot.tail_pi_ccs_accepted);
    assert!(snapshot.zero_nifs_proved);
    assert!(snapshot.zero_nifs_verified);
    assert!(snapshot.tail_nifs_proved);
    assert!(snapshot.tail_nifs_verified);
    assert_eq!(snapshot.linked_public_input.len(), F_PRIME_PUBLIC_INPUT_LEN);
    assert_eq!(snapshot.linked_public_input[0], 1);
    assert_eq!(snapshot.linked_tail_full_decode.len(), D * 5);
    assert_eq!(snapshot.linked_tail_full_decode[FIRST_COMPLETED_TAIL], (TAIL_VALUE, 0));
    assert!(snapshot.linked_tail_nifs_proved);
    assert!(snapshot.linked_tail_nifs_verified);
    assert!(!snapshot.linked_recursive_f_prime_built);
    assert!(!snapshot.linked_recursive_f_prime_satisfied);

    let emitted = emit_lean(&snapshot);
    let path = format!("{}{}", env!("CARGO_MANIFEST_DIR"), ARTIFACT_REL_PATH);
    let committed = std::fs::read_to_string(&path).unwrap_or_default();
    if committed != emitted {
        let expected_path = format!("{path}.expected");
        let parent = std::path::Path::new(&expected_path)
            .parent()
            .expect("artifact path has a parent");
        std::fs::create_dir_all(parent).expect("create generated artifact directory");
        std::fs::write(&expected_path, &emitted).expect("write .expected artifact");
        panic!(
            "fixed-carrier NIFS Lean artifact drifted. Wrote {expected_path}; inspect it and promote it deliberately."
        );
    }
}
