import tests.EvidenceTargets
import NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingWork

/-! Standalone inspection driver. Each witness graph includes its exact target.
Run through validate.sh after building the library and tests.EvidenceTargets.
-/

#evidence_export LeanGraph.Targets.pilotAssignment
#evidence_export LeanGraph.Targets.piCCSAssignment
#evidence_export LeanGraph.Targets.piCCSPublicAssignment
#evidence_export LeanGraph.Targets.stage1TerminalAssignment
#evidence_export LeanGraph.Targets.stage1TerminalParent

-- The final target and its separate probability/clock correspondence obligations.
#evidence_export LeanGraph.Targets.hyperNovaLinearSecurity
#evidence_export NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingProbability.successProbability_tendsto
#evidence_export NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingWork.driverMean_tendsto
#evidence_export NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingWork.entered_exhaustion_tendsto
#evidence_export NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingWork.retryMean_zero_eq_runWork
#evidence_export NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingWork.retryMean_succ_eq_runWork
#evidence_export NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingWork.driverMean_eq_runWork
#evidence_export NightstreamFPrime.Lifecycle.Nifs.AdaptiveBindingWork.prepared_expected_work_polynomial_bound
