import tests.EvidenceTargets
import NightstreamFPrime.Export.Stage1.PiCCSCarriedMoments
import NightstreamFPrime.Export.Stage1.PiCCSCarriedAccumulation

/-! Exact dependency graph for the first-round replay kernel. -/
#evidence_export LeanGraph.Targets.piCCSFirstRoundReplayKernel
#evidence_export NightstreamFPrime.Export.Stage1.PiCCSCarriedMoments.full_components_eq_firstRound
#evidence_export NightstreamFPrime.Export.Stage1.PiCCSCarriedAccumulation.moment_of_exact_row_callbacks

#evidence_export LeanGraph.Targets.piCCSNormPrefixKernel
#evidence_export NightstreamFPrime.Export.Stage1.PiCCSPrefixCodeFold.decode_pairedCodes
#evidence_export NightstreamFPrime.Export.Stage1.PiCCSPrefixCodeFold.code_byte

#evidence_export LeanGraph.Targets.piCCSPrefixNormAccumulation
#evidence_export NightstreamFPrime.Export.Stage1.PiCCSPrefixNormBuckets.finish_accumulate_eq_add_range
#evidence_export NightstreamFPrime.Export.Stage1.PiCCSPrefixNormBuckets.accumulate_append
