import Nightstream.Implementation.Nebula.Commitment.Terminal.ProductCommitmentBridge

/-! Focused gates for the exact V2 product-commitment algebra. -/

set_option autoImplicit false

namespace tests.NebulaProductCommitmentAlgebra

open Nightstream.Implementation.Nebula

#check AlignedLaneAction.Slice.project_act
#check AlignedLaneAction.Slice.project_combineAssignments
#check AlignedLaneAction.Slice.project_recomposeAssignment
#check ProductCommitmentAlgebra.commit_combine
#check ProductCommitmentAlgebra.commit_recompose
#check ProductCommitmentAlgebra.piRlcAlgebra
#check ProductCommitmentAlgebra.piDecAlgebra
#check ProductCommitmentAlgebra.paperProfile
#check ProductCommitmentAlgebra.terminal_children_match_superNeo
#check TerminalProductCommitmentBridge.commit_eq_exactBundle
#check TerminalProductCommitmentBridge.product_opening_of_terminal_rows

end tests.NebulaProductCommitmentAlgebra
