import DirectCcsFPrime.ProofSystem.Production.Impl.Backend.DirectParentOnlyProductionConcreteFPrimePriorBackend

/-!
Typed interface for runtime-backend authority in the concrete prior F' verifier.

Spec: `specs/ProofSystem/Production/Impl/Backend/DirectParentOnlyProductionConcreteFPrimePriorBackend.spec.md`
-/

namespace DirectCcsFPrime

namespace DirectParentOnlyProductionConcreteFPrimePriorBackendInterface

abbrev ProductionContext :=
  DirectParentOnlyProductionConcreteFPrimePriorBackend.ProductionContext

abbrev PublicImage :=
  DirectParentOnlyProductionConcreteFPrimePriorBackend.PublicImage

abbrev ProofCarryingPriorProof :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.ProofCarryingPriorProof

abbrev ConcreteRuntimeBackendSurface :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.ConcreteRuntimeBackendSurface

abbrev RuntimeVerifyPrior :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.RuntimeVerifyPrior

abbrev authorityOpenerOfRuntimeBackend :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.authorityOpenerOfRuntimeBackend

abbrev AcceptedRuntimeBackendEvidence :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.AcceptedRuntimeBackendEvidence

abbrev runtimeVerifyPrior_acceptedOpens :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.runtimeVerifyPrior_acceptedOpens

abbrev runtimeVerifyPrior_evidence :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.runtimeVerifyPrior_evidence

abbrev certifiedPriorVerifierOfRuntimeBackend :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.certifiedPriorVerifierOfRuntimeBackend

abbrev runtimeVerifyPrior_openedAuthority_accepts_of_open :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.runtimeVerifyPrior_openedAuthority_accepts_of_open

abbrev runtimeVerifyPrior_reaches_prior :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.runtimeVerifyPrior_reaches_prior

abbrev runtimeVerifyPrior_cannot_accept_unreachable_prior :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.runtimeVerifyPrior_cannot_accept_unreachable_prior

abbrev certifiedSingleTerminalEndToEnd_ofRuntimeBackendLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.certifiedSingleTerminalEndToEnd_ofRuntimeBackendLatestStep

abbrev nonAggregatePrivateDecStageFacts_ofRuntimeBackendLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.nonAggregatePrivateDecStageFacts_ofRuntimeBackendLatestStep

abbrev section71StageTargetAuditTrail_ofRuntimeBackendLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.section71StageTargetAuditTrail_ofRuntimeBackendLatestStep

abbrev ExactTerminalBoundaryPublicIO :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.ExactTerminalBoundaryPublicIO

abbrev ConcreteRuntimeExactPublicIOSurface :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.ConcreteRuntimeExactPublicIOSurface

abbrev runtimeBackendSurfaceOfExactPublicIO :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.runtimeBackendSurfaceOfExactPublicIO

abbrev RuntimeVerifyPriorOfExactPublicIO :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.RuntimeVerifyPriorOfExactPublicIO

abbrev AcceptedExactPublicIOEvidence :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.AcceptedExactPublicIOEvidence

abbrev runtimeVerifyPriorOfExactPublicIO_evidence :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.runtimeVerifyPriorOfExactPublicIO_evidence

abbrev certifiedPriorVerifierOfExactPublicIO :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.certifiedPriorVerifierOfExactPublicIO

abbrev certifiedSingleTerminalEndToEnd_ofExactPublicIOLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.certifiedSingleTerminalEndToEnd_ofExactPublicIOLatestStep

abbrev nonAggregatePrivateDecStageFacts_ofExactPublicIOLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.nonAggregatePrivateDecStageFacts_ofExactPublicIOLatestStep

abbrev section71StageTargetAuditTrail_ofExactPublicIOLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.section71StageTargetAuditTrail_ofExactPublicIOLatestStep

abbrev ConcreteRuntimeRawPublicIOSurface :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.ConcreteRuntimeRawPublicIOSurface

abbrev RuntimeVerifyPriorOfRawPublicIO :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.RuntimeVerifyPriorOfRawPublicIO

abbrev authorityOpenerOfRawPublicIO :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.authorityOpenerOfRawPublicIO

abbrev runtimeVerifyPriorOfRawPublicIO_acceptedOpens :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.runtimeVerifyPriorOfRawPublicIO_acceptedOpens

abbrev AcceptedRawPublicIOEvidence :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.AcceptedRawPublicIOEvidence

abbrev runtimeVerifyPriorOfRawPublicIO_evidence :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.runtimeVerifyPriorOfRawPublicIO_evidence

abbrev certifiedPriorVerifierOfRawPublicIO :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.certifiedPriorVerifierOfRawPublicIO

abbrev runtimeVerifyPriorOfRawPublicIO_openedAuthority_accepts_of_open :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.runtimeVerifyPriorOfRawPublicIO_openedAuthority_accepts_of_open

abbrev runtimeVerifyPriorOfRawPublicIO_reaches_prior :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.runtimeVerifyPriorOfRawPublicIO_reaches_prior

abbrev certifiedSingleTerminalEndToEnd_ofRawPublicIOLatestStep :=
  @DirectParentOnlyProductionConcreteFPrimePriorBackend.certifiedSingleTerminalEndToEnd_ofRawPublicIOLatestStep

end DirectParentOnlyProductionConcreteFPrimePriorBackendInterface

end DirectCcsFPrime
