import tests.Nebula.Implementation.Production.FPrime.Terminal.OpeningAuthorityCountermodels
import tests.Axioms.Support

set_option autoImplicit false

namespace tests.Axioms.NebulaProductionTerminalOpeningAuthorityCountermodels

open tests.NebulaProductionTerminalOpeningAuthorityCountermodels

/-- info: 'tests.NebulaProductionTerminalOpeningAuthorityCountermodels.omitted_commitment_alias_accepts_wrong_opening' does not depend on any axioms -/
#guard_msgs in
#audit_axioms omitted_commitment_alias_accepts_wrong_opening

/-- info: 'tests.NebulaProductionTerminalOpeningAuthorityCountermodels.separate_assignments_accept_conflicting_shared_column' does not depend on any axioms -/
#guard_msgs in
#audit_axioms separate_assignments_accept_conflicting_shared_column

end tests.Axioms.NebulaProductionTerminalOpeningAuthorityCountermodels
