import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.StreamingPiRLCFamilyContinuity

/-! Focused surface for accepted PiRLC family-state continuity. -/

set_option autoImplicit false

namespace tests.FPrimeFullHistoryStreamingPiRLCFamilyContinuity

open Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingPiRLCFamilyContinuity

#check familyStateDigest
#check Poseidon2FamilyStateCollision
#check state_digest_eq_family_state_digest
#check PublicStateContinuous
#check accepted_public_continuity

end tests.FPrimeFullHistoryStreamingPiRLCFamilyContinuity
