import Nightstream.Protocol.FPrime.Frozen

/-!
Focused interface gate for the model-proved delayed packed-`yZcol`
production deviation exposed separately by the frozen facade.
-/

namespace Nightstream.Tests.FPrimeFrozenProductionDeviations

open Nightstream.Protocol.FPrime.Frozen.ProductionDeviations

#check BlockLaneCombinedNc.expectedRound_quartic
#check BlockLaneCombinedNc.authoritativeRunningProjection_eq_projectedRawRecomposition
#check BlockLaneCombinedNc.accepted_implies_paper_and_yRingBound_or_yRingUnbound_or_badEvent

#check Holds
#check holds
#check stateBindingCheck_eq_true_iff
#check piCcsMessageCheck_eq_true_iff_accepted
#check paperOutputCheck_eq_true_iff
#check canonicalParentOpeningCheck_eq_true_iff
#check check_eq_true_iff_accepted
#check baseCheck_eq_true_iff_accepted
#check accepted_and_packed_implies_transition_or_yRingUnbound_or_badEvent
#check of_piDec_and_stateBindings
#check projectionOpeningAccepted_implies_packedYZcolBound_or_badEvent
#check acceptedPair_of_nextPacked_implies_previousClosed_or_failure
#check ClosedTrace
#check AllOutputsClosed
#check Failure
#check closedTrace_implies_baseAndAllClosed_or_failure

end Nightstream.Tests.FPrimeFrozenProductionDeviations
