import Nightstream.Implementation.R1CS.Correspondence.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.ActiveTraceRawProjectionRows
import Nightstream.Implementation.R1CS.Correspondence.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.TerminalRawOldBlockProjectionArtifact.FinalRoundFactorization
import Nightstream.Implementation.R1CS.Correspondence.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.TerminalRawOldBlockProjectionArtifact.ProductionHonestAssignment

/-!
Focused interface regression for terminal raw-old-block `y_zcol` authority.

The checked surface starts at the fixed generated runtime placement and
transparent authoritative assignment, reaches the terminal raw-opening
contract, and finishes at the explicit base/recursive/terminal one-fold-delay
theorem. A caller-selected execution-audit record is not authority here.
-/

namespace Nightstream.Tests.FPrimeSelectiveFixedPointPiCcsNcRawOldBlockExecution

open Nightstream.Implementation.R1CS.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection
open Nightstream.Implementation.R1CS.PiCcsNc.Authority.DelayedResidual.CombinedNc
open Nightstream.Implementation.R1CS.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.TerminalRawOldBlockProjectionArtifact
open Nightstream.Implementation.R1CS.Artifacts.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.CombinedNc.Generated.Execution.RawOldBlockProjectionRowAt

#check productionEmitterLayout
#check actualRow productionEmitterLayout
#check productionEmitterLayout_checked
#check productionAjtaiJoin_checked
#check productionProfile_checked
#check productionSelector_checked
#check productionPhysicalRow_mem
#check productionPhysicalRow_injective
#check productionPhysicalRow_unique
#check productionArtifactContract
#check productionWeightedPrefixProjection_factorFinalRound
#check productionBaselineRows_exact
#check productionBaselineAllocatedColumns_exact
#check productionFactoredFinalRoundRows_exact
#check productionFactoredFinalRoundAllocatedColumns_exact
#check productionFactoredFinalRoundRowSavings_exact
#check productionFactoredFinalRoundAllocatedColumnSavings_exact
#check productionRowStop
#check productionDerivedProgram
#check honestArtifactRowsSatisfied
#check physicalAssignment
#check canonicalAssignment
#check canonicalAssignment_eq_source
#check canonicalAssignment_rawWitness
#check productionRows_projectionOpeningAccepted
#check ProductionTerminal.ProjectionOpeningAccepted
#check ActiveBoundary.claimsAcceptedTerminalRawProjection_implies_packed_or_parentOpeningBadEvent
#check ActiveTrace.Trace.TerminalRawProjectionChecked
#check ActiveTrace.Trace.TerminalRawProjectionRowsChecked
#check ActiveTrace.Trace.terminalRawProjectionRowsChecked_implies_terminalRawProjectionChecked
#check ActiveTrace.Trace.terminalRawProjectionRowsChecked_implies_terminalChecked
#check ActiveTrace.Trace.terminalRawProjection_implies_baseAndAllPacked_or_parentOpeningFailure
#check ActiveTrace.Trace.terminalRawProjectionRows_imply_baseAndAllPacked_or_parentOpeningFailure
#check ActiveTrace.Trace.terminalRawProjectionRows_imply_baseAllPackedAndAllPaper_or_parentOpeningFailure_or_paperFailure

example : productionBaselineRows = 25243884 := productionBaselineRows_exact
example : productionBaselineAllocatedColumns = 25243776 :=
  productionBaselineAllocatedColumns_exact
example : productionFactoredFinalRoundRows = 24185169 :=
  productionFactoredFinalRoundRows_exact
example : productionFactoredFinalRoundAllocatedColumns = 24185061 :=
  productionFactoredFinalRoundAllocatedColumns_exact
example : productionBaselineRows - productionFactoredFinalRoundRows = 1058715 :=
  productionFactoredFinalRoundRowSavings_exact
example : productionBaselineAllocatedColumns -
    productionFactoredFinalRoundAllocatedColumns = 1058715 :=
  productionFactoredFinalRoundAllocatedColumnSavings_exact

end Nightstream.Tests.FPrimeSelectiveFixedPointPiCcsNcRawOldBlockExecution
