import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.FPrimeFullHistoryCurrentTerminalLinkCompletion

/-!
Focused elaboration boundary for constructive completion of the current plain
terminal-link owner from the captured full-history snapshot.
-/

namespace NightstreamTests.FPrimeFullHistoryCurrentTerminalLinkCompletion

open Nightstream.Implementation.R1CS.FPrimeFullHistoryCurrentTerminalLinkCompletion

#check completedAssignment
#check completedAssignment_canonical
#check currentRows_of_snapshotLinkRows
#check completedAssignment_producerAligned
#check output_and_snapshot_rows_construct_currentPlainOwner

end NightstreamTests.FPrimeFullHistoryCurrentTerminalLinkCompletion
