import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.StreamingLifecycle

/-! Focused surface for the streaming lifecycle correspondence owner. -/

set_option autoImplicit false

#check Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingLifecycleRelation.Base
#check Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingLifecycleRelation.Recursive
#check Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingLifecycleRelation.Terminal
#check Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingLifecycleRelation.Base.public_cursors_zero_one
#check Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingPreludeRelation.initialReplayFields_length
#check Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingPreludeRelation.workItem_exact
#check Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingPreludeRelationArtifact.source_rows_imply_holds
#check Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingPreludeXOutLifecycleBridge.base_rows_imply_cursor_fields_zero_one
#check Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.StreamingLifecycleRecursiveVerifierKeyRowSound.stage_rows_imply_outputs
#check Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingLifecycleSourceSemanticLinkArtifact.base_rows_refine_semanticLink
#check Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingLifecycleSourceSemanticLinkArtifact.recursive_rows_refine_semanticLink
#check Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingPaperNifsAuthority.recursive_output_exact
#check Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingPiRLCFamilyPublicDecoder.generated_public_run_exact
#check Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingPiRLCFamilyPublicDecoder.finalWordValue_eq_publicWordValue
#check Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingPiRLCFamilyLifecycleBridge.PublicBoundRecursiveArm.commonPublicBinding
#check Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingPiRLCFamilyLifecycleBridge.PublicBoundRecursiveArm.toBound_or_outer_collision
#check Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingPiRLCFamilyLifecycleBridge.BoundRecursiveRun.outputs_exact_or_failure
