import Nightstream.Implementation.Rust.CanonicalConformance.NativeStep.FixedOneCanonicalAdapter

/-!
Focused elaboration boundary for the universal native-step to frozen
fixed-one adapter.
-/

namespace NightstreamTests.FPrimeNativeStepFixedOneCanonicalAdapter

open Nightstream.Implementation.Rust.CanonicalConformance.NativeStep
open Nightstream.Implementation.Rust.CanonicalConformance.NativeStep.FixedOneCanonicalAdapter

#check application_eq_some_iff
#check priorHash_eq_computed
#check nextHash_eq_computed
#check active_freshPublic_eq_encode_prior_iff
#check transition_iff_holds
#check canonicalAccepts_iff_holds
#check nativeAccepted_with_boundaries_and_outgoing_iff_canonicalAccepts
#check checkedRecorded_with_boundaries_and_outgoing_iff_canonicalAccepts

end NightstreamTests.FPrimeNativeStepFixedOneCanonicalAdapter
