import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.StreamingPiRLCPhaseEnvelopeArtifact
import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.StreamingPiRLCPhaseEnvelopePublicDelegation

/-! Focused surface for the exact PiRLC carry-phase semantic envelope. -/

set_option autoImplicit false

namespace tests.FPrimeFullHistoryStreamingPiRLCPhaseEnvelope

open Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingPiRLCPhaseEnvelopeArtifact

#check artifact_valid
#check exact_source_identity
#check exact_source_ranges
#check public_delegation_exact
#check shared_payload_columns
#check semantic_outputs_feed_x_out
#check hash_constant_values
#check hash_local_alias_values
#check hash_trace_input_values
#check payload_column_le_one
#check hash_rows_refine_phase_envelope
#check x_out_semantic_refines_phase_envelope

end tests.FPrimeFullHistoryStreamingPiRLCPhaseEnvelope
