import Nightstream.Protocol.FPrime.ConcretePhi81.ActiveSemantics.Necessity.ObligationPlan.SelectedNifs.SemanticMinimality

/-! Focused interface gate for the closed selected-NIFS semantic leaves. -/

open Nightstream.Protocol.FPrime.ConcretePhi81.ActiveSemantics.Necessity.ObligationPlan.SelectedNifs.SemanticMinimality

#check BaselineRealization
#check baselineWitness
#check baselineCandidate
#check baselineTargetHolds
#check baselineAccepted
#check baseline
#check challengeStrongSet_necessary
#check parentExact_necessary
#check childrenExact_necessary
#check noParentContext
#check noParentCandidate
#check noParent_not_authorized
#check noParent_semantics_iff
#check noParentWeakened
#check noParentRejected
#check incomingAuthority_necessary
#check differentPriorPoint
#check differentPriorPoint_ne_source
#check mismatchedPolynomialInput
#check mismatchedPolynomialInput_ne_source
#check mismatchedPolynomialContext
#check mismatchedPolynomialCandidate
#check mismatchedPolynomial_not_bound
#check mismatchedPolynomial_semantics_iff
#check mismatchedPolynomialWeakened
#check mismatchedPolynomialRejected
#check polynomialInput_necessary
#check wrongStageFreshStatement
#check mismatchedSourceProduct
#check mismatchedSourceProduct_fresh
#check mismatchedSourceProduct_running
#check mismatchedSourceContext
#check mismatchedSource_runningAccepted
#check mismatchedSourceCandidate
#check mismatchedSource_not_bound
#check mismatchedSource_semantics_iff
#check mismatchedSourceWeakened
#check mismatchedSourceRejected
#check sourceProduct_necessary
#check PiCcs.CanonicalContext.sourceBound
#check PiCcs.CanonicalContext.runningAccepted
#check falseCcsData
#check falseCcs_not_freshCcs
#check falseCcsWeakened
#check falseCcsRejected
#check freshCcs_necessary
#check highNormData
#check highNorm_not_allSourceNorms
#check highNormWeakened
#check highNormRejected
#check allSourceNorm_necessary
#check forgedCarriedData
#check forgedCarried_not_evaluations
#check forgedCarried_sourceBound
#check forgedCarried_piDecAccepted
#check forgedCarried_runningAccepted
#check forgedCarriedWeakened
#check forgedCarriedRejected
#check carriedEvaluations_necessary
#check provedNecessaryLeaves
#check openNecessityLeaves
#check provedNecessaryLeaves_eq_checks
#check openNecessityLeaves_eq_nil
#check necessity_classified
#check necessity_classification_disjoint
#check NecessityWitnesses
#check necessityWitnesses
