import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.StreamingFPrimeProgramArtifact

/-! Focused surface for the Rust-conformant streaming F-prime program. -/

namespace tests.FPrimeFullHistoryStreamingProgram

open Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingProgramArtifact

#check artifact_geometry_exact
#check artifact_valid
#check rust_program_exact
#check rust_program_length_exact
#check rust_lifecycle_group_map_exact
#check rust_circuit_kind_map_exact
#check rust_claim_coordinate_overlay_kind_map_exact
#check rust_claim_coordinate_overlay_link_runs_exact
#check rust_claim_coordinate_overlay_link_census_exact
#check rust_pi_rlc_family_overlay_kind_map_exact
#check rust_combined_overlay_kind_map_exact
#check rust_pi_rlc_family_overlay_link_runs_exact
#check rust_pi_rlc_family_overlay_link_census_exact
#check rust_pi_rlc_family_physical_link_contract_exact
#check rust_pi_rlc_family_body_overlay_rows_exact
#check rust_phase_public_layout_exact

end tests.FPrimeFullHistoryStreamingProgram
