import Nightstream.Implementation.R1CS.Correspondence.FPrimeSelectiveFixedPoint.PiCcsNc

/-! Focused interface regression for the full packed-witness layout contract. -/

namespace Nightstream.Tests.FPrimeSelectiveFixedPointPiCcsNcPackedWitness

open Nightstream.SuperNeo.Concrete
open Nightstream.SuperNeo.Folding.PiCCS.PaperJoint
open Nightstream.SuperNeo.Folding.PiCCS.PaperJoint.PaperLinearAlgebra
open Nightstream.SuperNeo.Folding.PiCCS.SplitNc
open Nightstream.Implementation.R1CS.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.PackedWitness

#check semanticBlockCount_eq_rustBlockCount
#check semanticBlockOfRust_rustBlockOfSemantic
#check rustBlockOfSemantic_semanticBlockOfRust
#check unpack_pack
#check pack_unpack
#check coordinatesAligned_iff_unpack_eq
#check unpack_packFresh_logical
#check unpack_packFresh_tail_zero
#check decodedData_coordinatesAligned
#check decodedData_not_runningWitnessBindingFailure
#check Nightstream.Implementation.R1CS.Artifacts.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.PackedWitnessDecoder.commitmentProbeColumnAt_exact
#check Nightstream.Implementation.R1CS.Artifacts.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.PackedWitnessDecoder.fixtureCommitmentDataIndex_bijective
#check Nightstream.Implementation.R1CS.Artifacts.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.PackedWitnessDecoder.productionCommitmentDataIndex_bijective
#check Nightstream.Implementation.R1CS.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.PackedWitnessCommitment.matrixBlock_eq_assignmentBlock_unpack
#check Nightstream.Implementation.R1CS.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.PackedWitnessCommitment.matrixCommit_eq_typedCommit
#check Nightstream.Implementation.R1CS.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.PackedWitnessCommitment.productionFlattened_matrixCommit_at
#check Nightstream.Implementation.R1CS.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.PackedWitnessCommitment.rawRunningCommitmentsBound_of_openedPackedWitnesses
#check Nightstream.Implementation.R1CS.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.PackedWitnessCommitment.openedPackedWitnesses_iff_rawRunningCommitmentsBound
#check Nightstream.Implementation.R1CS.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.PackedWitnessCommitment.rawRunningCommitmentsUnbound_iff_exists_matrixCommit_ne
#check Nightstream.Implementation.R1CS.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.PackedWitnessProduction.check_eq_true_iff_accepted
#check Nightstream.Implementation.R1CS.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.PackedWitnessProduction.terminalCheck_eq_true_iff_accepted
#check Nightstream.Implementation.R1CS.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.PackedWitnessProduction.checkedPair_of_stateChecks_implies_previousSemanticFold_or_badEvent
#check Nightstream.Implementation.R1CS.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.PackedWitnessProduction.messageCheckedPair_of_nextPacked_of_openedPackedWitnesses_implies_previousPacked_or_parentBindingFailure
#check Nightstream.Implementation.R1CS.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.PackedWitnessProduction.parentOpeningExternalBindingFailure_iff
#check Nightstream.Implementation.R1CS.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.PackedWitnessProduction.checkedTerminal_implies_semanticFold_or_badEvent
#check Nightstream.Implementation.R1CS.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.PackedWitnessProduction.checkedPair_of_stateChecks_implies_previousSemanticFold_or_namedFailure
#check Nightstream.Implementation.R1CS.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.PackedWitnessProduction.checkedPair_of_stateChecks_implies_previousPaper_or_namedFailure
#check Nightstream.Implementation.R1CS.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.PackedWitnessProduction.checkedTerminal_implies_semanticFold_or_namedFailure
#check Nightstream.Implementation.R1CS.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.PackedWitnessProduction.checkedTerminal_implies_paper_or_namedFailure
#check Nightstream.Implementation.R1CS.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.RefinementBoundary.checkedPair_implies_previousSemanticFold_or_namedFailure
#check Nightstream.Implementation.R1CS.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.RefinementBoundary.checkedTerminal_implies_semanticFold_or_namedFailure

example {shape : SemanticShape}
    (assignment : Assignment F shape.carrierWidth) :
    unpack (pack assignment) = assignment :=
  unpack_pack assignment

example {shape : SemanticShape}
    (witness : Matrix shape) :
    pack (unpack witness) = witness :=
  pack_unpack witness

example :
    Nightstream.Implementation.R1CS.Artifacts.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.PackedWitnessDecoder.GeneratedLayout.fixtureCommitmentWidth = 4 /\
      Nightstream.Implementation.R1CS.Artifacts.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.PackedWitnessDecoder.GeneratedLayout.productionCommitmentWidth = 18 := by
  decide

end Nightstream.Tests.FPrimeSelectiveFixedPointPiCcsNcPackedWitness
