import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.StreamingPiRLCFamilyPhysicalSequence

/-! Focused surface for the accepted 110-arm physical PiRLC sequence. -/

set_option autoImplicit false

namespace tests.FPrimeFullHistoryStreamingPiRLCFamilyPhysicalSequence

open Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingPiRLCFamilyPhysicalSequence

#check AcceptedPhysicalRun
#check AcceptedPhysicalRun.adjacent_cursor_eq
#check AcceptedPhysicalRun.adjacent_state_or_collision
#check AcceptedPhysicalRun.semanticRun
#check AcceptedPhysicalRun.semanticRun_or_collision
#check AcceptedPhysicalRun.start_finish_recovers_inputs_or_failure_or_collision
#check AcceptedPhysicalRun.outputs_exact_or_failure_or_collision

end tests.FPrimeFullHistoryStreamingPiRLCFamilyPhysicalSequence
