import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.FPrimeFullHistoryCurrentTerminalAffineShell

/-!
Focused elaboration boundary for the coefficient-exact bounded current
terminal affine shell.
-/

namespace NightstreamTests.FPrimeFullHistoryCurrentTerminalAffineShell

open Nightstream.Implementation.R1CS.FPrimeFullHistoryCurrentTerminalAffineShellSound

#check Captured.pins_eq_partition
#check Captured.rows_iff_holds
#check Captured.priorLatestPins_eq_currentPlacement
#check Captured.priorLatest_iff_currentPlacementRows

end NightstreamTests.FPrimeFullHistoryCurrentTerminalAffineShell
