import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.NifsPaper.PiRlc.SelectiveCarrier

/-! Focused surface checks for the shape-indexed physical evaluation carrier. -/

namespace tests.FPrimeFullHistoryPiRlcClaimEvaluationCarrier

#check Nightstream.Implementation.R1CS.FPrimeFullHistoryNifsPaper.PiRlc.ClaimEvaluationCarrier.Columns
#check Nightstream.Implementation.R1CS.FPrimeFullHistoryNifsPaper.PiRlc.ClaimEvaluationCarrier.fromClaim
#check Nightstream.Implementation.R1CS.FPrimeFullHistoryNifsPaper.PiRlc.ClaimEvaluationCarrier.decode_size
#check Nightstream.Implementation.R1CS.FPrimeFullHistoryNifsPaper.PiRlc.ClaimEvaluationCarrier.decode_fromClaim_eq_decodedEvaluations
#check Nightstream.Implementation.R1CS.FPrimeFullHistoryNifsPaper.PiRlc.SelectiveCarrier.decode_size

end tests.FPrimeFullHistoryPiRlcClaimEvaluationCarrier
