import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.SelectiveCcs.RadixFourSourceStageCoverageArtifact

namespace Tests.FPrimeFullHistorySelectiveCcsSourceStageCoverage

open Nightstream.Implementation.R1CS.FPrimeFullHistorySelectiveCcs.RadixFourSourceStageCoverageArtifact

example := candidate_profile_exact
example := candidate_census_exact
example := candidate_owner_order_exact
example := candidate_pi_rlc_stage_count
example := candidate_coverage_valid
example := candidate_source_fields_partition

end Tests.FPrimeFullHistorySelectiveCcsSourceStageCoverage
