import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.SelectiveCcs.RadixFourFirstAcceptedSelectionArtifact

namespace Tests.FPrimeFullHistoryRadixFourFirstAcceptedSelection

open Nightstream.Implementation.R1CS.FPrimeFullHistorySelectiveCcs.RadixFourFirstAcceptedSelectionArtifact

example := candidate_profile_exact
example := candidate_dimensions_exact
example := candidate_sampler_count_exact
example := candidate_occurrence_count_exact
example := candidate_row_geometry_exact
example := candidate_coverage_valid
example := generated_currentAt_iff_aggregateAt

end Tests.FPrimeFullHistoryRadixFourFirstAcceptedSelection
