import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.NifsPaper.AlignedCompiler.ProductionCarrier

/-! Focused checks for the artifact-checked selective 270-carrier slice. -/

namespace tests.FPrimeFullHistorySelectiveCarrier270

open Nightstream.Implementation.R1CS.FPrimeFullHistoryNifsPaper.AlignedCompiler.ProductionCarrier

#check generated_layout_refines_model
#check decodedPaddingRows_length
#check generated_padding_rows_shape
#check encodedPaddingColumn_matches_typedCarrier
#check generated_padding_row_iff_zeroPin
#check generated_padding_row_canonical_complete

end tests.FPrimeFullHistorySelectiveCarrier270
