import Nightstream.Implementation.R1CS.Correspondence.FPrime.FPrimeProductionFreshPublicSingletonRows

/-!
Focused elaboration boundary for the singleton compact-adapter/physical-row
composition.
-/

namespace NightstreamTests.FPrimeProductionFreshPublicSingletonRows

open Nightstream.Implementation.R1CS.FPrimeProductionFreshPublicSingletonRows

#check rawClaimOfAssignment_length
#check sourceProgram_cost_eq_rows_plus_shape
#check selectedRows_iff_sourceCheck
#check selectedRows_iff_sourceProgram
#check selectedRows_iff_freshPublic_eq_encodeInstance
#check artifactRows_iff_freshPublic_eq_encodeInstance

end NightstreamTests.FPrimeProductionFreshPublicSingletonRows
