import Nightstream.Implementation.Rust.CanonicalConformance.TerminalLink.PhysicalRowsRefinement

open Nightstream.Implementation.Rust.CanonicalConformance.TerminalLink

#check PhysicalRowsRefinement.generated_batchSize_eq
#check PhysicalRowsRefinement.generated_rowCount_eq
#check PhysicalRowsRefinement.generated_columnCount_eq
#check PhysicalRowsRefinement.generated_rows_eq_selected
#check PhysicalRowsRefinement.generated_rows_eq_compiler_output
#check PhysicalRowsRefinement.generated_rows_exact_receipt_ownership
