import Nightstream.Implementation.R1CS.Correspondence.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.CombinedNc.SelectedRowsActiveComposition

/-!
Focused interface regression for the fixed-profile production combined-NC
acceptance bridge.

The terminal claim is computed from selected source rows and exact terminal
input-column bindings.  No checked theorem below accepts the terminal RHS,
the final-claim equality, source-row satisfaction, or semantic NC acceptance
as a premise.
-/

namespace Nightstream.Tests.FPrimeSelectiveFixedPointPiCcsNcProductionAcceptance

open Nightstream.Implementation.R1CS.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.CombinedNc
open Nightstream.Implementation.R1CS.FPrimeSelectiveFixedPoint.PiCcsNc.DelayedProjection.CombinedNc.Materialized
open SelectedRowsActiveComposition

#check ProductionTerminalBridge.computed_finalSum_eq_messageTerminal
#check ProductionColumnBindings.columnBindings_imply_exactDataflow
#check generatedEmittedRowsSatisfy_implies_claimsAccepted
#check generatedEmittedAssignmentSatisfies_implies_claimsAccepted
#check generatedEmittedAssignmentSatisfies_implies_claimsCheck
#check generatedEmittedAssignmentPair_of_nextPacked_implies_previousPacked_or_namedFailure

end Nightstream.Tests.FPrimeSelectiveFixedPointPiCcsNcProductionAcceptance
