import Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.StreamingLifecycle

/-! Focused surface for the streaming lifecycle correspondence owner. -/

set_option autoImplicit false

#check Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingLifecycleRelation.Base
#check Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingLifecycleRelation.Recursive
#check Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingLifecycleRelation.Terminal
#check Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingPreludeRelation.initialReplayFields_length
#check Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingPreludeRelation.workItem_exact
#check Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingPreludeRelationArtifact.source_rows_imply_holds
#check Nightstream.Implementation.R1CS.Correspondence.FPrimeFullHistory.StreamingLifecycleRecursiveVerifierKeyRowSound.stage_rows_imply_outputs
#check Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingLifecycleSourceSemanticLinkArtifact.base_rows_refine_semanticLink
#check Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingLifecycleSourceSemanticLinkArtifact.recursive_rows_refine_semanticLink
#check Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingPaperNifsAuthority.recursive_output_exact
#check Nightstream.Implementation.R1CS.FPrimeFullHistoryStreamingPiRLCFamilyLifecycleBridge.BoundRecursiveRun.outputs_exact_or_failure
