import Nightstream.Implementation.NebulaV2.ProductionMemoryBatchCcsLinkRows

/-! Regression surface for complete production memory-to-CCS authority rows. -/

set_option autoImplicit false

namespace tests.NebulaV2ProductionMemoryBatchCcsLinkRows

open Nightstream.Implementation.NebulaV2.ProductionMemoryBatchCcsLinkRows

#check claimStateDigestWord_eq_encoding_of_ccsPublicPlaced
#check claimMemoryDigestWord_eq_encoding_of_ccsPublicPlaced
#check claimCcsPublicExact_of_ccsPublicPlaced
#check CcsPublicExact.fullMatches
#check rows_imply_fullMatches_of_ccsPublicPlaced
#check rows_length_exact
#check candidate_row_count_table

end tests.NebulaV2ProductionMemoryBatchCcsLinkRows
