import Nightstream.Implementation.NebulaV2.ProductionProductNifsPublicTranscript

/-! Regression surface for the field-native production paper-NIFS transcript. -/

set_option autoImplicit false

namespace tests.NebulaV2ProductionProductNifsPublicTranscript

open Nightstream.Implementation.NebulaV2.ProductionProductNifsPublicTranscript

#check fixedPrefix_candidate_injective
#check publicNifsFields_length
#check publicInputOf_native_encoding
#check publicNifsFields_of_value
#check publicNifsFields_ne_of_candidate_ne
#check frame_length
#check frame_eq_recovers_direct_authority_or_memory_collision
#check frames_ne_of_candidate_ne
#check equal_publicState_recovers_authority_or_named_failure

end tests.NebulaV2ProductionProductNifsPublicTranscript
