import Nightstream.Implementation.NebulaV2.ProductionPaperExactLifetimeSoundness

/-! Regression surface for the exponent-indexed F-prime soundness bridge. -/

set_option autoImplicit false

namespace tests.NebulaV2ProductionPaperExactLifetimeSoundness

open Nightstream.Implementation.NebulaV2.ProductionPaperExactLifetimeSoundness

#check MemoryFailure
#check Failure
#check CertifiedExecution
#check CertifiedExecution.baseChallengeAuthorityExact
#check CertifiedExecution.exactClaimSchedule
#check CertifiedExecution.fixedBranchSchedule
#check CertifiedExecution.receiptsExact
#check CertifiedExecution.consumerInvocationIndicesExact
#check CertifiedExecution.fullStateContinuityExact
#check CertifiedExecution.exactClaimOpenings
#check CertifiedExecution.everyConsumedBundleOpens
#check CertifiedExecution.everyConsumedClaimHolds
#check exact_lifetime_implies_certificate_or_failure
#check exact_lifetime_implies_execution_or_failure

end tests.NebulaV2ProductionPaperExactLifetimeSoundness
