import Nightstream.Implementation.NebulaV2.ProductPiDecTypedBridgeFor

set_option autoImplicit false

namespace tests.NebulaV2ProductPiDecTypedBridgeFor

open Nightstream.Implementation.NebulaV2.ProductPiDecTypedBridgeFor

#check typedEquations_of_rows
#check paperAccepted_of_rows_for_attempt

end tests.NebulaV2ProductPiDecTypedBridgeFor
