import Nightstream.Implementation.NebulaV2.ProductPiCcsTranscriptCursorFor

set_option autoImplicit false

namespace tests.NebulaV2ProductPiCcsTranscriptCursorFor

open Nightstream.Implementation.NebulaV2.ProductPiCcsTranscriptCursorFor

#check fullOutputPayload_length
#check fullOutputFields_length
#check replayRounds_absorbed
#check afterFullOutput_absorbed

end tests.NebulaV2ProductPiCcsTranscriptCursorFor
