import Nightstream.Protocol.NebulaV2.ProductionBatchedGlobalFPrimeCountermodels

set_option autoImplicit false

namespace tests.NebulaV2ProductionBatchedGlobalFPrimeCountermodels

open Nightstream.Protocol.NebulaV2.ProductionBatchedGlobalFPrimeCountermodels

#check weak_local_checks_accept_changed_authority
#check fixed_lifetime_authority_rejects_countermodel

end tests.NebulaV2ProductionBatchedGlobalFPrimeCountermodels
