import Nightstream.Implementation.NebulaV2.ProductionPaperRecursiveAcceptedRowsFor

/-! Regression surface for recursive statement-identity authority. -/

namespace tests.NebulaV2ProductionPaperRecursiveAcceptedRowsFor

open Nightstream.Implementation.NebulaV2.ProductionPaperRecursiveAcceptedRowsFor

#check Rows.challengeStatementIdentityExact

end tests.NebulaV2ProductionPaperRecursiveAcceptedRowsFor
