import Nightstream.Implementation.NebulaV2.ProductionPaperRecursiveInvocationRowsSoundFor

open Nightstream.Implementation.NebulaV2.ProductionPaperRecursiveInvocationRowsSoundFor

#check exact_of_supplement
#check rows_imply_exact_core
