import Nightstream.SuperNeo.Folding.Nifs.ConcretePhi81.Authority.PackedYZcol

/-! Public theorem-surface gate for packed `yZcol` authority at the NIFS boundary. -/

open Nightstream.SuperNeo.Folding.Nifs.ConcretePhi81.Authority.PackedYZcol

#check sourceBound_iff_packedYZcolBound
#check canonicalParentAssignment
#check rawSourceFold_eq_canonicalParentAssignment
#check canonicalParentClaim
#check canonicalParentClaim_eq_sourceAggregate
#check ParentProjectionMatches
#check ParentProjectionMismatch
#check packedYZcolBound_or_mixingCollision_or_badRoot_or_parentProjectionMismatch
#check accepted_implies_refinement_or_yRingUnbound_or_mixingCollision_or_projectionBadRoot_or_parentProjectionMismatch_or_badEvent
