import Nightstream.Implementation.Rust.CanonicalConformance.PiCcsPaperRectangular.Conformance

open Nightstream.Implementation.Rust.CanonicalConformance.PiCcsPaperRectangular

#check Artifact.carried_input_length
#check Artifact.carried_count_eq_shape
#check Artifact.fresh_gamma_slots_match
#check Artifact.norm_gamma_slots_match
#check Artifact.carried_gamma_slots_match
#check Artifact.covers_both_rectangular_directions
