import Nightstream.Implementation.R1CS.Correspondence.PiCcsMatrix.Phi81BarMatrixRefinement

open Nightstream.Implementation.R1CS.Phi81BarMatrixRefinement

#check runtimeEntryNat
#check runtimeBarEntry
#check artifact_shape
#check runtimeBarEntry_eq_native
#check runtimeBarBasis
#check runtimeBarBasis_eq_barBasis
#check runtimeKernel
#check runtimeKernel_constant_eq
#check runtimeKernel_weight_eq_phi81Kernel
#check runtimeConstantTermLaw
