import Nightstream.SuperNeo.Folding.PiCCS.PaperJoint.StrongExecution.SecurityContracts

/-! Focused interface regression for the named causal `Pi_CCS` security contracts. -/

namespace tests.PiCcsPaperJointStrongExecutionSecurityContracts

open Nightstream.SuperNeo.Folding.PiCCS.PaperJoint.StrongExecution.SecurityContracts

#check mixingRootEvent
#check sumCheckBadChallengeEvent
#check MixingRootProbabilityContract
#check SumCheckSoundnessContract
#check fixedFirstBad_eq_mixing_or_sumCheck
#check fixedFirstBadBound_of_securityContracts
#check extraction_after_first_success_of_securityContracts
#check extraction_after_success_gate_of_securityContracts

end tests.PiCcsPaperJointStrongExecutionSecurityContracts
