import Nightstream.SuperNeo.Folding.PiCCS.SplitNc.Necessity.CarrierCoverage

open Nightstream.SuperNeo.Folding.PiCCS.SplitNc.Necessity.CarrierCoverage

#check logicalWidthCube_covers_lanes
#check logicalWidth_lt_carrierWidth
#check firstCompletedTail_outside_columnCube
#check logicalWidthCube_does_not_cover
