import Nightstream.Implementation.R1CS.Correspondence.PiCcsNc.CarrierCoverageRefinement

open Nightstream.Implementation.R1CS.PiCcsNc.CarrierCoverageRefinement

#check artifact_dimensions
#check artifact_shape_validation_accepts_pair
#check artifact_pi_ccs_accepts_pair
#check artifact_extension_values_are_base
#check logical_decodes_equal
#check full_decodes_differ
#check tail_first_completed_coordinate
#check y_zcol_outputs_equal
#check tail_logical_is_full_prefix
#check zero_assignment_materializes_full_decode
#check tail_assignment_materializes_full_decode
#check tail_logical_base_fields_exact
#check zero_full_base_fields_exact
#check tail_logical_decode_norm_bounded
#check zero_full_decode_norm_bounded
#check tail_full_decode_not_norm_bounded
#check zero_semantic_assignment_truth
#check tail_semantic_assignment_not_truth
#check production_observation_collision_changes_nc_truth
#check artifact_checked_pi_ccs_acceptance_changes_nc_truth
