import Nightstream.Implementation.R1CS.Correspondence.PiCcsNc.SourceRefinement

open Nightstream.Implementation.R1CS.PiCcsNc.SourceRefinement

#check implementationShape
#check directDiagonal_orderedAssignment
#check directDiagonal_at_coveredCoordinates
#check truth_iff_inputsNormBoundedTwo
#check assignmentsFitColumnDomain_of_covers
#check truth_implies_trueInitial_eq_zero
