import Nightstream.SuperNeo.Folding.PiCCS.PaperJoint.Phi81MatrixSource

open Nightstream.SuperNeo.Folding.PiCCS.PaperJoint.Phi81MatrixSource

#check phi81Shape
#check phi81Shape_coefficientCount
#check source
#check source_kernel_eq
#check source_matrix_embedLogical
#check source_matrix_tail_zero
#check coefficientMatrix_constant_apply
#check coefficientMatrix_constant_embedLogical
#check coefficientMatrix_constant_tail_zero
