import Nightstream.SuperNeo.Folding.PiCCS.PaperJoint.Necessity.PaddedCarrier

open Nightstream.SuperNeo.Folding.PiCCS.PaperJoint.Necessity.PaddedCarrier

#check completed_matrix_tail_zero
#check tail_coefficient_entry_eq_one
#check logicalProjections_eq
#check carrierAssignments_ne
#check zeroAssignment_coefficientImage_eq_zero
#check tailAssignment_coefficientImage_eq_one
#check omitting_completed_carrier_changes_coefficient_image
