import Nightstream.SuperNeo.Folding.PiCCS.PaperJoint.ProtocolDataRefinement

open Nightstream.SuperNeo.Folding.PiCCS.PaperJoint.ProtocolDataRefinement
open Nightstream.SuperNeo.Folding.PiCCS.PaperJoint.ConstraintPolynomialLift

#check ProtocolLift.map_zero
#check ProtocolLift.toConstraintEvaluationLaws
#check liftMonomial_totalDegree
#check liftConstraintPolynomial
#check Nightstream.SuperNeo.Folding.PiCCS.PaperJoint.ConstraintPolynomialLift.Evaluation.EvaluationLaws
#check Nightstream.SuperNeo.Folding.PiCCS.PaperJoint.ConstraintPolynomialLift.Evaluation.evaluateMonomial_lift
#check Nightstream.SuperNeo.Folding.PiCCS.PaperJoint.ConstraintPolynomialLift.Evaluation.evaluatePolynomial_lift
#check evaluateMonomial_lift
#check evaluatePolynomial_lift
#check liftTable_tabulate
#check toProtocolData
#check ccsTable_eq
#check normTable_eq
#check toProtocolData_toJointData_eq
