import Nightstream.Implementation.R1CS.Correspondence.PiCcsNc.Authority.DelayedResidual.CombinedNc.ProductionPaperChecker
import Nightstream.Implementation.R1CS.Correspondence.PiCcsNc.Authority.DelayedResidual.CombinedNc.ProductionPaperSequence
import Nightstream.Implementation.R1CS.Correspondence.PiCcsNc.Authority.DelayedResidual.CombinedNc.ProductionPaperTerminal
import Nightstream.Implementation.R1CS.Correspondence.PiCcsNc.Authority.DelayedResidual.CombinedNc.ProductionPaperTrace

/-! Focused interface regression for the opening-derived paper checker and
its base/recursive/terminal composition. -/

namespace Nightstream.Tests.PiCcsNcProductionPaperComposition

#check Nightstream.Implementation.R1CS.PiCcsNc.Authority.DelayedResidual.CombinedNc.ProductionPaperChecker.check_eq_true_iff_accepted

#check Nightstream.Implementation.R1CS.PiCcsNc.Authority.DelayedResidual.CombinedNc.ProductionPaperSequence.checkedPair_of_nextPacked_implies_previousPackedAndPaper_or_namedFailure

#check Nightstream.Implementation.R1CS.PiCcsNc.Authority.DelayedResidual.CombinedNc.ProductionPaperTerminal.checkedTerminal_implies_packedAndPaper_or_namedFailure

#check Nightstream.Implementation.R1CS.PiCcsNc.Authority.DelayedResidual.CombinedNc.ProductionPaperTrace.closedTrace_implies_baseAndAllClosed_or_failure

end Nightstream.Tests.PiCcsNcProductionPaperComposition
