import Nightstream.Implementation.R1CS.Correspondence.PiCcsNc

/-! Focused signature regression for the delayed old-point binding surface. -/

open Nightstream.Implementation.R1CS.PiCcsNc.Authority.DelayedResidual
open Nightstream.Implementation.R1CS.PiCcsNc.Authority.DelayedResidual.ProductionRawChildren

#check acceptedProjectionIdentity_implies_oldPointRelation_or_badRoot
#check Fixed270.authoritativeRunningChild_getD
#check Fixed270.authoritativeRunningChildren_getD
#check Fixed270.authoritativeRunningChild_eq_orderedAssignment
#check Fixed270.assignmentsFitColumnDomain
#check Fixed270.acceptedProjectionIdentity_implies_oldPointRelation_or_badRoot
