import Nightstream.SuperNeo.Folding.PiCCS.PaperJoint.StrongReduction

open Nightstream.SuperNeo.Folding.PiCCS.PaperJoint
open Nightstream.SuperNeo.Folding.PiCCS.PaperJoint.StrongReduction

#check Statement.sourceProtocolData_toVerifierInput
#check Statement.projectOutput_eq_toOutputMessage
#check repeatedPublicOutputs_same_phi
#check ambientShape_sourceCount
#check Statement.ambientConnectedInputs
#check Statement.ambientUnifiedInputs
#check fullOutput_eq_honestAt_of_ambientOutputHolds
#check projectedOutput_eq_messageAt_of_ambientOutputHolds
#check acceptedProbe_extracts_source_or_badEvent
