import Nightstream.Implementation.R1CS.Correspondence.PiRlcChallenge.Sampler.Chunk.Acceptance

/-! Public theorem checks for the model-level chunk aggregate relation. -/

namespace tests.PiRlcChunkAggregateAcceptance

open Nightstream.Implementation.R1CS.PiRlcChallenge.Sampler.Chunk.Acceptance

#check productTreeMeaning_iff_equations
#check productTreeOutputBitRows_iff
#check productTreeAggregateRow_iff
#check allSourceBitsOne_iff_rejectionBucket
#check sourceAcceptanceMeaning_iff_verifier
#check aggregateAcceptanceRows_iff_sourceMeaning
#check aggregateAcceptanceRows_iff_verifierMeaning
#check aggregateAcceptanceRows_extension_exact
#check productTreeOutputBitRows_are_necessary
#check productTreeAggregateRow_is_necessary
#check finalAcceptanceRow_is_necessary

end tests.PiRlcChunkAggregateAcceptance
