import Nightstream.Implementation.NebulaV2.FPrime.Claim.DelayedTrace

set_option autoImplicit false

namespace tests.NebulaV2FullClaimDelayedTrace

open Nightstream.Implementation.NebulaV2.FullClaimDelayedTrace

#check check_authority_eq_true_iff_carries
#check singleton_freshLinked_iff_carries
#check Producer.outgoing_of_carries
#check Producer.carries_of_outgoing
#check Producer.freshLinked_of_outgoing

end tests.NebulaV2FullClaimDelayedTrace
