import Nightstream.Implementation.Nebula.Production.Carrier.StreamingPiRLCNormalizedLinkRows

namespace Nightstream.Tests.Axioms.Nebula.Implementation.Production.Carrier.StreamingPiRLCNormalizedLinkRows

open Nightstream.Implementation.Nebula.ProductionStreamingPiRlcNormalizedLinkRows.Normalized

#print axioms accepted_implies_fieldLinksHold
#print axioms overlaySourceColumnsExact_of_links
#print axioms bodyPhaseBindingPlaced_of_links
#print axioms accepted_implies_bodyPhaseBindingPlaced
#print axioms receipt_geometry_exact

end Nightstream.Tests.Axioms.Nebula.Implementation.Production.Carrier.StreamingPiRLCNormalizedLinkRows
